### ISSUE TITLE
使用infowindow组件时候会报出一个错

### ISSUE THREAD

**Issue by shifeng1993** [Dafrok/vue-baidu-map#1]
Uncaught (in promise) TypeError: Cannot read property 'querySelectorAll' of undefined

**Comment by Dafrok** [comment]
什么浏览器

**Comment by shifeng1993** [comment]
https://github.com/shifeng1993/easygoAdmin/blob/master/src/containers/machine/Map.vue  chrome浏览器内，这是我的源码地址

**Comment by shifeng1993** [comment]
需要开启node服务，因为是假mock数据，在根目录下的server文件夹内app.js

**Comment by Dafrok** [comment]
发现一个其它问题，infoWindowPosition 你定义了一个 null ，但是 InfoWindow 的 position 属性只接受对象，这个也是会报错的，我怀疑你这个问题也是由于数据类型引起的

**Comment by Dafrok** [comment]
还有就是 InfoWindow 是可以直接插子节点的，你不需要用字符串定义一大串 DOM 字符串写进去。

**Comment by shifeng1993** [comment]
可是按照你说的改了这两个还是会报错的啊，如下两张图
![default](https://cloud.githubusercontent.com/assets/20181287/22913825/14c1b9e2-f2a8-11e6-8240-09fc50473d64.jpg)
![map](https://cloud.githubusercontent.com/assets/20181287/22913826/14f37f7c-f2a8-11e6-8f90-c3c359435721.jpg)

**Comment by Dafrok** [comment]
我说的只是两个无关的问题，建议先用排除法把引起问题的字段找出来，把不会引起错误的地方注释掉我才好排查是哪里的问题。

**Comment by shifeng1993** [comment]
我的数据在文件根目录下的server文件夹内，是mock的假数据，cd  server    node app 开启node服务即可。，求大佬帮帮忙，这个问题困扰好几天了。是在没办法才来提问

**Comment by Dafrok** [comment]
看了一下，组件被莫名挂载了两次，第一次的实例被销毁后生命周期没有停止导致了这个问题，我再看看是什么引起的。

**Comment by Dafrok** [comment]
找到一种暂时的解决方法，把 `Marker` 组件和 `InfoWindow` 组件调换声明顺序即可，你先用这个方案，具体问题我下午抽时间看一下。

**Comment by Dafrok** [comment]
找到问题了，是由于 vDOM 引起的，InfoWindow 组件使用 $refs 引用了一个真实 DOM 并异步执行了一些东西，导致 v-for 动态渲染引起 DOM 改变的时候的时候真实 DOM 的引用没有发生变化导致而抛出异常。0.0.7 现在发布了，你可以更新一下试试看。
