### ISSUE TITLE
鼠标滚轮缩放不能用，vue3项目

### ISSUE THREAD

**Issue by WANGKEKE0814** [Dafrok/vue-baidu-map#1000]
<baidu-map class="map" :apiKey="apiKey" :zoom="15" :scroll-wheel-zoom="true">
        
</baidu-map>
照着官网写的，不行啊？用的谷歌浏览器。什么原因也没有报错

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
