### ISSUE TITLE
导入地图出现'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentSt

### ISSUE THREAD

**Issue by coderjiejie** [Dafrok/vue-baidu-map#1001]
![image](https://user-images.githubusercontent.com/86844785/185826093-9b311992-1000-4878-abd7-fb56715990bb.png)
导入地图用谷歌浏览器就会出现这个提示，但是没有报错，可以正常显示地图

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
