### ISSUE TITLE
bm-circle圆形控件editing初始值就为true会报错一个foreach方法遍历的值不存在，有个性地图需求是否可以升级下V3链接呢

### ISSUE THREAD

**Issue by YaoBoWen1** [Dafrok/vue-baidu-map#1003]
排查源码发现是Circle.vue组件的bindEditingNodeEvents方法中的originInstance[editingKey]值不存在，辛苦在前面加个判断比如：originInstance[editingKey]&&originInstance[editingKey].forEach，解决该问题，并且有个性地图需求V2的mapStyle方法会出现大量地图空白块问题，是否可以升级map.vue组件下的src到3.0呢，https://api.map.baidu.com/api?v=3.0&ak=${ak}&callback=_initBaiduMap
![image](https://user-images.githubusercontent.com/100560968/185892107-0f40826b-cb08-4cd5-8599-b3de1c6fa084.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
