### ISSUE TITLE
使用cdn引入vue，如何使用路书功能

### ISSUE THREAD

**Issue by whj0117** [Dafrok/vue-baidu-map#1015]
目前项目没有使用vue-cli搭建，vue使用cdn引入，但是路书组件只能通过import引入，有没有路书的cdn地址，方便使用

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by whj0117** [comment]
> 目前项目没有使用vue-cli搭建，vue使用cdn引入，但是路书组件只能通过import引入，有没有路书的cdn地址，方便使用
