### ISSUE TITLE
baidu-map组件zoom属性不更新问题

### ISSUE THREAD

**Issue by xiaowanhashi** [Dafrok/vue-baidu-map#102]
作者你好，关注你的更新状态 今天在做zoom级别切换的时候发现不能动态的更改,应该是跟你你前两天更新的marker animation同步更新一样的问题，

**Comment by Dafrok** [comment]
给你一个发 pr 的机会 😄

**Comment by xiaowanhashi** [comment]
上次改源码的事情我还历历在目，改坏了，用不了就尴尬了...哈哈

**Comment by Dafrok** [comment]
话说我没发现 zoom 有这个问题啊，能提供一个复现用例吗

**Comment by Dafrok** [comment]
@xiaowanhashi ping

**Comment by xiaowanhashi** [comment]
是这样的，我动态的更改zoom的缩放值是没问题的， 但是当我鼠标滚轮缩放后在动态更改zoom的值就起不到作用了

**Comment by Dafrok** [comment]
你是指 [文档](https://dafrok.github.io/vue-baidu-map/#/zh/map/baidu-map) 中最后一个示例的场景？

**Comment by xiaowanhashi** [comment]
不是文档，是我开发中的遇到的问题，就是我鼠标滚轮去缩放zoom的层级之后再不能动态的修改zoom的层级，

**Comment by Dafrok** [comment]
我问的是场景，是不是相同的场景和逻辑

**Comment by xiaowanhashi** [comment]
相同的场景，我就一个页面，第一次动态改变zoom是OK的，鼠标滚轮改变zoom之后就不能动态的更改了

**Comment by Dafrok** [comment]
我推测你的问题藏在你的业务代码里，根据文档的这个 case 还原一下你的场景排查一下吧。
