### ISSUE TITLE
用element-ui在el-dialog弹出层中嵌入地图坐标获取不准确啊

### ISSUE THREAD

**Issue by hank2718** [Dafrok/vue-baidu-map#103]

**Comment by Dafrok** [comment]
show your case

**Comment by hank2718** [comment]
![qq20170803-155052](https://user-images.githubusercontent.com/7368299/28911586-91880044-7863-11e7-88c3-4873ac02bc4a.gif)

**Comment by Dafrok** [comment]
最好给代码……不过目测你给地图容器加个 `position: relative` 的样式应该就可以了

**Comment by Dafrok** [comment]
如果不行的话，你在 codepen.io 上实现一个简单的复现用例我看一下

**Comment by hank2718** [comment]
https://jsfiddle.net/hank2718/t8z0n244/  这里demo  左键点击地图

**Comment by Dafrok** [comment]
看明白了，这是因为 DOM Element 使用 transform，鼠标点击的时候元素真实坐标没变，而视觉上向左移动了 50% 的宽度的距离。我觉得这个应该属于百度地图的一个 bug，你可以到官方社区去反馈一下。目前要解决这个问题的话建议你手动算一下这个距离，或者外层容器使用 `transform: translate` 之外的方式实现。

**Comment by Dafrok** [comment]
参考了一下官方的意见，官方建议你 modal 组件加载完成再初始化地图

**Comment by hank2718** [comment]
谢谢了 👍   如果不是项目需要，真不想用百度地图，

**Comment by hank2718** [comment]
把element的样式修改了一下可以了，去掉了transform属性

**Comment by loocao** [comment]
同样遇到了弹窗坐标定位问题，参考 @Dafrok 的提议，给`baidu-map`添加v-if完美解决 😄

**Comment by tat757** [comment]
@loocao v-if会造成一个新BUG，就是你用modal定位中心后，关掉modal然后再打开时地图就又移位了。因为v-if是[lazy](https://vuejs.org/v2/guide/conditional.html)的。 改用v-show能解决。
