### ISSUE TITLE
地区检索返回的数据名称异常问题

### ISSUE THREAD

**Issue by SviAnL** [Dafrok/vue-baidu-map#1034]
![c0d53c407ec90056145f504930529aa](https://github.com/Dafrok/vue-baidu-map/assets/99179201/578f9b0d-f278-4fc4-b45e-75c742b09309)
返回的数据名称 有问题，比如是麦当劳 它返回的是卖当劳，酒店返回的是大店
这个是否有解决方案？

**Comment by jyk0201** [comment]
这边大麦bp可长期提供，有需要的来➕q2814249606，标明github

**Comment by 18303060635** [comment]
2814249606跑路狗 别上当
