### ISSUE TITLE
能否增加点击选址的功能？

### ISSUE THREAD

**Issue by aylanbrown** [Dafrok/vue-baidu-map#104]
早前用了这框架，很棒。但后来市场部反馈说不能点击选址，客户觉得很麻烦，能不能加上点击返回点击所在地方的地址的功能

**Comment by Dafrok** [comment]
点击选址属于业务逻辑，本库只负责处理视图逻辑。
点击选址功能你可以使用 click 事件配合 LocalSearch 组件进行实现。
