### ISSUE TITLE
添加折线后，滚动鼠标滚轮缩放的中心点偏移问题

### ISSUE THREAD

**Issue by hellovue** [Dafrok/vue-baidu-map#105]

**Comment by Dafrok** [comment]
Show your case

**Comment by hellovue** [comment]
<baidu-map class="bm-view" :center="center" :zoom="15" :scroll-wheel-zoom="true" :double-click-zoom="false">
                        <bm-scale anchor="BMAP_ANCHOR_BOTTOM_LEFT"></bm-scale>
                        <bm-polyline :path="polylinePath"></bm-polyline>
                    </baidu-map>
这是我写的代码，只要添加了bm-polyline这个标签，就用滚轮去缩放地图是中心点就会偏移，去掉这个标签就是好的

**Comment by Dafrok** [comment]
看不到你的代码，codepen.io 上写一个复现用例吧。

**Comment by hellovue** [comment]
https://dafrok.github.io/vue-baidu-map/#/zh/overlay/polyline  我和这个demo写的一样的

**Comment by Dafrok** [comment]
这段代码我亲测没有复现您说的问题，您也可以自己跑下在文档，在文档源码基础上还原一个复现用例看看到底问题出在哪。

**Comment by hellovue** [comment]
好的，我自己去试试

**Comment by Dafrok** [comment]
@hellovue 有复现用例了吗

**Comment by hellovue** [comment]
这段时间没有关注这个bug，刚才我重新测试了一下。出现的问题主要有：
1，如果在弹出框中显示地图，并且在地图上有一些marker,首次弹出时，是没问题的，但是再次打开就会出现位置偏移的问题
2，如果在弹出框的地图中添加了折线功能，那么滚轮滚动的居中点存在问题

**Comment by hellovue** [comment]
顺便问个问题，这个组件怎么清除所有的覆盖物，是this.BaiduMap.clearOverlays(); 方法么

**Comment by hellovue** [comment]
@Dafrok

**Comment by Dafrok** [comment]
我大概知道你的问题了，应该是在地图实例化之后，对父元素添加了 translate，导致地图初始化的原点产生了偏移。解决方法有两个，一是不用 translate，二是在 translate 的重绘完成后再实例化百度地图（可以用 v-if 控制）。

清除覆盖物理论上是没有必要的，你的所有覆盖物都是数据决定的，你只要把数据清掉覆盖物自然就都没了。

**Comment by Lpbzzz** [comment]
在不同浏览器上的表现也不一样：火狐的正常，chrome就会“中心点偏移”

**Comment by Dafrok** [comment]
chrome 更新之后出 bug 了，这个向官方反馈吧

**Comment by Lpbzzz** [comment]
这.....这该如何描述....没有向chrome提过....

**Comment by Dafrok** [comment]
@hellovue 偏移问题官方确认是 chrome 版本升级造成的

**Comment by zhangSiQiTop** [comment]
> @hellovue 偏移问题官方确认是 chrome 版本升级造成的

有解决方案吗
