### ISSUE TITLE
控件offset 偏移量能给个demo吗?

### ISSUE THREAD

**Issue by ShawLyon** [Dafrok/vue-baidu-map#107]
**这是百度地图官网的写法,但是在vue中怎么写呢?**

控件位置偏移
除了指定停靠位置外，还可以通过偏移量来指示控件距离地图边界有多少像素。如果两个控件的停靠位置相同，那么控件可能会重叠在一起，这时就可以通过偏移值使二者分开显示。
本示例将比例尺放置在地图的左下角，由于API默认会有版权信息，因此需要添加一些偏移值以防止控件重叠。
 ` var opts = {offset: new BMap.Size(150, 5)}  `
`map.addControl(new BMap.ScaleControl(opts)); `

**Comment by Dafrok** [comment]
[文档](https://dafrok.github.io/vue-baidu-map/#/zh/start/base) 中有关于私有类型的解释，直接传序列化的数据即可。

**Comment by Dafrok** [comment]
百度地图的 [官方文档](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference_3_0.html#a1b3) 就使用的是这个属性名，如果不遵循官方的命名规范，后期维护会有不少风险
