### ISSUE TITLE
地图高度设置100%后出不来，设置为px可以出来，怎么让地图全屏显示呢

### ISSUE THREAD

**Issue by bigbigbigbear** [Dafrok/vue-baidu-map#108]
地图高度设置100%后出不来，设置为px可以出来，怎么让地图全屏显示呢
`<template>
<baidu-map class="map"></baidu-map>
</template>
<style>
.map {
  width: 100%;
  height: 100%;
}
</style>`

**Comment by For-me** [comment]
检查下你自己的样式代码是否正常，组件本身是没有问题的

**Comment by ettingshausen** [comment]
@bigbigbigbear 问题解决了么？遇到了同样的问题。

**Comment by ettingshausen** [comment]
解决了:
```less
width: 100%;
height: 100vh;
```
