### ISSUE TITLE
使用vue-baidu-map 之后获取map对象报错，应该怎么使用呢

### ISSUE THREAD

**Issue by beckyzhan** [Dafrok/vue-baidu-map#11]
![image](https://cloud.githubusercontent.com/assets/10825353/23833110/281ff81c-077c-11e7-8663-a0af6deffbea.png)
![image](https://cloud.githubusercontent.com/assets/10825353/23833119/3a9023be-077c-11e7-92f0-fb839a1f3010.png)
![1489332978 1](https://cloud.githubusercontent.com/assets/10825353/23833208/5fd863f6-077d-11e7-89ca-3ddb9f978513.jpg)

**Comment by fqy110** [comment]
? 怎么解决的
