### ISSUE TITLE
bm-driving动态修改问题

### ISSUE THREAD

**Issue by xiaowanhashi** [Dafrok/vue-baidu-map#110]
一个页面 我定义一个空的坐标点 start ,end分别为空对象
<bm-driving :start="start" :end="end" :auto-viewport="true" ></bm-driving>
bm-driving这个组件上面绑定的start，end动态添加上去不显示
现在我点击某一个按钮去动态的改变这两个对象 
this.start = {lat:30.71505143847,lng:114.44050991562}
 this.end = {lat:30.618374556626,lng:114.24471011275}

导航是不显示的 数据确实是有

**Comment by Dafrok** [comment]
数据确实是有是什么意思？

**Comment by xiaowanhashi** [comment]
<bm-driving :start="start" :end="end" :auto-viewport="true" ></bm-driving> 驾车路线不显示

**Comment by xiaowanhashi** [comment]
<bm-driving>这个组件的 之前我提交的标签一直不显示..提交了半天

**Comment by xiaowanhashi** [comment]
一个页面 我定义一个空的坐标点 start ,end分别为空对象
现在我点击某一个按钮去动态的改变这两个对象 
this.start = {lat:30.71505143847,lng:114.44050991562}
 this.end = {lat:30.618374556626,lng:114.24471011275}
bm-driving这个组件上面绑定的start，end动态添加上去不显示导航

**Comment by Dafrok** [comment]
你把 1 楼说的又重复一遍是什么意思……不如直接上 codepen，show your code

**Comment by xiaowanhashi** [comment]
`<bm-driving :start="start" :end="end" :auto-viewport="true"></bm-driving>`
`data () {
      return {
           start:{},
           end:{}
      }
}`
`methods:{
    handle () {
        this.start = {lat:30.71505143847,lng:114.44050991562}
        this.end = {lat:30.618374556626,lng:114.24471011275}
   }
}`
导航不显示..

**Comment by Dafrok** [comment]
建议没有数据的时候不要挂载组件。百度地图会把你的坐标渲染到 0, 0 去的

**Comment by xiaowanhashi** [comment]
数据是后台实时推的，其实我这边只要有数据就去哪起始坐标规划线路,现在问题是不能实时的去填这个数据

**Comment by Dafrok** [comment]
不需要你填啊，设个判断一下条件决定它存不存在就好了。

**Comment by Dafrok** [comment]
百度地图的文档里也写了，这个参数只接收 Point 实例，你填个空对象不符合序列化数据结构，肯定有问题的。

**Comment by xiaowanhashi** [comment]
这边数据经过vuex存了然后 我通过computed拿到的这两个起始坐标直接填进去也不行,只有一上来在data里面写死的就可以显示

**Comment by Dafrok** [comment]
> 设个判断条件决定它存不存在就好了。

**Comment by xiaowanhashi** [comment]
还是不行,我这边computed拿到的数据我直接打印了是有的，难道是我穿过来的格式不对吗？我传的是这种格式{lat:30.71505143847,lng:114.44050991562}

**Comment by Dafrok** [comment]
show your code

**Comment by xiaowanhashi** [comment]
现在是想点击某个按钮之后再展示
`data () {
      return {       
        start: {},
        end: {} 
      }
    },`

computed里面返回的数据
```
getsPoint () {
        return this.$store.getters.getsPoint
},
```
      getePoint () {
        return this.$store.getters.getePoint
      }
我点击某个按钮的函数
```
goRoute () {
        this.start = this.getsPoint
        this.end = this.getePoint
       // console.log(this.start) {lat:30.71505143847,lng:114.44050991562}
        // console.log(this.end) {lat:30.618374556626,lng:114.24471011275}
      },
```
组件的展示
`<bm-driving :start="start?start:null" :end="start?start:null" :auto-viewport="true"></bm-driving>`

**Comment by Dafrok** [comment]
v-if 控制一下

**Comment by Dafrok** [comment]
刚才说过文档里写这里只接收 Point 参数，你传个 null 进去是想干嘛 🤒

**Comment by xiaowanhashi** [comment]
不是 ，我是不知道最后判断什么，我刚刚v-if了一下还是不行的，我把data里面的start ,end 改为null，然后去判断不为null，的时候去绑定属性 结果还是不行

**Comment by Dafrok** [comment]
看着像个 bug，我抽时间查一下

**Comment by xiaowanhashi** [comment]
公司我一个人搞这玩意儿，前端没得聊，跟后台哥们交流次数都没跟你交流的多，哈哈

**Comment by Dafrok** [comment]
确认是 bug，新版已发，谢谢反馈。

**Comment by xiaowanhashi** [comment]
ok 我更新一下在跑一下

**Comment by xiaowanhashi** [comment]
你好，看了覆盖物的相关文档，能否判断某个已知坐标点计算是否在自定义多边形覆盖物内呢？

**Comment by Dafrok** [comment]
能，但是你应该去社区提问，这不是视图逻辑的讨论范围

**Comment by xiaowanhashi** [comment]
用的BmPolygon组件，随机连线生成的一个多边形把一个已知经纬度的marker圈在里面，此时我要根据什么去判断在这个区域里面呢？看了您的文档，只有鼠标移入移出来判断是否在区域内,只是比较关系是如何判断鼠标是否进入或离开这个区域，规则是怎么样的(不好意思，打扰了，基于这个组件的应用确实没多少人能回答.)

**Comment by Dafrok** [comment]
这是一道已知坐标求交点的高中解析几何数学题，和组件、文档什么都没关系。
