### ISSUE TITLE
地图的路线规划功能可以关闭吗？按钮样式乱了，应该是样式冲突了

### ISSUE THREAD

**Issue by Dingxiaobai** [Dafrok/vue-baidu-map#111]
点击地图上的一个位置，弹出在附近找、到哪里去等等几项，但是下面搜索按钮后面的一个按钮只显示一一半

**Comment by Dingxiaobai** [comment]
![qq 20170814172249](https://user-images.githubusercontent.com/20110220/29265851-217ae112-8115-11e7-8523-66f6919503a6.png)

**Comment by Dafrok** [comment]
组件库没有定义任何私有样式，请检查是否是你的 css 和百度地图生成的样式有冲突。

**Comment by Dingxiaobai** [comment]
谢谢！已经解决
