### ISSUE TITLE
bm-driving 组件，动态更改 start，end属性，不触发地图响应

### ISSUE THREAD

**Issue by kuerbb** [Dafrok/vue-baidu-map#112]
`<template>
  <div>
    <button @click="handleClick">点我动态更改</button>
    <baidu-map class="map" :center="center" :scroll-wheel-zoom="true" :zoom="15">
      <bm-view style="position: absolute; top: 100px; bottom: 100px; left: 300px; right: 10px"></bm-view>
      <bm-driving
          :start="start"
          :end="end"
          :auto-viewport="true"
          :panel="false">
        </bm-driving>
    </baidu-map>
  </div>
</template>

<script>
export default {
  data () {
    return {
      center: {
        lng: 116.404,
        lat: 39.915
      },
      start: {lng: 0, lat: 0},
      end: {lng: 0, lat: 0},
      zoom: 15
    }
  },
  methods: {
    handleClick (row) {
      this.start.lng = 113.14999
      this.start.lat = 27.879228
      this.end.lng = 118.852544
      this.end.lat = 31.947559
    }
  }
}
</script>

<style lang="less" scoped>
.map {
  width: 500px;
  height: 500px;
}
</style>`

这是我的demo代码

**Comment by Dafrok** [comment]
#110
