### ISSUE TITLE
无法在circle上添加菜单...

### ISSUE THREAD

**Issue by yunfengsay** [Dafrok/vue-baidu-map#114]
![image](https://user-images.githubusercontent.com/15527378/29314513-d151270a-81f0-11e7-8888-6f963e1464ca.png)
想要做到这样...
![image](https://user-images.githubusercontent.com/15527378/29314519-e3fa177c-81f0-11e7-997b-756dd7d604fc.png)

请问如何实现

**Comment by Dafrok** [comment]
ContextMenu 只能作为 Map 和 Marker 组件的子组件，详见[官方文档](http://lbsyun.baidu.com/cms/jsapi/class/jsapi_reference.html#a0b0)。具体业务逻辑请参考这个原则进行设计。
