### ISSUE TITLE
center的问题

### ISSUE THREAD

**Issue by Lyule** [Dafrok/vue-baidu-map#116]
我需求通过调用后台接口来设置中心点，但是没有效果，一直都是初始化的center（我是用组件引入的方式）

**Comment by For-me** [comment]
show u code?

**Comment by Lyule** [comment]
mounted(){
            getProjectDetail({projectId: this.projectId}).then(response => {
                if (response.statusText === 'OK') {


                    this.center = {lat: data.latitude, lng: data.longitude};
                }

            });
        }

**Comment by Lyule** [comment]
我看到 文档上的 示例 ， 但是，我的需求 就是通过ajax 来获取center 和 marker

**Comment by For-me** [comment]
建议不要再mounted的时候初始化，这个阶段data以及被绑定上了，并且地图中心点已经被初始化了。提前初始化就OK

**Comment by Lyule** [comment]
拿到 map 对象后操作地图好像也没有用？？？

**Comment by Dafrok** [comment]
文档上写了关于生命周期以及 ready 事件的注意事项，再仔细看阅读一下吧。

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-baidu-map/#/zh/start/usage 参考常见问题部分。

**Comment by zhangya5847** [comment]
按照文档中的正确的写法写的，地图渲染不出来

**Comment by zhangya5847** [comment]
![image](https://user-images.githubusercontent.com/15855773/30960510-d61a068c-a408-11e7-9a1a-8e3e9d3e2d9c.png)
页面结果：
![image](https://user-images.githubusercontent.com/15855773/30960539-eb815dcc-a408-11e7-8ffe-82ad73dc043b.png)

**Comment by Dafrok** [comment]
你没有设置 zoom。我这块文档有疏漏，稍后更新一下。

**Comment by zhangya5847** [comment]
谢谢！已解决。

**Comment by guohuihot** [comment]
鼠标缩放后，地图的中心点怎么变了？但是看地图上设置的center（center是不是双向绑定不清楚）是没有变的，鼠标滚动时怎样让地图的中心保持不变
