### ISSUE TITLE
无法自定义marker

### ISSUE THREAD

**Issue by yunfengsay** [Dafrok/vue-baidu-map#117]
想实现这样的效果
![image](https://user-images.githubusercontent.com/15527378/29360123-053fba40-82b4-11e7-9c02-71d795d5e319.png)
可以点击出现infoWindow
![image](https://user-images.githubusercontent.com/15527378/29360151-349409fe-82b4-11e7-917e-df90f316838b.png)
bm-label中不能添加子组件，请问如何实现

**Comment by Dafrok** [comment]
这个有点麻烦，只能用 custom overlay，生成自定义覆盖物的抽象方法过于自由，没办法封装成组件，只能手动调用 BMap 核心类的 API。

**Comment by Dafrok** [comment]
我想了一下你的 case，label 的 content 是支持解析 HTML string 的，你可以利用这个 feature 进行实现。

**Comment by Dafrok** [comment]
补充一句，由于被百度地图 JS API 的设计所限制，InfoWindow 组件也只能作为 Marker 和 Map 的子组件出现，你可以在 Map 实例中定义好一个 InfoWindow 然后根据你的鼠标点击位置渲染到正确的位置。
