### ISSUE TITLE
请问使用BmLocalSearch组件搜索出来位置的图标能不能修改或者自定义？

### ISSUE THREAD

**Issue by ZbWeb** [Dafrok/vue-baidu-map#118]

**Comment by Dafrok** [comment]
不可以，此 feature 受限于百度地图 JS API。
如果你需要自定义检索功能，可以通过请求 [百度地图 Web API](http://lbsyun.baidu.com/index.php?title=webapi/guide/webservice-placeapi) 获取数据，然后再通过自定义组件进行渲染。
