### ISSUE TITLE
怎么实现自定义遮盖物？

### ISSUE THREAD

**Issue by HandsomeRonnieLee** [Dafrok/vue-baidu-map#119]

**Comment by yunfengsay** [comment]
![image](https://user-images.githubusercontent.com/15527378/29451686-29fd9090-8436-11e7-811b-d764b007d538.png)
我是这么实现的
先在源码中自定义一个模块
![image](https://user-images.githubusercontent.com/15527378/29451631-ecc55f00-8435-11e7-97a9-6b5e0d8f16bf.png)
在load回调中添加方法
![image](https://user-images.githubusercontent.com/15527378/29451841-bc023680-8436-11e7-8c73-9573ac7076d6.png)

然后自己添加样式
![image](https://user-images.githubusercontent.com/15527378/29451778-7c148500-8436-11e7-9ec4-8a31f3aaebb4.png)
![image](https://user-images.githubusercontent.com/15527378/29451797-8c58e56e-8436-11e7-8f28-84554bea5022.png)

**Comment by Dafrok** [comment]
自定义覆盖物的问题我已经设计很久了，始终无法解决抽象方法 `draw` 的声明式问题。这个方法定制性太强了，如果想抽象出来就必须加一些官方文档中不存在的属性，这和我的总体设计是有矛盾的。我在想不如把它完全开放给开发者，让开发者自己去定制重绘方法。

**Comment by Dafrok** [comment]
自定义覆盖物已实现，[文档](https://dafrok.github.io/vue-baidu-map/#/zh/overlay/overlay) 更新完毕。请升级到 0.12 版本进行使用。
