### ISSUE TITLE
地图缩放的性能为什么不如官方的好

### ISSUE THREAD

**Issue by brahmachen** [Dafrok/vue-baidu-map#12]
使用你们的组件，地图用滚轮缩放的时候的体验  比不上  不用组件流畅啊
1）没有缓存的情况下，缩放时少量情况下需要等待1S以上
2）拖动的时候，没有惯性效果

**Comment by Dafrok** [comment]
您说的是官方是官方的 http://lbsyun.baidu.com/index.php?title=jspopular 还是 map.baidu.com？

**Comment by brahmachen** [comment]
http://lbsyun.baidu.com/jsdemo.htm#a1_2

**Comment by Dafrok** [comment]
只要把惯性拖拽选项设为 true 就可以。刚才追踪了一下，这里是官方文档写错了，vue-baidu-map 组件的 option 是严格按照文档初始化默认值的。

> http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a0b0 查找关键字 **enableInertialDragging** ，文档描述为『启用地图惯性拖拽，默认禁用』。

**Comment by Dafrok** [comment]
0.1.4 版本已经发布，解决了这个问题。
