### ISSUE TITLE
地图的多点标注，为什么不是从A和B开始，反而是D到C的顺序？

### ISSUE THREAD

**Issue by Kanchil** [Dafrok/vue-baidu-map#122]
![image](https://user-images.githubusercontent.com/20110220/29556263-dd48e3ce-8757-11e7-80df-d922bac2e9eb.png)
![image](https://user-images.githubusercontent.com/20110220/29556303-005538e0-8758-11e7-8414-3e579b8431bc.png)

**Comment by Dafrok** [comment]
有两个问题：
1. 我比较好奇你的版本 API 版本，我是用的 latest 版本 marker 上没有那个字母。
2. template 标签在你的场景下似乎没什么意义，可以省略。

**Comment by Dafrok** [comment]
第一个问题我打开你 icon 里那张图就明白了。错位说明你的 index 有问题，打印出来看一下吧。

**Comment by Dafrok** [comment]
解决了就好
