### ISSUE TITLE
在使用BmCircle组件时，页面第一次加载之后，圆形能正常显示。当页面切换之后再切换回来，圆形就无法显示了，请问该如何解决？（移动端单页面）

### ISSUE THREAD

**Issue by ZbWeb** [Dafrok/vue-baidu-map#123]

**Comment by Dafrok** [comment]
文档也是以单页面 App 形式写的，你可以参考一下，对比一下看有什么不同。

**Comment by ZbWeb** [comment]
`问题解决了。之前我给`<baidu-map></baidu-map>`绑定的center="center"，给`<bm-circle></bm-circle>`绑定的:center="circlePath.center"。绑定center和circlePath.center的数据是一样的，但是就是会出现切换回来圆形消失的问题。之后我把`<baidu-map></baidu-map>`绑定的数据改为center="circlePath.center"。就没问题了

**Comment by ZbWeb** [comment]
解决了。之前我绑定数据时是<baidu-map :center=="center"></baidu-map>和<bm-circle :center="circlePath.center"></bm-circle >。其中center和circlePath.center的数据是一样的。现在我改为了<baidu-map :center=="circlePath.center"></baidu-map>和<bm-circle :center="circlePath.center"></bm-circle >。

**Comment by ZbWeb** [comment]
之前：`<baidu-map  :center="center" ><bm-circle :center="circlePath.center"></baidu-map>`

**Comment by ZbWeb** [comment]
解决了。是数据绑定问题。
之前：`<baidu-map :center="center" ><bm-circle :center="circlePath.center"></bm-circle></baidu-map>`
其中：center和circlePath.center数据是一样的
改为：`<baidu-map :center="circlePath.center" ><bm-circle :center="circlePath.center"></bm-circle></baidu-map>`

**Comment by Dafrok** [comment]
你这个 case 也是一个问题，我抽时间检查一下。
