### ISSUE TITLE
点聚合

### ISSUE THREAD

**Issue by Answer912** [Dafrok/vue-baidu-map#124]
mapUpdata (e) {
        let zooms = e.target.getZoom()
        console.log(zooms)
        let MAX = 12,
            markers = [],
            pt = null
        for (let i=0;i<MAX;i++){
          pt = new BMap.Point(Math.random() * 40 + 85, Math.random() * 30 + 21)
          markers.push(new BMap.Marker(pt))
        }
        console.log(markers)
      }
按着官方文档写的。  后面是怎么把页面弄成点聚合啊？ 
官方上的最后一步看不懂！
var markerClusterer = new BMapLib.MarkerClusterer(map, {markers:markers});

**Comment by Dafrok** [comment]
官方的点聚合不支持模块化，请自己封装一下。

**Comment by Dafrok** [comment]
https://www.npmjs.com/package/bmaplib.markerclusterer

简单地封装了一下，不保证没坑。如果有问题可以来 [这里] (https://github.com/Dafrok/BMapLib.MarkerClusterer) 发 ISSUE。

**Comment by Dafrok** [comment]
点聚合组件已强势插入，这里是 [传送门](https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/markerclusterer)。
