### ISSUE TITLE
build打包后，百度地图不显示

### ISSUE THREAD

**Issue by Answer912** [Dafrok/vue-baidu-map#125]
GET file://api.map.baidu.com/api?v=2.0&ak=iGWVzbKZshGN5RhV9c39efrGqojGTATu&callback=_initBaiduMap net::ERR_FILE_NOT_FOUND

**Comment by Dafrok** [comment]
`file://`

**Comment by Answer912** [comment]
file://api.map.baidu.com/api?v=2.0&ak=iGWVzbKZshGN5RhV9c39efrGqojGTATu&callback=_initBaiduMap net::ERR_FILE_NOT_FOUND
是file://

**Comment by For-me** [comment]
file是你本地路径，请查看你的publicPath设置是否正确

**Comment by Dafrok** [comment]
@For-me 不是 public path 的问题，出现 file 协议说明他没开静态服务直接在本地双击 html 文件打开的……

**Comment by Answer912** [comment]
我打包到手机APP上也是空白的。。这个要怎么解决啊 。没做过这个

**Comment by Dafrok** [comment]
请看 console

**Comment by Answer912** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by Dafrok** [comment]
说明你本地没有启用静态服务

**Comment by Answer912** [comment]
这个有教程吗？ 我找了一下 感觉都不对的样子。

**Comment by Dafrok** [comment]
我想了一下，好像让 App 在本地开静态服务也不太合适，这里我做下兼容处理把。

**Comment by Answer912** [comment]
好的。感谢大佬。

**Comment by Dafrok** [comment]
0.12.1 已发版，请更新。

**Comment by Answer912** [comment]
还是不行。。大佬。
百度自定义覆盖物里面引用的图面没打包。  点  的图片也没打包
