### ISSUE TITLE
CDN引用了vue-baidu-map的js以后是否可以直接使用百度地图的API

### ISSUE THREAD

**Issue by HHH1994** [Dafrok/vue-baidu-map#126]
CDN引用了vue-baidu-map的js以后是否可以直接使用百度地图的API？

**Comment by For-me** [comment]
有ready方法暴露了地图实例和方法，可以通过这个来使用

**Comment by HHH1994** [comment]
谢谢啊 老铁

**Comment by Dafrok** [comment]
ready 事件是给异步加载的场景使用的，如果你是用同步依序加载，可以直接去全局拿 BMap 变量。

**Comment by For-me** [comment]
@Dafrok 还是金花稳

**Comment by malaimoo** [comment]
@Dafrok 请问如何从全局拿到 BMap 变量
