### ISSUE TITLE
bm-driving中坐标问题

### ISSUE THREAD

**Issue by China-lin** [Dafrok/vue-baidu-map#127]
:waypoints="['昆山']"中的这个坐标怎么写啊   求解答  谢谢

**Comment by Dafrok** [comment]
这个属性的坐标类型处理我似乎遗漏了，马上进行跟进。

**Comment by Dafrok** [comment]
0.12.2 发版，[文档相关部分](https://dafrok.github.io/vue-baidu-map/#/zh/search/driving) 已更新，增加了示例说明。
