### ISSUE TITLE
定位成功后的回调函数怎么监听的？

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#128]
请问定位成功后的回调函数怎么监听的？我用v-bind明显不行

**Comment by Dafrok** [comment]
没看懂你的需求

**Comment by front-end-john** [comment]
locationIcon可自定义定位中心点的Icon样式不起作用，请问这是什么原因呢？
<bm-geolocation anchor="BMAP_ANCHOR_BOTTOM_RIGHT" @locationSuccess="getLocation"
                      @locationError="locationError" :locationIcon="{url:'http://lbsyun.baidu.com/jsdemo/img/Mario.png',size:{width: 30,height: 57}}"
                      :showAddressBar="true" :autoLocation="true"></bm-geolocation>

**Comment by Dafrok** [comment]
icon 这里是个 bug，但是你这个问题和上面的问题有何关系？

**Comment by Dafrok** [comment]
Icon 的问题已解决，请更新到 0.12.3

**Comment by front-end-john** [comment]
谢谢，移动端使用anchor="BMAP_ANCHOR_BOTTOM_RIGHT" 没有动画效果，请问有什么解决方案？

**Comment by Dafrok** [comment]
请查阅 JS API 官方文档

**Comment by front-end-john** [comment]
bug又来了，驾车路线规划，是否选展现检索结果面板<bm-driving :start="fbtDriving.start" :end="fbtDriving.end" :auto-viewport="true" :panel="false"></bm-driving>
失败啊！

**Comment by front-end-john** [comment]
panel=false  不展现检索结果面板失败

**Comment by Dafrok** [comment]
不同的问题请新开 issue 方便其他人查找。这个问题不再回了。
