### ISSUE TITLE
BmDriving组件中的起始点Marker的气泡可以修改吗

### ISSUE THREAD

**Issue by China-lin** [Dafrok/vue-baidu-map#130]
驾车路线的起始点的Marker的气泡 或者隐藏 我使用BmMarker组件  麻烦解答一下  谢谢

**Comment by Dafrok** [comment]
此类请先查阅 [官方文档](http://lbsyun.baidu.com/cms/jsapi/class/jsapi_reference.html#a7b16)，参考官方 API 是否提供能力再来询问，谢谢。
