### ISSUE TITLE
在弹窗组件中设置center居中效果不对

### ISSUE THREAD

**Issue by buildJava** [Dafrok/vue-baidu-map#132]
HI,
在弹窗中设置center pointer并不能居中，请问如何解决
![image](https://user-images.githubusercontent.com/18717339/29952814-5ffdc3c2-8efe-11e7-95b9-57e3eec59ae3.png)

**Comment by Dafrok** [comment]
根据你的描述无法看出任何问题

**Comment by buildJava** [comment]
我用bootstrap的Modal做弹窗的组件，
`<template>
  
  <div class="modal fade modal-mapview" tabindex="0" role="dialog" aria-hidden="true">
    <div :class="'modal-dialog ' + modalclass">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title"><i class='fa fa-map-marker'></i>--{{ location }}</h4>
        </div>
        <div class="modal-body" style="padding: 0px;">
          <baidu-map :bclass="bclass" :center="center" :position="position" :location="location"></baidu-map>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import BaiduMap from '../BaiduMap'
  export default {
    name: 'MapModal',
    components: {
      BaiduMap
    },
    props: {
      modalclass: {
        type: String,
        default () {
          return 'modal-lg'
        }
      },
      bclass: {
        type: String,
        default () {
          return 'map-container-modal-lg'
        }
      },
      modalData: {
        type: Object
      }
    },
    data () {
      return {
        center: {
          lng: 116.404,
          lat: 39.915
        },
        position: {
          lng: 116.404,
          lat: 39.915
        },
        location: ''
      }
    },
    watch: {
      modalData (val) {
        this.modalData = val
        if (this.modalData !== null && this.modalData !== {} && this.modalData.gps !== undefined) {
          var gps = this.modalData.gps.split(',').slice(0, 2)
          this.center.lng = gps[0]
          this.center.lat = gps[1]
          this.position = this.center
          this.location = this.modalData.location
        }
      }
    }
  }
</script>
`
初始化后标记点没有居中

**Comment by Dafrok** [comment]
如果不在 modal 里会出现这个问题吗？

**Comment by Dafrok** [comment]
@buildJava ping

**Comment by Dafrok** [comment]
@buildJava 🔔

**Comment by Dafrok** [comment]
没有后续响应，先关掉了。
