### ISSUE TITLE
自定义覆盖物draw的方法发现位置无法调整

### ISSUE THREAD

**Issue by China-lin** [Dafrok/vue-baidu-map#134]
el.style.left = pixel.x - 70 + 'px'
      el.style.top = pixel.y - 20 + 'px'

可以获取到el.style     el.style.left 就没有  请教大牛给我指点一下

**Comment by Dafrok** [comment]
请参考文档中的示例

**Comment by Dafrok** [comment]
@China-lin 问题弄明白了么？

**Comment by China-lin** [comment]
没有用成功  我用标签做的

**Comment by Dafrok** [comment]
还没明白你的问题在哪。用示例的代码不 work 吗？

**Comment by China-lin** [comment]
等下我报错发你看看

**Comment by Dafrok** [comment]
用 [codepen](http://codepen.io/) 弄个在线演示吧，报错很多东西看不出来。

**Comment by China-lin** [comment]
嗯嗯 好的

**Comment by Dafrok** [comment]
@China-lin ping

**Comment by Dafrok** [comment]
@China-lin 🔔

**Comment by Dafrok** [comment]
长期无人响应，暂时关掉。获得复现用例再打开。
