### ISSUE TITLE
地图生成后，点击“返回”的按钮回到上一个页面，再次进入地图显示空白

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#135]
地图生成后，点击“返回”的按钮回到上一个页面，再次进入地图显示空白，原先画好的路径什么都不现实，刷新整个地图页面才显示出来，已经使用vue的keep-alive了，依然空白，求大牛看看是什么问题？

**Comment by Dafrok** [comment]
就是因为 keepalive 了才会空白吧，请在组件 deactive 的时机把地图卸载

**Comment by Dafrok** [comment]
我抽时间跟一下这个问题，这个体验确实不好。如果你有需求先按照上面的方法适配一下，等新版发布了会在这里告知。

**Comment by Dafrok** [comment]
针对这个情况进行了修正，请更新到 0.12.5。

**Comment by hellolxl** [comment]
刚更新到你的0.12.5，本来初次打开有图，现在初次打开是白屏

**Comment by Dafrok** [comment]
有图是啥意思

**Comment by hellolxl** [comment]
更新前 地图会展现。

更新后 页面整个是灰色。没有内容，inspect DOM地图有渲染。但是就是页面不展现。

用的是你局部加载的范例

**Comment by Dafrok** [comment]
文档就是基于 0.12.5 的，你那边看着有问题吗？

**Comment by Dafrok** [comment]
@hellolxl

**Comment by hellolxl** [comment]
你用文档上局部加载的范例，使用0.12.3. 地图可以直接显示
同样的代码，使用0.12.5，默认是不显示的。
<template>
  <baidu-map class="bm-view" ak="YOUR_APP_KEY">
  </baidu-map>
</template>

<script>
import {BaiduMap} from 'vue-baidu-map'
export default {
  components: {
    BaiduMap
  }
}
</script>

<style>
.bm-view {
  width: 100%;
  height: 300px;
}
</style>

**Comment by Dafrok** [comment]
知道你的问题了。这里是我特意改成这样的，在没有设置 center 的时候，从语义上讲地图不应定位在任何位置的，就是一个『空』的状态，如果你有需要，可以自行初始化 center 属性。

**Comment by TigerTTT** [comment]
大佬 我用 Hbuilder 打包成APP 后为什么地图就是不显示呢？ 有什么需要注意的地方吗 ？ 请大佬赐教啊   拜谢！
