### ISSUE TITLE
高分辨率手机端地图文字显示过小，请问能怎么解决

### ISSUE THREAD

**Issue by chenxiong666** [Dafrok/vue-baidu-map#136]
打包APP后在手机端放到最大都看不清地图上的文字，meta标签也设置了，怎么能解决这个问题

**Comment by Dafrok** [comment]
文档示例中的文字也很小吗？

**Comment by chenxiong666** [comment]
我是用的淘宝的那个代码做的手机端rem自适应，不知道该怎么解决了

**Comment by Dafrok** [comment]
文档中有写适配高清屏的参数，你可以尝试一下。另外此类问题不涉及本项目 feature ，建议去官方社区讨论。

**Comment by Dafrok** [comment]
我看了下那个参数默认似乎就是 true，你去官方社区问一下把，我这边能给出的建议就是用 transform 放大到 dpi 的倍数。

**Comment by chenxiong666** [comment]
好的，谢谢建议
