### ISSUE TITLE
更改了center后，点击地图的其他标识，地图会移到别的地方去

### ISSUE THREAD

**Issue by yiiouo** [Dafrok/vue-baidu-map#137]
更新了代码
 
    //  伪代码
    <template>
      <div v-if='ifShow'>
        <baidu-map  :center='center' class="map" ak="bb1wdmvddqf1Ghaov4lr3toy" @ready="handler"  :zoom="15"  :scroll-wheel-zoom="true">
        </baidu-map>
      </div>
    </template>

    <script>
    /* eslint-disable */
    import { BaiduMap } from 'vue-baidu-map'
    import { BmView } from 'vue-baidu-map'

    export default {
      name: 'test',
      data() {
        return {
          center: { lng: 13, lat: 0 },
          ifShow: false
        }
      },
      components: {
        BaiduMap,
        BmView
      },
      mounted() {
        // this.center = {
        //   lng: 113.40594,
        //   lat: 23.100172
        // }
        this.ifShow = true
      },
      methods: {
        handler({ BMap, map }) {
          this.BMap = BMap
          this.getPos()
        },
        // 获取当前位置
        getPos() {
          navigator.geolocation.getCurrentPosition((e) => {
            var ggPoint = new this.BMap.Point(e.coords.longitude, e.coords.latitude)
            var convertor = new this.BMap.Convertor()
            var pointArr = []
            pointArr.push(ggPoint)

            convertor.translate(pointArr, 1, 5, (data) => {
              // 初始化地图，设置中心点坐标和地图级别
              const pos = data.points[0]
              console.log(pos)
              this.center = pos
              this.ifShow = true
              this.markerPoint = pos
            })
          })
        }
      }
    }
    </script>

    <style lang='scss' scoped>
      .map{
        height: 100vh;
      }
    </style>

然后我更改了`center`之后，再点击地图的一些标识，整个地图的位置就会移动到的地方去。

如果我一开始`center`定义的数值是我更改了`center`之后的数值，就不会触发这种情况。

或者有没有办法，在未初始化地图时，可以实现转换坐标？

**Comment by Dafrok** [comment]
第二行开始的这个是啥意思？
```
{
    center: { lng: 0, lat: 2 }
}
```

**Comment by Dafrok** [comment]
我尝试了一下你的 case，没有出现你说的情况，你方便提供一个在线展示或者能还原问题的精简源码吗？

**Comment by Dafrok** [comment]
排查了一下，你的初始化 center 值溢出了经纬度的合法值引，所以起了地图渲染的异常。你如果着急解决问题的话可以先用一个合法值进行初始化。
我觉得这个开发体验确实不好，有改进的空间，今明天尝试修复这个问题。

**Comment by yiiouo** [comment]
有点懵B。。。`navigator.geolocation.getCurrentPosition`我用这个方法，谷歌浏览器要`https`才支持 ，我在本地的话，问题还存在。但是我用了百度那个回到当前位置的组件，却没问题。[测试链接](navigator.geolocation.getCurrentPosition)。我再看看有什么办法先，或者你可以复制上面我贴的代码在本地试下。谢谢。

**Comment by Dafrok** [comment]
已经做了优化，请尝试更新到 0.12.4 版本，如果有其它问题可以开新 issue 提问。
