### ISSUE TITLE
vue2 + webpack3 无法局部加载。

### ISSUE THREAD

**Issue by hellolxl** [Dafrok/vue-baidu-map#138]
import { BaiduMap } from 'vue-baidu-map'

    export default {
        name:'map',
        data() {
          return {
             center: {lng: 0, lat: 0}
          }
        },
        componets:{
            BaiduMap
        },
    }

报以下错误：
[Vue warn]: Unknown custom element: <baidu-map> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by Dafrok** [comment]
你有个单词拼错了，好好检查一下吧。
