### ISSUE TITLE
更新到最新版本后，还存在“跳转到下一个页面”的地图不显示bm-marker自定义的图标的bug

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#139]
更新最新版本后，还存在“跳转”到下一个页面时，页面的地图不显示bm-marker自定义的图标，刷新该页面可以显示图标；如果再次返回上一个页面，同样存在该问题，麻烦大神抽空再看下，谢谢！

**Comment by Dafrok** [comment]
请发一个 bad case 吧。我还原不了你的场景，心有余而力不足。

**Comment by front-end-john** [comment]
意思是目前有两个地图的页面公用通一个地图组件，第一页面的地图所有组件显示正常，点击一个按钮跳转到下一个页面，bm-marker的icon就不显示了

**Comment by Dafrok** [comment]
你这个场景我尝试过还原了，确实复现不了。用 [codepen](https://codepen.io) 说话吧。

**Comment by Dafrok** [comment]
我又尝试还原了你描述的场景，确实无法复现，提供一下在线展示吧。

**Comment by Dafrok** [comment]
我又尝试还原了几种你描述的场景的可能性，依然无法复现，请务必提供一下在线展示。

**Comment by Dafrok** [comment]
@front-end-john 🔔

**Comment by front-end-john** [comment]
最近实在太忙，没法弄在线展示，我先自己调看下能不能解决吧

**Comment by Dafrok** [comment]
提供一个逻辑精简的代码也可以

**Comment by Dafrok** [comment]
这个问题还有后续吗？

**Comment by front-end-john** [comment]
这个问题好了
