### ISSUE TITLE
不能出现mark标志，地图经纬度已经过去但是没显示标志

### ISSUE THREAD

**Issue by qinyang1018** [Dafrok/vue-baidu-map#14]
![image](https://cloud.githubusercontent.com/assets/15726024/23847521/b95a1236-080d-11e7-80f2-0b726cc7e5c1.png)

**Comment by Dafrok** [comment]
提供一下能够复现该问题的源码

**Comment by qinyang1018** [comment]
方便加下我QQ吗？  8400074

**Comment by Dafrok** [comment]
不怎么上QQ，你新建个仓库，或者把会出问题的代码精简一下发这里吧

**Comment by qinyang1018** [comment]
`<template>
    <el-form :data="data" label-width="100px" style="margin:20px;width:60%;min-width:500px;">
        <el-form-item label="场馆名称">
            <el-input v-model="data.name"></el-input>
        </el-form-item>
        <el-form-item label="是否启用" prop="delivery">
            <el-switch on-text="是" off-text="否" v-model="value"></el-switch>
        </el-form-item>
        <el-form :inline="true" style="margin-left: 100px;width:60%;min-width:500px;">
            <el-form-item>
                <el-input width="10" v-model="keyWords" placeholder="关键字"></el-input>
            </el-form-item>
            <el-form-item>
                <el-button type="primary" v-on:click="">搜索</el-button>
            </el-form-item>
        </el-form>
        <el-form-item label="地图">
            <bm-view class="bm-view">
            </bm-view>
            <baidu-map class="map" :center="{lng: lng, lat:lat}" :zoom="15">
                <bm-marker :point="{lng:lng, lat:lat}" :dragging="true" animation="BMAP_ANIMATION_BOUNCE" :label="{content: 'Marker Label', opts: {offset: {width: 20, height: -10}}}"></bm-marker>
                <bm-geolocation anchor="BMAP_ANCHOR_BOTTOM_RIGHT" :showAddressBar="true" :autoLocation="true" />
                 <bm-local-search :keyword="keyWords" :auto-viewport="true" :location="location"></bm-local-search>
        </el-form-item>
    </el-form>
</template>
<script type="text/javascript">
import util from '../../common/js/util';
import NProgress from 'nprogress';
import BaiduMap from 'vue-baidu-map';
import Vue from 'vue'
Vue.use(BaiduMap, {
    // ak 是在百度地图开发者平台申请的密钥 详见 http://lbsyun.baidu.com/apiconsole/key */
    ak: 'EUpkvAQEyvQ6GYaTUGqMhC5t'
})
export default {
    data() {
            return {
                value: true,
                data: {},
                keyWords: '',
                lng: '',
                lat: '',
            }
        },
        methods: {
            searchMap: function() {

            }
        },
        mounted() {
            console.log(this.$route.query.venueData);
            this.data = JSON.parse(this.$route.query.venueData);
            this.value = this.data.inUse == 1 ? true : false;
            var map = this.data.location.split(',');
            this.lat = map[0];
            this.lng = map[1];
            console.log(this.lat + "---" + this.lng);
        }
}
</script>
<style>
/* 地图容器必须设置宽和高属性 */

.map {
    width: 600px;
    height: 400px;
}
</style>`

**Comment by qinyang1018** [comment]
<template>
    <el-form :data="data" label-width="100px" style="margin:20px;width:60%;min-width:500px;">
        <el-form-item label="场馆名称">
            <el-input v-model="data.name"></el-input>
        </el-form-item>
        <el-form-item label="是否启用" prop="delivery">
            <el-switch on-text="是" off-text="否" v-model="value"></el-switch>
        </el-form-item>
        <el-form :inline="true" style="margin-left: 100px;width:60%;min-width:500px;">
            <el-form-item>
                <el-input width="10" v-model="keyWords" placeholder="关键字"></el-input>
            </el-form-item>
            <el-form-item>
                <el-button type="primary" v-on:click="">搜索</el-button>
            </el-form-item>
        </el-form>
        <el-form-item label="地图">
            <bm-view class="bm-view">
            </bm-view>
            <baidu-map class="map" :center="{lng: lng, lat:lat}" :zoom="15">
                <bm-marker :point="{lng:lng, lat:lat}" :dragging="true" animation="BMAP_ANIMATION_BOUNCE" :label="{content: 'Marker Label', opts: {offset: {width: 20, height: -10}}}"></bm-marker>
                <bm-geolocation anchor="BMAP_ANCHOR_BOTTOM_RIGHT" :showAddressBar="true" :autoLocation="true" />
                 <bm-local-search :keyword="keyWords" :auto-viewport="true" :location="location"></bm-local-search>
        </el-form-item>
    </el-form>
</template>

**Comment by qinyang1018** [comment]
`
<template>
    <el-form :data="data" label-width="100px" style="margin:20px;width:60%;min-width:500px;">
        <el-form-item label="场馆名称">
            <el-input v-model="data.name"></el-input>
        </el-form-item>
        <el-form-item label="是否启用" prop="delivery">
            <el-switch on-text="是" off-text="否" v-model="value"></el-switch>
        </el-form-item>
        <el-form :inline="true" style="margin-left: 100px;width:60%;min-width:500px;">
            <el-form-item>
                <el-input width="10" v-model="keyWords" placeholder="关键字"></el-input>
            </el-form-item>
            <el-form-item>
                <el-button type="primary" v-on:click="">搜索</el-button>
            </el-form-item>
        </el-form>
        <el-form-item label="地图">
            <bm-view class="bm-view">
            </bm-view>
            <baidu-map class="map" :center="{lng: lng, lat:lat}" :zoom="15">
                <bm-marker :point="{lng:lng, lat:lat}" :dragging="true" animation="BMAP_ANIMATION_BOUNCE" :label="{content: 'Marker Label', opts: {offset: {width: 20, height: -10}}}"></bm-marker>
                <bm-geolocation anchor="BMAP_ANCHOR_BOTTOM_RIGHT" :showAddressBar="true" :autoLocation="true" />
                 <bm-local-search :keyword="keyWords" :auto-viewport="true" :location="location"></bm-local-search>
        </el-form-item>
    </el-form>
</template>
`

**Comment by qinyang1018** [comment]
怎么排都会乱掉  不知道这样能看不，实在不好意思

**Comment by Dafrok** [comment]
我帮你排版了 好好读下markdown的spec

**Comment by Dafrok** [comment]
首先你的 `bm-view` 放到 `baidu-map` 外面了，`bm-view` 必须是 `baidu-map` 的子组件，这个文档里已经说明了。其次你的 `baidu-map` 组件没有闭合，你参照文档先把这两个地方跑通再看看有没有问题。

**Comment by Dafrok** [comment]
你的 setCenter 怎么定义和调用的？建议你把 script 标签也贴上来看看。

**Comment by qinyang1018** [comment]
```
<script type="text/javascript">
import util from '../../common/js/util';
import NProgress from 'nprogress';
import BaiduMap from 'vue-baidu-map';
import Vue from 'vue'
Vue.use(BaiduMap, {
    // ak 是在百度地图开发者平台申请的密钥 详见 http://lbsyun.baidu.com/apiconsole/key */
    ak: 'EUpkvAQEyvQ6GYaTUGqMhC5t'
})
export default {
    data() {
            return {
                value: true,
                data: {},
                keyWords: '',
                lng: '',
                lat: '',
            }
        },
        methods: {
            searchMap: function() {

            }
        },
        mounted() {
            console.log(this.$route.query.venueData);
            this.data = JSON.parse(this.$route.query.venueData);
            this.value = this.data.inUse == 1 ? true : false;
            var map = this.data.location.split(',');
            this.lat = map[0];
            this.lng = map[1];
            console.log(this.lat + "---" + this.lng);
        }
}
</script>
<style>
/* 地图容器必须设置宽和高属性 */

.map {
    width: 600px;
    height: 400px;
}
</style>
```

**Comment by Dafrok** [comment]
是这样，vue-baidu-map 是一个纯异步渲染的组件，你直接在mounted里修改data是不可以的，你需要在`baidu-map`的ready事件中进行渲染后的相关操作。

**Comment by qinyang1018** [comment]
是改成这样吗？  我之前写java的 刚接触vue 
```
<script type="text/javascript">
import util from '../../common/js/util';
import NProgress from 'nprogress';
import BaiduMap from 'vue-baidu-map';
import Vue from 'vue'
Vue.use(BaiduMap, {
    // ak 是在百度地图开发者平台申请的密钥 详见 http://lbsyun.baidu.com/apiconsole/key */
    ak: 'EUpkvAQEyvQ6GYaTUGqMhC5t'
})
export default {
    data() {
            return {
                value: true,
                data: {},
                keyWords: '',
                lng: '',
                lat: '',
            }
        },
        methods: {
            searchMap: function() {

            }
        },
        ready() {
            console.log(this.$route.query.venueData);
            this.data = JSON.parse(this.$route.query.venueData);
            this.value = this.data.inUse == 1 ? true : false;
            var map = this.data.location.split(',');
            this.lat = map[0];
            this.lng = map[1];
            console.log(this.lat + "---" + this.lng);
        },
        mounted() {

        }
}
</script>
<style>
```

**Comment by Dafrok** [comment]
概念错误。。。。

```vue
<baidu-map @ready="yourMethod">
```

> 参考 https://cn.vuejs.org/v2/guide/events.html

**Comment by qinyang1018** [comment]
好的 谢谢了
