### ISSUE TITLE
chrome浏览器报错：A Parser-blocking, cross site，地图空白

### ISSUE THREAD

**Issue by shandafu** [Dafrok/vue-baidu-map#140]
Vue 2.4.2版本，使用全局或局部加载都报错，地图空白：A Parser-blocking, cross site (i.e. different eTLD+1) script, http://api.map.baidu.com/getscript?v=2.0&ak=XXXX&services=&t=20170823191629, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.

**Comment by Dafrok** [comment]
错误信息里给出原因了：https://www.chromestatus.com/feature/5718547946799104

> Intervention: Blocking the load of cross-origin, parser-blocking scripts inserted via document.write for users on 2G
Performance
For users on slow connections such as 2G, the performance penalty from third-party scripts loaded via document.write is often so severe as to delay display of main page content for tens of seconds. This feature will block the load of cross-origin, parser-blocking scripts inserted via document.write in case of an HTTP cache miss for users on a 2G connection. The feature will only be applicable to such scripts in the main frame.

**Comment by Dafrok** [comment]
这是 API 本身的问题，建议你检查一下 http://api.map.baidu.com/getscript?v=2.0&ak=XXXX&services=&t=20170823191629  里在哪里出现了 document.write，如果有可以去官方社区反馈一下。
