### ISSUE TITLE
chorme warn:  [Violation] Added non-passive event listener to a scroll-blocking

### ISSUE THREAD

**Issue by shunyizero** [Dafrok/vue-baidu-map#141]
![image](https://user-images.githubusercontent.com/3906714/30528091-2793f27e-9c62-11e7-8d68-0807036e430b.png)
每次移动或者缩放地图的时候，都会出现一堆warn。貌似只有谷歌浏览器有这现象。
麻烦请问一下，有解决方案嘛.
补充一点：这个现象是在模仿聚合效果页面出现的.

**Comment by Dafrok** [comment]
[文档](https://dafrok.github.io/vue-baidu-map/#/zh/start/usage) 中做出相同的行为也会有这个警告吗？

**Comment by shunyizero** [comment]
![image](https://user-images.githubusercontent.com/3906714/30536106-290f0a28-9c97-11e7-8006-39eef2afd51c.png)
最新版本的谷歌浏览器，在教程的页面中，添加聚合点后，移动地图就会出现这个现象。

**Comment by Dafrok** [comment]
windows 10 + Chrome 61.0.3163.91 吗？

**Comment by Dafrok** [comment]
除了点聚合组件，其它组件也有这个问题吗？

**Comment by shunyizero** [comment]
win7 +Chrome 61.0.3163.91
![image](https://user-images.githubusercontent.com/3906714/30573126-9c4f6130-9d24-11e7-934f-26a8f5cce031.png)
这类问题。貌似是因为添加了随机点后，才会有这现象
![image](https://user-images.githubusercontent.com/3906714/30573236-3b5be6f4-9d25-11e7-8e26-b58e628cfb52.png)
这里每次点击切换。也会有这种现象

**Comment by Dafrok** [comment]
好，先保留 issue。不过我推断可能是百度地图 JS API 自身的问题，推荐去 [官方社区](http://bbs.lbsyun.baidu.com/forum.php?mod=forumdisplay&fid=5) 反馈一下。

**Comment by shunyizero** [comment]
好的，另外麻烦请教大神一个问题哈。
百度的聚合功能有优化的可能性嘛。如果能的话，有啥建议不。
业务场景：上海市的某个区(以浦东新区为例)，大概要撒1000~2000个点。整个上海大概5w点左右。

**Comment by Dafrok** [comment]
可以在视图层前通过算法进行处理，然后通过 canvas 进行一次性渲染。DOM 元素的批量渲染是最消耗时间的。点聚合组件已经针对这个问题做了一定的优化。

另外无关问题请新开 issue 方便其他人搜索。

**Comment by shunyizero** [comment]
好的，多谢

**Comment by Dafrok** [comment]
排查了一下，这确实是 JS API 本身就存在的问题，组件库没法干涉，（详见http://lbsyun.baidu.com/jsdemo.htm?a#c1_4）。如果该问题对生产环境有影响建议通过官方渠道进行反馈。

**Comment by Dafrok** [comment]
> 大概要撒1000~2000个点。整个上海大概5w点左右。

我抽时间测试了一下，这个数量级的点使用常规的 JS API 是没法控制性能损耗的，推荐使用 [MapV](https://github.com/huiyan-fe/mapv/#readme) 做海量点的处理。

**Comment by Dafrok** [comment]
海量点组件已加入，能够处理万级别的点坐标。请更新至版本 0.16.0，文档参考 https://dafrok.github.io/vue-baidu-map/#/zh/overlay/point-collection

**Comment by Dafrok** [comment]
海量点组件已加入，能够处理万级别的点坐标。请更新至版本 0.16.1，文档参考 https://dafrok.github.io/vue-baidu-map/#/zh/overlay/point-collection

**Comment by shunyizero** [comment]
good job，赞一个
