### ISSUE TITLE
自定义覆盖物bm-overlay从父组件传入position属性，draw方法返回的值不动态更新

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#142]
<template>
  <bm-overlay
    :class="{sample: true, active}"
    pane="labelPane"
    @draw="draw">
    <div v-text="text"></div>
  </bm-overlay>
</template>

<script>
export default {
  props: ['text', 'position', 'active'],
  methods: {
    draw ({el, BMap, map}) {
      const {lng, lat} = this.position
      const pixel = map.pointToOverlayPixel(new BMap.Point(lng, lat))
      el.style.left = pixel.x - 70 + 'px'
      el.style.top = pixel.y - 20 + 'px'
    }
  }
}
</script>
自定义覆盖物bm-overlay从父组件传入position属性，draw方法返回的值不动态更新
例如： 父组件第一次传入position{
  "lng": 121.773936,
  "lat": 31.2052
}
第二次传入position{
  "lng": 113.331607,
  "lat": 23.433091
}
此时draw方法获取到的this.position仍为第一次的position

**Comment by Dafrok** [comment]
可以排下版吗

**Comment by Dafrok** [comment]
另外你的 tamplate 是怎么写的？

**Comment by front-end-john** [comment]
<template>
  <bm-overlay :class="{tooltips: true, activeTips}" pane="labelPane" @draw="draw">
    <div class="bm-info">
      <p>
</p>
    </div>
  </bm-overlay>
</template>

<script type="text/ecmascript-6">
  export default {
    props: ['content', 'position', 'activeTips', 'surplus'],
    methods: {
      draw ({el, BMap, map, overlay}) {
          // console.log(this.position.lng);
        const {lng, lat} = this.position;
        const pixel = map.pointToOverlayPixel(new BMap.Point(lng, lat));
        // console.log(pixel);
        el.style.left = pixel.x - 60 + 'px';
        el.style.top = pixel.y - 36 + 'px';
      }
    }
  };
</script>

<style lang="stylus" rel="stylesheet/stylus">
  .tooltips
    position absolute
    &.active
      background rgba(0,0,0,0.75)
      color #fff
    &>.bm-info
      background #fff
      padding 4px 8px
      width 130px
      border-radius 20px
      &:after
        position absolute
        bottom -10px
        left 0
        right 0
        margin 0 auto
        content ''
        display block
        width 0
        height 0
        border-left 11px solid transparent
        border-right 11px solid transparent
        border-top 11px solid #fff
      &>p
        font-size 10px
        &>span
          margin-left 10px
          color rgb(0,94,245)
</style>

**Comment by front-end-john** [comment]
`<template>`
  `<bm-overlay :class="{tooltips: true, activeTips}" pane="labelPane" @draw="draw">`
    `<div class="bm-info">`
      `<p>内容</p>`
    `</div>`
  `</bm-overlay>`
`</template>`

`<script type="text/ecmascript-6">`
  `export default {`
    `props: ['position', 'activeTips'],`
    `methods: {`
      `draw ({el, BMap, map, overlay}) {`
         ` // console.log(this.position); // 此处打印的经纬度不变化，但是每次切换position已经从父组件传过来`
        `const {lng, lat} = this.position;`
        `const pixel = map.pointToOverlayPixel(new BMap.Point(lng, lat));`
        `el.style.left = pixel.x - 60 + 'px';`
        `el.style.top = pixel.y - 36 + 'px';`
      `}`
   ` }`
  `};`
`</script>`

`<style lang="stylus" rel="stylesheet/stylus">`
  `.tooltips`
    `position absolute`
    `&.active`
      `background rgba(0,0,0,0.75)`
      `color #fff`
    `&>.bm-info`
      `background #fff`
      `padding 4px 8px`
      `width 130px`
      `border-radius 20px`
     ` &:after`
        `position absolute`
       ` bottom -10px`
       ` left 0`
        `right 0`
        `margin 0 auto`
        `content ''`
        `display block`
        `width 0`
        `height 0`
        `border-left 11px solid transparent`
        `border-right 11px solid transparent`
        `border-top 11px solid #fff`
      `&>p`
        `font-size 10px`
        `&>span`
          `margin-left 10px`
         ` color rgb(0,94,245)`
`</style>`

**Comment by Dafrok** [comment]
这。。先说一句排版辛苦了，其实 markdown 支持 ` ``` ` 三反引号代码块语法的，像这样

```vue
<template>
<bm-overlay :class="{tooltips: true, activeTips}" pane="labelPane" @draw="draw">
<div class="bm-info">
<p>内容</p>
</div>
</bm-overlay>
</template>

<script type="text/ecmascript-6">
export default {
props: ['position', 'activeTips'],
methods: {
draw ({el, BMap, map, overlay}) {
// console.log(this.position); // 此处打印的经纬度不变化，但是每次切换position已经从父组件传过来
const {lng, lat} = this.position;
const pixel = map.pointToOverlayPixel(new BMap.Point(lng, lat));
el.style.left = pixel.x - 60 + 'px';
el.style.top = pixel.y - 36 + 'px';
}
}
};
</script>

<style lang="stylus" rel="stylesheet/stylus">
.tooltips
position absolute
&.active
background rgba(0,0,0,0.75)
color #fff
&>.bm-info
background #fff
padding 4px 8px
width 130px
border-radius 20px
&:after
position absolute
bottom -10px
left 0
right 0
margin 0 auto
content ''
display block
width 0
height 0
border-left 11px solid transparent
border-right 11px solid transparent
border-top 11px solid #fff
&>p
font-size 10px
&>span
margin-left 10px
color rgb(0,94,245)
</style>
```

**Comment by Dafrok** [comment]
我尝试了下你的源码，没有发现你所说的 draw 方法被调用的时候 position 没有发生改变的问题。
因此我猜测你是不是想要通过 position 方法调整 overlay 位置的时候没有即时生效？我先针对这个问题解释一下原因：draw 方法的触发时机仅在地图发生更新时，它是不会检测你的父组件的属性发生什么变化的，所以你需要手动去访问 Overlay 实例的 reload 方法去刷新这个组件的位置。这个问题很有价值，我会抽时间把这些东西更新入文档。另外建议你更新一下版本，因为较早版本的 Overlay 组件的 reload 方法有一个变量没回收，会导致一些 bug 出现。

**Comment by front-end-john** [comment]
文档里面只有initialize，draw这两个方法，调用reload方法好像并不起左右

**Comment by Dafrok** [comment]
initialize 和 draw 不是方法，是事件，你要搞混。reload 是实例方法，需要访问到组件实例才能调用，你检查一下是不是调用方式有问题。

**Comment by Dafrok** [comment]
文档已更新相关示例。

**Comment by front-end-john** [comment]
示例在哪，没找到

**Comment by Dafrok** [comment]
BmOverlay 组件文档最后一个示例做了一些变更。

**Comment by front-end-john** [comment]
好，试了一下，终于正常了，多谢大神

**Comment by front-end-john** [comment]
用是可以用了，但是第一次加载会报下面的警告
```[Vue warn]: Error in callback for watcher "position": "TypeError: Cannot read property 'reload' of undefined"```

**Comment by Dafrok** [comment]
说明你生命周期没控制好，参考一下示例的实现吧。

**Comment by leopoo** [comment]
我也遇到这个问题, 好像初始化的时候, 如果没有指定覆盖物的 point  然后再去动态设定point 此问题100%复现,,,  我现在临时决定 失败给个坐标设置  v-if = false 隐藏掉 -

**Comment by Dafrok** [comment]
你说那个警告？

**Comment by caoyudanq** [comment]
> BmOverlay 组件文档最后一个示例做了一些变更。

请问这个BmOverlay在哪可以找到啊
