### ISSUE TITLE
CDN引用，还是无法初始化地图。

### ISSUE THREAD

**Issue by giky** [Dafrok/vue-baidu-map#155]

**Comment by giky** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Document</title>
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-baidu-map"></script>
<script>
	Vue.use(VueBaiduMap.default, {
		ak: '40GWXiduhOft266lK4N1dopL'
	})
</script>
<style>
.map {
  width: 100%;
  height: 400px;
}
</style>
</head>
<body>
<baidu-map class="map" center="北京"></baidu-map>	
</body>
</html>

**Comment by giky** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Document</title>
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-baidu-map"></script>
<script>
	Vue.use(VueBaiduMap.default, {
		ak: '40GWXiduhOft266lK4N1dopL'
	})
</script>
<style>
.map {
  width: 100%;
  height: 400px;
}
</style>
</head>
<body>
<baidu-map class="map" center="北京"></baidu-map>	
</body>
</html>`

**Comment by giky** [comment]
> <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Document</title>
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/vue-baidu-map"></script>
<script>
	Vue.use(VueBaiduMap.default, {
		ak: '40GWXiduhOft266lK4N1dopL'
	})
</script>
<style>
.map {
  width: 100%;
  height: 400px;
}
</style>
</head>
<body>
<baidu-map class="map" center="北京"></baidu-map>	
</body>
</html>

**Comment by giky** [comment]
VueBaiduMap.default的作用是什么

**Comment by Dafrok** [comment]
请参考 vue 文档的插件章节。Issue 区用于收集组件库相关问题，不负责解答基础知识问题。
