### ISSUE TITLE
0.17.0版本引入报错$BAIDU$未定义

### ISSUE THREAD

**Issue by 00520** [Dafrok/vue-baidu-map#156]
换到老版本不会报这个错误，但是会有其他的未定义错误，weex框架

**Comment by Dafrok** [comment]
没用过 weex 不知道什么原理。$BAIDU$ 变量在 [这里](https://github.com/Dafrok/BMapLib.TextIconOverlay/blob/3287eb420d00fd015284f92871b07e6e54225a7c/index.js#L16) 声明的，如果没有需求你把点聚合组件 tree shaking 掉就行了。

**Comment by Dafrok** [comment]
已确认是某个依赖项引用了 window 对象，更新到 0.17.1 试试吧。

**Comment by Dafrok** [comment]
已确认是某个依赖项引用了 window 对，0.17.1 升级了这个依赖，更新下看看吧。

**Comment by Dafrok** [comment]
已确认是因为某个依赖项引用了 window 对象。0.17.1 升级了这个依赖，更新下看看吧。
