### ISSUE TITLE
请问怎么给market类加上zIndex这个属性呢

### ISSUE THREAD

**Issue by zhangqi053694** [Dafrok/vue-baidu-map#158]
请问怎么给market类加上zIndex这个属性呢

**Comment by Dafrok** [comment]
你单词是不是拼错了？

Marker 类有一个 setIndex 方法官方文档里有写。封装的时候忽略了这个 API，今天抽时间搞一下。如果你比较着急可以通过调用组件实例的 originInstance 属性拿到覆盖物实例进行设置。

**Comment by Dafrok** [comment]
请更新至 0.17.2，增加了 zIndex 和 top 两个属性，文档已同步更新。

**Comment by guohuihot** [comment]
zIndex 不起作用啊，marker还是在overlay下面
