### ISSUE TITLE
地图控件

### ISSUE THREAD

**Issue by zhangqi053694** [Dafrok/vue-baidu-map#160]
地图控件的左下角属性‘BMAP_ANCHOR_BOTTOM_LEFT‘好像没有用，你试试看，也可能是我自己的问题！

**Comment by Dafrok** [comment]
Show your code

**Comment by zhangqi053694** [comment]
<bm-navigation anchor="BMAP_ANCHOR_BOTTOM_LEFT"></bm-navigation>

**Comment by Dafrok** [comment]
版本？

**Comment by Dafrok** [comment]
ping

**Comment by Dafrok** [comment]
@zhangqi053694 Ping
