### ISSUE TITLE
bm-geolocation中showAddressBar和autoLocation设置无效

### ISSUE THREAD

**Issue by China-lin** [Dafrok/vue-baidu-map#161]
我想实现点击立即定位  触发组件bm-geolocation  调用自动定位 获取经纬度    我发现之前有人提过     
求大神指教

**Comment by Dafrok** [comment]
请参考其它 issue 中的回答

**Comment by Dafrok** [comment]
@China-lin Ping

**Comment by Dafrok** [comment]
其它 ISSUE 里已经解释过为什么不能进行定位，如果没有附加问题我就关闭了。

**Comment by maomaoxiyu123** [comment]
哪里看其他的issue啊
