### ISSUE TITLE
关于BmMarker获取实例对象

### ISSUE THREAD

**Issue by CristalFJJ** [Dafrok/vue-baidu-map#163]
挺好用的，但是在使用BmMarker时如何直接获取实例对象并进行直接操作？通过类似click事件时可以获取e.target对象，但是不通过事件时如何获取呢？因为想通过这个对象，直接设置时时运动，通过改变position属性是直接到达，中间没有运动的效果，谢谢了。

**Comment by CristalFJJ** [comment]
找到了，通过ref实例里面的originInstance属性找到了。

**Comment by Dafrok** [comment]
实时运动不如用路书来的方便
