### ISSUE TITLE
关于BmMarker的方向问题

### ISSUE THREAD

**Issue by CristalFJJ** [Dafrok/vue-baidu-map#164]
marker有设置动态方向,但是点击marker出现infowindow弹窗时 marker的方向会自动变为初始的方向, 要鼠标移动下地图才能变回正确的方向 ，还有滚轮缩放地图时marker的方向也有这个问题~~

**Comment by Dafrok** [comment]
setRotation 这个方法我封装的时候忽略了，下一个版本完善一下。

**Comment by Dafrok** [comment]
更正一下，Marker 组件是封装了 rotation 属性的，上次我看漏了。我目前复现不出你的问题，最好提供一个复现用例，你也可以用文档中的实例自己试一下。

**Comment by Dafrok** [comment]
@CristalFJJ Ping

**Comment by CristalFJJ** [comment]
没懂~，可以详细点吗，谢谢了

**Comment by Dafrok** [comment]
不知道怎么解释，展示一下你的代码吧

**Comment by CristalFJJ** [comment]
<template>

<baidu-map id="map" :center="{lng: 116.404, lat: 39.915}" :zoom="zoom" @zoomend="zoomEnd" ak="您的ak" :scroll-wheel-zoom="true" @ready="ready">
<bml-marker-clusterer :averageCenter="true">
<bm-marker
:icon="{url: 'http://developer.baidu.com/map/jsdemo/img/fox.gif', size: {width: 300, height: 157}}"
:position="{lng: 116.404, lat: 39.915}"
:rotation="45"
@click="markerDetail({lng: 116.404, lat: 39.915})"
>
</bm-marker>
</bml-marker-clusterer>
<bm-info-window :position="infoWindow" :show="showWindow" @clickclose="infoWindowClose" @open="infoWindowOpen">
<p style="text-align:center;margin-bottom:10px">测试专用</p>
</bm-info-window>
</baidu-map>
</template>

<script>
import {BaiduMap,BmlMarkerClusterer,BmMarker,BmInfoWindow} from 'vue-baidu-map';
export default {
components: {
BaiduMap,
BmlMarkerClusterer,
BmMarker,
BmInfoWindow
},
data () {
return {
map: '',
BMap: '',
zoom: 10,
infoWindow: {lng: 116.404, lat: 39.915},
showWindow: false
}
},
methods: {
ready({map,BMap}) {
this.map = map;
this.BMap = BMap;
},
zoomEnd() {
this.$nextTick(()=>{
this.zoom = this.map.getZoom();
})
},
markerDetail(val) {
this.infoWindow = val;
this.showWindow = true;
},
infoWindowClose() {
this.showWindow = false;
},
infoWindowOpen() {
this.showWindow = true;
}

}
}
</script>

<style>
#map {
width: 100%;
height: 500px;
}
</style>

**Comment by CristalFJJ** [comment]
<template>
<baidu-map id="map" :center="{lng: 116.404, lat: 39.915}" :zoom="zoom" @zoomend="zoomEnd" ak="您的ak" :scroll-wheel-zoom="true" @ready="ready">
<bml-marker-clusterer :averageCenter="true">
<bm-marker
:icon="{url: 'http://developer.baidu.com/map/jsdemo/img/fox.gif', size: {width: 300, height: 157}}"
:position="{lng: 116.404, lat: 39.915}"
:rotation="45"
@click="markerDetail({lng: 116.404, lat: 39.915})"
>
</bm-marker>
</bml-marker-clusterer>
<bm-info-window :position="infoWindow" :show="showWindow" @clickclose="infoWindowClose" @open="infoWindowOpen">
<p style="text-align:center;margin-bottom:10px">测试专用</p>
</bm-info-window>
</baidu-map>
</template>
<script>
import {BaiduMap,BmlMarkerClusterer,BmMarker,BmInfoWindow} from 'vue-baidu-map';
export default {
components: {
BaiduMap,
BmlMarkerClusterer,
BmMarker,
BmInfoWindow
},
data () {
return {
map: '',
BMap: '',
zoom: 10,
infoWindow: {lng: 116.404, lat: 39.915},
showWindow: false
}
},
methods: {
ready({map,BMap}) {
this.map = map;
this.BMap = BMap;
},
zoomEnd() {
this.$nextTick(()=>{
this.zoom = this.map.getZoom();
})
},
markerDetail(val) {
this.infoWindow = val;
this.showWindow = true;
},
infoWindowClose() {
this.showWindow = false;
},
infoWindowOpen() {
this.showWindow = true;
}

}
}
</script>

<style>
#map {
width: 100%;
height: 500px;
}
</style>

**Comment by CristalFJJ** [comment]
<template>

<baidu-map id="map" :center="{lng: 116.404, lat: 39.915}" :zoom="zoom" @zoomend="zoomEnd" ak="您的ak" :scroll-wheel-zoom="true" @ready="ready">
<bml-marker-clusterer :averageCenter="true">
<bm-marker
:icon="{url: 'http://developer.baidu.com/map/jsdemo/img/fox.gif', size: {width: 300, height: 157}}"
:position="{lng: 116.404, lat: 39.915}"
:rotation="45"
@click="markerDetail({lng: 116.404, lat: 39.915})"
>
</bm-marker>
</bml-marker-clusterer>
<bm-info-window :position="infoWindow" :show="showWindow" @clickclose="infoWindowClose" @open="infoWindowOpen">
<p style="text-align:center;margin-bottom:10px">测试专用</p>
</bm-info-window>
</baidu-map>
</template>

<script>
import {BaiduMap,BmlMarkerClusterer,BmMarker,BmInfoWindow} from 'vue-baidu-map';
export default {
components: {
BaiduMap,
BmlMarkerClusterer,
BmMarker,
BmInfoWindow
},
data () {
return {
map: '',
BMap: '',
zoom: 10,
infoWindow: {lng: 116.404, lat: 39.915},
showWindow: false
}
},
methods: {
ready({map,BMap}) {
this.map = map;
this.BMap = BMap;
},
zoomEnd() {
this.$nextTick(()=>{
this.zoom = this.map.getZoom();
})
},
markerDetail(val) {
this.infoWindow = val;
this.showWindow = true;
},
infoWindowClose() {
this.showWindow = false;
},
infoWindowOpen() {
this.showWindow = true;
}

}
}
</script>

<style>
#map {
width: 100%;
height: 500px;
}
</style>

**Comment by Dafrok** [comment]
InfoWindow 应该作为 Marker 的子组件出现，文档示例里有说明。

**Comment by CristalFJJ** [comment]
把InfoWindow作为子组件，也是一样的，且同为子组件的label在鼠标缩放时也会消失
下面是demo
<template>
  <baidu-map id="map" :center="{lng: 116.404, lat: 39.915}" :zoom="zoom" @zoomend="zoomEnd" ak="您的ak" :scroll-wheel-zoom="true" @ready="ready">
    <bml-marker-clusterer :averageCenter="true">
      <bm-marker :icon="{url: 'http://developer.baidu.com/map/jsdemo/img/fox.gif', size: {width: 300, height: 157}}" :position="{lng: 116.404, lat: 39.915}" :rotation="45" @click="markerDetail({lng: 116.404, lat: 39.915})">
        <bm-label content="123456" :labelStyle="{color: 'red', fontSize : '16px'}" :offset="{width: -35, height: 30}"/>
        <bm-info-window :position="infoWindow" :show="showWindow" @clickclose="infoWindowClose" @open="infoWindowOpen">
        <p style="text-align:center;margin-bottom:10px">测试专用</p>
      </bm-info-window>
      </bm-marker>
    </bml-marker-clusterer>
    <bm-info-window :position="infoWindow" :show="showWindow" @clickclose="infoWindowClose" @open="infoWindowOpen">
      <p style="text-align:center;margin-bottom:10px">测试专用</p>
    </bm-info-window>
  </baidu-map>
</template>

<script>
import { BaiduMap, BmlMarkerClusterer, BmMarker, BmInfoWindow,BmLabel,} from 'vue-baidu-map';
export default {
  components: {
    BaiduMap,
    BmlMarkerClusterer,
    BmMarker,
    BmInfoWindow,
    BmLabel
  },
  data() {
    return {
      map: '',
      BMap: '',
      zoom: 10,
      infoWindow: { lng: 116.404, lat: 39.915 },
      showWindow: false
    }
  },
  methods: {
    ready({ map, BMap }) {
      this.map = map;
      this.BMap = BMap;
    },
    zoomEnd() {
      this.$nextTick(() => {
        this.zoom = this.map.getZoom();
      })
    },
    markerDetail(val) {
      this.infoWindow = val;
      this.showWindow = true;
    },
    infoWindowClose() {
      this.showWindow = false;
    },
    infoWindowOpen() {
      this.showWindow = true;
    }

  }
}
</script>

<style>
#map {
  width: 100%;
  height: 500px;
}
</style>

**Comment by Dafrok** [comment]
你最好把这些代码用三个反引号扩起来然后加上缩进，读这个代码太费劲了。。

**Comment by CristalFJJ** [comment]
抱歉哈，修改了点格式
把InfoWindow作为子组件，也是一样的，且同为子组件的label在鼠标缩放时也会消失
下面是demo
<template>
  <baidu-map id="map" :center="{lng: 116.404, lat: 39.915}" :zoom="zoom" @zoomend="zoomEnd" ak="您的ak" :scroll-wheel-zoom="true" @ready="ready">
    <bml-marker-clusterer :averageCenter="true">
      <bm-marker :icon="{url: 'http://developer.baidu.com/map/jsdemo/img/fox.gif', size: {width: 300, height: 157}}" :position="{lng: 116.404, lat: 39.915}" :rotation="45" @click="markerDetail({lng: 116.404, lat: 39.915})">
        <bm-label content="123456" :labelStyle="{color: 'red', fontSize : '16px'}" :offset="{width: -35, height: 30}"/>
        <bm-info-window :position="infoWindow" :show="showWindow" @clickclose="infoWindowClose" @open="infoWindowOpen">
        <p style="text-align:center;margin-bottom:10px">测试专用</p>
      </bm-info-window>
      </bm-marker>
    </bml-marker-clusterer>
  </baidu-map>
</template>

<script>
import { BaiduMap, BmlMarkerClusterer, BmMarker, BmInfoWindow,BmLabel,} from 'vue-baidu-map';
export default {
  components: {
    BaiduMap,
    BmlMarkerClusterer,
    BmMarker,
    BmInfoWindow,
    BmLabel
  },
  data() {
    return {
      map: '',
      BMap: '',
      zoom: 10,
      infoWindow: { lng: 116.404, lat: 39.915 },
      showWindow: false
    }
  },
  methods: {
    ready({ map, BMap }) {
      this.map = map;
      this.BMap = BMap;
    },
    zoomEnd() {
      this.$nextTick(() => {
        this.zoom = this.map.getZoom();
      })
    },
    markerDetail(val) {
      this.infoWindow = val;
      this.showWindow = true;
    },
    infoWindowClose() {
      this.showWindow = false;
    },
    infoWindowOpen() {
      this.showWindow = true;
    }

  }
}
</script>

<style>
#map {
  width: 100%;
  height: 500px;
}
</style>

**Comment by CristalFJJ** [comment]
> <template>
>   <baidu-map id="map" :center="{lng: 116.404, lat: 39.915}" :zoom="zoom" @zoomend="zoomEnd" ak="您的ak" :scroll-wheel-zoom="true" @ready="ready">
>     <bml-marker-clusterer :averageCenter="true">
>       <bm-marker :icon="{url: 'http://developer.baidu.com/map/jsdemo/img/fox.gif', size: {width: 300, height: 157}}" :position="{lng: 116.404, lat: 39.915}" :rotation="45" @click="markerDetail({lng: 116.404, lat: 39.915})">
>         <bm-label content="123456" :labelStyle="{color: 'red', fontSize : '16px'}" :offset="{width: -35, height: 30}"/>
>         <bm-info-window :position="infoWindow" :show="showWindow" @clickclose="infoWindowClose" @open="infoWindowOpen">
>         <p style="text-align:center;margin-bottom:10px">测试专用</p>
>       </bm-info-window>
>       </bm-marker>
>     </bml-marker-clusterer>
>   </baidu-map>
> </template>
> 
> <script>
> import { BaiduMap, BmlMarkerClusterer, BmMarker, BmInfoWindow,BmLabel,} from 'vue-baidu-map';
> export default {
>   components: {
>     BaiduMap,
>     BmlMarkerClusterer,
>     BmMarker,
>     BmInfoWindow,
>     BmLabel
>   },
>   data() {
>     return {
>       map: '',
>       BMap: '',
>       zoom: 10,
>       infoWindow: { lng: 116.404, lat: 39.915 },
>       showWindow: false
>     }
>   },
>   methods: {
>     ready({ map, BMap }) {
>       this.map = map;
>       this.BMap = BMap;
>     },
>     zoomEnd() {
>       this.$nextTick(() => {
>         this.zoom = this.map.getZoom();
>       })
>     },
>     markerDetail(val) {
>       this.infoWindow = val;
>       this.showWindow = true;
>     },
>     infoWindowClose() {
>       this.showWindow = false;
>     },
>     infoWindowOpen() {
>       this.showWindow = true;
>     }
> 
>   }
> }
> </script>
> 
> <style>
> #map {
>   width: 100%;
>   height: 500px;
> }
> </style>

**Comment by CristalFJJ** [comment]
抱歉哈
把InfoWindow作为子组件，也是一样的，且同为子组件的label在鼠标缩放时也会消失
下面是demo
```
<template>
  <baidu-map id="map" :center="{lng: 116.404, lat: 39.915}" :zoom="zoom" @zoomend="zoomEnd" ak="您的ak" :scroll-wheel-zoom="true" @ready="ready">
    <bml-marker-clusterer :averageCenter="true">
      <bm-marker :icon="{url: 'http://developer.baidu.com/map/jsdemo/img/fox.gif', size: {width: 300, height: 157}}" :position="{lng: 116.404, lat: 39.915}" :rotation="45" @click="markerDetail({lng: 116.404, lat: 39.915})">
        <bm-label content="123456" :labelStyle="{color: 'red', fontSize : '16px'}" :offset="{width: -35, height: 30}"/>
        <bm-info-window :position="infoWindow" :show="showWindow" @clickclose="infoWindowClose" @open="infoWindowOpen">
        <p style="text-align:center;margin-bottom:10px">测试专用</p>
      </bm-info-window>
      </bm-marker>
    </bml-marker-clusterer>
  </baidu-map>
</template>

<script>
import { BaiduMap, BmlMarkerClusterer, BmMarker, BmInfoWindow,BmLabel,} from 'vue-baidu-map';
export default {
  components: {
    BaiduMap,
    BmlMarkerClusterer,
    BmMarker,
    BmInfoWindow,
    BmLabel
  },
  data() {
    return {
      map: '',
      BMap: '',
      zoom: 10,
      infoWindow: { lng: 116.404, lat: 39.915 },
      showWindow: false
    }
  },
  methods: {
    ready({ map, BMap }) {
      this.map = map;
      this.BMap = BMap;
    },
    zoomEnd() {
      this.$nextTick(() => {
        this.zoom = this.map.getZoom();
      })
    },
    markerDetail(val) {
      this.infoWindow = val;
      this.showWindow = true;
    },
    infoWindowClose() {
      this.showWindow = false;
    },
    infoWindowOpen() {
      this.showWindow = true;
    }

  }
}
</script>

<style>
#map {
  width: 100%;
  height: 500px;
}
</style>
```

**Comment by Dafrok** [comment]
你的问题我已经成功复现了，这两天抽空查一下。

**Comment by CristalFJJ** [comment]
好

**Comment by CristalFJJ** [comment]
InfoWindow也可以单独的使用才对，marker是循环数组的话，就只需一个InfoWindow就行

**Comment by Dafrok** [comment]
可以是可以，但是百度地图为 Marker 类提供了 AddInfoWindow 的接口，可以省去你处理一些处理样式的逻辑。

**Comment by Dafrok** [comment]
找到原因了。你 Marker 的 icon 属性使用了匿名对象，这会导致 vue 在每次渲染的时候创建一个新的 icon 对象的引用，引用变化会导致 Marker 组件调用 setIcon 方法重新设置 icon。而百度地图 API 在重新设置 icon 时会重置 rotation。如果你急用，可以先使用具名对象替代。重置 rotation 的问题建议向官方论坛反馈一下，我认为这是个 bug。

**Comment by CristalFJJ** [comment]
抱歉，具名对象是怎么设置~~

**Comment by Dafrok** [comment]
匿名是这样的：

```html
<bm-marker :icon="{...}">
```

具名就是给它个名字

```vue
<template>
<bm-marker :icon="myIcon">
</template>

<script>
export default {
  data () {
    return: {myIcon: {...}}
  }
}
</script>
```

**Comment by CristalFJJ** [comment]
谢啦，不过这样的话Icon是变量就不行了~~，还有那个label缩放消失的问题~~

**Comment by Dafrok** [comment]
为什么 Icon 是变量就不行？

**Comment by Dafrok** [comment]
Label 的问题新开 issue 吧，方便其他人查询。

**Comment by CristalFJJ** [comment]
因为我的marker是循环的，每个点的icon对应的是数组里相应的属性，是要根据数组中的属性来变化，如果是data里面的话，一改就所有都改了，而且用方法method 做判断return也是不行~

**Comment by Dafrok** [comment]
你可以在 computed 属性里 return一个 iconList

**Comment by Dafrok** [comment]
但是最好还是反馈到官方论坛，毕竟 API 层面的问题组件库是没办法解决的。

**Comment by CristalFJJ** [comment]
好的，感谢您的指导 ^ ^
