### ISSUE TITLE
关于 测量尺 和 标注 怎么去添加，有封装好的 标签吗

### ISSUE THREAD

**Issue by zhaixi** [Dafrok/vue-baidu-map#166]
https://user-images.githubusercontent.com/29477194/31592463-08c657b0-b25b-11e7-83d2-82169bce0a5f.png

**Comment by Dafrok** [comment]
图从何来？

**Comment by zhaixi** [comment]
是从 百度地图官网上找到的，就是这种工具类该怎么去添加，vue baidu map 里面有类似封装好的功能吗？类似于控件里的 比例尺 和 缩放的那种

**Comment by Dafrok** [comment]
提供了自定义控件组件。你可以结合百度地图 JS API 推荐的一些开源库来使用。

**Comment by zhaixi** [comment]
我用自定义组件，利用百度地图 JS API，加上了这个功能，可是发现用  element.vue 里的<el-dialog>这个写，发现他会有偏差，这个怎处理？
图片如下：
https://user-images.githubusercontent.com/29477194/31605553-19d93f16-b299-11e7-8556-06b4aea6a57e.png

**Comment by Dafrok** [comment]
transform 会影响百度的定位，需要等 transform 的元素渲染完毕再初始化地图。我把这个问题补充在文档里吧。

**Comment by Dafrok** [comment]
`position: fixed` 会影响百度地图的定位，你可以向官方社区反馈下这个问题，我之前反馈过没有回复。如果你着急用的话，把 fixed 的元素用 absolute 模拟一下即可。

**Comment by Dafrok** [comment]
文档中添加了引入第三方控件的指导，可以参考下。
传送门：https://dafrok.github.io/vue-baidu-map/#/zh/control/control

**Comment by zhaixi** [comment]
太感谢了

**Comment by zhaixi** [comment]
额。。。貌似还是有异常，首次进入自定义控件Map的时候 正常，但是，从自定义控件 切换到 全景下，再次切换到自定义控件页面，然后使用 地图测距，就不触发这个方法，测距无效，这个怎么弄？？？
还有 import DistanceTool from 'bmaplib.distancetool' ，bmaplib.distancetool 这个是外部引入的js 吗？
路书 import {BmlLushu} from 'vue-baidu-map'  ，他们两个不一样吗？路书这个直接就可以用了
