### ISSUE TITLE
wap端不能显示地图

### ISSUE THREAD

**Issue by pangxieju** [Dafrok/vue-baidu-map#167]
PC浏览器上使用基本没问题，在手机浏览器上测试地图无法显示。
手机系统：安卓 4.4.4
浏览器：QQ 手机浏览器 7.9.0.3634
检查浏览器代码，在 QQ 手机浏览器 html 里没有写出标签；

**Comment by Dafrok** [comment]
https://github.com/Dafrok/vue-baidu-map/issues/86
