### ISSUE TITLE
点聚合过滤数据的时候报错

### ISSUE THREAD

**Issue by celleychen** [Dafrok/vue-baidu-map#168]
点聚合的数组进行过滤时候报错，markers数组更新的时候如果存在之前存在的值，是不是不行呢？

  <bml-marker-clusterer :averageCenter="true">
    <bm-marker v-for="marker of markers" :position="{lng: marker.lng, lat: marker.lat}"></bm-marker>
  <bml-marker-clusterer>

It seems there are duplicate keys that is causing an update error. Make sure each v-for item has a unique key.
Error in nextTick: "TypeError: Cannot read property 'key' of undefined"

**Comment by Dafrok** [comment]
```
Error in nextTick: "TypeError: Cannot read property 'key' of undefined"
```
看看你哪个变量引用了 key 这个属性

**Comment by Dafrok** [comment]
@celleychen 还有后续问题吗？
