### ISSUE TITLE
没有找到清除覆盖物的方法

### ISSUE THREAD

**Issue by qinyang1018** [Dafrok/vue-baidu-map#17]
我又来  我现在想要在检索后清除所有的覆盖物 然后添加检索第一条的数据为marker   然后可以拖动改变位置   没有找到clearOverlays清除覆盖物的方法

**Comment by Dafrok** [comment]
用 mvvm 的思想解决问题 清除数据就可以了……

**Comment by qinyang1018** [comment]
没太懂 我看百度js原生的api是有清除方法的  这个mvvm的思想是该怎么来清除呢？

**Comment by Dafrok** [comment]
v-if

**Comment by qinyang1018** [comment]
```
 resultshtmlset: function(results) {
                console.log(results);
                this.lat = results.point.lat;
                this.lng = results.point.lng;
                this.data.name = results.title;
                map.clearOverlays();
            }
```
我这么清除了。。。。

**Comment by Dafrok** [comment]
这么做不行，你把视图层的 overlay 去掉了，组件的引用还在，相当于在 mvvm 里用 jquery 操作 DOM。请用 v-if 控制独立的点，用 v-for 控制多个点。

**Comment by qinyang1018** [comment]
你的意思是让我循环清除？

**Comment by Dafrok** [comment]
不是………………你循环一个数组，数组里存点的信息，你操作这个数组，marker 就会发生相应的变化。

**Comment by qinyang1018** [comment]
大佬  我实在是转不过来这个思想了，能提供个例子吗。。。。

**Comment by Dafrok** [comment]
你怎么控制一个div的显隐？

**Comment by qinyang1018** [comment]
...我竟无言以对  我还是先看看基础吧  这是我第三天写js  好多都不懂  我在自己研究看看   谢了
