### ISSUE TITLE
鼠标绘制工具异常

### ISSUE THREAD

**Issue by zhaixi** [Dafrok/vue-baidu-map#171]
大神，劳烦看一下，刚刚接触地图没多久，比较菜，所以遇到了一些bug，求助以下
1.用vue Baidu Map 引入API 里的，点击画圆，就一直报下图的错误，鼠标放入地图，就会重复报这个错误，不知道怎么解决。
https://user-images.githubusercontent.com/29477194/31645621-9fb0648e-b32f-11e7-8f05-7baaa79849ab.png
2.鼠标测量尺，自定义一个控件，
<bm-control anchor="BMAP_ANCHOR_TOP_RIGHT" :offset="{width: 130, height: 80}">
       <button @click="addDistance()">
            <span >鼠标测距</span>
       </button>
</bm-control>
，首次进入点击正常使用，但是别的页面也引用这个的时候，就会分别出现以下异常
如图：

https://user-images.githubusercontent.com/29477194/31653401-0884b490-b355-11e7-8be6-1efc997e5fa8.png
https://user-images.githubusercontent.com/29477194/31653402-08b9f952-b355-11e7-9d13-dec451258355.png
https://user-images.githubusercontent.com/29477194/31653427-23750b7e-b355-11e7-83a9-e5bb1acf8b11.png
但是刷新页面后，首次进入当前页面测量尺正常，切换页面后就会报错。
劳烦看一下，谢谢啦

**Comment by Dafrok** [comment]
有没有 keep-alive？

**Comment by zhaixi** [comment]
没有用这个

**Comment by Dafrok** [comment]
最好能提供一个复现用例，光看错误信息看不出什么。

**Comment by zhaixi** [comment]
您那有vue Baidu map 的 鼠标测量尺 和 鼠标绘制工具之类的例子吗？ 我这个太乱了，不知道怎么去做

**Comment by Dafrok** [comment]
没有。你可以试试引入这个 https://github.com/Dafrok/BMapLib.DistanceTool/blob/master/index.js，我刚刚封装的，还没测试和发布。

**Comment by Dafrok** [comment]
这个问题和之前的问题重复了，先关闭了。
