### ISSUE TITLE
怎么实现多个marker 和多个infowindow，用循环不行啊

### ISSUE THREAD

**Issue by willy8239917** [Dafrok/vue-baidu-map#175]
我想在地图上添加多个marker，对应多个infoWindow；
代码如下
 <bm-marker v-for="(m,index) in markers" :position="m" :dragging="true" animation="BMAP_ANIMATION_BOUNCE">
     	<bm-info-window  :position="m" title="Info Window Title" :show="infoWinOpen" @close="infoWindowClose" @open="infoWindowOpen" >
	       <p v-text="infoContent"></p> 
	      <button @click="clear">Clear</button> 
	    </bm-info-window>
  </bm-marker>
点是出来多个，但是窗体才出现最后一个，这个怎么解决，万分感谢

**Comment by Dafrok** [comment]
请把问题描述清晰

**Comment by willy8239917** [comment]
我想在地图上添加多个marker，对应多个infoWindow；
代码如下

<bm-info-window :position="m" title="Info Window Title" :show="infoWinOpen" @close="infoWindowClose" @OPEN="infoWindowOpen" >

<button @click="clear">Clear


点是出来多个，但是窗体才出现最后一个，这个怎么解决，万分感谢

**Comment by willy8239917** [comment]
<bm-marker v-for="(m,index) in markers" :position="m" :dragging="true" animation="BMAP_ANIMATION_BOUNCE">
     	<bm-info-window  :position="m" title="Info Window Title" :show="infoWinOpen" @close="infoWindowClose" @open="infoWindowOpen" >
	       <p v-text="infoContent"></p> 
	      <button @click="clear">Clear</button> 
	    </bm-info-window>
    </bm-marker>

**Comment by Dafrok** [comment]
百度地图只允许同时显示一个 InfoWindow，如果类似需求请使用其它覆盖物代替。

**Comment by willy8239917** [comment]
嗖嘎，但是用什么覆盖物代替了，显示的东西还挺多

**Comment by Dafrok** [comment]
如果现有覆盖物不满足，可以自定义

**Comment by willy8239917** [comment]
好的，谢谢

**Comment by se905565669** [comment]
![1548039892 1](https://user-images.githubusercontent.com/29478382/51450822-350a0280-1d6d-11e9-854d-a034def3c7a1.jpg)
![1548039918 1](https://user-images.githubusercontent.com/29478382/51450830-42bf8800-1d6d-11e9-8de1-5f902796f5fe.jpg)
![qq 20190121111033](https://user-images.githubusercontent.com/29478382/51450849-5834b200-1d6d-11e9-9383-27723b5ef0b8.png)

 @Dafrok 建议在文档中新增注释或者说明把这个方法给说明一下，看着文档写这个很蛋疼，就怕组件调用顺序出错报错，还不好处理。。。这位LZ应该也是同样的问题，我看官网看了整整一下午也没看到相关的代码案例，都准备换个方式写了，还好的是试成功了。。省了很多事。。

**Comment by tsurumure** [comment]
@se905565669 感谢，另外建议在[文档](https://dafrok.github.io/vue-baidu-map/#/zh/overlay/marker)说明一下

**Comment by Dafrok** [comment]
InfoWindow 可以作为 Marker 的子组件出现，这个在文档里有写

**Comment by liuliuzx** [comment]
@tsurumure 老哥，我用你的方法，会重复触发几次close 和open方法啊，可以把代码贴一下吗？
