### ISSUE TITLE
测距页面切换地图后，再次进入测距不显示

### ISSUE THREAD

**Issue by zhaixi** [Dafrok/vue-baidu-map#180]
首次进入自定义控件Map的时候 正常，但是，从自定义控件 切换到 全景下，再次切换到自定义控件页面，然后使用 地图测距，触发测距，但是测距无效，这个怎么弄？？？是第一次离开后，监听方法给移除了吗？
还有 import DistanceTool from 'bmaplib.distancetool' ，bmaplib.distancetool 这个是外部引入的js 吗？
路书 import {BmlLushu} from 'vue-baidu-map' ，他们两个不一样吗？路书这个直接就可以用了

**Comment by Dafrok** [comment]
你的问题复现不了，请提供复现用例。

**Comment by zhaixi** [comment]
就是 https://dafrok.github.io/vue-baidu-map/#/zh/control/control 里面，
进入自定义控件导航下，执行鼠标测距，显示正常，从左侧导航切换到全景模块下，然后在重新切换到 自定义控件 导航下，这时候执行鼠标测距方法，鼠标测距不显示，方法不执行。怎样让他再次执行这个方法呢？

**Comment by Dafrok** [comment]
我明白了，一开始以为是同时使用测距和全景模式会出问题，这个应该是 bug，我查一下。

**Comment by Dafrok** [comment]
我看了下测距工具的源码，页面上不允许同时 open 两次测距工具，第二次进入页面的时候没有把第一个测距工具 close 掉。所以你只要在释放地图的同时 close 掉测距工具就行了。

**Comment by Dafrok** [comment]
测距工具本身也有个全局变量的问题，我尝试修复一下

**Comment by Dafrok** [comment]
是 BMapLib.DistanceTool 的问题，一个闭包没有被释放，你升级一下这个包就行了，文档稍后也会进行跟进的。
