### ISSUE TITLE
请问能支持离线地图吗

### ISSUE THREAD

**Issue by taojianjian32** [Dafrok/vue-baidu-map#181]
或有什么途径吗

**Comment by Dafrok** [comment]
http://bbs.lbsyun.baidu.com/forum.php

**Comment by bitqiang** [comment]
请问楼主有啥方法支持离线地图了吗？ 我自己下载了瓦图，项目内网使用的。不知道怎么样离线使用这个库？

**Comment by Dafrok** [comment]
国内的地图均不支持脱机工作，存在一些敏感问题，建议用国外的地图产品
