### ISSUE TITLE
vue引入鼠标绘制工具条库 

### ISSUE THREAD

**Issue by zhaixi** [Dafrok/vue-baidu-map#182]
在 
mounted(){
this.mapfun();
} 
里面 引入这个方法，代码如下：
<baidu-map class="map" center="上海" id="map" @ready="handler"></baidu-map>
方法如下
mapfun(){
        this.map = new BMap.Map("map",{enableMapClick:false});
        this.map.centerAndZoom(new BMap.Point(116.413554,39.911013),11);
        this.map.enableScrollWheelZoom();
        var styleOptions = {
            strokeColor:"red",    //边线颜色。
            fillColor:"red",      //填充颜色。当参数为空时，圆形将没有填充效果。
            strokeWeight: 3,       //边线的宽度，以像素为单位。
            strokeOpacity: 0.8,    //边线透明度，取值范围0 - 1。
            fillOpacity: 0.6,      //填充的透明度，取值范围0 - 1。
            strokeStyle: 'solid' //边线的样式，solid或dashed。
        }
        //实例化鼠标绘制工具
        var drawingManagerNew = new BMapLib.DrawingManager(this.map, {
            isOpen: false, //是否开启绘制模式
            enableDrawingTool: true, //是否显示工具栏
            drawingToolOptions: {
                anchor: BMAP_ANCHOR_TOP_RIGHT, //位置
                offset: new BMap.Size(5, 5), //偏离值
               drawingTypes : [
                    BMAP_DRAWING_MARKER,
                    BMAP_DRAWING_CIRCLE,
                    BMAP_DRAWING_POLYLINE,
                    BMAP_DRAWING_POLYGON,
                    BMAP_DRAWING_RECTANGLE 
               ]
            },
            circleOptions: styleOptions, //圆的样式
            polylineOptions: styleOptions, //线的样式
            polygonOptions: styleOptions, //多边形的样式
            rectangleOptions: styleOptions //矩形的样式
        }); 
    },
直接在 index.html 里面引入 <script type="text/javascript" src="http://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js"></script>
出现异常，
[Vue warn]: Error in mounted hook: "TypeError: BMapLib.DrawingManager is not a constructor"
TypeError: BMapLib.DrawingManager is not a constructor
这个怎么改？是引入的时候错误吗？

**Comment by Dafrok** [comment]
`TypeError: BMapLib.DrawingManager is not a constructor` 这个问题和组件库无关，请在其它技术社区询问。
