### ISSUE TITLE
使用Marker动态改变位置，传入的rotation旋转角度没有发生改变

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#184]
<img width="689" alt="22" src="https://user-images.githubusercontent.com/21167738/31805936-5641ccf0-b52a-11e7-8add-93c4170ef5f1.png">

**Comment by Dafrok** [comment]
什么叫使用 marker 动态改变位置？

**Comment by Dafrok** [comment]
什么叫使用 marker 动态改变位置？

**Comment by front-end-john** [comment]
就是每次从接口获取一个最新的position，然后更新marker

**Comment by Dafrok** [comment]
什么地方用到 marker 组件了？

**Comment by front-end-john** [comment]
下面是浏览器报错
<img width="732" alt="error" src="https://user-images.githubusercontent.com/21167738/31806527-3f89593e-b52e-11e7-8d8d-ba0220a754e5.png">

**Comment by Dafrok** [comment]
这种报错什么信息都没有，你做好定位一下出问题的点，和文档的实例对比一下哪里不一样

**Comment by front-end-john** [comment]
下面是代码， this.setRotation is not a function，这个地方怎么使用setRotation
<template>
  <baidu-map class="map" :center="{lng: 113.834719, lat: 22.618067}" :zoom="15">
    <bm-marker :position="list.position"
               :dragging="false"
               :rotation="list.rotation"
               :icon="icon">
      <bm-label :content="list.content"
              :label-style="{color: '#323232', fontSize : '10px',
              borderRadius: '20px', border: 'none', padding: '0 5px'}"
              :offset="{width: -35, height: -20}"/>
    </bm-marker>
  </baidu-map>
</template>

<script type="text/ecmascript-6">
  export default {
    data() {
      return {
        icon: {
          url: require('../overlay/img/icon-bus-1.png'),
          size: {
            width: 20,
            height: 40
          },
          opts: {
            anchor: {
              width: 10,
              height: 40
            },
            imageSize: {
              width: 20,
              height: 40
            }
          }
        },
        list: {
          position: {lng: 113.834719, lat: 22.618067},
          content: '测B4434',
          rotation: 180
        }
      };
    },
    created() {
      this.ws.onmessage = (event) => {
        if (event.data) {
          let dataObj = JSON.parse(event.data);
          let typeArr = Object.keys(dataObj);
          if (typeArr[0] === 'gps') {
            this.list.position = {
              lng: parseFloat(dataObj.gps.lng),
              lat: parseFloat(dataObj.gps.lat)
            };
            this.list.type = dataObj.gps.type;
            this.list.rotation = parseFloat(dataObj.gps.course);
          }
        }
      };
    }
  };
</script>

<style lang="stylus" rel="stylesheet/stylus">

</style>

**Comment by Dafrok** [comment]
可以排个版吗？

**Comment by front-end-john** [comment]
排好了，你刷新看下

**Comment by Dafrok** [comment]
好 我看一下

**Comment by Dafrok** [comment]
这是个 bug，我修复后发一版。

**Comment by front-end-john** [comment]
好，顺便问个问题，能否实现点击bm-marker去控制里面的bm-label切换显示和隐藏？

**Comment by Dafrok** [comment]
请更新至 0.18.3
