### ISSUE TITLE
请问该项目不支持ie11吗？

### ISSUE THREAD

**Issue by zhongzhifa** [Dafrok/vue-baidu-map#185]
我用ie11打开您的项目预览地址，发现一片空白。在我的项目中，使用局部注册，地图也是出不来

**Comment by Dafrok** [comment]
理论上需要打 polyfill

**Comment by Dafrok** [comment]
看下你的控制台需要打什么 polyfill，如果打完 polyfill 还有问题再开这个 issue。

**Comment by zhongzhifa** [comment]
好的，谢谢。控制台没有任何报错

**Comment by Dafrok** [comment]
你使用的版本是哪个？

**Comment by zhongzhifa** [comment]
直接npm最新版，重新测试，有报错了，Error in mounted hook: "ReferenceError: “Promise”未定义"

**Comment by Dafrok** [comment]
那就对了 去打 polyfill 吧

**Comment by zhongzhifa** [comment]
好的，谢谢。感谢你的及时回复。
