### ISSUE TITLE
局部注册使用v-show会使center失效

### ISSUE THREAD

**Issue by zhongzhifa** [Dafrok/vue-baidu-map#186]
`<baidu-map class="map" ak="****" :scroll-wheel-zoom="true" :double-click-zoom="false" center="广州市" @click="marker"></baidu-map>`
使用v-if能够正常显示广州市，使用v-show显示的是非洲+南极洲+亚洲的最小图

**Comment by Dafrok** [comment]
不支持 v-show，原因比较复杂，建议全部换成 v-if。

**Comment by zhongzhifa** [comment]
好的。

**Comment by kk-fan** [comment]
这个貌似是因为在一开始处于v-show=false状态下  地图渲染是一个点 当v-show=true时 中心点就跑到坐上角了 我是在使用element的tabs标签页 当地图不是处于第一个tab是遇到的 请问有解决方法吗
