### ISSUE TITLE
怎么实时获取地图zoom缩放级别

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#188]
怎么实时获取地图zoom缩放级别

**Comment by Dafrok** [comment]
数据驱动视图 + 双向绑定

**Comment by front-end-john** [comment]
zoomend结束时，里面的数据没有zoom，可以给个例子不

**Comment by Dafrok** [comment]
文档里就有，认真看一遍吧

**Comment by gypjoy** [comment]
双向绑定zoom，鼠标滚动放大缩小，zoom并不会变化

**Comment by gypjoy** [comment]
<baidu-map class="map-view" :center="center" :mapClick="false" :zoom="zoom" :scroll-wheel-zoom="true" @zoomstart="zoomstart" ref="map">
