### ISSUE TITLE
请问咱们框架，未来会有很大变动吗？

### ISSUE THREAD

**Issue by brahmachen** [Dafrok/vue-baidu-map#19]
如题。现在处于开发的什么阶段？未来会有扩充或者较大的变化吗？

**Comment by Dafrok** [comment]
0.1 版本后 API 基本稳定了，以后只会有一些扩充和完善。

**Comment by brahmachen** [comment]
扩充是哪方面的呢？

**Comment by Dafrok** [comment]
http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html

**Comment by brahmachen** [comment]
好吧
