### ISSUE TITLE
定位组件点严重偏移

### ISSUE THREAD

**Issue by happlyfox** [Dafrok/vue-baidu-map#190]
bm-geolocation 组件 定位组件点严重偏移

**Comment by Dafrok** [comment]
http://bbs.lbsyun.baidu.com/forum.php

**Comment by Dafrok** [comment]
使用中遇到问题请按照以下步骤进行检查：

- [] 查看 ISSUE 中是否有人提过相同的问题。
- [] 参照文档中的示例代码做对比，示例是否有同样的问题，你的代码与示例哪里不一样。
- [] 输入相同的参数，组件库的输出与百度地图是否相同。
- [] 提供问题复现用例
    - 可以是一段代码，务必使用三个连续反引号加语言名称 （如：```vue） 括起进行排版（参考 https://guides.github.com/features/mastering-markdown/）
    - 也可以是一个在线演示（推荐使用 https://codepen.io）。
- [] 定位出问题的点，具体加入了哪个参数 / 哪行代码 / 做了哪些操作能使问题复现。

百度地图组件库是百度地图 JS API 的一个视图逻辑的抽象，不涉及任何核心业务逻辑。如果您的问题不满足前三项条件，请移步官方社区 http://bbs.lbsyun.baidu.com/forum.php 进行反馈。

不满足以上任何条件的 ISSUE，将被立即关闭。
