### ISSUE TITLE
bm-info-window在v-for的渲染问题

### ISSUE THREAD

**Issue by zhj-040352** [Dafrok/vue-baidu-map#191]
我的代码：
`<div class="addMarker">

        <bm-marker v-for="marker of markers" :position="{lng: marker.lng, lat: marker.lat}" :dragging="false" @click="infoWindowOpen(marker)">

          <bm-info-window title="实时数据：" :closeOnClick="true" :show="marker.showFlag" @close="infoWindowClose(marker)" @open="infoWindowOpen(marker)">

            <p v-text="marker.contents"></p>

          </bm-info-window>

</bm-marker>

`

`<script>

export default {

  data () {
    return {
      markers: []
    }
  },

  mounted () {
    this.loadnewMarker()
  },

  methods: {

    infoWindowClose: function (marker) {
      marker.showFlag = false
    },

    infoWindowOpen: function (marker) {
      marker.showFlag = true
      marker.contents = 'dddddd'
    },

    loadnewMarker: function () {
      for (var i = 0; i < 2; i++) {
        var p = {lng: Math.random() * 40 + 85, lat: Math.random() * 30 + 21}
        this.markers.push(p)
      }

    }

  }

}
</script>`

测试消息框的时候， 点击不起作用， 控制台显示inforWindowClose/Open接受marker和数据更新都在执行， 但是 bm-info-window的show/content都没有能工作， 是哪儿出问题了吗？

**Comment by Dafrok** [comment]
问题没描述清楚。什么叫不起作用？你希望它什么样，实际什么样？

**Comment by zhj-040352** [comment]
谢谢回复！
希望的behavior:
点击不同的bm-marker显示不同的bm-info-window. 上面这段代码点击不显示info-window. 但是我刚刚改动了代码， 再inforwindowOpen函数里面加了经纬度赋值就work了， 无法理解。。。

`<bm-info-window title="实时数据：" :closeOnClick="true" :autoPan="true" :show="marker.showFlag" @close="infoWindowClose(marker)" @open="infoWindowOpen(marker)">

            <div class="infoContent">

              <p>经度: {{pLng}}</p>

              <p>维度: {{pLat}}</p>

            </div>
          </bm-info-window>
`
`
infoWindowOpen: function (marker) {
      marker.showFlag = true
      this.pLng = marker.lng
      this.pLat = marker.lat
    },`

**Comment by Dafrok** [comment]
能给你的代码排个版吗？我在 issue template 里已经说明了排版方法。

**Comment by zhj-040352** [comment]
在哪儿可以看到issue template? 这个排版我也很无奈 ：）

**Comment by zhj-040352** [comment]
还是有问题， 后面的代码放大缩小地图后点击bm-marker info-window出不来。。。

**Comment by zhj-040352** [comment]
从新排版了一下
希望的behavior:
点击不同的bm-marker显示不同的bm-info-window. 上面这段代码点击不显示info-window. 我改动了代码， 再inforwindowOpen函数里面加了经纬度赋值就work了， 第一次点击work，但是第二次点击不显示info-window。
`<div class="addMarker">

        <bm-marker v-for="marker of markers" :position="{lng: marker.lng, lat: marker.lat}" :dragging="false" @click="infoWindowOpen(marker)">

          <bm-info-window title="实时数据：" :closeOnClick="true" :autoPan="true" :show="marker.showFlag" @close="infoWindowClose(marker)" @open="infoWindowOpen(marker)">

            <div class="infoContent">

              <p>温度：{{tempreture}}</p>
              <p>湿度：{{humidity}}</p>
              <p>电压：{{pressure}}</p>
              <p>经度: {{pLng}}</p>
              <p>维度: {{pLat}}</p>

            </div>

          </bm-info-window>

        </bm-marker>`

`<script>
export default {
  data () {
    return {
      markers: [],
      pLng: '',
      pLat: ''
    }
  }，

  mounted () {
    this.loadnewMarker()
  },

  methods: {
    infoWindowClose: function (marker) {
      marker.showFlag = false
    },
    infoWindowOpen: function (marker) {
      marker.showFlag = true
      this.pLng = marker.lng
      this.pLat = marker.lat
    },
    loadnewMarker: function () {
      for (var i = 0; i < 2; i++) {
        var p = {lng: Math.random() * 40 + 85, lat: Math.random() * 30 + 21}
        this.markers.push(p)
      }
    }
  }
}
</script>`

**Comment by ly645091114** [comment]
这个问题我也遇到点击第一次是能显示信息窗口的，但是关闭后再点击就无法显示了

**Comment by Dafrok** [comment]
你发 issue 的时候会有一个注释，你已经删掉了，在评论框下面有一个 Markdown styling guide 你最好看一下规范

**Comment by zhj-040352** [comment]
Ok thanks! 我这个问题有解决办法吗？ 个人感觉是个bug

**Comment by Dafrok** [comment]
然而你的代码太乱了 请编辑一下……

**Comment by zhj-040352** [comment]
编辑了一下， 以下代码的问题：
1： info-window, 第二次点击无法显示
2：在infoWindowOpen里面拿掉this.pLng this.pLat 的赋值语句，infoWindow 就不能显示了

```
  <bm-marker v-for="marker of markers" :position="{lng: marker.lng, lat: marker.lat}" :dragging="false" @click="infoWindowOpen(marker)">

      <bm-info-window title="实时数据：" :closeOnClick="true" :autoPan="true" :show="marker.showFlag" @close="infoWindowClose(marker)" @open="infoWindowOpen(marker)">

        <div class="infoContent">

          <p>经度: {{pLng}}</p>
          <p>维度: {{pLat}}</p>

        </div>

      </bm-info-window>

    </bm-marker>

```

```
<script>
  export default {
    data () {
       return {
        markers: [],
        pLng: '',
        pLat: ''
        }
    }，

    mounted () {
      this.loadnewMarker()
    },
 
    methods: {
      infoWindowClose: function (marker) {
        marker.showFlag = false
      },
      infoWindowOpen: function (marker) {
        marker.showFlag = true
        this.pLng = marker.lng
        this.pLat = marker.lat
      },
    loadnewMarker: function () {
      for (var i = 0; i < 2; i++) {
        var p = {lng: Math.random() * 40 + 85, lat: Math.random() * 30 + 21}
        this.markers.push(p)
      }
    }
  }
}
</script>
```

**Comment by zhj-040352** [comment]
谢谢回复， 问题在于经纬度变量必须在info-window用到的函数里被访问才会有效， 上面的代码如果在close函数里置空PLng和pLat二次点击就有效了， 不知道是Vue的用法还是这个组件的用法。

**Comment by Dafrok** [comment]
我大概知道你是什么问题了，估计是你设置了 closeOnClick，在点击地图触发窗体开启的同时把自己干掉了。用 nextTick 解决吧。

**Comment by alexKeleon** [comment]
> 我大概知道你是什么问题了，估计是你设置了 closeOnClick，在点击地图触发窗体开启的同时把自己干掉了。用 nextTick 解决吧。

遇到了类似的问题：
```
<baidu-map class="map" ak="G27wbIITCDYT83a5OxvN6hLm67KtZvwZ" :center="center" :zoom="zoom" @ready="handler">
        <div v-for="(item, itemIndex) of deviceConfigList" v-bind:key="itemIndex">
          <bm-marker :position="item.geolocation" :dragging="true" @click="infoWindowOpen(item)">
            <bm-info-window :position="item.geolocation" :title="item.serial_id" :show="item.show" :closeOnClick="false" @close="infoWindowClose(item)" @open="infoWindowOpen(item)">
              {{item.device_desc}}
            </bm-info-window>
          </bm-marker>
        </div>
      </baidu-map>


 methods: {
    handler ({BMap, map}) {
      this.zoom = 15
    },
    infoWindowClose (item) {
      item.show = false
    },
    infoWindowOpen (item) {
      console.log(item)
      item.show = true
    }
  }
```
就算把closeOnclick设置成false, onclick后也仍然打不开窗体

**Comment by zhj-040352** [comment]
收到 谢谢
| |
张海健
|
|
邮箱：zhj_040352@126.com
|

签名由 网易邮箱大师 定制

在2019年11月14日 22:37，yichao.wu 写道：

我大概知道你是什么问题了，估计是你设置了 closeOnClick，在点击地图触发窗体开启的同时把自己干掉了。用 nextTick 解决吧。

遇到了类似的问题：

<baidu-map class="map" ak="G27wbIITCDYT83a5OxvN6hLm67KtZvwZ" :center="center" :zoom="zoom" @ready="handler">

        <div v-for="(item, itemIndex) of deviceConfigList" v-bind:key="itemIndex">

          <bm-marker :position="item.geolocation" :dragging="true" @click="infoWindowOpen(item)">

            <bm-info-window :position="item.geolocation" :title="item.serial_id" :show="item.show" :closeOnClick="false" @close="infoWindowClose(item)" @open="infoWindowOpen(item)">

              {{item.device_desc}}

            </bm-info-window>

          </bm-marker>

        </div>

      </baidu-map>





 methods: {

    handler ({BMap, map}) {

      this.zoom = 15

    },

    infoWindowClose (item) {

      item.show = false

    },

    infoWindowOpen (item) {

      console.log(item)

      item.show = true

    }

  }



就算把closeOnclick设置成false, onclick后也仍然打不开窗体
