### ISSUE TITLE
关于聚合点 marker 问题

### ISSUE THREAD

**Issue by zhaixi** [Dafrok/vue-baidu-map#195]
我在<el-dialog> 中加入了 vue baidu map ，然后首次进入弹层 点聚合正常，关闭弹层 把聚合点数组 制空，然后再次进入弹层地图，发现聚合点不显示，只要轻轻拖动地图，点聚合显示，这是什么引起的？

**Comment by Dafrok** [comment]
请发 issue 时参照预置 issue 模板
