### ISSUE TITLE
路书暂停和行进问题

### ISSUE THREAD

**Issue by tingwu55** [Dafrok/vue-baidu-map#196]
您好！参照您的路书示例成功引入路书组件。我现在需要使用两个按钮控制行进和暂停。但是暂停按钮只有第一次有效，并且再次点击开始后图标都是从最开始的位置重新运动而不是从暂停的位置开始。看了许久也没找着原因。以下是我的代码：
<bm-driving 
    :start="startPoint" 
    :end="endPoint"  
    @searchcomplete="handleSearchComplete" 
    :panel="false" 
    :autoViewport="true"></bm-driving>
  <bml-lushu
    @stop="reset"
    :play="play"
    :speed="5000"
    :infoWindow="false"
    :autoView="true"
    :path="path"></bml-lushu>
  <bm-view class="map-view"></bm-view>
  <bm-scale anchor="BMAP_ANCHOR_TOP_RIGHT"></bm-scale>
  <div class="tool-bar">
    <-button @click="play = true" type="primary" class="btn">开始</-button>
    <-button @click="play = false" type="primary" class="btn">暂停</-button>
  </div>
另： 使用 import LuShu from "bmaplib.lushu"; 调用LuShu .start() & LuShu .pause()效果也是一样的（暂停之后都是从头开始运动而不是从暂停的位置）

**Comment by Dafrok** [comment]
文档有哪里写的不明白吗？

**Comment by tingwu55** [comment]
文档很清楚，我已经成功引入路书组件了。就是暂停会有上述的问题。我是参考的示例代码，只是我加了两个按钮来改变绑定的**play**属性，用以控制暂停和开始
<-button **@click="play = true"** type="primary" class="btn">开始 <-button **@click="play = false"** type="primary" class="btn">暂停

**Comment by Dafrok** [comment]
我没有复现成功，但感觉上是地图被重载了

**Comment by tingwu55** [comment]
地图应该没有被重载，因为我在地图<baidu-map>@ready="handler"函数只进入一次。但是就是不明白为什么会每次都从最开始的位置开始

**Comment by tong36** [comment]
@tingwu55  ，你好，想问下你最后怎么解决的？

**Comment by Dafrok** [comment]
@tong36 你遇到了相同的问题吗，可不可以提供一个复现场景

**Comment by tong36** [comment]
@Dafrok 我试着做个可以复现的场景,发上来、

**Comment by Dafrok** [comment]
codepen 和 jsfiddle 就可以

**Comment by tingwu55** [comment]
@tong36 当时没有找着具体原因，所有没有解决。

**Comment by tong36** [comment]
应该不是这个库的原因，我在单独调用百度地图也有问题，应该是我使用的问题，我再去看看api。
@Dafrok  还有那个线上复现我就先不做了，谢谢了你了。

**Comment by Dafrok** [comment]
@tong36 好的，有问题及时反馈

**Comment by tong36** [comment]
@Dafrok  这个问题你看一下，什么问题、
文档链接 ： https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/lushu
问题描述：就是当小车第一次正常跑完结束后，点击操作下面的按钮小车开始跑动后，然后再次点击操作下面的按钮，理想输出应该是小车暂停，实际则无反应，再次点击则暂停。

**Comment by Dafrok** [comment]
@tong36 看了一下这里是有点问题，不过是示例本身写的不好，和楼主的问题应该没关系，我稍后改一下

**Comment by tong36** [comment]
另外我还想咨询一下
**文档链接** ： https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/lushu

暂停 和 停止都是属性  _play_  为 _false_ 就可以了吗
这个是我找的百度的路书地址： http://api.map.baidu.com/library/LuShu/1.2/docs/symbols/BMapLib.LuShu.html

**Comment by Dafrok** [comment]
查了一下发现是路书的 bug。。。

刚发了新版，文档等 travis build 结束之后这块应该就正常了

**Comment by tong36** [comment]
@Dafrok  贴下地址 谢谢了。

**Comment by Dafrok** [comment]
地址没变，还是原来那个

**Comment by tong36** [comment]
@Dafrok  有个小问题，我就不新开 issus 了。
路书文档： https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/lushu
问题描述： 轨迹运行结束后，信息窗体有点问题。
谢谢了。

**Comment by Dafrok** [comment]
还真是，大意了。

**Comment by Dafrok** [comment]
@tong36 已发版。

**Comment by tong36** [comment]
@Dafrok  谢谢了。

**Comment by tong36** [comment]
@Dafrok  你好，实在抱歉，还有个问题想咨询一下。

**问题描述**： 当我切换路书的path数据时，地图的轨迹已经更改，但是更改后的轨迹运动速度变得特别慢，（注：路书第一次加载好之后，一切正常。）不知什么问题？

谢谢了。

**Comment by Dafrok** [comment]
我最好新开个 issue ，我最近忙，放在这里可能会忘记

**Comment by tong36** [comment]
@Dafrok  OK！

**Comment by FeiChaoyu** [comment]
我也遇到这个问题，停止是让play=false，那暂停呢？

**Comment by feichaoyu** [comment]
我也遇到这个问题，停止和暂停都是play=false，怎么区分呀

**Comment by shrrio** [comment]
请问下，bml-lushu里这个暂停后再开始不是从暂停的点启动啊

**Comment by super-lkl** [comment]
@tong36 你好，请问这个问题你解决了吗？暂停后启动是从起点开始的
