### ISSUE TITLE
vue-router进行$router.push切换时，MapOverlayMarker只在第一次加载生效。

### ISSUE THREAD

**Issue by shifeng1993** [Dafrok/vue-baidu-map#2]
后续进行来回切换就不会出现覆盖物了。
<img width="1160" alt="2" src="https://cloud.githubusercontent.com/assets/20181287/23011874/3c41ac90-f45e-11e6-8ac6-ef0221288123.png">
<img width="1019" alt="1" src="https://cloud.githubusercontent.com/assets/20181287/23011873/3c419b60-f45e-11e6-8128-c17f36c31339.png">

**Comment by Dafrok** [comment]
Show me the code

**Comment by Dafrok** [comment]
原因查明，生命周期问题，20 分钟后 release 0.0.8 解决这个问题。感谢反馈。

**Comment by Dafrok** [comment]
0.0.8 已发布
