### ISSUE TITLE
能不能直接引用js文件来使用呢?

### ISSUE THREAD

**Issue by wenner** [Dafrok/vue-baidu-map#20]
就是说不用webpack,直接在页面中引用script src 这种方式使用这个地图组件呢???

我把index.js加进去,然后
```
Vue.use(VueBaiduMap , {
ak:"xxx"
});
```
这样,不起作用....

如果可以,应该怎么做呢?

**Comment by Dafrok** [comment]
```javascript
Vue.use(VueBaiduMap.default)
```

**Comment by Dafrok** [comment]
看了一下社区的说法，这个调用方式确实不符合直觉，我会在下一个的版本修复这个问题。

**Comment by Dafrok** [comment]
0.1.9 版本已修复这个问题。可以在浏览器中直接使用 `Vue.use(VueBaiduMap , {ak:"xxx"});` 方式调用了。
