### ISSUE TITLE
自定义控件 offset  异常

### ISSUE THREAD

**Issue by zhaixi** [Dafrok/vue-baidu-map#205]
您好！我自定义控件正常，但是控制台系统报错，麻烦看一下怎么解决。以下是我的代码：
<baidu-map class="map" id="zdgzMap" :center="{lng: 116.404, lat: 39.915}"  :zoom="15"   :scroll-wheel-zoom="true" style="height: 550px;" @ready="handler">
        <bm-navigation anchor="BMAP_ANCHOR_TOP_RIGHT" :offset="{width: 10, height: 60}"></bm-navigation>
        <bm-control anchor="BMAP_ANCHOR_TOP_RIGHT" :offset="{width: 130, height: 80}">
       </bm-control>
</baidu-map>

    handler ({BMap,map}){
          this.zdgzMap = map;
          this.zdgzMap.centerAndZoom(new BMap.Point(116.404,39.915),11,{enableMapClick:false});
          this.distanceTool = new DistanceTool(map, {lineStroke : 2})
      },

控制台显示：
[Vue warn]: Error in callback for watcher "offset": "TypeError: Cannot read property 'setOffset' of undefined"
这是怎么引起的？怎么修复，感觉是 bm-control   offset 有问题，可是我看bm-navigation 里面 正常 啊

**Comment by Dafrok** [comment]
确定是 bm-navigation 的问题吗？去掉了就正常吗？

**Comment by Dafrok** [comment]
另外请认真阅读 issue 模板，把你的代码用 markdown 符号括起来，不然没办法阅读

**Comment by zhaixi** [comment]
感觉是  <bm-control>  offset 的问题 ，这个去掉 offset 就正常了 ，可是 他的位置就没法定义了

**Comment by Dafrok** [comment]
https://codepen.io/Dafrok/pen/mwjqKM?editors=1010

还原了一下你的代码，并没有发现问题

**Comment by Dafrok** [comment]
@zhaixi 可以在我的在线演示基础上还原出你的问题吗？

**Comment by Dafrok** [comment]
@zhaixi ping

**Comment by zhaixi** [comment]
谢谢，暂时不出现这种异常了，等在发现了在给问·向您请教

**Comment by Dafrok** [comment]
好的

**Comment by Mrlk** [comment]
我也遇到了相同的问题， 直接copy 示例里的代码 在自定义控件中加上  `:offset="{width: 430, height: 94}"`   控制台就会报这样的错误， 去掉 offset后恢复正常，我的出现问题的代码: 
`          <bm-control anchor="BMAP_ANCHOR_TOP_RIGHT" >
            <show-switch ref="switch" :status="status.switch" :offset="{width: 430, height: 94}" @changeSwitchStatus="changeStatus"></show-switch>
          </bm-control>`
很奇怪的问题。。。

**Comment by Mrlk** [comment]
我在向 show-switch 组件用props 通信的时候，会出现这个问题，其他状态下不会

**Comment by Dafrok** [comment]
@Mrlk 我查一下看看

**Comment by Dafrok** [comment]
@Mrlk 我按照你的描述随便写了一个组件，用 prop 传值进去并尝试修改这个值，依然复现不了你的问题，最好能把你 show-switch 的逻辑精简一下看看是不是和 DOM 紧偶或者其他什么原因引起的

```vue
<template>
<span>{{foo}}</span>
</template>
<script>
export default {
  props: ['foo']
}
</script>
```

**Comment by Mrlk** [comment]
@Dafrok   感谢您的回复   我这里尝试在复现一下我的问题，打包源码给您发过去

**Comment by Mrlk** [comment]
@Dafrok   复现还是不行，我把状态放入了 vuex 暂时绕过了这个问题，现在正常，如果在有问题我在联系您，感谢您的解答。

**Comment by Dafrok** [comment]
好，最好能有完整的复现用例，不然我也很难查

**Comment by sd445419855** [comment]
> @Dafrok 复现还是不行，我把状态放入了 vuex 暂时绕过了这个问题，现在正常，如果在有问题我在联系您，感谢您的解答。
我也遇到了这个问题，我的情况是：bm-control 直接用字面量绑定一个对象就会报这个错，但是如果绑定的是 data 里的变量，且在地图初始化完成前不去修改它，就不会报错。像使用 computed、watch、mounted 来更新 offset 都是会报错的。如果要修改它，可以在地图初始化完成的回调里进行。我是这么解决的。不过虽然我这边报错了，但对它没有任何影响。
![6CB9CDF4-FDF5-4311-B798-2A02548CD676](https://user-images.githubusercontent.com/58387070/202720451-5a153a97-6f52-49ea-b429-08e86685eabf.png)
