### ISSUE TITLE
会考虑支持typescript吗？目前用typescript导入包的时候会直接报错

### ISSUE THREAD

**Issue by drinksober** [Dafrok/vue-baidu-map#208]
```import { BaiduMap, BmGeolocation, BmMarker, BmLabel } from 'vue-baidu-map';```
 Could not find a declaration file for module 'vue-baidu-map'
版本信息
vue: 2.5.2
typescript: 2.0.1
vue-baidu-map: 0.15.1

**Comment by Dafrok** [comment]
一个.d.ts就能搞定。欢迎pr

**Comment by Dafrok** [comment]
算了我自己来吧。。就一行的事儿

**Comment by Dafrok** [comment]
请更新到 0.18.7

**Comment by drinksober** [comment]
哈哈  。。。 那天我刚学ts， 试着搞了一下 没搞定。 谢谢啦。。。
