### ISSUE TITLE
BmPointCollection 使用失败

### ISSUE THREAD

**Issue by Lyule** [Dafrok/vue-baidu-map#212]
![image](https://user-images.githubusercontent.com/18359788/32586512-87931e14-c4c8-11e7-8c3d-8e7cf2ede543.png)

**Comment by Dafrok** [comment]
请好好看文档

**Comment by Lyule** [comment]
抱歉， 我有点着急了，  但是我确实没有在 vue-baidu-map 组件中看到 bm-point-collection 模块，希望您能 确认一下 
![image](https://user-images.githubusercontent.com/18359788/32587160-6498b8de-c4cc-11e7-862b-7d172c4c0ec5.png)

**Comment by Dafrok** [comment]
你有认真看 issue 模板的要求提供的东西吗？

**Comment by Dafrok** [comment]
其实我知道你的问题是什么，但是如果你有认真地按照 issue 模板的要求去做，是绝对不会问出这个问题的，所以这个问题是没有意义的。
