### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Alva-Zhen** [Dafrok/vue-baidu-map#213]
你好，我在使用的时候一直报这个错，我是通过npm 安装的，我想问一下这是为啥啊
![image](https://user-images.githubusercontent.com/26182339/32645335-73d13a84-c5ac-11e7-82c0-04ef6b0e9f00.png)

**Comment by Alva-Zhen** [comment]
大神真了不起

**Comment by Dafrok** [comment]
请先认真阅读 issue template，这是互相尊重的基础。

**Comment by Alva-Zhen** [comment]
请不要误会，我不是嘲讽你，我是觉得你们都很厉害，可能我的表达方式不对，那我想你道歉。。。。。。我是js小白，所以羡慕你们这样的人，只想表达我的钦佩的意思

**Comment by Dafrok** [comment]
如果使用中问题请务必按照 issue 模板的要求提供一下排查问题所需要的必要信息，减少沟通成本，节省双方的时间，谢谢

**Comment by ChobitsSP** [comment]
vue-cli dev环境可以使用`<BaiduMap></BaiduMap>`这种标签写法
这样使得events.js中无法匹配到组件的$options._componentTag 导致这个问题

**Comment by Dafrok** [comment]
厉害啊

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
