### ISSUE TITLE
地图容器是否有设置地图显示范围的属性，超出地图范围显示空白

### ISSUE THREAD

**Issue by roadbook** [Dafrok/vue-baidu-map#215]
1、在文档中并没有提供设置地图显示范围的API
2、地图在拖拽出显示范围后显示空白区域，例如顶部、底部超出范围后显示空白，而百度地图官网拖拽到顶部后就禁止拖动了，左右可无限拖动

**Comment by Dafrok** [comment]
百度地图 api 没有就是没有

**Comment by Dafrok** [comment]
http://lbsyun.baidu.com/index.php?title=jspopular

你说的官网的示例是这个吗？

**Comment by roadbook** [comment]
1、设置地图显示范围的API，在百度地图JS API中是有提供的
```
//百度地图API功能	
	var map = new BMap.Map("allmap");
	map.centerAndZoom(new BMap.Point(116.404, 39.915), 13);
	map.enableScrollWheelZoom();
	var b = new BMap.Bounds(new BMap.Point(116.027143, 39.772348),new BMap.Point(116.832025, 40.126349));
	try {	
		BMapLib.AreaRestriction.setBounds(map, b);
	} catch (e) {
		alert(e);
	}
```
在vue-baidu-map中并没有提供此属性

2、官网示例http://map.baidu.com/
超出地图显示范围则无法拖动，demo中往上拖拽，超出显示范围后显示空白

**Comment by Dafrok** [comment]
1、这是基于 map 对象的插件，不是 JS API 的功能，该插件的功能仅仅是在经纬度超出一定范围时把经纬度拉回预设范围，使用 vue 可以轻松实现，因此不予支持。
2、这是百度地图的官网，不是百度地图 JS API 的官网，这两个的内核完全不一样，不要弄混。。
