### ISSUE TITLE
在ready事件中能获取BMap核心类，在moveend等事件中无法BMap核心类

### ISSUE THREAD

**Issue by roadbook** [Dafrok/vue-baidu-map#217]
在ready事件中获取BMap核心类能进行操作，在moveend等事件中能否获取BMap的核心类

**Comment by roadbook** [comment]
moveend事件初始化后执行两次

**Comment by Dafrok** [comment]
原生的 moveend 确实不会提供核心类，所以你可以尝试 ready 事件执行时把核心类挂到实例上。

**Comment by Dafrok** [comment]
执行两次的问题以前有人提到过，但是没有人提供能够真正复现问题的场景，我无论如何也复现不了，如果可以的话希望你能提供一个在线展示或者靠谱的复现用例。

**Comment by roadbook** [comment]
在BaiduMap上绑定moveend事件，初始化后就会执行两次moveend事件

**Comment by Dafrok** [comment]
需要靠谱的 **复现用例**，而不是语言描述。
