### ISSUE TITLE
在操作清除路书并重新绘画东西的时候行走的小车没有清除掉，但是路书的线路清除了请问怎么清除行进中的小车

### ISSUE THREAD

**Issue by Whbstrive** [Dafrok/vue-baidu-map#219]
this.map.removeOverlay(this.lushuLine)      //此处清除路书线路
          this.lushuLine = null;
          if(this.lushuPoi.length>0){                            //此处清除线路上的marker点
            for(var i = 0; i < this.lushuPoi.length;i++){
              this.map.removeOverlay(this.lushuPoi[i])
            }
          }

**Comment by Dafrok** [comment]
请按照 issue 模板进行提问
