### ISSUE TITLE
地图的默认字体和官方的不太一样，导致增加路况层的时候出现重影

### ISSUE THREAD

**Issue by brahmachen** [Dafrok/vue-baidu-map#22]
官方默认字体：
![qq 20170317143119](https://cloud.githubusercontent.com/assets/12797533/24031825/b20dfe10-0b1f-11e7-9f05-676e743f0b8c.png)
本地图字体：
![qq 20170317143130](https://cloud.githubusercontent.com/assets/12797533/24031848/c864407a-0b1f-11e7-8586-ed379e69c50f.png)
增加路况图层后出现重影：
![qq 20170317143211](https://cloud.githubusercontent.com/assets/12797533/24031860/da4d3c56-0b1f-11e7-8fb3-b1d0bf031e0e.png)

测试代码：
```Vue
<template>
	<baidu-map v-bind:style="{
		width: '100%',
		height: mapHeight + 'px'
	}" 
		:center="{lng: 116.404, lat: 39.915}" 
		:zoom="15" 
		:scroll-wheel-zoom="true" 
		@ready="ready"
		>
		
	</baidu-map>
</template>

<script>
	export default{
		data() {
			return{
				mapHeight: 400
			}
		},
		mounted() {
			this.mapHeight = 500;
		},
		methods:{
			ready(obj){
				const { BMap, map } = obj;
				map.addTileLayer(new BMap.TrafficLayer);
				
			}
		}
	}
</script>
```

**Comment by Dafrok** [comment]
检查一下 BMap 属性的 option ，可能和上次惯性拖拽和平滑缩放问题的情况差不多，官方文档没有及时更新。

**Comment by brahmachen** [comment]
检查了一遍，能试的都试了，没找到那个属性。。。

**Comment by Dafrok** [comment]
目前没网，晚上排查一下。

**Comment by brahmachen** [comment]
好的，谢啦

**Comment by Dafrok** [comment]
顺便说一下 TileOverlay 组件也是准备要加的 不过最近太忙了…

**Comment by Dafrok** [comment]
问题出在默认主题上，更新到 0.1.10 解决这个问题。

**Comment by brahmachen** [comment]
这里还有一个问题，使用`map.setMapStyle({style:'light'});`主题时还是会出现这个问题。
不过我的问题已经解决了，谢啦
