### ISSUE TITLE
请问怎样实现自定义信息窗口

### ISSUE THREAD

**Issue by lf7817** [Dafrok/vue-baidu-map#220]
请问怎样实现自定义信息窗口，就是百度开源库里的infoBox，查看了下文档好像没有，现有的infoWindow不能随意修改不满足需求~~望告知~~

**Comment by For-me** [comment]
infowWindow是基于slot模式渲染子节点，您说的不能自定义是什么意思？slot模式已经很开放了。

**Comment by Dafrok** [comment]
infoBox 的本质是自定义覆盖物，如果你需要的话用 Overlay 组件定制一个就行了。

**Comment by lf7817** [comment]
谢谢哈~刚接触有点迷糊

**Comment by lf7817** [comment]
"vue": "^2.5.2",
"vue-baidu-map": "^0.18.9",
浏览器IE11
自定义覆盖物在IE下有问题,首次加载没有问题，切换其他页面再切换回来，就会报“SCRIPT5007: 无法获取未定义或 null 引用的属性“style””和“SCRIPT5007: 无法获取未定义或 null 引用的属性“children””,
```
// 用的文档上的demo，没修改
<bm-overlay
        pane="floatPane"
        :class="{sample: true, active}"
        @draw="draw"
        @mouseover.native="active = true"
        @mouseleave.native="active = false">
        <div>我爱北京天安门</div>
</bm-overlay>
```
![image](https://user-images.githubusercontent.com/17609173/33199190-2f4390ea-d12a-11e7-8368-cfb10ee3fef4.png)
![y](https://user-images.githubusercontent.com/17609173/33199202-3c864e6e-d12a-11e7-86be-2906357cb3f3.gif)

**Comment by lf7817** [comment]
@Dafrok

**Comment by Dafrok** [comment]
仅在 IE 下？

**Comment by lf7817** [comment]
测了火狐谷歌360IE，就IE下有这个问题，而且IE下地图总感觉卡顿

**Comment by Dafrok** [comment]
I hate IE，这个 error message 看上去像是地图 JS API 去获取一个 DOM 元素失败了。你 keep alive 了吗？

**Comment by lf7817** [comment]
yes，i use it. i hate IE , too. But, the customer likes

**Comment by lf7817** [comment]
去掉keep alive 是没有问题的

**Comment by Dafrok** [comment]
目前手头没有 IE，等我下班腾下硬盘装虚拟机看看。。

**Comment by lf7817** [comment]
0.0,,,,,,,麻烦了亲。。。。
