### ISSUE TITLE
调试的时候打开vue devtools巨卡

### ISSUE THREAD

**Issue by lf7817** [Dafrok/vue-baidu-map#223]
### 浏览器版本号

chrome v62

### Vue 版本号

2.5.2

### 组件库版本号

0.18.8

### 现象描述

```
一打开vue devtools页面就卡住了 ，vue devtools V3.16
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

https://github.com/lf7817/water-price

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
你目前这个 case 和昨天的相比有提交什么新的东西吗，我用你昨天的 case 跑了一下没出现卡顿问题

**Comment by lf7817** [comment]
没有什么区别，只有打开vue devtools的时候才会卡，没法调试代码了,你那边没问题那可能是我版本问题了，我换个版本，先关了

**Comment by Dafrok** [comment]
好，有问题在这个 issue 里继续反馈就行了

**Comment by Dafrok** [comment]
好，如果确实有问题在这个 issue 里继续反馈就行了

**Comment by kaven276** [comment]
我 Vue.js devtools 4.1.0，只要用到 vue-baidu-map，cpu 过会就飙到 200% 以上，然后 devtools 对操作就没响应了

**Comment by Dafrok** [comment]
你打开在线文档，devtools 会卡死吗？

**Comment by zhangdaiscott** [comment]
Vue.js devtools
6.4.5
也非常的卡
