### ISSUE TITLE
closeOnClick 默认值不是 true

### ISSUE THREAD

**Issue by zaxlct** [Dafrok/vue-baidu-map#224]
### 浏览器版本号

chrome 62

### Vue 版本号

2.5.6

### 组件库版本号

0.18.7

### 现象描述

文档上 closeOnClick 属性默认是 true，但是实际上不行，必须手动指定为 true 才生效

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

```bm-info-window(:closeOnClick="true")```

### 复现用例

```
```bm-info-window(:closeOnClick="true")```
```

### 预期输出

```
为 true
```

### 实际输出

```
为 false
```

**Comment by Dafrok** [comment]
update 0.18.9
