### ISSUE TITLE
Map.vue中的activated的deactivated逻辑不必要，keep-alive的时候，会多次初始化地图

### ISSUE THREAD

**Issue by xuqinjie** [Dafrok/vue-baidu-map#225]
### 浏览器版本号

0

### Vue 版本号

2

### 组件库版本号

1

### 现象描述

```
Map.vue中的activated的deactivated逻辑不必要，keep-alive的时候，会多次初始化地图
```

### 完整异常信息

```
Map.vue中的activated的deactivated逻辑不必要，keep-alive的时候，会多次初始化地图
```

### 在线示例 / 仓库 URL

Map.vue中的activated的deactivated逻辑不必要，keep-alive的时候，会多次初始化地图

### 复现用例

```
Map.vue中的activated的deactivated逻辑不必要，keep-alive的时候，会多次初始化地图
```

### 预期输出

```
Map.vue中的activated的deactivated逻辑不必要，keep-alive的时候，会多次初始化地图
```

### 实际输出

```
Map.vue中的activated的deactivated逻辑不必要，keep-alive的时候，会多次初始化地图
```

**Comment by xuqinjie** [comment]
keep-alive的时候是不会的，你可以试试。keep-alive的时候，dom会restore，这时你再reset地图，原先地图上放置的元素就都没了。这个reset最好由用户在parent级别发起操作。
ps:发多次，是因为你提供的模板，是强制所有字段都输入的。不仅仅是有红色星号标准的那个。

**Comment by Dafrok** [comment]
所以我说这属于 featrue，你按照 bug 来发当然找不到填哪了，你可以试试去掉 active 和 deactive 的逻辑就明白了，这个问题是在 #135 的问题中发现的。

**Comment by Dafrok** [comment]
另外如果你的状态正确的保存，没有做和 DOM 紧耦的操作，视图是不会丢的，因为一切视图都是由状态生成的。

**Comment by Dafrok** [comment]
@xuqinjie 这个体验已经发现在某些场景里会存在问题，预计在下一个版本进行更改。

**Comment by Dafrok** [comment]
0.19.4 修复了该问题，已发版
