### ISSUE TITLE
vue-baidu-map不支持window

### ISSUE THREAD

**Issue by haoxl3** [Dafrok/vue-baidu-map#23]
安装此插件时，警告：npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.1.1，使用时也总说BMap未定义，是因为此组件不支持window系统吗

**Comment by Dafrok** [comment]
clone 这个仓库，拉到本地，然后执行：
```
$ npm install
$ npm run dev
```
然后访问 localhost:8080

**Comment by Dafrok** [comment]
没有问题我就关ISSUE了？
