### ISSUE TITLE
tilesloaded这个地图容器方法为什么每次拖动时都会触发？

### ISSUE THREAD

**Issue by SYHQ** [Dafrok/vue-baidu-map#231]
### 相关文档 URL

https://dafrok.github.io/vue-baidu-map/#/zh/map/baidu-map

### 问题描述

```
这个方法具体触发的条件是什么？感觉和dragend方法有点像
```

### 改进建议

```
无
```

**Comment by Dafrok** [comment]
关闭理由：问题与组件库无关，请自行查阅百度地图 JS API 文档

**Comment by tat757** [comment]
这个是百度地图渲染完成后触发的事件
