### ISSUE TITLE
Error in callback for watcher "mapType": "TypeError: Cannot read property 'setMapType' of undefined"

### ISSUE THREAD

**Issue by w550** [Dafrok/vue-baidu-map#233]
`
https://github.com/Dafrok/vue-baidu-map/blob/master/src/map/Map.vue

    mapType (val) {
      const {map} = this
      map.setMapType(global[val])
    },
`
这里会报错。
复现的方法是 弱网情况下，切换 地图类型

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
