### ISSUE TITLE
离线地图能使用这个插件吗?

### ISSUE THREAD

**Issue by cchenggit** [Dafrok/vue-baidu-map#236]
### 在线示例 URL

无

### 功能描述

```
现在想在内网尝试一下vuejs+百度离线地图的功能,请问这个插件支持吗?
```

### 用法示例

```
无
```

**Comment by Dafrok** [comment]
请提供用法示例和在线演示，不能提供演示的请求无法予以支持

**Comment by Dafrok** [comment]
看了下百度地图 JS API 的文档，不支持离线地图，因此任何第三方组件库都无法予以支持。提出功能请求前请先做好调研工作。

**Comment by DesignHhuang** [comment]
> 看了下百度地图 JS API 的文档，不支持离线地图，因此任何第三方组件库都无法予以支持。提出功能请求前请先做好调研工作。

文档中没有写，但是百度地图肯定是有方式离线的哇，只是做起来会比较复杂。

**Comment by Mrzhang-ziqian** [comment]
https://leafletjs.com/plugins.html 可以尝试这个
