### ISSUE TITLE
定位控件bm-geolocation的icon每点定位击一次，就会多生成一张icon叠加在上面

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#237]
### 浏览器版本号

Google Chrome62.0.3202.94

### Vue 版本号

2.3.3

### 组件库版本号

0.18.7

### 现象描述

```
定位控件bm-geolocation的icon每点击定位一次，就会多生成一张icon叠加在上面
```

### 完整异常信息

```
点击定位控件一次，就生成一张icon
```

### 在线示例 / 仓库 URL

无需事例

### 复现用例

```
无需事例
```

### 预期输出

```
点击定位控件一次，如果没有icon则生成一张，有则无需生成icon
```

### 实际输出

```
定位控件bm-geolocation的icon每点击定位一次，就会多生成一张icon叠加在上面
```

**Comment by front-end-john** [comment]
![img_3786 20171207-141730](https://user-images.githubusercontent.com/21167738/33701586-5bd907fe-db5a-11e7-9670-c114931ae70c.jpg)

**Comment by Dafrok** [comment]
我看了 JS API 的实现，这貌似是本来就有的 feature。

> http://lbsyun.baidu.com/jsdemo.htm#b0_7

**Comment by Dafrok** [comment]
你的问题我已经通过官方渠道反馈了，他们如果认为这个不是问题只能通过手动维护 Marker 来解决了

**Comment by Dafrok** [comment]
官方给答复了，说这里是设计缺陷，会增加一个事件去暴露生成的 marker，下周上线。
后续有更新再同步。

**Comment by front-end-john** [comment]
好的，辛苦了

**Comment by Dafrok** [comment]
官方已在 loginSuccess 事件中增加了 marker 参数，你可以在这个事件中获得 marker 实例，自行操作和销毁。

**Comment by songispm** [comment]
locationSuccess({point, AddressComponent, marker}){
        //多次点击定位按钮会重复覆盖定位的图标，所以要删除旧的保留新的
        map.removeOverlay(window.myGeoMarker)
        window.myGeoMarker = marker
},
