### ISSUE TITLE
使用bm-local-search在浏览器第一次打开网页时，会导致页面整体刷新

### ISSUE THREAD

**Issue by yizhigui** [Dafrok/vue-baidu-map#238]
<bm-local-search  :selectFirstResult="true" :pageCapacity="1" @searchcomplete="getPostion" style="opacity: 0;display: none;" :keyword="addressStr" :auto-viewport="true"></bm-local-search>

如上，通过修改addressStr的值，重新搜索位置，但是在浏览器第一次打开网页的时候会导致页面整体刷新，之后又不再重现该问题，只会在第一次的时候出现该问题。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
