### ISSUE TITLE
android 4.4.4 以下  webview 有错误

### ISSUE THREAD

**Issue by w550** [Dafrok/vue-baidu-map#24]
@Dafrok

我抓了一下 webview 的log。没有报错。

就出现了这些。
不是安卓的浏览器哦，是安卓的 webview

**Comment by Dafrok** [comment]
出现了哪些啊。。。

**Comment by w550** [comment]
@Dafrok 
空的，就是html的注释符号

**Comment by Dafrok** [comment]
没有安卓设备 提供一些更详细的问题描述吧

**Comment by w550** [comment]
@Dafrok 
找个好几天，定位到 Promise 的错误
android 4.4 不支持 Promise 
android 4.4.4 才开始支持

**Comment by Dafrok** [comment]
加个 Polyfill 吧。。

**Comment by Dafrok** [comment]
按理说 Promise 对象不存在的话会抛出 `Promise is not defined` 异常的，你这个情况确实诡异

**Comment by w550** [comment]
@Dafrok 
稍等
for (let $node of this.$slots.default ) {
        // if ($node.componentOptions && $node.componentOptions.tag === 'bm-view') {
        //   $el = $node.elm
        // }
      }

这句也貌似会影响
我注释掉，地图就出来了。
不注释，就不显示

**Comment by Dafrok** [comment]
这句是用来判断地图是否包含 `bm-view` 组件的，如果有这个组件就会在 `bm-view` 中渲染地图，否则就在根节点渲染地图。检查一下你的组件里是否包含了样式有问题的 `bm-view` ？

**Comment by w550** [comment]
@Dafrok 
我现测试的当前这个master 分支。
在你的 demo 里面测试的，没有自定义

**Comment by Dafrok** [comment]
哪个 demo

**Comment by w550** [comment]
/src/map/Map.vue

**Comment by w550** [comment]
```
for (let $node of this.$slots.default || []) {
        if ($node.componentOptions && $node.componentOptions.tag === 'bm-view') {
          $el = $node.elm
        }
      }
```

**Comment by w550** [comment]
```
try {
        for (let $node of this.$slots.default || []) {
          console.log($node)
          if ($node.componentOptions && $node.componentOptions.tag === 'bm-view') {
            $el = $node.elm
          }
        }
      } catch (err) {
        console.log(err)
      }
```
```
ReferenceError {} index.js:25216
```

**Comment by Dafrok** [comment]
所以说究竟有没有抛出异常啊

**Comment by w550** [comment]
抛出了。
ReferenceError

**Comment by Dafrok** [comment]
能完整的把错误信息发一下吗

**Comment by w550** [comment]
执行 for (let $node of this.$slots.default || []) 这句话，只抓到一个错误
ReferenceError {} index.js:25216
就是上面那句话。就这一句。

**Comment by w550** [comment]
说白了。我用try 包起来。地图显示了。

**Comment by w550** [comment]
比例尺也显示了

**Comment by Dafrok** [comment]
你打印 `this.$slots.default`、`$node` 都是什么？

**Comment by w550** [comment]
this.$slots.default
如图
![11](https://cloud.githubusercontent.com/assets/11831434/24349217/e4689d2c-1310-11e7-8ad0-54e784fc2c75.png)
至于$node 在安卓 4.4.2上 没有循环进去，直接报错了。所以没打印出来
try 捉到了 ReferenceError {} index.js:25216 这个错误

**Comment by Dafrok** [comment]
trace 到 25216 行看下是那行是啥

**Comment by w550** [comment]
![2](https://cloud.githubusercontent.com/assets/11831434/24349441/aa5fd32e-1311-11e7-9b5d-feace9e81fd1.png)

**Comment by w550** [comment]
![33](https://cloud.githubusercontent.com/assets/11831434/24349493/d22d0f34-1311-11e7-92ff-00a882ac9ba4.png)

**Comment by w550** [comment]
![44](https://cloud.githubusercontent.com/assets/11831434/24349597/1b9c4df6-1312-11e7-8b21-432d80ad89cf.png)
![Uploading 44.png…]()

**Comment by Dafrok** [comment]
看样子像是没有 Symblo 对象 你加个 Symblo 的 polyfill 试试看

**Comment by Dafrok** [comment]
解决了吗？

**Comment by w550** [comment]
@Dafrok 
没有卡住了。。。
今天项目要上线，安卓4.4.2 不现实地图。。。

**Comment by Dafrok** [comment]
加了Symblo polyfill 也报这个错？你注释掉这里然后 `npm run build` 本地编译一下使用，这个我还需要找个设备研究一下。

**Comment by w550** [comment]
@Dafrok 
没找到 Symblo polyfill 这个包。没用过~

**Comment by Dafrok** [comment]
直接上babel-polyfill理论上就可以

**Comment by w550** [comment]
@Dafrok 
刚刚测试了一下，main.js 里面
import "babel-polyfill";
这个确实可以了。
我在重新整理一下。

**Comment by Dafrok** [comment]
那问题就确定了，安卓4.4.4以下不支持某些ES2015新特性，需要加polyfill。

**Comment by w550** [comment]
@Dafrok 
是的
import "babel-polyfill";
你要加一下发布一次吗？

**Comment by Dafrok** [comment]
polyfill不是lib本身的问题，是应该由用户根据自己需求主动添加在全局的。

**Comment by w550** [comment]
@Dafrok 
所以，今天更新 npm 吗？

**Comment by Dafrok** [comment]
这个不更新，刚刚说过 babel-polyfill 是全局的包，配合 babel 使用的。
