### ISSUE TITLE
添加 types 支持

### ISSUE THREAD

**Issue by hwen** [Dafrok/vue-baidu-map#240]
### 在线示例 URL

https://github.com/hwen/vue-baidu-map/commit/69fc4ac8e4e5e290bd8aa64a5d47edeebcde7435

### 功能描述

```
添加 types
目前在逐步补全中
```

### 用法示例

```
cd types 
tsc -p test/tsconfig.json
```

**Comment by Dafrok** [comment]
直接 pr 过来吧

**Comment by hwen** [comment]
好，另外写 types 过程中发现文档和代码有一些错我也直接 pr 了，不另开 issue ~

**Comment by Dafrok** [comment]
👏
