### ISSUE TITLE
你好，我想请问个问题

### ISSUE THREAD

**Issue by xzs333** [Dafrok/vue-baidu-map#241]
我想使用一个第三方插件，目前你的这个项目里没有添加
鼠标绘制工具条库 http://lbsyun.baidu.com/jsdemo/demo/f0_7.htm
这个我需要如何操作呢？只能在你的项目基础上添加？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
