### ISSUE TITLE
你好，我想添加一个新功能

### ISSUE THREAD

**Issue by xzs333** [Dafrok/vue-baidu-map#242]
### 在线示例 URL

http://lbsyun.baidu.com/jsdemo/demo/f0_7.htm

### 功能描述

```
鼠标绘制工具条库
```

### 用法示例

```
这个我需要如何操作呢？只能在你的项目基础上添加？如果我想单纯的使用min.js是不是得需要改造export格式的
```

**Comment by Dafrok** [comment]
这个比较麻烦，因为第三方库是依赖百度地图 API 的并且不支持模块化加载，而 vue-baidu-map 是异步加载的，所以推荐两个方法：
1. 第一是使用 script 标签手动引入 JS API 和第三方库，这样做比较简单也好理解。
2. 二是你需要改造这个库，让他支持模块化加载，可以参考我之前封装过的 [点聚合](https://github.com/Dafrok/BMapLib.MarkerClusterer) / [路书](https://github.com/Dafrok/BMapLib.LuShu) / [测距](https://github.com/Dafrok/BMapLib.DistanceTool) 等组件。

**Comment by xzs333** [comment]
第一种方法我不想使用，因为已经引用你的库了，这样子会重复引用百度api
第二种我也参照你的方法改造了，但是它引用百度api中的BMap了，页面加载时候会报错，找不到BMap，这个地方能延迟调用或者其他的引用方法吗？或者其他办法，还是我改造的有问题呢。
这么晚了还回复我，谢谢！

**Comment by Dafrok** [comment]
第一种方法不会重复加载，我在我的库里做了判断。
第二种方法你可以参考我封装那些库的做法，懒执行。

当然我是不建议你使用这个库的，因为你已经用了 vue，数据决定视图，这意味着你通过操作数据去实现这个功能是极其简单的，你只要通过事件 + 简单的数据操作逻辑就能在视图上绘制出任何各种点、线、多边形，为何还要用传统 care DOM 的方式呢？这也是我为什么没有移植这个第三方库的原因。

**Comment by xzs333** [comment]
好，明白了，真心谢谢你！这么晚还回复我。
早点休息吧。

**Comment by mythbobo** [comment]
不好意思刚才没看到这个问题,我想问一下,怎么实现通过事件 + 简单的数据操作逻辑就能在视图上绘制出各种点、线、多边形等，求给个方向。。水平有点差。谢谢了。

**Comment by Dafrok** [comment]
给楼上一个思路，你需要按钮可以用自定义控件，你需要视图可以通过点击行为维护一组数据，自己定义一个数据到视图的映射就好了。
