### ISSUE TITLE
请问如何用这个组件实现添加多边形或者圆形这样的功能？

### ISSUE THREAD

**Issue by mythbobo** [Dafrok/vue-baidu-map#243]
组件现在是可以修改一个多边形或者圆形，如果进行二次开发。需要在此基础上增加添加，删除，修改功能,包括还有框选之类的功能，这个可以做到吗？望回复。。谢谢

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
