### ISSUE TITLE
请问如何实现多边形，圆形之类的添加,删除功能？

### ISSUE THREAD

**Issue by mythbobo** [Dafrok/vue-baidu-map#244]
### 在线示例 URL

无

### 功能描述

```
看了下API，示例只有读取跟修改多边形的功能，，要进行二次开发，如何实现添加，删除，修改功能呢。。另问一下。。比如框选之类的功能现在的组件可以实现吗？
```

### 用法示例

```
无
```

**Comment by mythbobo** [comment]
仔细看了下,可以用第三方组件的方式引入,不知道是不是异步加载的问题。我引入的第三方库(DrawingManager)一直报错(BMap is not defined);@ready能获取到map对象。。ready定义的方法里我实例化DrawingManager的时候,好像是第三方库在实例化的时候比BMap先进行了。不知道是什么原因?

所以能不能考虑加入DrawingManager这个第三方库呢？

**Comment by mythbobo** [comment]
这次我又用了异步加载的方式引入第三方库，但是还是有问题。。BMapLib is not defined。都不知道怎么办了。

<template>
  <baidu-map class="map" :zoom="zoom" :center="{lng: 116.404, lat: 39.915}" @ready="setDrawingManagerInstance">
    <bm-control>
      <button @click="openDistanceTool">开启测距</button>
    </bm-control>
  </baidu-map>
</template>

<script>
export default {
  data() {
    return {
      drawingManager: null,
      zoom: 10
    };
  },
  mounted() {},
  methods: {
    loadJS(src, callback) {
      var script = document.createElement("script");
      var head = document.getElementsByTagName("head")[0];
      script.src = src;
      head.appendChild(script);
      callback();
    },
    loadDraw(map) {
      var overlays = [];
      var overlaycomplete = function(e) {
        overlays.push(e.overlay);
      };
      var styleOptions = {
        strokeColor: "red", //边线颜色。
        fillColor: "red", //填充颜色。当参数为空时，圆形将没有填充效果。
        strokeWeight: 3, //边线的宽度，以像素为单位。
        strokeOpacity: 0.8, //边线透明度，取值范围0 - 1。
        fillOpacity: 0.6, //填充的透明度，取值范围0 - 1。
        strokeStyle: "solid" //边线的样式，solid或dashed。
      };

      this.drawingManager = new BMapLib.DrawingManager(map, {
        isOpen: false, //是否开启绘制模式
        //enableDrawingTool: true, //是否显示工具栏
        drawingToolOptions: {
          anchor: BMAP_ANCHOR_TOP_RIGHT, //位置
          offset: new BMap.Size(5, 5) //偏离值
        },
        circleOptions: styleOptions, //圆的样式
        polylineOptions: styleOptions, //线的样式
        polygonOptions: styleOptions, //多边形的样式
        rectangleOptions: styleOptions //矩形的样式
      });

      //添加鼠标绘制工具监听事件，用于获取绘制结果
      this.drawingManager.addEventListener("overlaycomplete", overlaycomplete);
    },
    setDrawingManagerInstance({ map }) {
      console.log(map);
      var _this = this
      let url =
        "http://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js";
      this.loadJS(url, function(){
          _this.loadDraw( map )
      });
      //   const $script = document.createElement("script");
      //   document.body.appendChild($script);
      //   $script.src = `http://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js`;

      // this.distanceTool = new DistanceTool(map, { lineStroke: 2 });
    },
    openDistanceTool(e) {
      const { distanceTool } = this;
      distanceTool && distanceTool.open();
    }
  }
};
</script>
<style>
.map {
  width: 100%;
  height: calc(100vh - 61px);
  position: relative;
}
</style>

这是我的代码。。能帮忙分析一下什么原因吗?

**Comment by mythbobo** [comment]
代码有问题。。重发一下..
```html
<baidu-map class="map" :zoom="zoom" :center="{lng: 116.404, lat: 39.915}" @ready="setDrawingManagerInstance">
    <bm-control>
      <button @click="openDistanceTool">开启测距</button>
    </bm-control>
  </baidu-map>


<script>
export default {
  data() {
    return {
      drawingManager: null,
      zoom: 10
    };
  },
  mounted() {},
  methods: {
    loadJS(src, callback) {
      var script = document.createElement("script");
      var head = document.getElementsByTagName("head")[0];
      script.src = src;
      head.appendChild(script);
      callback();
    },
    loadDraw(map) {
      var overlays = [];
      var overlaycomplete = function(e) {
        overlays.push(e.overlay);
      };
      var styleOptions = {
        
      };

      this.drawingManager = new BMapLib.DrawingManager(map, {
        
      });

      //添加鼠标绘制工具监听事件，用于获取绘制结果
      this.drawingManager.addEventListener("overlaycomplete", overlaycomplete);
    },
    setDrawingManagerInstance({ map }) {
      console.log(map);
      var _this = this
      let url =
        "http://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js";
      this.loadJS(url, function(){
          _this.loadDraw( map )
      });
    },
    openDistanceTool(e) {
      const { distanceTool } = this;
      distanceTool && distanceTool.open();
    }
  }
};
</script>

**Comment by Dafrok** [comment]
其实你思考一下 vue 是怎么在视图上添加 DOM 的，就会发现你这个问题其实没什么意义，因为 MVVM 的核心是数据决定视图。

**Comment by mythbobo** [comment]
嗯。。我大概明白了。。可以直接在map的事件上获取坐标点。。push进数组。。感谢回复。。有问题再来请教

**Comment by change24** [comment]
vue 百度地图框选解决了吗  正好有这个需求
