### ISSUE TITLE
刷新报错以及IE没有渲染

### ISSUE THREAD

**Issue by ouyangxiaoai** [Dafrok/vue-baidu-map#249]
在chrome中第一次打开正常，刷新页面会报错如图：
![image](https://user-images.githubusercontent.com/27655473/33869189-6dc14418-df42-11e7-94d1-c67ea182b051.png)
在IE中第一次打开就是空白，查看源码发现地图组件的代码都没有渲染，刷新也会报chrome的相同错误
所以是我哪里有问题吗？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
