### ISSUE TITLE
显示隐藏地图时，中心点的问题

### ISSUE THREAD

**Issue by For-me** [Dafrok/vue-baidu-map#25]
当我初始化一个display:none的地图时，当我点击显示的时候，可视区域中心点并没有在指定的坐标位置上。通过:center初始化的。并且当我通过@ready方法拿到BMap的核心类和地图实例，也不能通过这个来调用panTo(new BMap.point())方法来移动中心点。
请问下应该怎么做呢？

**Comment by Dafrok** [comment]
你 `display: none` 的时候，地图视图区域是 0*0 ，这时候设置 center 中心点自然就是 {x: 0, y: 0} 了。

**Comment by For-me** [comment]
@Dafrok 谢谢解答。直接使用nextTick也没法改变的。必须要有个setTimeout去异步加载。已经解决了。作者是不是没有女朋友，回答的好快。

**Comment by Dafrok** [comment]
不好意思，结婚好久了 : )

**Comment by For-me** [comment]
哈哈哈哈。给你星星啦。。有时间我也来帮忙。。
还有个小问题。:icon中的url是用的相对路径么？

**Comment by Dafrok** [comment]
和百度地图 JS API 的 [Icon](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a3b5) 的规则是一致的，如果有不一致的地方请尽管指出。

**Comment by For-me** [comment]
嗯。require一个解决了。。还有那个local-search的组件，searchcomplete返回的是一个数组对象是吧。但是实际是undefined

**Comment by Dafrok** [comment]
看了下，文档写的返回值是 none，实测却是有的，是bug，我更新一下。另外不是同个问题就新开 issue 吧。

**Comment by Dafrok** [comment]
不对，我看了下自己的实现，是转发了事件的第一个参数的，实测不是undefined。

**Comment by For-me** [comment]
`<baidu-map id="mapCont" class="map-box" @moveend="syncCenter" :center="center" :zoom="18" 
:inertial-dragging="true" :pinch-to-zoom="true" :scroll-wheel-zoom="true">`
                                        
`<bm-marker :position="{lng:'104.067923',lat:'30.679943'}" :dragging="true"  :icon="{url: pointIcon, size: {width: 30, height: 30}}"></bm-marker>
                                         <bm-local-search :keyword="keyword" :auto-viewport="true" @searchcomplete="searchLocal"></bm-local-search>
                                    </baidu-map>`

按理这里的searchLocal应该就是返回参数呀

**Comment by For-me** [comment]
实际我通过searchLocal获得的第一个参数就是undefined,包括我直接打印arguments也是一样的

**Comment by Dafrok** [comment]
你可以本地 `npm run dev` 跑一下文档，这里确实不是 undefined，无法复现你的问题。
