### ISSUE TITLE
刷新报错以及IE没有渲染

### ISSUE THREAD

**Issue by ouyangxiaoai** [Dafrok/vue-baidu-map#250]
### 浏览器版本号

chrome 61 以及IE9以上

### Vue 版本号

2.4.2

### 组件库版本号

0.18.9

### 现象描述

```
在chrome中第一次打开正常，刷新页面会报错如图：
在IE中第一次打开就是空白，查看源码发现地图组件的代码都没有渲染，刷新也会报chrome的相同错误
```

### 完整异常信息

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

### 在线示例 / 仓库 URL

http://iot.iot-demo.cniotroot.cn/us/link-us

### 复现用例

```
每次
```

### 预期输出

```
没有报错并且IE9以上可以显示
```

### 实际输出

```
IE没有显示并且有报错
```

**Comment by Dafrok** [comment]
因为百度地图 JS API 是不支持 SSR 的。

**Comment by ouyangxiaoai** [comment]
@Dafrok这样子的啊，但是IE不显示的问题是为什么呢？

**Comment by Dafrok** [comment]
以你现在提供的信息无法做出判断

**Comment by ouyangxiaoai** [comment]
可是并没有报错信息，IE查看网页源码的时候发现地图的那段DOM没有渲染出来.在chrome中是有的
所以是初始化没有成功？
但是我没有写初始化的调用，我就是全局引入了，然后在组件中直接使用

**Comment by Dafrok** [comment]
确定？为何我用 IE 访问你的网站抛出一个语法错误？

**Comment by ouyangxiaoai** [comment]
语法错误？我这边只有一个警告，但是那个并不会影响地图。可以麻烦截图给我看一下那个语法错误吗？

**Comment by Dafrok** [comment]
![6cf2b9071e0f6ca92fe7db3027ecd21d](https://user-images.githubusercontent.com/6159588/33870544-3e491b32-df49-11e7-92be-72dc68d3a9dd.png)

**Comment by ouyangxiaoai** [comment]
你这个不是IE9以上的吧，我的IE10以及以上不会有语法错误。这些错误是不兼容es6造成的，但是没有考虑要兼容9以及以下

**Comment by Dafrok** [comment]
https://kangax.github.io/compat-table/es6/

**Comment by ouyangxiaoai** [comment]
嗯，感谢你给我说了这么多，非常抱歉占用你的时间。我再自己看看，谢谢
