### ISSUE TITLE
在iPhone6 ios8.4以下的手机无法使用整个百度控件，出行一片空白

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#251]
<img width="443" alt="bug" src="https://user-images.githubusercontent.com/21167738/33873301-66f26b68-df55-11e7-97d4-59c30fc138f8.png">

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
