### ISSUE TITLE
在iPhone6 ios8.4以下的手机无法使用整个百度控件，无法渲染地图

### ISSUE THREAD

**Issue by front-end-john** [Dafrok/vue-baidu-map#252]
### 浏览器版本号

ios自带浏览器，微信浏览器

### Vue 版本号

2.3.3

### 组件库版本号

0.18.7

### 现象描述

```
在iPhone6 ios8.4以下的手机浏览器网页，ready等方法都不执行了，无法渲染地图。其他设备测试一切正常啊！！！
```

### 完整异常信息

```
不兼容，无法渲染地图等等
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
兼容大部分ios系统，安卓系统
```

### 实际输出

```
不兼容
```

**Comment by front-end-john** [comment]
<img width="443" alt="bug" src="https://user-images.githubusercontent.com/21167738/33873431-e447d88c-df55-11e7-998f-c4246503d522.png">

**Comment by Dafrok** [comment]
异常信息不要瞎填

**Comment by front-end-john** [comment]
好的，希望大神能修复这个问题吧，好几个手机都没法显示地图了

**Comment by Dafrok** [comment]
以你目前提供的信息无法判断问题。issue 区是解决问题的地方，你胡乱提供信息任谁都无能为力。

**Comment by front-end-john** [comment]
我描述的问题就是这个地图兼容性有问题，例如：iOS8，地图无法渲染

**Comment by Dafrok** [comment]
不是人人都和你一样有 iOS 8 环境。如果想解决问题，就请按照 issue 模板把信息补充完全。

**Comment by front-end-john** [comment]
能填写的我都尽量填写了，示例或场景我是没办法还原了，这个兼容性之前在某些安卓机的浏览器上也见过，只不过当时没注意提。实在没办法解决我只能换个方法去搞了

**Comment by Dafrok** [comment]
至少 console 可以看一下吧？

**Comment by front-end-john** [comment]
我正在下载个模拟器，等下，刚刚是用别人的真机调试

**Comment by Dafrok** [comment]
不需要模拟器，Mac 的 Safari 可以直接看，你百度一下，很简单

**Comment by front-end-john** [comment]
Mac 的 Safari 都是iOS 10的，调试一切正常，真机那个是iOS8的就不行

**Comment by Dafrok** [comment]
Mac 的 Safari 可以看真机的 console，不是让你用 Mac 直接访问

**Comment by front-end-john** [comment]
知道，正在借手机

**Comment by front-end-john** [comment]
控制台没有输出任何东西

**Comment by front-end-john** [comment]
<img width="774" alt="bug2" src="https://user-images.githubusercontent.com/21167738/33875254-9fd26198-df5c-11e7-9a37-b905462a72a3.png">

**Comment by Dafrok** [comment]
截个 Element 标签是啥用意

**Comment by front-end-john** [comment]
.bmap class 里面没有生成地图

**Comment by Dafrok** [comment]
我上面说是说看眼 console，不是检查 element

**Comment by front-end-john** [comment]
<img width="1150" alt="bu3" src="https://user-images.githubusercontent.com/21167738/33875345-f2637bb8-df5c-11e7-919c-b477a5ed0a2f.png">

**Comment by Dafrok** [comment]
你访问一下文档的示例看看是不是也这样

**Comment by front-end-john** [comment]
一片空白

![iphone](https://user-images.githubusercontent.com/21167738/33875638-d1a0f5e4-df5d-11e7-8fbe-cc162b4ddc4a.jpeg)

**Comment by Dafrok** [comment]
做这三步工作：

1. 把 `node_module/vue-baidu-map/src` 的文件复制到你的 src 的某个文件夹下
2. 用 `import VueBaiduMap from '你复制的文件夹/index.js'` 代替 `import VueBaiduMap from 'vue-baidu-map'`
3. 在 `你复制的文件夹/map/Map.vue` 文件中找到的 `getMapScript` 和  `init` 两个实例方法，然后分别放 debugger 进去打一个断点，看一下是在哪一步跳出的

**Comment by For-me** [comment]
加上babel-polyfill试试

**Comment by Dafrok** [comment]
他 console 里没有 throw error，应该已经加过了

**Comment by front-end-john** [comment]
挂掉了
<img width="1667" alt="debug" src="https://user-images.githubusercontent.com/21167738/33877055-30340e12-df62-11e7-85ae-6b4a88e69523.png">

**Comment by Dafrok** [comment]
只复制 src，其它的不管

**Comment by front-end-john** [comment]
Unhandled rejection Error: Cannot find module 'pug'

<img width="1503" alt="budsda" src="https://user-images.githubusercontent.com/21167738/33877972-0ff77f96-df65-11e7-9ac4-e850ff4b98b8.png">

**Comment by Dafrok** [comment]
唉，真麻烦，需要 pug-loader，还有可能需要 stylus-loader

**Comment by front-end-john** [comment]
都有了
<img width="1312" alt="ddd" src="https://user-images.githubusercontent.com/21167738/33878544-a9e17994-df66-11e7-89c9-a39d844d39b2.png">

**Comment by Dafrok** [comment]
在 webpack 里设置一个 alias，把 @ 映射到 `你复制的文件夹`

**Comment by Dafrok** [comment]
大概是这样
```js
{
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '你的文件夹')
    }
  }
}
```

**Comment by Dafrok** [comment]
那就很奇怪了，`node_modules/vue-baidu-map/index.js` 是根据你复制出来这些东西打包而成的，并且刚刚校验过，完全符合 es5 标准，和你 import 的这坨源码应该是没区别的。

我现在依然不能确定你是在哪一步出的问题，如果你愿意继续追踪问题的话可以尝试执行以下操作：

1. 执行以下命令
```
$ cd node_modules/vue-baidu-map
$ npm i
$ webpack --config ./build/webpack.prod.config.js
```
2. 打开刚刚用命令打包生成的 `node_modules/vue-baidu-map/index.js` 按 `ctrl + f` 搜索，找到 `initMap: ` 和 `getMapScript: ` 两个实例方法，分别打一个断点。
3. 把 import VueBaiduMap from './你复制的文件夹/index.js' 改回 import VueBaiduMap from 'vue-baidu-map'。
4. 开启 dev server，看看你打断点的位置是否发生异常。

**Comment by front-end-john** [comment]
好的，等有空在具体看下，官网的示例在iPhone 6上也确实存在问题的，你可以试下

**Comment by Dafrok** [comment]
官网实例不是地图的问题，是使用 UI 框架不支持低版本浏览器

**Comment by front-end-john** [comment]
按照上面三步操作后，console错误：SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

**Comment by front-end-john** [comment]
应该是这个原因导致：https://github.com/mrdulin/blog/issues/35

**Comment by Dafrok** [comment]
https://unpkg.com/vue-baidu-map@0.19.0/index.js

这是编译后的代码，显然里面不包含 const 关键字，因此我推测这个错误和组件库没关系。最好检查一下具体哪一行报了这个错。
