### ISSUE TITLE
地图上只能显示一个信息窗体吗 ？

### ISSUE THREAD

**Issue by Troubledot** [Dafrok/vue-baidu-map#253]
麻烦问一下，我现在的需求是地图上要标记一些点，没个点上需要有个信息窗体来显示一些信息，但是不管写多少只显示一个。。
![qq20171213-105418](https://user-images.githubusercontent.com/18281900/33919513-febf0e44-dff3-11e7-9c7e-095809a27809.png)

![qq20171213-105154](https://user-images.githubusercontent.com/18281900/33919452-bd6c39bc-dff3-11e7-85fd-d54862868ad2.png)
只显示最后一个。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
