### ISSUE TITLE
地图上只能显示一个信息窗体

### ISSUE THREAD

**Issue by Troubledot** [Dafrok/vue-baidu-map#254]
### 浏览器版本号

Google Chrome 版本 63.0.3239.84（正式版本） （64 位）

### Vue 版本号

2.3.3

### 组件库版本号

0.18.9

### 现象描述

```
写了多个信息窗体，地图上只显示最后一个
```

### 完整异常信息

```
无报错
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
显示写了的多个信息窗体，每一个标注对应一个信息窗体
```

### 实际输出

```
只显示最后一个信息窗体
```

![qq20171213-105418](https://user-images.githubusercontent.com/18281900/33920256-e7b11a0e-dff7-11e7-8134-09845a2cf4d3.png)

![qq20171213-105154](https://user-images.githubusercontent.com/18281900/33920258-ea2695de-dff7-11e7-8f5a-22747156ca8d.png)

**Comment by Dafrok** [comment]
不是 bug，百度地图不提供此 feature。
