### ISSUE TITLE
如何实现画一个圆形或者矩形？

### ISSUE THREAD

**Issue by mythbobo** [Dafrok/vue-baidu-map#255]
### 在线示例 URL

无

### 功能描述

```
地图容器没有mousedown事件,如何实现画一个圆形或者矩形呢？
画一个圆形应该是会用到mousedown,mousemove,mouseup事件
但是容器上没有提供mousedown跟mouseup事件,而且会跟地图拖拽事件产生冲突,
问一下大神如何解决这个问题呢？
```

### 用法示例

```
无
```

**Comment by Dafrok** [comment]
click 事件不能添加数据吗？退一步讲，一定要用 mouseup + mousedown 事件的话，你创建一个支持这个事件元素去做代理就好了。

**Comment by mythbobo** [comment]
click事件的话,我如何判断什么时候结束呢。
创建一个支持这个事件元素去做代理是指什么意思呢？是新建一个自定义覆盖物吗？

**Comment by Dafrok** [comment]
click 事件既然能添加数据，为什么就不能修改数据和删除数据呢？

**Comment by mythbobo** [comment]
你的意思是点击第一下确定中心位置，再点下一次的时候就结束画圆吗？但这种体验很不好吧。

**Comment by Dafrok** [comment]
好不好是用户说了算。思路给你了，实在想不明白你可以参考 http://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager.js 的源码，注释写的很明白了，学习下它是怎么实现的。
