### ISSUE TITLE
关于Localsearch

### ISSUE THREAD

**Issue by For-me** [Dafrok/vue-baidu-map#26]
对比了一圈，发现你的vue版本用的2.1.8,我的是2.2.2.webpack你的版本是1.X，我的版本是2.X。不知道会不会是版本引起的返回参数undefined

**Comment by For-me** [comment]
确认了一下。确实在$emit的时候就已经是Undefined了

**Comment by For-me** [comment]
`addLocalSearch: function() {
var t = this,
							e = this.$parent,
							i = e.map,
							a = e.BMap,
							r = this.search,
							s = this.pageCapacity,
							l = this.autoViewport,
							c = this.selectFirstResult,
							u = this.highlightMode,
							f = this.location,
							p = this.resultPanel,
							d = "object" === ("undefined" == typeof f ? "undefined" : n(f)) ? (0, o.createBounds)(f) : f;
						this.local = new a.LocalSearch(d || i, {
							onMarkersSet: function(e) {
								t.$emit("markersset", e)
							},
							onInfoHtmlSet: function(e) {
								t.$emit("infohtmlset", e)
							},
							onResultsHtmlSet: function(e) {
								t.$emit("resultshtmlset", e)
							},
							onSearchComplete: function(e) {
								t.$emit("searchcomplete", 1)
							},
							pageCapacity: s,
							renderOptions: {
								map: i,
								panel: p && this.$el,
								selectFirstResult: c,
								autoViewport: l,
								highlightMode: u
							}
						});`

解压后的版本。这里的

**Comment by For-me** [comment]
@Dafrok 找到问题啦。当传入的keyword是一个数组，查询时如果没有检索到其中的任意一项，就会返回undefined。貌似是百度那边的问题？

**Comment by Dafrok** [comment]
嗯，本组件仅做转发，行为和类参考保持一致

**Comment by For-me** [comment]
还有个问题。localSearch那里按照百度地图API，可以接受point,map,null，你的location这个参数就是这样的。但是在工具方法createBounds那里，你接收了一个BMap作为参数，但是在localSearch那里又没有传入，这样就会导致创建point报错。

**Comment by For-me** [comment]
把BMap传入之后，回调参数就没有返回了。。只能定位到这儿了。。哈哈哈哈

**Comment by Dafrok** [comment]
patch 0.1.11 中修复，文档已更新。

**Comment by For-me** [comment]
@Dafrok 哈哈哈。还有个小问题，localSearch支持map,point,string类型作为基础搜索区域，当为map时，会自动将覆盖物填充到地图上，并且支持自动调整视野，而传入point或者string的话，搜索结果就不应该再被添加到地图上，但是这里如果我传入的是point或者stirng，一样会把结果添加到覆盖物上？请问这也应该是个Bug吧？

**Comment by For-me** [comment]
ok,源码中renderOptions写死了。我自己改改吧

**Comment by Dafrok** [comment]
不是我写死了，官方文档的 renderOptions 的 map 参数只能是 map 实例。

> http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a7b3

**Comment by For-me** [comment]
官方API表达的意思是当传了这个参数，就会起作用，没传或者为null就不会起作用(自动将结果添加到地图上)

**Comment by Dafrok** [comment]
你说的有道理，不过视图层上没有反馈，检索结果看起来也没什么意义。

**Comment by For-me** [comment]
嗯。有时候会有种需求是只是检索某个地点或者地图可视区域内的某些关键字的结果，并不需要反馈到地图上。其实就是当一个拿数据的接口了。。其实后面可以考虑把searchInBounds和searchNearBy这些也封装进去，现在我本地就是这样做的。但是其实这里都能拿到BMap核心类了，不知道是不是多此一举，或者说能够更方便？

**Comment by Dafrok** [comment]
那你新建一个实例，把 map-view 设为 display:none 就行了嘛
