### ISSUE TITLE
子组件独立数据问题。

### ISSUE THREAD

**Issue by giky** [Dafrok/vue-baidu-map#269]
我希望实现鼠标选中某条数据的时候，标注点的zindex变成99。
因为通过api拿到的数据是没有zindex字段的
目前我的实现方式是在父组件的data里面建立一个zindex数据。并且绑定到子组件。
`<bm-marker :position="{lng: item.x, lat: item.y}" :dragging="false"  v-for="(item, index) in pointdata" v-if="isloading" :key="index" ref="bmap" :zIndex="zIndex">
      <bm-label :content="index+item.userNickName" :offset="{width: -3, height: 30}"/>
    </bm-marker>`
但是这样操作，如果我在父组件修改了zindex，所有子组件的zindex都更新了。
我希望鼠标移到某条数据的时候，标注点的zindex才改变。我需要怎么做呢？可以提供一下思路吗？非常感谢。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
