### ISSUE TITLE
关于坐标系的问题

### ISSUE THREAD

**Issue by HiHeidiYoung** [Dafrok/vue-baidu-map#27]
百度地图官方使用BD09的坐标系，用这个插件需要转换吗，或者怎么转换？
![image](https://cloud.githubusercontent.com/assets/11813058/24834940/9694d470-1d25-11e7-894a-8fe4578f9472.png)

**Comment by Dafrok** [comment]
目前可以在地图组件的 ready 事件中调用 BMap.convertor，在回调函数中给相关 prop 传值，未来会考虑使用声明式的方法调用 BMap.convertor。

**Comment by HiHeidiYoung** [comment]
文档里说ready事件中有map参数（地图实例），我调用map缺报undifined。
handler() {
	console.log(map);
},

**Comment by Dafrok** [comment]
console.log(arguments)

**Comment by Dafrok** [comment]
根据百度地图 API 第一方研发人员的说法，坐标转换尽量在后端完成，前端`BMap.converter`的异步转换是没有视图层的纯函数，不适用于声明式调用，推荐在组件的`ready`事件中调该函数来实现，因此该问题被关闭。

**Comment by codeLittleNewbie** [comment]
这边问题是这样的, new BMap.Convertor().translate() 官方提供的方式这样转化坐标,在handler获取到的BMap不带Convertor,如果需要转化坐标我需要导官方script脚本吗?
