### ISSUE TITLE
全景组件BmPanorama如何拿到Panorama对象？

### ISSUE THREAD

**Issue by brahmachen** [Dafrok/vue-baidu-map#272]
### 相关文档 URL

https://dafrok.github.io/vue-baidu-map/#/zh/control/panorama

### 问题描述

```
目前的全景组件能不能做到传入经纬度就打开全景而不用地图选点？
```

### 改进建议

```
希望支持一下
```

**Comment by Dafrok** [comment]
你是指组件绑定的 Panorama 实例吗？访问 `originInstance` 属性即可。

**Comment by brahmachen** [comment]
BmPanorama通用性比较强，目前暂时用不到了。
不过发现百度全景在android微信端有一个闪退bug，这个[bug](http://bbs.lbsyun.baidu.com/forum.php?mod=viewthread&tid=134172&highlight=%E5%85%A8%E6%99%AF%E5%9C%B0%E5%9B%BE%2B%E9%97%AA%E9%80%80)之前有人提过 ，目前还没有直接解决方案

**Comment by Dafrok** [comment]
上头那个是底层 API 本身的性能问题，这个组件库是没法干预的，只能在那边反馈了。
