### ISSUE TITLE
切换页面回来后 Marker 丢失

### ISSUE THREAD

**Issue by solicomo** [Dafrok/vue-baidu-map#275]
### 浏览器版本号

Safari Version 11.0.2 (13604.4.7.1.3)

### Vue 版本号

2.5.13

### 组件库版本号

0.19.0

### 现象描述

```
切换页面导致后追加的 Marker 丢失
```

### 完整异常信息

```
无异常信息输出
```

### 在线示例 / 仓库 URL

https://jsfiddle.net/solicomo/e0gdfqqa/16/

### 复现用例

```
1. 模板创建时，markers 里只有一个 Marker，记为 A；
2. 地图初始化完成后，该 Marker A 正常显示；
3. 通过 ajax （用 timeout 模拟）获取另外两个 Marker，记为 B，C；
4. B，C 被追加到 markers 中后，正常显示；
5. 切换至另一页面（用的是 vue-router，并且 keepalive ）；
6. 再切回地图页；
```

### 预期输出

```
A、B、C 均正常显示。
```

### 实际输出

```
A 仍然显示，B、C 却消失。
```

**Comment by Dafrok** [comment]
你的 `fetchData` 是在 `created` 生命周期中完成的，`vue-router` 只会在初次加载的时候创建组件，路由切走之后你的组件状态就丢了。
目前有两个方法达到你的目的：
1. 把状态保存在组件外，如 `vuex` 中（推荐）
2. 在 `mounted` 生命周期中完成 `fetchData` 的行为

另外还有一种常规的方式，用 `<keep-alive>` 组件维持状态，但是由于百度地图 JS API 的一些特性和 `keep-alive` 有冲突，当前版本还不能这么玩儿，以后的版本计划修复这个问题。

**Comment by solicomo** [comment]
1. 在 `mounted` 中 `fetchData`，问题依旧；
2. 在 `mapReady` 中 `console.log(this.markers)` ，切换回地图时输出仍然是 `A`、`B`、`C` 三个 `Markers`。这是否能说明组件状态没丢？
3. 现在已经在使用 `<keep-alive>` 了，`A` 可以正常显示是否可以说明 `<keep-alive>` 可以维持状态？

[1 和 2 的新示例](https://jsfiddle.net/solicomo/e0gdfqqa/17/)

另外，请问在解决于 `API` 的冲突之前，还有其他方法绕过这个问题么？

**Comment by Dafrok** [comment]
抱歉我忽略了一个问题，我上面的说法是有错误的，百度地图的加载是异步的，但是组件生成是同步的，这就意味着在地图组件没有 ready 的时候你去修改 model 触发对应的 watcher 时，这些操作都是没有意义的。因此不应该在 `mounted` 周期中 `fetchData`，而是应该在 `@ready` 事件中，这个问题文档里有说明。

**Comment by Dafrok** [comment]
另外 `keep-alive` 是的确是可以维持状态，但是由于异步的问题，状态和地图视图不能马上同步，这个过程中会产生一些其它的问题。

**Comment by solicomo** [comment]
@Dafrok 

我把 `fetchData` 挪到 `mapReady` 中去执行了。
另外，为了不重复加载数据（每次切换页面 `mapReady` 都被调用），我在 `fetchData` 之前加了个判断。

问题依旧。

而以前的情况，因为是 `timeout` 模拟的 `ajax` 请求，所以添加 B、C 的时候应该已经 `ready` 了。
B、C 一开始都正常显示了。

这次把 `fetchData` 挪到 `mapReady` 中之后，应该能确定是 `ready` 之后才改的 model 了。
但问题还在。 [示例](https://jsfiddle.net/solicomo/e0gdfqqa/18/)

请问，有其他方法可以动态添加 Marker 并且切换页面不丢失么？

另外，这个问题和 #225 #135 有关系么？

**Comment by Dafrok** [comment]
粗略排查了一下，这里应该是个设计缺陷，为了规避 ready 事件被触发两次的问题，修复方案没有考虑周全。我今天下班时间跟进一下。

如果你着急实现功能，可以先在 `mapReady` 中修改你 model 中的引用以触发子组件的 watcher，这是肯定能正常同步状态的。

**Comment by solicomo** [comment]
@Dafrok 非常感谢。

在 `mapReady` 中加了个 `timeout` 更新了一下 `markers`， 可以了。

[示例](https://jsfiddle.net/solicomo/e0gdfqqa/19/)

非常感谢您的及时沟通，要不我又要在这个问题上耗一天了。

**Comment by Dafrok** [comment]
这是组件库本身的问题造成的麻烦，应该是我谢谢您的认真反馈！

**Comment by gh81997167** [comment]
如何动态添加marker和使用百度地图原生SDK

**Comment by Dafrok** [comment]
0.19.4 修复了该问题，已发版
