### ISSUE TITLE
移动端touchmove(genCenter)问题

### ISSUE THREAD

**Issue by kyuuta** [Dafrok/vue-baidu-map#276]
### 浏览器版本号

Chrome moblie模式 iphone 63.0.3239.108

### Vue 版本号

2.5.13

### 组件库版本号

0.19.0

### 现象描述

```
移动端touchmove无法实时的获取地图中心(e.target.getCtner) 换成moving也不行 地图拖动 移动 但是e.target.getCenter还是最开始触发的位置  麻烦大佬看一下 辛苦了
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

与官网例子 地图容器最后一个一样  只是事件都换过试了一下

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
你确定这个是组件库的问题而不是百度地图的 feature 吗

**Comment by kyuuta** [comment]
不太确定...麻烦了

**Comment by Dafrok** [comment]
你可以先看一下官方的 API 是不是也一样，如果表现不一致那肯定是组件库的 bug

**Comment by kyuuta** [comment]
试了一下...官方的touchmove也不会实时获取中心..sorry

**Comment by Dafrok** [comment]
看样子是不支持这个行为，如果有需求的话可以去官方社区发贴

**Comment by kyuuta** [comment]
谢谢大佬 ..用一个比较投机取巧的方法解决了业务 麻烦了~

**Comment by Dafrok** [comment]
机智如你

**Comment by songispm** [comment]
> 谢谢大佬 ..用一个比较投机取巧的方法解决了业务 麻烦了~

请问怎么个投机取巧的方法，我正好需要解决这个问题，谢啦

**Comment by songispm** [comment]
> 看样子是不支持这个行为，如果有需求的话可以去官方社区发贴

在PC端，dragging事件过程中，center是实时变化的，
到移动端，同样是dragging，center就不变了

touchmove也是，确实官方js api，就是这样，跟vue版大神封装没关系

但是js api到底是官方bug，还是故意为之的呢

**Comment by songispm** [comment]
如果是js api 本身bug，是否可修复

**Comment by kyuuta** [comment]
> > 看样子是不支持这个行为，如果有需求的话可以去官方社区发贴
> 
> 在PC端，dragging事件过程中，center是实时变化的，
> 到移动端，同样是dragging，center就不变了
> 
> touchmove也是，确实官方js api，就是这样，跟vue版大神封装没关系
> 
> 但是js api到底是官方bug，还是故意为之的呢

我个人觉得可能是那样的话 会有性能问题 所以官方不支持这样
我们的需求是要把一个icon移动的时候一直放在地图中心... 后来我直接把icon position fixed在地图中间了- - 要么你就 移动结束之后获取一下center icon给个动画 重新写进去 根据业务灵活调整一下吧..貌似只能这样了

**Comment by Dafrok** [comment]
你这个需求感觉应该用 custom control 来搞

**Comment by Dafrok** [comment]
如果你觉得 control 语义有问题的话，可以研究下 overlay 的 pane 属性

**Comment by songispm** [comment]
但是这没有直接面对这个js api的问题，都是在逃避，我现在有个需求是，用拖动地图用屏幕中心点画出轨迹(polyline/polygon)，在PC端没问题，在移动端一行代码不改就不行

**Comment by Dafrok** [comment]
js api 的问题请去官方社区反馈

**Comment by songispm** [comment]
好的，会去反馈，也请大神如果遇到相关同事，有空就问一下

**Comment by Dafrok** [comment]
这是个人项目，与公司无关
