### ISSUE TITLE
<bm-geolocation/>这个组件定位偏差太大了RIGHT"定位点图片只有在右下角有效果，左下角没有效果

### ISSUE THREAD

**Issue by Waullen** [Dafrok/vue-baidu-map#278]
<bm-geolocation/>这个组件定位偏差太大了，还有就是anchor属性定位点图片只有在右下角能显示，左下角是不显示的

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by Waullen** [comment]
厉害了，都已经按照你说的用issue生成器提交了，为什么删除呢，你这误差都超过五公里了，难道不是问题吗？
