### ISSUE TITLE
如何动态创建marker覆盖物

### ISSUE THREAD

**Issue by gh81997167** [Dafrok/vue-baidu-map#279]
### 浏览器版本号

Google Chrome 63.0.3239.108（正式版本） （64 位）

### Vue 版本号

2.x

### 组件库版本号

0.19.2

### 现象描述

```
文档没查到如何动态创建覆盖物和直接调用百度原生SDK
```

### 完整异常信息

```
文档没查到如何动态创建覆盖物和直接调用百度原生SDK
```

### 在线示例 / 仓库 URL

https://github.com/Dafrok/vue-baidu-map/issues/new

### 复现用例

```
文档没查到如何动态创建覆盖物和直接调用百度原生SDK
```

### 预期输出

```
文档没查到如何动态创建覆盖物和直接调用百度原生SDK
```

### 实际输出

```
文档没查到如何动态创建覆盖物和直接调用百度原生SDK
```

**Comment by Dafrok** [comment]
可以试试 `v-for`。

建议你先学一学 Vue 怎么更新视图再问问自己这个问题。如果觉得文档需要完善可以在 issue 生成器里选择文档问题来提交，issue 区不是灌水的地方，请尊重他人的时间。
