### ISSUE TITLE
bm-local-search使用问题

### ISSUE THREAD

**Issue by jinjinwa** [Dafrok/vue-baidu-map#28]
bm-local-search组件的searchcomplete方法，文档参数是这样的，请问下怎么用啊。
可以给一个demo么？

**Comment by Dafrok** [comment]
事件的用法在 vue 的文档有写。

> https://cn.vuejs.org/v2/guide/events.html#main

**Comment by jinjinwa** [comment]
我是这样用的，但是没拿到参数。。。
