### ISSUE TITLE
如何动态添加marker和使用百度地图原生SDK

### ISSUE THREAD

**Issue by gh81997167** [Dafrok/vue-baidu-map#280]
如何动态添加marker和使用百度地图原生SDK

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by fengqijie** [comment]
我也有同样的问题，楼主大神
