### ISSUE TITLE
路书Path数据切换之后，轨迹速度的问题。

### ISSUE THREAD

**Issue by tong36** [Dafrok/vue-baidu-map#282]
### 浏览器版本号

chrome 63

### Vue 版本号

2.5.2

### 组件库版本号

0.19.5

### 现象描述

```
当我切换路书的path数据时，地图的轨迹已经更改，但是更改后的轨迹运动速度变得特别慢，（注：路书第一次加载好之后，一切正常。）不知什么问题？
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
轨迹速度在Path切换之后，依然正常
```

### 实际输出

```
轨迹速度在Path切换之后，变得很慢很慢
```

**Comment by Dafrok** [comment]
最好能补充一个复现用例，用 codepen 或 jsfiddle 都可以

**Comment by tong36** [comment]
ok！

**Comment by tong36** [comment]
@Dafrok  确实是这样，谢谢了。
