### ISSUE TITLE
地图容器不支持 Theme 传入百度默认模板参数

### ISSUE THREAD

**Issue by kdush** [Dafrok/vue-baidu-map#283]
### 在线示例 URL

http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a0b6

### 功能描述

```
百度地图有有map.MapStyle函数,支持传入'googlelite','dark'等参数,但是vue-baidu-map中使用会提示 Expected Array, got String.
```

### 用法示例

```
<template>
  <baidu-map class="map-root" center="北京" :ak="" theme="dark">
    <bm-view class="bm-view"></bm-view>
  </baidu-map>
</template>
```

**Comment by Dafrok** [comment]
刚看文档以为是被遗漏的 feature，但是在文档中却找不到任何需要使用 `MapStyle` 类型的参数，并且我在唯一有可能使用到这个类型的 `Map.prototype.setMapStyle` 中尝试使用这个类型作为参数抛出了错误，因此我推测这个是官方文档忘记移除了这个类型，如果不是的话还需要你提供一下这个类型的正确使用方法。

**Comment by kdush** [comment]
sorry 可能是我表达的有问题

我的意思是这样让theme参数接受style的字符串参数
`<body>
<div id="mapbox"></div>
<script type="text/javascript">
var map = new BMap.Map("mapbox");
map.centerAndZoom(new BMap.Point(116.403765, 39.914850), 5);
map.setMapStyle({style:'midnight'});  
</script>`

当前vue-baidu-map里只接受形式的参数
`map.setMapStyle({
  styleJson:[[json对象]]
});`

当然我能直接调用地图实例去做map.setMapStyle({style:'midnight'});  这样的操作
期望能接受数组和字符串两种类型的参数,这样调用更优雅

**Comment by Dafrok** [comment]
抱歉昨天发烧有点糊涂，写了个错误的测试用例抛错了，以为 MapStyle 类型过时了，刚才重写了一个发现是正常的。这是个遗漏的 feature，我今天内发版。

**Comment by kdush** [comment]
另外有开发这群吗?求加 @Dafrok

**Comment by kdush** [comment]
@Dafrok 感谢

**Comment by kdush** [comment]
@Dafrok  感谢 请问有开发者群吗 求加

**Comment by Dafrok** [comment]
没有，QQ 上不谈代码

**Comment by Dafrok** [comment]
顺便文档更新了，因为你发现的这个问题和之前的属性有些冲突，所以 theme 属性 deprecate 了，以后都使用 `mapStyle`，不过在当前主版本号依然保持兼容。

**Comment by kdush** [comment]
提个建议, 建议文档中增加更新记录像[echarts](http://echarts.baidu.com/changelog.html) 
这样更新项目依赖的时候会心里有底,不怕和之前版本的使用方式冲突
当然 去看commit也可以,但是好像不太优雅  
最后感谢大神 对问题响应的速度真快

**Comment by Dafrok** [comment]
很好的建议，其实 change log 我本打算在发布 1.0.0 版本后做的，但总是能发现些设计缺陷所以迟迟没有发正式版，比较尴尬
