### ISSUE TITLE
跟进百度地图的第三方库

### ISSUE THREAD

**Issue by mcdongWang** [Dafrok/vue-baidu-map#287]
### 在线示例 URL

http://lbsyun.baidu.com/index.php?title=jspopular3.0/openlibrary

### 功能描述

```
无
```

### 用法示例

```
无
```

**Comment by Dafrok** [comment]
具体指哪些？比较重要的几个已经弄了，其他的基本上在 MVVM 中很好实现，不需要额外引入其他库。MapV 论外，它太庞大了，组件化的工程量远远超过了封装百度地图本身，可以令起新项目做。

**Comment by mcdongWang** [comment]
好的, 现在的路书, 我们做了一个富功能的版本, 等完善后可以考虑加入.

咱们有群或者其他的IM沟通方式么
