### ISSUE TITLE
路书小车在运动过程中的信息窗体的内容是否能根据当前点的内容实时切换？

### ISSUE THREAD

**Issue by tong36** [Dafrok/vue-baidu-map#288]
### 在线示例 URL

https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/lushu

### 功能描述

> 如题。[文档](https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/lushu)，[百度路书](http://api.map.baidu.com/library/LuShu/1.2/docs/symbols/BMapLib.LuShu.html)都是能显示信息窗体内容，却没有提到信息窗体的内容的随着当前点而变化。
谢谢了。

### 用法示例

```
无。
```

**Comment by Dafrok** [comment]
显示什么是你自己控制的。
