### ISSUE TITLE
autoLocation 无法自动获取定位

### ISSUE THREAD

**Issue by hivandu** [Dafrok/vue-baidu-map#29]
在定位控件中加入 :autoLocation = "true", 但是第一次打开地图的时候无法获取定位。

自行用geolocation 来获取定位，更新center后地图却不移动，一定要主动点击定位控件才会聚焦到定位地点。

**Comment by Dafrok** [comment]
https

> http://stackoverflow.com/questions/39366758/geolocation-without-ssl-connection

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-baidu-map/#/control/geolocation
