### ISSUE TITLE
bm-circle组件，当绑定的center或radius改变时，组件的editing状态会自动变为true

### ISSUE THREAD

**Issue by L-Chris** [Dafrok/vue-baidu-map#290]
### 浏览器版本号

chrome 63.0.3239.132

### Vue 版本号

2.x

### 组件库版本号

0.18.4

### 现象描述

```
bm-circle组件，当绑定的center或radius改变时，组件的editing状态会自动变为true
```

### 完整异常信息

```
组件的editing状态会自动变为true
```

### 在线示例 / 仓库 URL

https://dafrok.github.io/vue-baidu-map/#/zh/overlay/circle

### 复现用例

```
bm-circle组件，当绑定的center或radius改变时，组件的editing状态会自动变为true
```

### 预期输出

```
组件的editing状态不变
```

### 实际输出

```
组件的editing状态改变
```

**Comment by L-Chris** [comment]
看了源码，watch钩子里确实会重置为true，这是有意为之吗？

**Comment by Dafrok** [comment]
在哪重置的？可否说一下具体行数？

**Comment by Dafrok** [comment]
似乎是个 bug

**Comment by L-Chris** [comment]
哇大半夜还在处理，真是辛苦了，我遇到这个bug了，看了源码还挺疑惑的
当editing绑定为false时，center和radius改变后就不应该enableEditing()了

**Comment by Dafrok** [comment]
百度地图有一个 feature 导致常规的双向绑定抛错，这里是做了兼容处理

**Comment by Dafrok** [comment]
0.20.4 已发版
