### ISSUE TITLE
定位成功后怎么获取到定位的经纬度？

### ISSUE THREAD

**Issue by search-inner** [Dafrok/vue-baidu-map#292]
<bm-geolocation anchor="BMAP_ANCHOR_TOP_RIGHT" :showAddressBar="true" :autoLocation="true" ></bm-geolocation>

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
