### ISSUE TITLE
控件的触发事件为什么都回调不了？

### ISSUE THREAD

**Issue by horryw** [Dafrok/vue-baidu-map#296]
比如定位控件和缩略图控件都有对应的回调事件（如viewchanged等），我在method中定义了同名的方法，但都没有被回调到，是什么原因呢？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by horryw** [comment]
额，ok了，vue新手，大神见谅

**Comment by horryw** [comment]
顺便反馈一个小问题（不知道是不是我没用对），BMAP_ANIMATION_BOUNCE的动画效果无效
