### ISSUE TITLE
请问reload,load等实例方法是如何调用？

### ISSUE THREAD

**Issue by hopkinson** [Dafrok/vue-baidu-map#298]
![image](https://user-images.githubusercontent.com/13248613/35495265-0e2845a4-04fb-11e8-8f5e-5647b361ba3e.png)

![image](https://user-images.githubusercontent.com/13248613/35495275-18c8c060-04fb-11e8-976d-94dc47c3e438.png)
我已经在<baidu-map>里写了ref.但是不知道如何正确调用？

是否可以直接在某个点击事件上调用
`
    this.$refs.map.reload()
`

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
