### ISSUE TITLE
设置自定义样式后修改点、线数据闪屏

### ISSUE THREAD

**Issue by Lpbzzz** [Dafrok/vue-baidu-map#299]
### 浏览器版本号

chrome 64.0.3282.119（正式版本）

### Vue 版本号

2.1.10

### 组件库版本号

0.20.4

### 现象描述

```
设置mapstyle后更改地图内点、线等信息，地图反复重新加载导致闪屏
```

### 完整异常信息

```
-
```

### 在线示例 / 仓库 URL

-

### 复现用例

```
-
```

### 预期输出

```
-
```

### 实际输出

```
-
```

**Comment by Lpbzzz** [comment]
谢谢大佬开发维护组件

**Comment by Lpbzzz** [comment]
可能我说的不清楚。需求：轮询数据，在设置了自定义样式的地图上不停展示最新的数据。每次改变数据都会使地图重新加载一次。默认样式则不会如此。

**Comment by Dafrok** [comment]
要看你改的是什么，有些属性是没法动态变更的，只能通过 reload 同步视图。请提供一个简单的复现用例

**Comment by Lpbzzz** [comment]
<baidu-map class="map" :center="{lng: 116.410, lat: 39.935}" :zoom="14" :scroll-wheel-zoom="true" :mapStyle="{styleJson: styleJson}">

        <div v-for="items in markerPoints">
                <bm-marker :position="items" :icon="{url: '../img/lajiche.png', size: {width: 50, height: 30}}"></bm-marker>
        </div>

</baidu-map>
markerPoints：[
               {
                    lng: 116.404,
                    lat: 39.915
                }{
                    lng: 116.414,
                    lat: 39.925
                 }
]
地图设置了 styleJson，
markerPoints 一直在更新，
每次更新地图会闪一次（重新加载了地图？）

**Comment by Dafrok** [comment]
你为什么要包个 div 在 marker 外面？

**Comment by Dafrok** [comment]
另外光看 marker 没意义，show more your code

**Comment by Dafrok** [comment]
按照你的描述写了一个复现用例，无法复现你的问题。请将补充描述或在 codepen 或 jsfiddle 上提供完整的复现用例。

**Comment by Lpbzzz** [comment]
![pic](https://user-images.githubusercontent.com/28721487/35600056-e97fc570-0666-11e8-84ae-816b37baa37b.png)
1.包这个div是因为没注意到 ---海量点---0.0
2.
![pic1](https://user-images.githubusercontent.com/28721487/35600005-9a89a044-0666-11e8-8178-cc2a59ab5d03.png)
在地图上设置自定义样式:mapStyle="{styleJson: styleJson}"，绑定数据的  markerPoints  
![pic3](https://user-images.githubusercontent.com/28721487/35600055-e5b4eef2-0666-11e8-9a73-ebcccd8d53fe.png)
![pic](https://user-images.githubusercontent.com/28721487/35600064-f1975cc8-0666-11e8-87e0-2d905b1c1fe0.png)
模拟需求（socket或者轮询更新markerPoints）
![gif](https://user-images.githubusercontent.com/28721487/35600210-cbccfbc8-0667-11e8-8cfe-a41c45a40fe1.gif)

**Comment by Dafrok** [comment]
你这不是 `marker` 是 `point-collection` ……我大概知道怎么回事了

**Comment by Lpbzzz** [comment]
请教您一下：
1.如果我要展示很多点的位置是应该v-for单个点还是用海量点呢？
2.其实不管是点  还是海量点 ，最终的效果都是gif图的样子，每次改变点位置都会闪一次。这个是用在大屏展示，所以不能闪--。

**Comment by Dafrok** [comment]
1. 超过三位数的点一定要用海量点。`Marker` 封装程度太高，消耗资源很大，会卡顿。
2. 我昨天用一模一样的代码完全没复现出你的状况，希望能用 jsfiddler 弄一个在线演示。

**Comment by Dafrok** [comment]
好的，我抽空看看

**Comment by Dafrok** [comment]
看了下，你的 mapStyle 声明了一个匿名对象，所以在 model 更新的时候 vue 会重新声明一个新的长的一样但是引用不同的匿名对象，导致了新旧对象对比的时候发现不相等，触发了 mapStyle 的 watcher 重新渲染了一遍主题。要解决这个问题你直接在 model 里声明一个具名对象就行了。

**Comment by Lpbzzz** [comment]
- -。看懵了。大佬如果有时间可否详解一下？不胜感激

**Comment by Dafrok** [comment]
Good:

```html
<baidu-map :mapStyle="mapStyle">
```

Bad:

```html
<baidu-map :mapStyle="{styleJson: styleJson}">
```

**Comment by Lpbzzz** [comment]
谢谢解答！您可以挂个二维码什么的，大家都会支持一下开源作者的！

**Comment by Lpbzzz** [comment]
谢谢解答！您可以挂个二维码什么的。大家都会支持开源作者的！

**Comment by Lpbzzz** [comment]
对了，stylejson可以设置官方已有的吗？midnight 这种的

**Comment by Dafrok** [comment]
http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a0b6

**Comment by edgexie** [comment]
@Dafrok 作者你好，感谢你的贡献。我看到楼上有人问styleJson 是否可以设置成官方已有的比如midnight，我也很关心这个问题。但在您回的连接中我没有找到答案。您是否有解决办法？

**Comment by Dafrok** [comment]
http://lbsyun.baidu.com/custom/

**Comment by side9527** [comment]
要设置自定义样式不是要通过theme吗
