### ISSUE TITLE
有一个功能用上vue-baidu-map 不知道如何实现

### ISSUE THREAD

**Issue by Hogg222** [Dafrok/vue-baidu-map#3]
想实现这样一个需求
在BMap加载之后 获取用户位置 用户授权后 根据坐标搜周边超市

本想用MapControlGeolocation在加载后自动获取 发现并不会用这个组件 似乎不能通过 enableAutoLocation来自动定位...不知道如何在他自动定位后把相应的值赋给用户的坐标值

后来我用navigator.geolocation.getCurrentPosition来进行获取位置 但是再IOS10上无法正常显示...

想问如何实现和用好控件

**Comment by Dafrok** [comment]
经测试这应该是百度地图 JS API 的一个 bug，已经反馈给相关部门，有响应我会在这里追加评论。另外 `enableAutoLocation` 已经改名为 `autoLocation` 文档稍后会更新。

**Comment by Hogg222** [comment]
这是我从vue-amap上得到的信息
**由于 Chrome 、IOS10 等已不再支持非安全域的浏览器定位请求，为保证定位成功率和精度，请尽快升级您的站点到 HTTPS 。**
经实验换成https后 IOS10上是可以用了

**Comment by Dafrok** [comment]
原来如此，我确实是忽略了在 https 环境下测试一遍，感谢反馈！

**Comment by AntJavascript** [comment]
还是没解决怎么自动定位

**Comment by Dafrok** [comment]
文档已经解释的很详细了 https://dafrok.github.io/vue-baidu-map/#/zh/control/geolocation

**Comment by AntJavascript** [comment]
ready 之后是BMap怎么没有这个方法？getCurrentPosition,没有办法获取经纬度

**Comment by Dafrok** [comment]
看文档了吗？

**Comment by AntJavascript** [comment]
看了，没找到，能不能指点一下，怎么搞，急啊

**Comment by Dafrok** [comment]
> 根据 [W3C 标准](https://www.w3.org/TR/geolocation-API/#privacy_for_uas) 描述，为保证用户隐私安全，geoLocation API 必须使用 SSL 连接，并获得用户的手动许可。请确保使用该属性时满足上述条件。

为了防止以后有人不明白为什么在这里解释一下吧：

1. 为什么需要用户手动许可

如果 web 页面可以在用户不需要手动确认的情况下获取用户的地理位置意味着什么？假设有人让你打开了一个钓鱼页面，这个页面里恰好嵌入了一段获取地理位置的脚本并发送给了服务器，任何人都可以轻易获取你的所在位置，这是非常危险的。

2. 为什么必须使用 https

http 协议是明文传输数据的，http 包一旦被劫持，可以轻易获取你的地理位置信息并用于不法用途。

**Comment by Hu-liang** [comment]
地图挂载的速度可能比较慢 , 可以自己做单例模式检查实例是否挂载上 @AntJavascript
