### ISSUE TITLE
我需要在vue中画多边形，需要引入鼠标绘制工具条库DrawingManager类，但是npm里面没有，该怎么办

### ISSUE THREAD

**Issue by cyemeng** [Dafrok/vue-baidu-map#301]
### 在线示例 URL

http://lbsyun.baidu.com/jsdemo/demo/f0_7.htm

### 功能描述

```
需要在vue项目里使用绘制工具
```

### 用法示例

```
http://lbsyun.baidu.com/jsdemo/demo/f0_7.htm
```

**Comment by Dafrok** [comment]
以前有人问过同样的问题，建议先翻翻 issue list。
https://github.com/Dafrok/vue-baidu-map/issues/242
