### ISSUE TITLE
请问lushu覆盖物可否添加点击事件

### ISSUE THREAD

**Issue by tingwu55** [Dafrok/vue-baidu-map#307]
### 在线示例 URL

无

### 功能描述

```
lushu覆盖物可否添加点击事件
```

### 用法示例

```
无
```

**Comment by Dafrok** [comment]
http://api.map.baidu.com/library/LuShu/1.2/docs/symbols/BMapLib.LuShu.html

路书组件是百度地图第三方路书插件的抽象，路书本身没有暴露生成的 marker，你可以通过访问路书组件的 `originInstance` 来访问路书实例，并自行添加点击事件。
