### ISSUE TITLE
地区检索结果自定义视图或者点击事件

### ISSUE THREAD

**Issue by kangxiaojun** [Dafrok/vue-baidu-map#308]
### 浏览器版本号

Chrome 64.0.3282.119

### Vue 版本号

2.5.2

### 组件库版本号

0.20.7

### 现象描述

```
目前的地区检索功能，拿到结果后，会自动将结果显示在地图上，能不能设置成根据需求自定义是否要将搜索结果显示到地图上，或者给每个显示在地图上的marker添加一个自定义点击事件
```

### 完整异常信息

```
地区检索功能获取数据后无法关闭自动填充到地图中
```

### 在线示例 / 仓库 URL

https://dafrok.github.io/vue-baidu-map/#/zh/search/local-search

### 复现用例

```
https://dafrok.github.io/vue-baidu-map/#/zh/search/local-search
```

### 预期输出

```
搜索到结构后可以自定义是否显示marker，或者可以给marker添加自定义的点击事件
```

### 实际输出

```
搜索到结果后总是自动将结果显示到地图中，并且每个marker的点击事件不能自定义
```

**Comment by Dafrok** [comment]
地区检索组件是百度地图 JS API 中 [LocalSearch](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference_3_0.html#a7b0) 类的抽象，该类没不支持定制。

如果有定制需求，可以自行调用 百度地图 [Web API](http://lbsyun.baidu.com/index.php?title=webapi) 来获取数据，并按照你的期望渲染到视图上。
