### ISSUE TITLE
覆盖点 BmPointCollection 异步获取 points 控制台报错

### ISSUE THREAD

**Issue by CosSalt** [Dafrok/vue-baidu-map#312]
### 浏览器版本号

Google Chrome  65.0.3325.162（正式版本） （64 位）

### Vue 版本号

2.5.13

### 组件库版本号

0.20.7

### 现象描述

```
覆盖点 BmPointCollection 异步获取 points 控制台报错，测试用的是vue.$nextTick方法
```

### 完整异常信息

```
[Vue warn]: Error in callback for watcher "points": "TypeError: Cannot read property 'clear' of undefined"

found in

---> <BmPointCollection>
       <BmMap>

vue.runtime.esm.js?ff9b:1737 TypeError: Cannot read property 'clear' of undefined
    at VueComponent.handler (index.js?7401:1)
    at Watcher.run (vue.runtime.esm.js?ff9b:3229)
    at flushSchedulerQueue (vue.runtime.esm.js?ff9b:2977)
    at Array.eval (vue.runtime.esm.js?ff9b:1833)
    at flushCallbacks (vue.runtime.esm.js?ff9b:1754)
```

### 在线示例 / 仓库 URL

无（测试时用的官方随机生成海量覆盖点的案例）

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
把你的代码附上，这很重要

**Comment by CosSalt** [comment]
<template>
  <baidu-map class="bm-view" center='四川' :scroll-wheel-zoom="true" >
    <bm-point-collection :points="points" shape="BMAP_POINT_SHAPE_WATERDROP"  @click="clickHandler"></bm-point-collection>
  </baidu-map>
</template>
<script>
export default {
  data () {
    return {
      points: []
    }
  },
  created(){
    this.$nextTick(() =>{
      this.addPoints()
    })
  },
  methods: {
    clickHandler (e) {
      alert(`单击点的坐标为：${e.point.lng}, ${e.point.lat}`);
    },
    addPoints () {
      const points = [];
      for (var i = 0; i < 1000; i++) {
        const position = {lng: Math.random() * 40 + 85, lat: Math.random() * 30 + 21}
        points.push(position)
      }
      this.points = points
    }
  }
}
</script>

<style>
.bm-view {
  width: 100%;
  height: 300px;
}
</style>

**Comment by CosSalt** [comment]
﻿

```
<template>
  <baidu-map class="bm-view" center='四川' :scroll-wheel-zoom="true" >
    <bm-point-collection :points="points" shape="BMAP_POINT_SHAPE_WATERDROP"  @click="clickHandler"></bm-point-collection>
  </baidu-map>
</template>
<script>
export default {
  data () {
    return {
      points: []
    }
  },
  created(){
    this.$nextTick(() =>{
      this.addPoints()
    })
  },
  methods: {
    clickHandler (e) {
      alert(`单击点的坐标为：${e.point.lng}, ${e.point.lat}`);
    },
    addPoints () {
      const points = [];
      for (var i = 0; i < 1000; i++) {
        const position = {lng: Math.random() * 40 + 85, lat: Math.random() * 30 + 21}
        points.push(position)
      }
      this.points = points
    }
  }
}
</script>

<style>
.bm-view {
  width: 100%;
  height: 300px;
}
</style>
```

**Comment by Dafrok** [comment]
是不是没认真文档？ready 事件了解一下

**Comment by CosSalt** [comment]
重新试了下，没报错了 非常抱歉
