### ISSUE TITLE
如何多次触发ready 事件（在ready事件外如何触发handler()方法，需要带什么参数？）

### ISSUE THREAD

**Issue by QiDekang** [Dafrok/vue-baidu-map#313]
### 问题描述
需求是使用BMap.Geocoder()方法将用户输入的地址解析成经纬度坐标。
目前能够在 ready 事件中使用返回的 BMap 类和 map 实例进行手动控制。但是ready事件只能在地图创建时运行一次。

当我试图在input的change事件中触发handler方法时，报错Cannot read property 'BMap' of undefined"
[错误信息](https://raw.githubusercontent.com/QiDekang/feedback/master/others/BMap.png)

ready事件只能在地图创建时运行一次，无法对用户输入做出响应。在ready事件外触发handler()方法又不知道需要传递什么参数才可以。

万望大神不吝赐教。

### 代码
    <template>
      <div class="test">
        <baidu-map class="AddressMap" :center="center" :zoom="15" :scroll-wheel-zoom="true" @ready="handler">
          <group class="AddressInput">
            <x-input placeholder="请输入详细地址" v-model="communityInputValue" @on-change="change"></x-input>
          </group>
        </baidu-map>
      </div>
    </template>

    <script>
    import { Group, XInput } from 'vux'

    export default {
      components: {
        Group,
        XInput
      },
      data () {
        return {
          center: {lng: 0, lat: 0},
          zoom: 3,
          communityInputValue: ''
        }
      },
      methods: {
        handler ({BMap, map}) {
          console.log(BMap, map)
          this.center.lng = 116.404
          this.center.lat = 39.915
          this.zoom = 15
          // 创建地址解析器实例
          var myGeo = new BMap.Geocoder()
          // 将地址解析结果显示在地图上，并调整地图视野
          var myAddress = this.communityInputValue
          if (myAddress.length > 0) {
            myGeo.getPoint(myAddress, function (point) {
              if (point) {
                map.centerAndZoom(point, 16)
                map.addOverlay(new BMap.Marker(point))
                console.log(point)
              } else {
                console.log('您选择的地址没有解析到结果!')
              }
            },
            '北京市')
          }
        },
        change (val) {
          this.handler()
          //  this.handler(this.BMap, this.map)
        }
      }
    }
    </script>

    <style lang="stylus">
    @import "../../common/stylus/variable"
    .test
      .AddressMap
        width: 100vw
        height: 100vh
        .AddressInput
          width: 100vw
          position: absolute
          top: 4.0005vw
          z-index: 20
    </style>

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
