### ISSUE TITLE
海量点在移动端无法点击

### ISSUE THREAD

**Issue by gwshawsh** [Dafrok/vue-baidu-map#316]
### 在线示例 URL

https://dafrok.github.io/vue-baidu-map/#/zh/overlay/point-collection

### 功能描述

```
海量点在移动端无法点击
```

### 用法示例

```
海量点在移动端无法点击
```

**Comment by Dafrok** [comment]
![img_2755](https://user-images.githubusercontent.com/6159588/37637763-7a8c4996-2c44-11e8-8bf1-9b52703c3479.PNG)
