### ISSUE TITLE
您好，我想咨询一下你项目里面的index.js的内容从何而来

### ISSUE THREAD

**Issue by WuPanFeng** [Dafrok/vue-baidu-map#32]
您好，我想咨询一下你项目里面的index.js的内容从何而来。我想用腾讯地图做一个vue组件。学习了你的项目，想去实践一下。但是不知道这个index.js的内容从何而来。

**Comment by Dafrok** [comment]
当然是自己写的啊😂

**Comment by WuPanFeng** [comment]
高手。我已经在用了，求加入逆地址解析，距离计算。非常感谢！！！

**Comment by Dafrok** [comment]
逆地址解析和距离计算不涉及视图，vue 只负责处理视图部分的，纯计算的部分可以通过在全局ready事件中调用 BMap 核心类和 map 实例进行 model 层的操作。

**Comment by WuPanFeng** [comment]
哦。 明白啦 谢谢告知。
