### ISSUE TITLE
在你的vue-baidu-map中的DrawingManager的new BMap怎么处理

### ISSUE THREAD

**Issue by swliu920322** [Dafrok/vue-baidu-map#320]
### 在线示例 URL

https://github.com/swliu920322/vue-baidu-map.git

### 功能描述

```
业务需要用了你的vue-baidu-map,需要DrawingManager，不太会，就在你里面按你的代码改，由于继承了Bmap原形，提示 Uncaught ReferenceError: BMap is not defined
```

### 用法示例

```
<bml-drawing-manager :isOpen="isOpen" :enableDrawingTool="enableDrawingTool">
  
  </bml-drawing-manager>
```

**Comment by Dafrok** [comment]
自己封装组件？

**Comment by Dafrok** [comment]
简单 review 了一下你的问题，先说原因：组件库中的百度地图的引入是异步的，这意味着你引入 Drawing Manager 的时候百度地图 API 还没有 ready，自然就 not defined 了。

三个建议，按推荐度排序：
1. 不用 DrawingManager。因为在 MVVM 中图形是非常简单的事，只操作数据就够了，不需要额外引入类库。
2. 同步引入百度地图 API，即使用官网推荐的 script 标签直接声明。
3. 二次封装 DrawingManager，使其支持异步加载，可以参考 https://github.com/Dafrok/BMapLib.LuShu ，有一点上手难度。

**Comment by swliu920322** [comment]
好的，谢谢，昨天晚上就在照着lushu再做，由于没有去看你所有的代码，遇到了很多问题，目前在.vue文件里面定义的props，在.md里面使用，一直告诉我Property or method "drawingToolOptions" is not defined on the instance but referenced during render

**Comment by Dafrok** [comment]
绘制图形的问题似乎很多人都提了，其实没什么难度的。
我打算这几天在文档里补上一个 Guide，简单举几个例子说明这个问题

**Comment by swliu920322** [comment]
那多谢了，大佬加油，

**Comment by swliu920322** [comment]
我自己按照lushu的搞了一个bmaplib.drawingManager,之前看你的lushu里面继承Bmap原形的都放进方法里面调用的时候继承，不过第一次用百度地图，不是很知道有些东西的加载顺序，刚学vue，感觉有点难度，做现在的事情

**Comment by swliu920322** [comment]
直接画多边形时，通过click事件往多边形数组里面加点，由于需求要绘制工具条，所以谢谢你了

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-baidu-map/#/zh/guide/painting

简单撸了一个图形绘制的示例，参考这个搞吧，应该比引入第三方库简单很多。

**Comment by cjj0619** [comment]
> https://dafrok.github.io/vue-baidu-map/#/zh/guide/painting
> 
> 简单撸了一个图形绘制的示例，参考这个搞吧，应该比引入第三方库简单很多。
你好，这个有属性设置吗？？

**Comment by sunflowerSmileAndSmile** [comment]
https://dafrok.github.io/vue-baidu-map/#/zh/guide/painting 不知道为什么使用MVVM做的图形绘制，项目运行一阵之后就卡，使用原生百度地图的就不会，还有就是使用vue-baidu-map之后，不知道是操作问题还是咋的，经常vue扩张工具崩溃？？？
