### ISSUE TITLE
使用dialog加载弹窗，中心点问题

### ISSUE THREAD

**Issue by fengzhentian** [Dafrok/vue-baidu-map#321]
### 在线示例 URL

无

### 功能描述

```
我在列表页面，使用dialog的方式弹出添加页、修改页，这两个页面使用了同一个vue文件
按照我们的业务逻辑，打开添加页时，将一个默认的城市中心点设置为地图中心点
打开修改页，将这条信息里绑定的经纬度，设置为地图中心点
这里共用了一个center变量，存储当前地图的中心点

现在的问题是，如果我先打开修改页。关闭后，再打开添加页后，地图居中到了一个奇怪的地方
如果先打开添加页，添加页显示正常，再打开修改页，修改页正常。再打开添加页，添加页不正常。。。

只要打开过修改页，添加页就不能居中到我指定的点
不同信息的修改页，都是可以正常居中的
```

### 用法示例

```
无
```

**Comment by Dafrok** [comment]
建议延迟一下再重新修改 center 位置，检查到底是数据的问题还是组件的问题

**Comment by fengzhentian** [comment]
setTimeout(() => {
	this.mapOption.center.lng = p.lng
	this.mapOption.center.lat = p.lat
	this.mapOption.zoom = 14
}, 100)

添加页，这么处理就可以了
第一次打开后，地图应该已经算是正常加载完了，我觉得应该可以直接调用了呀
按照我的理解应该不用加setTimeout
加了setTimeout相当于再启动一个异步来设置

而且，使用nextTick也是不能处理的，好像只有setTimeout可以
this.$nextTick(() => {
	this.mapOption.center.lng = p.lng
	this.mapOption.center.lat = p.lat
	this.mapOption.zoom = 14
})

**Comment by Dafrok** [comment]
视图出问题说明数据不对，打断点看看你的数据是怎么变化的

**Comment by fengzhentian** [comment]
我跟到了map.vue组件里，查看watch里这两个是正常赋值的，但是并没有将地图对应的我指定的位置
我加了setTimeout和不加，new BMap.Point里传递的值是一样的
但是加了setTimeout居中的位置就是对的
不加就会偏移到了我指定的点的右下角的一个位置上

  watch: {
    'center.lng'(val, oldVal) {
      const { BMap, map, zoom, center } = this;
      if (val !== oldVal && val >= -180 && val <= 180) {
        map.centerAndZoom(new BMap.Point(val, center.lat), zoom);
      }
    },
    'center.lat'(val, oldVal) {
      const { BMap, map, zoom, center } = this;
      if (val !== oldVal && val >= -74 && val <= 74) {
        map.centerAndZoom(new BMap.Point(center.lng, val), zoom);
      }
    },

**Comment by fengzhentian** [comment]
如果不加setTimeout，偏移的幅度为
大约是我指定的这个中心点，变成左上角的点

**Comment by Dafrok** [comment]
希望能提供一个能还原场景的示例，我周末尝试了一下没有复现成功

**Comment by fengzhentian** [comment]
https://codepen.io/fengzhentian/pen/pLWdNZ
https://codepen.io/fengzhentian/full/pLWdNZ/

借鉴了别人的示例，在这个网址上简单加了下
我在这里描述下，第一次打开页面后，打开添加、修改都是正常的
但是先打开添加后，再打开修改不正常。
先打开修改后，再打开添加不正常

**Comment by guohuihot** [comment]
我也遇到这个问题了，作了个st

**Comment by Dafrok** [comment]
没有想到什么好办法，在源码里 setTimeout 感觉有点 dirty

**Comment by guohuihot** [comment]
造成这个问题的原因是什么呢？

**Comment by guohuihot** [comment]
还有一个问题，就是map放dialog后，只有dialog弹出后才执行，map的ready方法，有没有办法，让dialog没弹出前就执行？

**Comment by dingfeipeng** [comment]
我也遇到了，但是中心点问题倒是解决了，但是鼠标滑轮缩放，中心点偏移到大西洋，同样是Modal 对话框

**Comment by fengzhentian** [comment]
使用图形绘制（bm-control）来画多边形时，如果是正常的页面，是可以正常绘制的
但是使用dialog的方式弹出时，绘制点也是会偏移
我百度搜索地图显示偏移问题，大部分都是说dialog采用的是position:fixed的方式来定位，造成的百度地图定位不准，但是没有找到解决方法

**Comment by fengzhentian** [comment]
这个是示例
https://codepen.io/fengzhentian/pen/gevmzX

**Comment by dingfeipeng** [comment]
没有使用多边形绘制

**Comment by dingfeipeng** [comment]
非常感谢
，您百忙之中查看我遇到的BUG，并针对我的问题email

**Comment by dingfeipeng** [comment]
具体的BUG在这里http://otogjolty.bkt.clouddn.com/GIF.gif

**Comment by fengzhentian** [comment]
绘制多边形这个问题，在el-dialog里补充上这个属性配置，就可以了。。。
:append-to-body="true"

**Comment by Dafrok** [comment]
@fengzhentian 没用过 element，竟然有这种骚操作。。。

**Comment by chaofan-rensheng** [comment]
@dingfeipeng 你的问题有没有解决就是缩放的时候中心点偏移

**Comment by xiaohaiH** [comment]
地图的祖先级元素，有没有用 transform

**Comment by MrZhouZh** [comment]
目前也碰到这种情况，我用了一个笨方法：v-if 指令强制注销 vue-baidu-map 组件

**Comment by chenchenwuai** [comment]
> @dingfeipeng 你的问题有没有解决就是缩放的时候中心点偏移

我这边设置了中心点和缩放等级的双向绑定，就不漂移了。 [参考官网demo 双向绑定](https://dafrok.github.io/vue-baidu-map/#/zh/map/baidu-map)
