### ISSUE TITLE
如何让ready事件在vue的mounted后执行

### ISSUE THREAD

**Issue by fengqijie** [Dafrok/vue-baidu-map#323]
您好，我需要先在vue的mounted方法里面执行获取坐标的函数，然后再在ready里面执行handler函数，handler中需要将我获取到的数据转换成您的组件支持的坐标格式。但是mounted还未执行，ready已经执行了，导致split为null。请大神指教
handler() {
      var vm = this;
      var pArray = vm.resPosition.split(",");
      vm.transPoint = {
        lng: parseFloat(pArray[0]),
        lat: parseFloat(pArray[1])
      };
    },

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
