### ISSUE TITLE
海量点，根据数据的状态渲染不同的颜色

### ISSUE THREAD

**Issue by Lpbzzz** [Dafrok/vue-baidu-map#326]
### 浏览器版本号

chrome 64位 65.0.3325.181

### Vue 版本号

2.1.10

### 组件库版本号

0.20.4

### 现象描述

```
海量点如何根据数据的状态渲染不同的颜色，自己写了一下但是没实现。
```

### 完整异常信息

```
海量点如何根据数据的状态渲染不同的颜色，自己写了一下但是没实现
```

### 在线示例 / 仓库 URL

https://github.com/Lpbzzz/vue-baidu-map-test.git

### 复现用例

```
根据数据的状态status ，completed 时渲染绿色点，否则红色
```

### 预期输出

```
根据数据的状态status ，completed 时渲染绿色点，否则红色
```

### 实际输出

```
全部为某一颜色。不知道怎么写，还望赐教!
```

**Comment by Dafrok** [comment]
用两个海量点组件不就行了…

**Comment by Lpbzzz** [comment]
数据量在100-500之间，多个组件这样会损失很多性能吗？多个海量点的性能肯定是比多个普通点的性能好吧？另外，地图上的覆盖物多了之后，用滚轮控制zoom，地图中心点会来回跳。。。

**Comment by Lpbzzz** [comment]
哦哦。我好像明白您说的了，先把complete的和非completed的分开是吧?

**Comment by Dafrok** [comment]
你可以试着用百度地图API的海量点类实现一下你的需求就明白了，逻辑是守恒的，百度地图做不到的事，翻译成模板也做不到
