### ISSUE TITLE
更新聚合类

### ISSUE THREAD

**Issue by li3007liuu** [Dafrok/vue-baidu-map#329]
更新了百度地图聚合类，想问一下，怎么添加到包里使用呢？现在有本地MarkerClusterer.js TextIconOverlay.js，不知道该如何修改 MarkerClusterer.vue引用才能加载进去呢？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
