### ISSUE TITLE
marker的属性没写全？

### ISSUE THREAD

**Issue by jeromelive** [Dafrok/vue-baidu-map#33]
怎么设置信息窗口，marker 里面只有一个 label 的例子。marker 有 infowindowclose infowindowopen 这两个事件，怎么能触发？能随手写个点和弹框的例子吗？麻烦了！！

**Comment by jeromelive** [comment]
点击 marker  弹出一个 信息窗口

**Comment by Dafrok** [comment]
文档更新了 `BmMarker` 组件的第三个示例，请更新到 0.10.1 参照文档使用。

> https://dafrok.github.io/vue-baidu-map/#/overlay/marker
