### ISSUE TITLE
PC端和移动端不兼容问题

### ISSUE THREAD

**Issue by Zhantrywei** [Dafrok/vue-baidu-map#335]
PC端没有报Unexpected token o in JSON at position 1问题,用浏览器调试或者手机调试,切换成移动端的就报这个错误,前端小白,希望大神回答帮忙解决下,谢谢!

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
