### ISSUE TITLE
点聚合首次加载不显示

### ISSUE THREAD

**Issue by chris1025** [Dafrok/vue-baidu-map#338]
使用点聚合功能，加载页面后不显示，需要拖动地图后才能显示
` <bml-marker-clusterer :averageCenter="true">
        <bm-marker v-for="item in deviceDataList" :position="item.location" :dragging="false">
        </bm-marker>
</bml-marker-clusterer>`

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by Yin-Xie** [comment]
哥 你解决了吗
