### ISSUE TITLE
设置点 自定义图标报错。

### ISSUE THREAD

**Issue by yuanyuangong** [Dafrok/vue-baidu-map#34]
[Vue warn]: Error in callback for watcher "icon": 
(found in <BmMarker>)

TypeError: Cannot read property 'setIcon' of undefined
    at VueComponent.handler (eval at <anonymous> (app.js:3479), <anonymous>:1:30612)
    at Watcher.run (eval at <anonymous> (app.js:809), <anonymous>:2552:19)
    at flushSchedulerQueue (eval at <anonymous> (app.js:809), <anonymous>:2330:13)
    at Array.eval (eval at <anonymous> (app.js:809), <anonymous>:506:20)
    at nextTickHandler (eval at <anonymous> (app.js:809), <anonymous>:455:16)

**Comment by Dafrok** [comment]
请参照文档示例中的用法

**Comment by Dafrok** [comment]
有复现场景吗

**Comment by yuanyuangong** [comment]
大神 这是我的代码  /5555 我已经放弃了 。因为 用vue-cli 打包 出来  用浏览器打开 地图不显示 也不报错。bm-info-window 这个组件里的 内容 直接 显示在 页面下面 。如果可以 不知道 大神 是否可以加个Q 我截图比较好说明
<bm-marker v-for="(item,index) in geoCoordMap" :position="{lng: item[0], lat:item[1]}" :icon="{url:'../../../static/assets/images/'+item[2]+'.png', size: {width: 32, height: 32}}" :title="'32131'" animation="null" @click="infoWindowOpen(index)"></bm-marker>

**Comment by yuanyuangong** [comment]
我QQ1075805990

**Comment by yuanyuangong** [comment]
我现在 用IFRAME  把 百度地图嵌在VUE 框架里。感觉不伦不类

**Comment by yuanyuangong** [comment]
看 vue-baidu-map 源码 暂时 还没找到 http://api.map.baidu.com/api?v=2.0&ak=AK 这个链接 也是郁闷了

**Comment by Dafrok** [comment]
github 是可以截图的……

**Comment by Dafrok** [comment]
https://github.com/Dafrok/vue-baidu-map/blob/master/src/map/Map.vue#L221
链接不是在这里吗

**Comment by Dafrok** [comment]
我大概分析了一下，你的 geoCoordMap 对象是不是在地图组件加载完之前进行的赋值操作？所有的 model 层操作都是要在对应组件 ready 事件中完成的。
