### ISSUE TITLE
vue build打包发布问题

### ISSUE THREAD

**Issue by wsh0521** [Dafrok/vue-baidu-map#341]
build 打包的时候回出现这个 error ！
ERROR in static/js/vendor.8d9fdaf01f202a25ab31.js from UglifyJs
Unexpected token: operator (>) [./node_modules/_vue-baidu-map@0.21.3@vue-baidu-map/components/base/bindEvent.js:6,0][static/js/vendor.8d9fdaf01f202a25ab31.js:269,26]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by wsh0521** [comment]
build 打包的时候回出现这个 error ！
ERROR in static/js/vendor.8d9fdaf01f202a25ab31.js from UglifyJs
Unexpected token: operator (>) [./node_modules/_vue-baidu-map@0.21.3@vue-baidu-map/components/base/bindEvent.js:6,0][static/js/vendor.8d9fdaf01f202a25ab31.js:269,26]

**Comment by cnqiuxue** [comment]
{
                test: /\.js$/,
                loader: 'babel-loader?cacheDirectory',
                include: [ 
                    resolve('src'), 
                    resolve('test'),
                    resolve('node_modules/vue-baidu-map'), //  添加这个后好了
                ]
            },
