### ISSUE TITLE
marker单击不能显示BmInfoWindow，需要双击才显示。

### ISSUE THREAD

**Issue by airbreak** [Dafrok/vue-baidu-map#346]
### 浏览器版本号

chrome  65.0.3325.181

### Vue 版本号

2.5.2

### 组件库版本号

0.21.7

### 现象描述

```
marker单击不能显示BmInfoWindow，需要双击才显示。
```

### 完整异常信息

```
给marker添加点击事件，在事件中实现BmInfoWindow 展示。现发现以下问题：如果在事件中动态改变 BmInfoWindow 的 position ，则单击不能实现，必须双击。如果不动态改变position，则单击也可以展示BmInfoWindow 
```

### 在线示例 / 仓库 URL

git@github.com:airbreak/my-vue-bmap.git

### 复现用例

```
暂无
```

### 预期输出

```
点击可展示BmInfoWindow
```

### 实际输出

```
必须双击才能展示BmInfoWindow
```

**Comment by Dafrok** [comment]
为什么要改 position？

**Comment by airbreak** [comment]
我的每个marker点有对应的详细信息。这些信息放在信息窗口里面，所以位置要改，和marker对应起来。

**Comment by Dafrok** [comment]
不应该这么做，这个问题在 infowindow 组件的文档里有正确的示例

**Comment by airbreak** [comment]
按照你的建议，我修改了实现方案：在 bm-marker 标签里包裹了 bm-info-window，这样基本实现了我的需求。
但是遇到一个小问题：移动地图时，信息框会消失。我已经把 closeOnClick 属性设置为 false, 点击地图不会消失，移动会消失。
如需重现案例，可参照我的代码 git@github.com:airbreak/my-vue-bmap.git

**Comment by gypjoy** [comment]
请问下：移动地图时，信息框会消失。我已经把 closeOnClick 属性设置为 false, 点击地图不会消失，移动会消失。
这个问题您是怎么解决的？

**Comment by airbreak** [comment]
非常抱歉，我最后也没解决，就这样用着。
如果你解决了，请告知

**Comment by gypjoy** [comment]
多个marker共用一个infoWindow,点击不同marker动态改变infoWindow的position，用clickclose，不要用close。           <bm-info-window :position="infoWindowPosition" title="Info Window Title" :show="infoWindow.show" @clickclose="infoWindowClose" :closeOnClick="false">
