### ISSUE TITLE
城市控件选择城市后，报错

### ISSUE THREAD

**Issue by mcDullLi** [Dafrok/vue-baidu-map#348]
`<bm-city-list anchor="BMAP_ANCHOR_TOP_LEFT" :offset="{width: 10, height: 10}"></bm-city-list>`
该控件选择其他城市后，
![image](https://user-images.githubusercontent.com/29831936/39283312-41479eba-4940-11e8-8051-259866846245.png)
如何解决？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
