### ISSUE TITLE
打包部署上线，报错！！

### ISSUE THREAD

**Issue by XPLing** [Dafrok/vue-baidu-map#349]
在打包时出现以下错误：
![image](https://user-images.githubusercontent.com/15956969/39294841-5b08e5be-496f-11e8-83ce-ae79114ea04a.png)
这是我webpack哪里配置出错了吗？希望大家能帮忙看看，谢谢~~

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
