### ISSUE TITLE
打包出错

### ISSUE THREAD

**Issue by XPLing** [Dafrok/vue-baidu-map#350]
### 浏览器版本号

Google Chrome 64.0.3282.186

### Vue 版本号

2.5.2

### 组件库版本号

0.21.7

### 现象描述

```
在打包压缩的时候出现错误，在使用npm run  dist 时出现错误
```

### 完整异常信息

```
ERROR in static/js/0.21f95664f692630389ff.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./~/_vue-baidu-map@0.21.7@vue-baidu-map/components/base/factory.js:1,0][static/js/0.21f95664f692630389ff.js:75,36]
```

### 在线示例 / 仓库 URL

https://github.com/XPLing/baidu-map-issue-demo.git

### 复现用例

```
npm i
npm run dist
```

### 预期输出

```
可以正常打包，不会报错
```

### 实际输出

```
ERROR in static/js/0.21f95664f692630389ff.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./~/_vue-baidu-map@0.21.7@vue-baidu-map/components/base/factory.js:1,0][static/js/0.21f95664f692630389ff.js:75,36]
```

**Comment by XPLing** [comment]
@Dafrok 请大神帮忙看看，是我哪里出问题了，项目等着救急，拜托拜托

**Comment by Dafrok** [comment]
package 里的文件是 es6 module，你没编译成 es5，uglify 不了

**Comment by 3vand0ng** [comment]
同问打包出错，引用 'vue-baidu-map/components/overlays/Marker'，里面引用的 'vue-baidu-map/components/base/mixins/common.js' 未编译成 es5，无法uglify，求教如何编译？
