### ISSUE TITLE
请问怎么可以在created钩子函数里直接调用定位

### ISSUE THREAD

**Issue by toFrankie** [Dafrok/vue-baidu-map#351]
使用了BmGeolocation控件，现在只能要手动触发按钮才能实现定位，但根据项目的需要，想要进入当前路由就触发定位事件。但似乎文档里没有介绍，请问大佬，怎么才能在created钩子函数里进行定位？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
