### ISSUE TITLE
请问怎么可以在created钩子函数里直接调用定位

### ISSUE THREAD

**Issue by toFrankie** [Dafrok/vue-baidu-map#352]
### 相关文档 URL

https://dafrok.github.io/vue-baidu-map/#/zh/control/geolocation

### 问题描述

```
使用了BmGeolocation控件，现在只能要手动触发按钮才能实现定位，但根据项目的需要，想要进入当前路由就触发定位事件。但似乎文档里没有介绍，是无法自动触发定位操作吗？
```

### 改进建议

```
请问大佬，怎么才能在created钩子函数里进行定位？
```

**Comment by toFrankie** [comment]
谢谢大佬，先前看过，然后又忘了，想到解决方法了！

**Comment by lrjxhchina** [comment]
@toFrankie 什么办法

**Comment by toFrankie** [comment]
@lrjxhchina 看我写的这篇文章：https://www.jianshu.com/p/39e755e7cbac
