### ISSUE TITLE
使用Vue Baidu Map后Vue Devtools很快就会崩溃

### ISSUE THREAD

**Issue by 963838470** [Dafrok/vue-baidu-map#353]
### 浏览器版本号

Chrome  64.0.3282.186（正式版本） （32 位）

### Vue 版本号

2.5.2

### 组件库版本号

0.21.3

### 现象描述

```
打开运行一段时间后 Vue Devtools 极易崩溃，去除Vue Baidu Map则插件正常，不会崩溃
```

### 完整异常信息

```
Vue.js devtools 4.1.4  ID： nhdogjmejiglipccpnnnanhbledajbpd
```

### 在线示例 / 仓库 URL

暂无

### 复现用例

```
暂无
```

### 预期输出

```
暂无
```

### 实际输出

```
暂无
```

**Comment by Dafrok** [comment]
开官网的文档，devtool 会崩溃吗？

**Comment by 963838470** [comment]
npm run dev 官网的demo，调试模式开启一段时间后也会崩溃
![image](https://user-images.githubusercontent.com/20849815/39355478-edc49256-4a3f-11e8-83b6-4d0510ad2977.png)

**Comment by Dafrok** [comment]
把做了什么操作，用了多长时间详细说一下

**Comment by 963838470** [comment]
打开了几个页面，然后在页面上画了一些线，然后等待3-5分钟，插件崩溃，并且期间浏览器有明显卡顿

**Comment by Dafrok** [comment]
这3、5分钟没有做任何操作对吧

**Comment by 963838470** [comment]
是，等待的几分钟没做操作

**Comment by Dafrok** [comment]
我复现一下看看

**Comment by Dafrok** [comment]
发现卡顿的问题了。原因是鼠标在地图上晃动的时候会 emit 大量事件，这些 event 对象会被 devtool 捕获并缓存下来无法释放掉，如果没有开 devtool 这些事件在执行完时会被立刻释放掉。

**Comment by 963838470** [comment]
好的，那这样应该不会影响生产环境

**Comment by Dafrok** [comment]
发了一个新版本 0.21.8，做了一波优化，绕开了 vue 的事件机制。现在应该没事了
