### ISSUE TITLE
地区检索后中心点获取问题

### ISSUE THREAD

**Issue by xiaomingdexian** [Dafrok/vue-baidu-map#354]
### 浏览器版本号

all browsers

### Vue 版本号

2.5.2

### 组件库版本号

0.21.3

### 现象描述

```
在onsearchcomplete回调中调用map.getCenter方法，获取的中心点是search之前的中心点，目前采取的是setTimeout来获取，请问有什么更好的解决方案吗
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
这个问题和 #321 是一个原因导致的，目前还没有想到较好的解决方法，集中到那边去讨论，这边先关了
