### ISSUE TITLE
bm-auto-complete在baidu-map外面使用

### ISSUE THREAD

**Issue by guohuihot** [Dafrok/vue-baidu-map#355]
### 在线示例 URL

https://dafrok.github.io/vue-baidu-map/#/issues

### 功能描述

```
rt 在外面使用
```

### 用法示例

```
rt
```

**Comment by Dafrok** [comment]
http://lbsyun.baidu.com/index.php?title=webapi

**Comment by guohuihot** [comment]
ok,那只能用这种了

**Comment by Dafrok** [comment]
这个组件在 1.0.0 后可能删除，因为它其实也是 webapi 封装的，不够灵活
