### ISSUE TITLE
关于文档中的属性set值

### ISSUE THREAD

**Issue by GrreyWang** [Dafrok/vue-baidu-map#357]
### 相关文档 URL

https://dafrok.github.io/vue-baidu-map/#/zh/control/navigation

### 问题描述

```
type属性的值应该怎样设置？？ 加上“:”报错，不加也报错。
```

### 改进建议

```
能否给出确定的使用方式？
```

**Comment by Dafrok** [comment]
你最好看一下究竟报了什么错

**Comment by GrreyWang** [comment]
类似的， anchor属性的值就是直接常量：

BMAP_ANCHOR_TOP_LEFT | 控件将定位到地图的左上角
BMAP_ANCHOR_TOP_RIGHT | 控件将定位到地图的右上角
BMAP_ANCHOR_BOTTOM_LEFT | 控件将定位到地图的左下角
BMAP_ANCHOR_BOTTOM_RIGHT | 控件将定位到地图的右下角

用这几个直接赋值就好了

**Comment by Dafrok** [comment]
复现了一下发现是个 bug。预计今天修复发版

**Comment by GrreyWang** [comment]
追加一个问题， 怎么给地图的组件做初始化配置？
我现在想要的是，当标记点的数据返回时，在地图上点击标记点的时候执行自定义的event handler。
看了几个demo都不是vue2.0的方式

**Comment by GrreyWang** [comment]
有微信么？？？加个微信交流方便我的，born_hong

**Comment by Dafrok** [comment]
@click 即可

**Comment by GrreyWang** [comment]
@click??

应该是我没说清，是通过local-search 查找回来的数据，然后动态生成的marker。怎么来自定义event handler?

**Comment by Dafrok** [comment]
百度地图 JS API 的 LocalSearch 类是会自动生成 marker 的，这个没办法控制。如果你想自己控制视图，可以调用百度地图的 WEB API，请求数据回来然后通过 v-for 渲染一组你自定义的 marker 上去来搞。

**Comment by Dafrok** [comment]
你也可以在 markerset 事件后面执行 JS API 的 removeMarker 把 LocalSearch 给你渲染的 marker 都移除掉，然后用这些 marker 的经纬度维护一组自己的 marker。当然我是不推荐这个方法的，因为性能上肯定比直接使用 WEB API 差很多，多了很多没用的渲染步骤。

**Comment by GrreyWang** [comment]
通过infohtmlset应该可以吧，我看文档上写的是返回的是marker的DOM。可以这个事件没触发啊

**Comment by Dafrok** [comment]
0.21.10 已发版，如果有其他不相关问题可以开新的 issue 讨论。
