### ISSUE TITLE
绘画矩形及重载地图的reload方法使用

### ISSUE THREAD

**Issue by ccyytt** [Dafrok/vue-baidu-map#365]
### 相关文档 URL

https://dafrok.github.io/vue-baidu-map/#/zh/start/base

### 问题描述

```
请问在vue使用中绘画矩形是调用哪个组件或者方法？
关于手动重载地图的reload 的方法如何调用未找到例子 请给个demo谢谢了
```

### 改进建议

```
希望能有个demo
```

**Comment by Dafrok** [comment]
1. 矩形属于多边形。
2. `全局组件实例方法` 的意思就是每个组件的实例上都有这个方法。

**Comment by ccyytt** [comment]
很抱歉我是个web端新手，所以想看到一个列子知道如何编写要手动触发的时候 这个reload 应该如何写 
麻烦您给个代码片段我参考一下。

**Comment by Dafrok** [comment]
善用搜索 https://github.com/Dafrok/vue-baidu-map/search?utf8=%E2%9C%93&q=reload%28%29&type=

**Comment by harwinvoid** [comment]
调用 this.$refs.map.reload() 报 reload is not a function
