### ISSUE TITLE
地图左下方为什么有其他的网站

### ISSUE THREAD

**Issue by boneq** [Dafrok/vue-baidu-map#37]
© 2017 Baidu - GS(2016)1069号 - Data © 长地万方 & OpenStreetMap & HERE

 & OpenStreetMap & HERE

**Comment by Dafrok** [comment]
http://lbsyun.baidu.com/jsdemo.htm#a1_2

**Comment by boneq** [comment]
我说的只是有这个& OpenStreetMap & HERE，百度API他有前面的但是没有& OpenStreetMap & HERE这个东西，这个是个其他网站的连接

**Comment by Dafrok** [comment]
那个是地图数据源的版权声明，百度世界地图的一部分数据是由 OpenStreetMap 和 Here 提供的，你把地图缩放到国内就只有长地天方了。

**Comment by boneq** [comment]
感谢感谢，我懂了，真的浪费你很多时间啊，我把百度地图放成世界地图的时候也有那个标签，不好意思啊
