### ISSUE TITLE
MarkerClusterer如何获取聚合下Marker的数据？

### ISSUE THREAD

**Issue by htengweb** [Dafrok/vue-baidu-map#375]
### 相关文档 URL

https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/marker-clusterer

### 问题描述

```
不能获取聚合下的marker的所有数据？
```

### 改进建议

```
MarkerClusterer添加事件，获取每次缩放时聚合下的marker所有数据，或可以直接扩展方法吗？
```

**Comment by Dafrok** [comment]
为什么要获取数据，数据不是你自己通过 prop 传进去的么

**Comment by htengweb** [comment]
每次缩放都会聚合一次，现在只是显示所聚合的个数，那如果我想知道具体聚合的哪几个数据，想获取它们的信息，怎么办？。。。

**Comment by Dafrok** [comment]
可以访问实例去执行这个方法

**Comment by htengweb** [comment]
覆盖物中的信息窗口要是能完全用HTML自定义就好了，现在的样式很难改呀，对了，请问一下是如何去访问实例的呀。。。

**Comment by Dafrok** [comment]
MVVM 有 MVVM 的玩儿法，你有些过分关注视图层了。正确的做法应该是用百度地图 web API 进行查询，拿到数据后丢进 VM。

**Comment by DxQ-dingxuan** [comment]
请问解决了吗？
点击聚合的点  获取里面的数据

**Comment by DxQ-dingxuan** [comment]
> 
![image](https://user-images.githubusercontent.com/32954734/157611533-6e01a374-85e9-47b8-af39-90f960c0b3ca.png)

请问  什么时候去获取实例呢？
聚合的点没有事件
