### ISSUE TITLE
我想要改变改变检索的折现颜色，但是没办法做到

### ISSUE THREAD

**Issue by sparGuan** [Dafrok/vue-baidu-map#377]
![image](https://user-images.githubusercontent.com/28480563/40152862-aa348d0a-59b9-11e8-890d-6918f33e5122.png)

能不能提供一个参数让我可以改变折现颜色，绿色太浅了，不适合作为关注色

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
