### ISSUE TITLE
internet explorer 11 语法错误

### ISSUE THREAD

**Issue by hst0305** [Dafrok/vue-baidu-map#379]
浏览器版本号
internet explorer 11 版本: 11.431.16299.0

Vue 版本号
2.9.3

组件库版本号
"vue-baidu-map": "^0.21.10",

现象描述
局部注册组件
npm run dev
访问app出现：“语法错误”   指向 app.js 位置如下：
eval("/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__events_js__ = __webpack_require__(\"./node_modules/vue-baidu-map/components/base/events.js\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__util_js__ = __webpack_require__(\"./node_modules/vue-baidu-map/components/base/util.js\");\n\n\n\n/* harmony default export */ __webpack_exports__[\"a\"] = (function (instance, eventList) {\n  const ev = eventList || __WEBPACK_IMPORTED_MODULE_0__events_js__[\"a\" /* default */][Object(__WEBPACK_IMPORTED_MODULE_1__util_js__[\"b\" /* toKebabCase */])(this.$options._componentTag)]\n  ev && ev.forEach(event => {\n    const hasOn = event.slice(0, 2) === 'on'\n    const eventName = hasOn ? event.slice(2) : event\n    const listener = this.$listeners[eventName]\n    listener && instance.addEventListener(event, listener.fns)\n  })\n});\n//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9ub2RlX21vZHVsZXMvdnVlLWJhaWR1LW1hcC9jb21wb25lbnRzL2Jhc2UvYmluZEV2ZW50LmpzLmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL3Z1ZS1iYWlkdS1tYXAvY29tcG9uZW50cy9iYXNlL2JpbmRFdmVudC5qcz8xZTkzIl0sInNvdXJjZXNDb250ZW50IjpbImltcG9ydCBldmVudHMgZnJvbSAnLi9ldmVudHMuanMnXG5pbXBvcnQge3RvS2ViYWJDYXNlfSBmcm9tICcuL3V0aWwuanMnXG5cbmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIChpbnN0YW5jZSwgZXZlbnRMaXN0KSB7XG4gIGNvbnN0IGV2ID0gZXZlbnRMaXN0IHx8IGV2ZW50c1t0b0tlYmFiQ2FzZSh0aGlzLiRvcHRpb25zLl9jb21wb25lbnRUYWcpXVxuICBldiAmJiBldi5mb3JFYWNoKGV2ZW50ID0+IHtcbiAgICBjb25zdCBoYXNPbiA9IGV2ZW50LnNsaWNlKDAsIDIpID09PSAnb24nXG4gICAgY29uc3QgZXZlbnROYW1lID0gaGFzT24gPyBldmVudC5zbGljZSgyKSA6IGV2ZW50XG4gICAgY29uc3QgbGlzdGVuZXIgPSB0aGlzLiRsaXN0ZW5lcnNbZXZlbnROYW1lXVxuICAgIGxpc3RlbmVyICYmIGluc3RhbmNlLmFkZEV2ZW50TGlzdGVuZXIoZXZlbnQsIGxpc3RlbmVyLmZucylcbiAgfSlcbn1cblxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vbm9kZV9tb2R1bGVzL3Z1ZS1iYWlkdS1tYXAvY29tcG9uZW50cy9iYXNlL2JpbmRFdmVudC5qc1xuLy8gbW9kdWxlIGlkID0gLi9ub2RlX21vZHVsZXMvdnVlLWJhaWR1LW1hcC9jb21wb25lbnRzL2Jhc2UvYmluZEV2ZW50LmpzXG4vLyBtb2R1bGUgY2h1bmtzID0gMCJdLCJtYXBwaW5ncyI6IkFBQUE7QUFBQTtBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTsiLCJzb3VyY2VSb290IjoiIn0=\n//# sourceURL=webpack-internal:///./node_modules/vue-baidu-map/components/base/bindEvent.js\n");

npm run build 发布APP
访问app出现：“语法错误”

export default function (instance, eventList) {
  const ev = eventList || events[toKebabCase(this.$options._componentTag)]
  ev && ev.forEach(event => { //调试程序错误指向这里
    const hasOn = event.slice(0, 2) === 'on'
    const eventName = hasOn ? event.slice(2) : event
    const listener = this.$listeners[eventName]
    listener && instance.addEventListener(event, listener.fns)
  })
}

在线示例 / 仓库 URL
无

复现用例
无
预期输出
无
实际输出
语法错误

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
