### ISSUE TITLE
热力图不能更新？

### ISSUE THREAD

**Issue by leeycode** [Dafrok/vue-baidu-map#381]
我在data中给热力图赋值，热力图可以正常显示，但是随着数据变化，之前的图层没有消失，最新的热力图会覆盖上面。请问有什么办法可以重置热力图？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
