### ISSUE TITLE
vue2引入后使用报错

### ISSUE THREAD

**Issue by zsio** [Dafrok/vue-baidu-map#382]
### 浏览器版本号

Google Chrome 66.0.3359.181

### Vue 版本号

2.5.2

### 组件库版本号

0.21.10

### 现象描述

```
引入使用的时候报错，`Uncaught RangeError: Maximum call stack size exceeded`
```

### 完整异常信息

```
Uncaught RangeError: Maximum call stack size exceeded
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
能正常使用
```

### 实际输出

```
报错
```

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
