### ISSUE TITLE
当map父元素高度小于内容高度，地图zoom会出现偏移

### ISSUE THREAD

**Issue by xinheHuang** [Dafrok/vue-baidu-map#386]
### 浏览器版本号

Chrome浏览器

### Vue 版本号

2.5.16

### 组件库版本号

0.21.10

### 现象描述

```
当map父元素高度小于内容高度，地图zoom会出现偏移
```

### 完整异常信息

```
当map父容器高度固定，overflow为scroll，地图的缩放会出现问题
```

### 在线示例 / 仓库 URL

https://jsfiddle.net/2rvb7ygu/1/

### 复现用例

```
https://jsfiddle.net/2rvb7ygu/1/
```

### 预期输出

```
缩放正常
```

### 实际输出

```
缩放偏移
```

**Comment by Dafrok** [comment]
貌似是 JS API 的问题，和组件没啥关系

**Comment by xinheHuang** [comment]
所以这是百度地图本身的bug吗

**Comment by Dafrok** [comment]
直接调用百度地图，如果这个场景有问题那就是本身的问题
