### ISSUE TITLE
调用 Geocoder.getPoint()方法总是  is not function

### ISSUE THREAD

**Issue by Monk-Wangrl** [Dafrok/vue-baidu-map#387]
> 我从 ready回调中拿到BMap对象，然后从BMap中获取了Geocoder属性值，但是嗲用 getPoint方法为什么说没有这个方法

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
