### ISSUE TITLE
getPoint 方法总是 is not function错误

### ISSUE THREAD

**Issue by Monk-Wangrl** [Dafrok/vue-baidu-map#388]
### 浏览器版本号

chrome 

### Vue 版本号

2.5.2

### 组件库版本号

vue-baidu-map 0.21.10

### 现象描述

```
能拿到 BMap.Geocoder属性，但是获取不到但是Geocoder.getPoint方法时总是报is not a function,我看官方baidu地图 api都是可以直接调用的
```

### 完整异常信息

```
getPoint is not a function
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
获取坐标
```

### 实际输出

```
is not a funcition
```

**Comment by Dafrok** [comment]
请提供在线复现场景

**Comment by Monk-Wangrl** [comment]
### ready事件所执行的方法
![image](https://user-images.githubusercontent.com/31736592/40916338-ef5f45ec-6831-11e8-86e3-6dc465ea5d06.png)

### 调用的结果
![image](https://user-images.githubusercontent.com/31736592/40916320-dec98472-6831-11e8-8791-ebe928346923.png)

**Comment by Monk-Wangrl** [comment]
### ready事件执行的方法
![image](https://user-images.githubusercontent.com/31736592/40916455-5c46416a-6832-11e8-8b5d-716b9a2071a9.png)

### 调用结果
![image](https://user-images.githubusercontent.com/31736592/40916477-70571274-6832-11e8-8b5c-7a5c43d4ec53.png)

**Comment by Dafrok** [comment]
你需要再认真阅读一下百度地图 JS API 的文档和示例
