### ISSUE TITLE
请问通过已有的坐标来获取当前坐标所在的地区（精确到乡镇），有方法实现吗？

### ISSUE THREAD

**Issue by jeromelive** [Dafrok/vue-baidu-map#39]
如题！！麻烦开发了！

**Comment by jeromelive** [comment]
目前只能获取到市

**Comment by Dafrok** [comment]
vue 组件库仅处理视图逻辑，纯业务逻辑请移步 [百度地图 JS API 官方文档](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html) 查看详细。
