### ISSUE TITLE
移动端调试iOS端页面全部不显示

### ISSUE THREAD

**Issue by cn-zx** [Dafrok/vue-baidu-map#391]
# [BUG 反馈] 移动端出现不兼容的问题
## 浏览器版本号
Chrome浏览器Mac版， 67.0.3396.62版本

## Vue 版本号
2.5.2

## 组件库版本号
0.21.10

## 现象描述
mac chrome上显示正常，无报错
手机模式下调试，华为荣耀 android v5.1.1 上显示正常，iOS 11系统以上显示正常，iOS 9.3.5上全部页面不显示

## 完整异常信息
报错信息
![wx20180607-115807](https://user-images.githubusercontent.com/29486720/41078397-2fb0bb52-6a4f-11e8-8c3c-17e1860e5074.png)

定位代码
![wx20180607-115852](https://user-images.githubusercontent.com/29486720/41078424-53632670-6a4f-11e8-95be-16467aa01f7f.png)

## 复现用例
无

## 预期输出
**_我是用单组件引入的，我该如何临时修复？_**
![wx20180607-123801](https://user-images.githubusercontent.com/29486720/41078492-bbb4dd40-6a4f-11e8-9868-6c1361193f2c.png)

## 实际输出
报错：SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
