### ISSUE TITLE
[BUG反馈]移动端出现不兼容的问题

### ISSUE THREAD

**Issue by cn-zx** [Dafrok/vue-baidu-map#392]
### 浏览器版本号

Chrome浏览器Mac版，67.0.3396.62版本

### Vue 版本号

2.5.2

### 组件库版本号

0.21.10

### 现象描述

```
mac chrome上显示正常，无报错
手机模式下调试，华为荣耀android v5.1.1上显示正常，iOS 11系统以上显示正常，iOS 9.3.5上全部页面不显示。
webpack-dev-server版本号2.9.1
```

### 完整异常信息

```
https://user-images.githubusercontent.com/29486720/41078397-2fb0bb52-6a4f-11e8-8c3c-17e1860e5074.png
```

### 在线示例 / 仓库 URL

https://user-images.githubusercontent.com/29486720/41078424-53632670-6a4f-11e8-95be-16467aa01f7f.png

### 复现用例

```
无
```

### 预期输出

```
我是单组件引入的，我该如何临时修复这个问题？
https://user-images.githubusercontent.com/29486720/41078492-bbb4dd40-6a4f-11e8-9868-6c1361193f2c.png
```

### 实际输出

```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
```

**Comment by Dafrok** [comment]
请自行 google `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`
