### ISSUE TITLE
请问如何实现汽车实时轨迹的功能，不是路书还原那样？

### ISSUE THREAD

**Issue by milktea555** [Dafrok/vue-baidu-map#393]
我看了路书，数据好像不能动态加载。数据一更新什么都没有了

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by myf-sky** [comment]
请问您的问题解决了吗？
