### ISSUE TITLE
可以实现百度地图离线开发么

### ISSUE THREAD

**Issue by wuweihust** [Dafrok/vue-baidu-map#394]
# [BUG 反馈] map.vue第85行map.centerAndZoom报错
## 浏览器版本号

> chrome 66.0.3359.181

## Vue 版本号

> 使用的vue-cli

## 组件库版本号

> 0.21.10

## 现象描述
可以实现百度地图离线开发么
## 在线示例 / 仓库 URL
没有

##复现用例

##预期输出

##实际输出

##标签部分

> 

##引用部分

>

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
