### ISSUE TITLE
自定义覆盖物如何添加？

### ISSUE THREAD

**Issue by zhaozhe0831** [Dafrok/vue-baidu-map#40]
需要添加自定义覆盖物的话，现在支持吗？

**Comment by Dafrok** [comment]
自定义覆盖物在官方文档中是使用两个抽象方法来做的。由于这两个抽象方法的定制性和自由度过高，目前没有很好的组件化方式，建议使用官方文档中的方法，或者如果您有什么 idea 也可以提出进行讨论。

**Comment by Dafrok** [comment]
如果暂时没有异议，就关闭 ISSUE 了，欢迎继续讨论。

**Comment by Dafrok** [comment]
自定义覆盖物已实现，[文档](https://dafrok.github.io/vue-baidu-map/#/zh/overlay/overlay) 更新完毕。请升级到 0.12 版本进行使用。

**Comment by zhaozhe0831** [comment]
Thank you！
