### ISSUE TITLE
海量自定义marker，10000左右加载特别慢。页面卡死

### ISSUE THREAD

**Issue by wudiansi** [Dafrok/vue-baidu-map#401]
### 浏览器版本号

版本 66.0.3359.139（正式版本） （64 位）

### Vue 版本号

2.2.0

### 组件库版本号

2.0.23

### 现象描述

```
海量自定义点 直接卡死 加载约一分钟能加载出1万多点
```

### 完整异常信息

```
无报错 卡
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
自定义图标marker 聚合方式快速渲染
```

### 实际输出

```
加载很慢，并且卡死
```

**Comment by Dafrok** [comment]
所以百度地图官方才会推荐开发者使用 PointCollection 类

**Comment by wudiansi** [comment]
然而PointCollection不支持自定义图标 需求大大不满足 这里的聚合有没有邪门歪道的优化方式呢

**Comment by Dafrok** [comment]
用 mapv，canvas 渲染。marker 是 IE 时代的产物，还保留着兼容性，性能确实不是很好。

**Comment by 1008611** [comment]
@wudiansi 可以只加载再可视范围内marker
