### ISSUE TITLE
api文档有一处需要修改

### ISSUE THREAD

**Issue by sungycc** [Dafrok/vue-baidu-map#402]
import BaiduMap from 'vue-baidu-map/components/Map/Map.vue'
这个是文档中局部引入的写法，但是实际上npm安装的依赖，components下面没有Map这个文件夹，但是有map文件夹，在windos下没有影响，依然可以构建成功，但在linux下构建是不会成功的，好像是linux区分文件路径大小写，所以构建时总是找不到这个组件，改成下面这样就好了
import BaiduMap from 'vue-baidu-map/components/map/Map.vue'

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
