### ISSUE TITLE
api文档-开始-快速上手有一处不兼容linux

### ISSUE THREAD

**Issue by sungycc** [Dafrok/vue-baidu-map#403]
### 浏览器版本号

66.0.3359.139

### Vue 版本号

2.5.16

### 组件库版本号

0.21.10

### 现象描述

```
局部引入在linux下构建总是找不到map.vue组件
```

### 完整异常信息

```
构建总是报找不到局部引入的组件
```

### 在线示例 / 仓库 URL

这个必须在linux下运行

### 复现用例

```
只要在linux下局部引入然后构建就会有这个问题
```

### 预期输出

```
构建成功
```

### 实际输出

```
import BaiduMap from 'vue-baidu-map/components/map/Map.vue'（实际安装的依赖包，cpmponents下面有map文件夹但没有Map文件夹）
```

**Comment by Dafrok** [comment]
从你的描述看起来和 linux 没什么关系

**Comment by sungycc** [comment]
可能是的我表达能力太差了，我是局部引入的，在自己(win10)和同事(win7)的电脑上都可以构建成功，运维那边做自动化部署时总是失败，后来在运维的xshell5跑了一下npm run build总是失败，提示找不到import BaiduMap from 'vue-baidu-map/components/Map/Map.vue'这个组件，然后我去对应node_modules里看了一下vue-baidu-map的目录结构，发现components里面只有map文件夹没有Map文件夹，然后把import BaiduMap from 'vue-baidu-map/components/Map/Map.vue'改为import BaiduMap from 'vue-baidu-map/components/map/Map.vue'后就构建成功了，当时我很正经，可能平时玩linux比较少，然后我就在win10里面打开cmd用命令行操作，发现win是不区分路径大小写的，linux下是区分的，这个都不重要，还是烦请修改一下文档的路径或者依赖包文件夹名，这样以后大家就不用踩这个坑了，很感谢这个开源项目，开发方便不少，辛苦了哈！

**Comment by Dafrok** [comment]
哦，linux 是大小写敏感的，但是文档中的示例也是大写文件名，所以按照文档操作是不会有问题的。类和组件以大写开头是一个约定俗成的规则，vue 的 best practice 中也是这么推荐的，所以这里不做修改了。

**Comment by sungycc** [comment]
![qq 20180623220329](https://user-images.githubusercontent.com/38499198/41815191-db563858-7795-11e8-9932-db9f7711e743.png)
![qq 20180624100315](https://user-images.githubusercontent.com/38499198/41815194-e8144cc4-7795-11e8-9367-2aeb82499c0c.png)
文档的局部引入路径或者依赖包文件夹名必须有一个地方是需要修改的，现在好多公司都做持续集成，局部引入的话，linux那就会构建失败呀

**Comment by sungycc** [comment]
看来我真的需要好好提升下我的表达能力了！~~~手动捂脸

**Comment by Dafrok** [comment]
文档中的文件夹名有误，你可以先 fork 发 pr，我回去合一下。现在我在一个没法用 npm 的地方，大概5天后可以发版。

如果持续集成需要，你可以先把你工程中 package.json 中声明依赖的位置做如下改动：
```
"dependencies": {
  "vue-baidu-map": 你 fork 的仓库地址
} 
```
