### ISSUE TITLE
自定义控件设置显示位置无效

### ISSUE THREAD

**Issue by wjm901215** [Dafrok/vue-baidu-map#407]
<bm-control anchor="BMAP_ANCHOR_BOTTOM_RIGHT">
      <button @click="" >缩放至最大</button>
</bm-control>

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
