### ISSUE TITLE
加:scroll-wheel-zoom="true"报错，"TypeError: Cannot read property 'centerAndZoom' of undefined"

### ISSUE THREAD

**Issue by juntaoshuai** [Dafrok/vue-baidu-map#408]
代码：
<template>
  <div style="height: 290px; background: #a7c0e0;">
    <baidu-map v-if="organId" class="bmap" :center="center" :zoom="zoom" :scroll-wheel-zoom="true" @ready="handler" ak="TF8bsPxPOPpGZpyN4aact4fl5WVdHUiG">
      <bm-marker :position="center" :dragging="true">
        
      </bm-marker>
    </baidu-map>
  </div>
</template>

<script>
import BaiduMap from 'vue-baidu-map/components/Map/Map.vue'
import BmMarker from 'vue-baidu-map/components/overlays/Marker.vue'
// import BmLabel from 'vue-baidu-map/components/overlays/Label.vue'
import { queryCommunityById } from '@/api/modules/hqManage'
import {SHOW_TOAST} from 'store/types.js'
export default {
  name: 'HospitalMap',
  components: {
    BaiduMap,
    BmMarker
    // BmLabel
  },
  data () {
    return {
      center: {lng: 0, lat: 0},
      zoom: 3
    }
  },
  computed: {
    organId () {
      return this.$store.state.medical.organId
    }
  },
  watch: {
    organId () {
      this.getMapInfo()
    }
  },
  methods: {
    handler ({BMap, map}) {
      this.zoom = 19
    },
    getMapInfo () {
      queryCommunityById({communityId: this.organId}).then(res => {
        if (res.data.code === '0' && res.data.data.community) {
          this.center.lng = res.data.data.community.longitude
          this.center.lat = res.data.data.community.latitude
        }
      }, res => {
        this.$store.dispatch(SHOW_TOAST, '地图加载失败')
      })
    }
  },
  mounted () {
    if (this.organId) {
      this.getMapInfo()
    }
  }
}
</script>

<style>
.bmap {
  width:290px;
  height: 290px;
}
.anchorBL{display:none;} 
</style>

运行报错：
vue.esm.js?65d7:591 [Vue warn]: Error in callback for watcher "center.lng": "TypeError: Cannot read property 'centerAndZoom' of undefined"

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
