### ISSUE TITLE
[求助] 与MapV集成

### ISSUE THREAD

**Issue by Nioty** [Dafrok/vue-baidu-map#409]
### 浏览器版本号

Google Chrome 67.0.3396.99 / Linux

### Vue 版本号

2.5.16

### 组件库版本号

0.21.10

### 现象描述

```
使用NPM安装的mapv,在ready中取得BMap实例,参考http://mapv.baidu.com/examples/#baidu-map-point-icon.html写了demo, 如下:
```
    mapReady ({ BMap, map }) {
      var randomCount = 100000

      var data = []

      var citys = ['北京', '天津', '上海', '重庆', '石家庄', '太原', '呼和浩特', '哈尔滨', '长春', '沈阳', '济南', '南京', '合肥', '杭州', '南昌', '福州', '郑州', '武汉', '长沙', '广州', '南宁', '西安', '银川', '兰州', '西宁', '乌鲁木齐', '成都', '贵阳', '昆明', '拉萨', '海口']

      var img = new Image()
      img.src = 'img/top.gif'

      while (randomCount--) {
        var cityCenter = mapv.utilCityCenter.getCenterByCityName(citys[parseInt(Math.random() * citys.length)])
        data.push({
          geometry: {
            type: 'Point',
            coordinates: [cityCenter.lng - 2 + Math.random() * 4, cityCenter.lat - 2 + Math.random() * 4]
          },
          deg: 360 * Math.random(),
          icon: img
        })
      }
      var dataSet = new mapv.DataSet(data)

      var options = {
        draw: 'icon',
        methods: {
          click: function (item) {
            console.log(item)
          }
        }
      }
      /* eslint-disable */
      var mapvLayer = new mapv.baiduMapLayer(map, dataSet, options)

    }```
 但是控制台报错: Error in event handler for "ready": "TypeError: this.show is not a function": 如下: 
```
 Error in event handler for "ready": "TypeError: this.show is not a function" ```

当动态修改node_modules/mapv/build/mapv.js 后热重载后可以正常显示...  
```

### 完整异常信息

```
TypeError: this.show is not a function
    at new CanvasLayer (mapv.js?2ba4:2943)
    at new Layer$$1 (mapv.js?2ba4:4670)
    at VueComponent.mapReady (index.vue?0dbc:100)
    at VueComponent.invoker (vue.esm.js?efeb:2027)
    at VueComponent.Vue.$emit (vue.esm.js?efeb:2538)
    at VueComponent.e.(:8080/anonymous function) [as $emit] (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:17624)
    at VueComponent.init (index.js?7401:1)
    at VueComponent.initMap (index.js?7401:1)
```

### 在线示例 / 仓库 URL

相关issus: https://github.com/huiyan-fe/mapv/issues/93

### 复现用例

```
来自 kdush的 https://github.com/kdush/MapvBugDemo
```

### 预期输出

```
-
```

### 实际输出

```
-
```

**Comment by Nioty** [comment]
已经解决, 留下方法给其他人参考
问题出在 在头部使用后import引入的时候,由于vue-baidu-map为异步加载, 会存在找不到BMap...
解决办法就是在ready中使用require引入mapv, 
```
mapReady ({ BMap, map }) {
    var mapv = require('mapv')
   mapv.xxxxxx
}```

Close

**Comment by Dafrok** [comment]
其实也可以直接在 head 里引入百度地图 API，这样可能损失一些首屏速度但可以根治异步的问题。
