### ISSUE TITLE
如何使用测距工具？  DistanceTool   没有找到    还有关键字输入提示，关键字输入提示词条哪里获取

### ISSUE THREAD

**Issue by zooeyking** [Dafrok/vue-baidu-map#410]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by dary16** [comment]
要安装distancetool,然后引入，就可以用了，按照说明文档上来
