### ISSUE TITLE
cordova 打包的APP，iOS端定位失败

### ISSUE THREAD

**Issue by liuxiaofan** [Dafrok/vue-baidu-map#415]
### 浏览器版本号

Safari

### Vue 版本号

2.5.2

### 组件库版本号

0.19.2

### 现象描述

```
定位失败
```

### 完整异常信息

```
error JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
定位信息
```

### 实际输出

```
错误信息
```

**Comment by Dafrok** [comment]
异常信息写的蛮清楚了，你 devtools 看下那个对象出问题就行了

**Comment by liuxiaofan** [comment]
app调试的时候没法看devtool，不打包，用浏览器浏览的时候，有一条错误信息是：整体定位超时

**Comment by Dafrok** [comment]
我是说你发的这个：`JSON.stringify cannot serialize cyclic structures`

搜一下源码就可以看到，整个组件库就只有点聚合在监听 styles 属性的时候用到了这个方法，你只要查一下传入组件的 styles 到底哪里有 `cyclic structures` 就行了。
