### ISSUE TITLE
DOMException: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by xiaomingdexian** [Dafrok/vue-baidu-map#418]
### 浏览器版本号

任意浏览器

### Vue 版本号

2.0以上版本

### 组件库版本号

最新版本

### 现象描述

```
见示例
```

### 完整异常信息

```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.insertBefore (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:5325:14)
    at updateChildren (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:5838:32)
    at patchVnode (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:5923:29)
    at VueComponent.patch [as __patch__] (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:6083:9)
    at VueComponent.Vue._update (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:2670:19)
    at VueComponent.updateComponent (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:2788:10)
    at Watcher.get (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:3140:25)
    at Watcher.run (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:3217:22)
    at flushSchedulerQueue (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:2981:13)
    at Array.<anonymous> (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:1839:12)
```

### 在线示例 / 仓库 URL

http://jsfiddle.net/tb4sap2c/6/

### 复现用例

```
见上
```

### 预期输出

```
.
```

### 实际输出

```
.
```

**Comment by Dafrok** [comment]
刷新 overlay 用 `draw` 事件，文档里有写

**Comment by xiaomingdexian** [comment]
@Dafrok
感谢B大回复
不知是不是我看文档理解错误
我封装了一个`Myoverlay`对`position`进行监听，手动调用`reload`方法，实现数据驱动
这里是只进行一次刷新demo，是可以成功的[demo](http://jsfiddle.net/tb4sap2c/12/)
问题我做了个定时器刷新多次的时候，vue抛出了异常[请看这里](http://jsfiddle.net/tb4sap2c/10/)
不知道是什么导致的，已经弄了好久了= =（衰
还请B大指教一下

**Comment by xiaomingdexian** [comment]
第一次刷新不会报错，第二次必现，不管st多长时间[链接](http://jsfiddle.net/tb4sap2c/13/)

**Comment by Dafrok** [comment]
可能是因为 `reload` 删除了一些节点造成的，我抽时间看下吧，最近太忙了

**Comment by xiaomingdexian** [comment]
B大辛苦了0.0

**Comment by xiaomingdexian** [comment]
有个[新发现](http://jsfiddle.net/tb4sap2c/36/)
如果两个数组元素数量一样是不会报错的

**Comment by Dafrok** [comment]
收到

**Comment by xiaomingdexian** [comment]
使用[render](http://jsfiddle.net/tb4sap2c/37/)解决了此问题，不明所以
如果是vue本身机制的问题，还望B大去vue提个issues

**Comment by Dafrok** [comment]
template 最后都会被编译成 render 的，可以对比下不一样的地方，话说你的 bad case 被删了，我没法追了。。。

**Comment by xiaomingdexian** [comment]
[bad case](http://jsfiddle.net/tb4sap2c/21/)在这

**Comment by Dafrok** [comment]
👌

**Comment by xiaomingdexian** [comment]
经测试
用[render](http://jsfiddle.net/tb4sap2c/37/)在chrome上表现正常
IE会出现有些overlay未被删除的情况(markerPane里有重复的marker)
怀疑是removeOverlay的参数导致的
目前采用渲染完成后手动清除多余结点的方式解决

**Comment by Dafrok** [comment]
其实有个比较晦涩的解决方案，就是在 `refreshOverlay` 的时候延迟一下：

```
refreshOverlay(){
  const arr = this.overlayList1
  this.overlayList1 = this.overlayList2
  this.$nextTick(() => {this.overlayList2 = arr})
}
```

**Comment by Dafrok** [comment]
嗯以前出过类似的问题，因为你的 overlay 节点被 vue 创建之后又 append 到百度地图的 pane 里去了，vue 更新数据的时候做 diff，发现节点多出来就会在父节点上执行 `insertBefore`，这一执行发现  `this.$el` 不是他孩子了，于是就抛错了

**Comment by Dafrok** [comment]
两个 `v-for` 在同一个父节点下声明就会触发这个 diff 的机制

**Comment by Dafrok** [comment]
nextTick 可以避免两个 list 同时更新触发这个 diff 机制

**Comment by xiaomingdexian** [comment]
哇  那我直接在v-for外面套层`div`就解决啦

**Comment by xiaomingdexian** [comment]
OK，谢谢B大，强！

**Comment by Dafrok** [comment]
理论上是的
