### ISSUE TITLE
局部注册出错

### ISSUE THREAD

**Issue by jinjinwa** [Dafrok/vue-baidu-map#42]
![19bb6e86-c619-4395-8308-c0f5884104ea](https://cloud.githubusercontent.com/assets/12455937/25790338/6167a4ea-33ea-11e7-8f95-1b9aa26aaa8b.png)
![7f23cbeb-1e11-48f8-af2b-20c3a10b06f0](https://cloud.githubusercontent.com/assets/12455937/25790379/a8efe8f4-33ea-11e7-9a00-e95ef188f1fe.png)
![Uploading 55574E09-F2AD-427A-BDEC-458DB2F18DF3.png…]()

按照官方文档步骤，局部注册报错。
以上是代码截图。请问哪里出错了么？

**Comment by Dafrok** [comment]
您好 图挂了一张

**Comment by jinjinwa** [comment]
我另外写了一个.vue文件，按照官网例子，注册了一个BaiduMap组件，还是报错。

**Comment by jinjinwa** [comment]
![image](https://cloud.githubusercontent.com/assets/12455937/25792359/bca84202-33f8-11e7-861b-3e442e9f9f26.png)
![image](https://cloud.githubusercontent.com/assets/12455937/25792385/da66aafe-33f8-11e7-88ac-e578873d21e1.png)
代码如上，您可以指导下哪里写的有问题么？

**Comment by Dafrok** [comment]
![image](https://cloud.githubusercontent.com/assets/6159588/25792408/03a29af4-33f9-11e7-8f24-7670ef78c4d4.png)

**Comment by Dafrok** [comment]
你的版本是？

**Comment by jinjinwa** [comment]
"vue-baidu-map": "^0.1.11"
"vue": "^2.2.2"

**Comment by Dafrok** [comment]
0.1 是较早的版本了，不支持局部注册。更新一下即可。

**Comment by jinjinwa** [comment]
嗯，果然是版本的问题。现在解决了。我npm下载的时候没有指定版本号，所以默认下载的都是老的版本。感谢您的耐心回复。

**Comment by Dafrok** [comment]
解决问题就好，最近版本更比较频繁，还请留心关注 😄
