### ISSUE TITLE
控制台有保错，但不影响使用

### ISSUE THREAD

**Issue by qm8956** [Dafrok/vue-baidu-map#420]
![default](https://user-images.githubusercontent.com/18099332/42792317-40365352-89a7-11e8-91da-19c17f9901fb.PNG)
点击一个点，打开信息窗体报错，暂时没有发现对使用有什么影响，问一下这个报错时我使用不当造成的吗?

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
