### ISSUE TITLE
关于生产环境访问的问题

### ISSUE THREAD

**Issue by nanyoullm** [Dafrok/vue-baidu-map#423]
请问一下，在断外网的生产环境中，如何配置url访问权限来使得vue-baidu-map的正常使用？配置vue-baidu-map里涉及的 https/http 开头的 url 可以吗？谢谢

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
