### ISSUE TITLE
关于断网生产环境访问的问题

### ISSUE THREAD

**Issue by nanyoullm** [Dafrok/vue-baidu-map#424]
### 在线示例 URL

none

### 功能描述

```
请问一下，在断外网的生产环境中，如何配置url访问权限来使得vue-baidu-map的正常使用？如果配置vue-baidu-map里涉及的 https/http 开头的 url 可访问互联网，是否可行呢？谢谢
```

### 用法示例

```
none
```

**Comment by Dafrok** [comment]
此类问题和组件无关，请移步官方社区

**Comment by nanyoullm** [comment]
官方社区地址是？

**Comment by Dafrok** [comment]
https://www.baidu.com/s?wd=%E7%99%BE%E5%BA%A6%E5%9C%B0%E5%9B%BE%20AO&rsv_spt=1&rsv_iqid=0xb40827bc0000cac0&issp=1&f=8&rsv_bp=0&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_sug3=29&rsv_sug1=11&rsv_sug7=101&rsv_t=cf4cfBD%2BNGFqPIfPedLfwj9HRaCEA9hCkYfvs1F6pe0tencmr1n54OmXCw7SWr1YMwuX&rsv_sug2=0&inputT=6658&rsv_sug4=6659

**Comment by Dafrok** [comment]
http://bbs.lbsyun.baidu.com/forum.php
