### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by zooeyking** [Dafrok/vue-baidu-map#425]
bue-baidu-map   编译报错，貌似是没有经过 babel  编译；

ERROR in static/js/3.a6aa66ec2dd03b54dcb2.js from UglifyJs
Unexpected token: operator (>) [./~/vue-baidu-map/components/base/mixins/common.js:16,0][static/js/3.a6aa66ec2dd03b54dcb2.js:265,30]

ERROR in static/js/4.10ff4b4cacceb4be070c.js from UglifyJs
Unexpected token: operator (>) [./~/vue-baidu-map/components/base/mixins/common.js:16,0][static/js/4.10ff4b4cacceb4be070c.js:208,30]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
