### ISSUE TITLE
程序打包的时候报错

### ISSUE THREAD

**Issue by hw37du** [Dafrok/vue-baidu-map#427]
打包的时候出现如下错，麻烦告知该如何处理，谢谢了
ERROR in static/js/vendor.dc2204f563e3f684d53d.js from UglifyJs
Unexpected token: operator (>) [./~/_vue-baidu-map@0.21.10@vue-baidu-map/components/base/mixins/common.js:16,0][static/js/vendor.dc2204f563e3f684d53d.js:284,30]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
