### ISSUE TITLE
程序打包的时候报错，请帮忙看看

### ISSUE THREAD

**Issue by hw37du** [Dafrok/vue-baidu-map#428]
### 浏览器版本号

Chrome  67.0.3396.87

### Vue 版本号

2.5.2

### 组件库版本号

0.21.10

### 现象描述

```
打包的时候出现如下错误：
ERROR in static/js/vendor.dc2204f563e3f684d53d.js from UglifyJs
Unexpected token: operator (>) [./~/_vue-baidu-map@0.21.10@vue-baidu-map/components/base/mixins/common.js:16,0][static/js/vendor.dc2204f563e3f684d53d.js:284,30]
```

### 完整异常信息

```
ERROR in static/js/vendor.dc2204f563e3f684d53d.js from UglifyJs
Unexpected token: operator (>) [./~/_vue-baidu-map@0.21.10@vue-baidu-map/components/base/mixins/common.js:16,0][static/js/vendor.dc2204f563e3f684d53d.js:284,30]
```

### 在线示例 / 仓库 URL

https://dafrok.github.io/vue-baidu-map

### 复现用例

```
https://dafrok.github.io/vue-baidu-map
```

### 预期输出

```
希望能打包成功
```

### 实际输出

```
https://dafrok.github.io/vue-baidu-map
```

**Comment by Dafrok** [comment]
> ERROR in static/js/vendor.dc2204f563e3f684d53d.js from UglifyJs

说明你组件没编译，uglify 不认识 ES Next，这一点文档里写了。

**Comment by Dafrok** [comment]
可能是和 exclude 有冲突，可以参考 https://github.com/webpack/webpack/issues/2031 做适当的调整

**Comment by hw37du** [comment]
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          path.resolve(__dirname, "src"),
          path.resolve(__dirname, "node_modules/vue-baidu-map")
        ]
      }
我的配置
错误如下
ERROR in static/js/vendor.a39fd17728e24c9a1d77.js from UglifyJs
Unexpected token: operator (>) [./~/_vue-baidu-map@0.21.10@vue-baidu-map/components/base/mixins/common.js:16,0][static/js/vendor.a39fd17728e24c9a1d77.js:487,30]

**Comment by Dafrok** [comment]
你匹配的是 .js 文件

**Comment by hw37du** [comment]
请问下我改匹配什么，从错误来看，好像是common.js里有es6的语法，babel没有解析

**Comment by Dafrok** [comment]
你说的这些 .js 文件 vue 组件引入的，先过了一手 vue-loader。你可以尝试修改 vue-loader 的配置去命中这些文件，原理就是这样已经讲得很清楚了，剩下问题请参照文档修改配置。

传送门：
> https://vue-loader.vuejs.org/zh/guide/pre-processors.html#babel

**Comment by hw37du** [comment]
@Dafrok 不好意思，还得打扰你下，我昨天按照你说的修改vue-loader的配置，不管我用include:[resolve("node_modules/vue-baidu-map/components")]，还是用exclude: file => (
          /node_modules/.test(file) &&
          !/\.vue\.js/.test(file)
        )
都没有办法命中解析

**Comment by codeLittleNewbie** [comment]
我也碰到同样的问题,两者都尝试了,打包依旧报错..

**Comment by codeLittleNewbie** [comment]
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')],
        exclude: file => (
          /node_modules/.test(file) &&
          !/\.vue\.js/.test(file)
        )
      },

**Comment by Oldboyyyy** [comment]
如果是用 cnpm 安装的包 报名前面会加上`_`, 所以`include` 的路径要做修改
```
{
  test: /.js$/,
  loader: 'babel-loader',
  include: [
    path.resolve(__dirname, "src"),
    // npm | yarn 方式安装
    path.resolve(__dirname, "node_modules/vue-baidu-map"),
    // cnpm 方式安装
    path.resolve(__dirname, "node_modules/_vue-baidu-map")
  ]
}
```
@hw37du @codeLittleNewbie

**Comment by Tony-Code** [comment]
亲测有用。我是用cnpm安装的，局部引用方式。如下
```
{
        test: /\.js$/,
        loader: 'babel-loader',
        //限制范围，提高打包速度
        include: [
            path.resolve(__dirname, "../src"),
            // npm | yarn 方式安装
            path.resolve(__dirname, "../node_modules/vue-baidu-map"),
            // cnpm 方式安装（我用的是cnpm安装）
            path.resolve(__dirname, "../node_modules/_vue-baidu-map")
        ],

        //一定要注释掉exclude
        // exclude: file => (
        //     /node_modules/.test(file) &&
        //     !/\.vue\.js/.test(file)
        //   )
      },
