### ISSUE TITLE
center 属性有点问题

### ISSUE THREAD

**Issue by zaxlct** [Dafrok/vue-baidu-map#43]
首先非常感谢您的开源库，非常感谢，

我在设置 center 属性时遇到点问题：
`:center="'杭州市'"`  这样是正常的，地区会切换到杭州市。
`:center="'New York'"` 这样地图是一片空白，打开浏览器控制台提示：

VM48647:1 Uncaught TypeError: Cannot read property 'style' of undefined
 at Gg.Ig.VO (eval at yZ xxxx)

center 属性是不能解析国外的地址吗？
我想实现的效果是，有个输入框，输入美国的一些城市或者街区，地区能相应的切换，但是设置 center 属性遇到了这个问题，不知道怎么回事。

开发环境：
"vue-baidu-map": "^0.10.4"
"vue": "^2.2.6",

麻烦您了，再次感谢。

**Comment by zaxlct** [comment]
修改标题

**Comment by Dafrok** [comment]
您好，谢谢您的信任。经过官方途径咨询，目前百度地图 JS API 由于数据版权问题暂时未开放国际地区检索。vue-baidu-map 库是用来处理视图逻辑的库，核心功能和业务逻辑问题反馈可移步：[百度地图官方社区](http://bbs.lbsyun.baidu.com/forum.php)

**Comment by Dafrok** [comment]
发现一个问题。如果输入不存在的地区名按理说控制台是不应该报错的，方便提供您的代码吗？

**Comment by zaxlct** [comment]
```html
<template>
  <section id="map_search">
    <Row :gutter="24">
      <Coll span="16" class="map_container">
        <baidu-map
          class="bm_view"
          :ak="BD_SDK"
          :scroll-wheel-zoom="true"
          :inertial-dragging="true"
          :zoom="10"
          :center="'New York'">
          <bm-navigation anchor="BMAP_ANCHOR_TOP_RIGHT"/>
        </baidu-map>
      </Coll>
      <Coll span="8" class="house_list">
        <div class="house_list"></div>
      </Coll>
    </Row>
  </section>

</template>

<script>
import { BaiduMap, BmNavigation } from 'vue-baidu-map'
import { SDK } from '../../libs/CONSTANT'
import { Row, Col } from 'iview/src/components/grid'

export default {
  name: 'MapSearch',
  components: {
    BaiduMap,
    BmNavigation,
    Row,
    Coll: Col,
  },
  data() {
    return {
      BD_SDK: SDK.BAIDU_MAP,
    }
  },
}
</script>

<style>

.bm_view {
  width: 100%;
  height: 600px;
}

.house_list {
  height: 500px;
  background: #fff;
}
</style>

```

**Comment by zaxlct** [comment]
@Dafrok 谢谢，我还真不知道不支持国际地区检索。看来只能用谷歌地图了，哈哈。

**Comment by Dafrok** [comment]
百度地图的同学在尽力争取版权，但愿能尽快开放吧 😄

**Comment by Dafrok** [comment]
按照您的逻辑写了一个在线演示 http://codepen.io/Dafrok/pen/pPdYwM，并没发现有控制台抛错现象，如果方便的话能够提供更详细复现场景描述吗？十分感谢。

**Comment by zaxlct** [comment]
@Dafrok 
我刚刚又启动了一下项目，center 属性输入了 「New York」，但是不报错了 。。😓。。
页面是空白的。

不好意思哈，我也无语了。

然后非常支持你们的项目，维护一个开源项目太不容易了！

**Comment by Dafrok** [comment]
能帮到你就好，感谢反馈 🌝

**Comment by zaxlct** [comment]
@Dafrok 问题复现了，我用触控板，进行滚动操作时，又报那个错误了。😓
其实我上面发的代码已经很全了，就这一个文件。。有什么好办法分享一下

**Comment by zaxlct** [comment]
http://pbbi4w.natappfree.cc/map_search
我开了一个本地端口映射，你可是访问，调试看一下。
刚打开的时候有点慢。

**Comment by Dafrok** [comment]
问题已核实，百度地图在没有设置中心坐标时使用滚轮缩放确实是会抛错，已通过官方渠道反馈。再次感谢您的贡献！

**Comment by zaxlct** [comment]
@Dafrok 好的，不客气，应该的，嘿嘿。
