### ISSUE TITLE
点聚合功能

### ISSUE THREAD

**Issue by 531431988** [Dafrok/vue-baidu-map#433]
### 浏览器版本号

谷歌最新

### Vue 版本号

2.5.1

### 组件库版本号

0.19

### 现象描述

```
点聚合功能
```

### 完整异常信息

```
希望能添加如下效果
```

### 在线示例 / 仓库 URL

https://github.com/FishZodiac/mapCity

### 复现用例

```
https://github.com/FishZodiac/mapCity
```

### 预期输出

```
https://github.com/FishZodiac/mapCity
```

### 实际输出

```
https://github.com/FishZodiac/mapCity
```

**Comment by Dafrok** [comment]
组件库是 JS API 的视图层实现，业务功能请自行开发。
