### ISSUE TITLE
navigation set type is object ? 

### ISSUE THREAD

**Issue by gypjoy** [Dafrok/vue-baidu-map#436]
### 浏览器版本号

67.0.3396.99

### Vue 版本号

2.0

### 组件库版本号

0.21.10

### 现象描述

```
使用bm-navigation无法设置type='MAP_NAVIGATION_CONTROL_ZOOM',报l类型错误
```

### 完整异常信息

```
type check failed for prop "type". Expected Object, got String.
```

### 在线示例 / 仓库 URL

<baidu-map class="map-view" ak='ChGRjQlgN2LxG7ezwOTEEaCl9Oj4Op8L' :center="center" :mapClick="false" :zoom="zoom" :scroll-wheel-zoom="true" @ready="handler">     <bm-navigation type="MAP_NAVIGATION_CONTROL_ZOOM" anchor="BMAP_ANCHOR_TOP_LEFT" ref="A"></bm-navigation></baidu-map>

### 复现用例

```
不知道传什么object
```

### 预期输出

```
希望输出仅包含缩放按钮
```

### 实际输出

```
输出报错
```

**Comment by Dafrok** [comment]
目测是 bug

**Comment by Dafrok** [comment]
updated in 0.21.11
