### ISSUE TITLE
正常安装注册地图，更新到最新版本后，使用报错，是什么原因呢

### ISSUE THREAD

**Issue by beckyzhan** [Dafrok/vue-baidu-map#44]
![ifbgg 8zrrmeq 3 j80 ta](https://cloud.githubusercontent.com/assets/10825353/25834771/a3ac0e0a-34ac-11e7-8b95-0ecb3f4ff8ae.png)
![5u a73 _ gdh8w t24csh](https://cloud.githubusercontent.com/assets/10825353/25834772/a3b2662e-34ac-11e7-98a1-d72ec48c328e.png)
![k gjt 3 1hx rw8xri 3vm](https://cloud.githubusercontent.com/assets/10825353/25834773/a3b39a44-34ac-11e7-95fa-6816ef894238.png)

![qd4dyx r ea4g07hb p8g](https://cloud.githubusercontent.com/assets/10825353/25834836/1f8e17b6-34ad-11e7-83fb-ba058e4276c3.jpg)

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-baidu-map/#/start/usage 请认真阅读第一小节前两段
