### ISSUE TITLE
关于百度地图页面测距工具的问题

### ISSUE THREAD

**Issue by richardxgy** [Dafrok/vue-baidu-map#442]
前辈你好,我最近在使用百度地图需要添加一个页面测距的功能，百度地图版本是2.0  ，页面测距DistanceTool包引用的是1.2版本，在使用的时候发现我打开地图，调用open(),方法后,可以实现测距. 但是当我舒心了地图,或者把地图重新打开后,再去调用open方法就不行了,测距功能就无法打开.   这时候除非点击浏览器左上角的刷新按钮,再去调用才能正常.  我查了一下看到你之前为其他朋友回答过这个问题,当时你说"测距工具本身也有个全局变量的问题，我尝试修复一下" , "是 BMapLib.DistanceTool 的问题,"  "需要升级一下这个包"  但我去官方看了一下  文档还是没有改变 ,  请问BMapLib.DistanceTool 这个包升级到哪个版本了?       或者这个问题大概如何解决 
                                                                                          (文字稍多,望前辈指点...)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by richardxgy** [comment]
请问一下  BMapLib.DistanceTool 这个包升级到哪个版本了?   之前看你说过这个包似乎有问题,需要修改

**Comment by richardxgy** [comment]
我去官方文档看了一下  似乎还是1.2版本,   我看到前辈之前说  一个闭包没有被释放，需要升级一下这个包. 但我去文档看  似乎还是1.2版本  .  你之前说"页面上不允许同时 open 两次测距工具,这是一个bug"

**Comment by Dafrok** [comment]
1. 不是 bug，我没有这么说过
2. BMapLib.distanceTool 只是模块化，在原有基础上没有进行改动
3. MVVM 的测距完全没必要使用第三方工具这么麻烦，画出折线调用用 map.getInstance 直接就出结果了
4. 发 ISSUE 前请阅读下被你删掉的注释

**Comment by richardxgy** [comment]
恩恩  ,  谢谢前辈 我再去看下
