### ISSUE TITLE
baidu-map标签绑定的事件里面如何获取BMap对象

### ISSUE THREAD

**Issue by cn-zx** [Dafrok/vue-baidu-map#443]
### 浏览器版本号

chrome 68.0.3440.84

### Vue 版本号

2.5.2

### 组件库版本号

0.21.11

### 现象描述

```
想在dragend(e)事件里面获取BMap对象
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
dragend (e) {
  const {lng, lat} = e.target.getCenter()
  this.location.lng = lng
  this.location.lat = lat
}

想在这个方法里面拿到BMap对象
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by JakeWoki** [comment]
new window.BMap。dragend的参数其实是{type, target, pixel, point}

**Comment by Dafrok** [comment]
ready 之后把 BMap 对象挂到实例上
