### ISSUE TITLE
如何模块化同时引入vue-baidu-map和vue-echarts而不使用script标签引入bmap.js

### ISSUE THREAD

**Issue by juntan86** [Dafrok/vue-baidu-map#445]
### 浏览器版本号

67.0.3396.99

### Vue 版本号

2.5.16

### 组件库版本号

0.21.11

### 现象描述

```
使用vue-echarts时需要用到bmap，想通过使用vue-baidu-map来引入bmap而不是使用script标签引入bmap.js （主要担心api key泄露）
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

暂无

### 复现用例

```
无
```

### 预期输出

```
使用vue-baidu-map引入bmap，之后不再需要因为vue-echarts用到bmap而需要引入script标签
```

### 实际输出

```
使用vue-baidu-map后（引用方式参照官方示例）依旧需要引入script标签才能正确使用vue-echarts/echarts的bmap功能
```

**Comment by mzy2240** [comment]
同问。同有此种需求。

**Comment by Dafrok** [comment]
> 主要担心api key泄露

担心是多余的，引入百度地图必须把 key 写在前端，写在前端就异味着能被任何人看到。正确的做法是限制 refer。

**Comment by songispm** [comment]
担心key确实是多余的，但是我确实想把echarts与vue-baidumap结合怎么弄，毕竟想要[这个效果](http://echarts.baidu.com/examples/editor.html?c=map-bin)  ，好像是借助echarts这个[地图扩展](https://github.com/apache/incubator-echarts/tree/master/extension/bmap)实现的，如果是原生js在head标签引入原生js百度地图api写了echarts的option就自动帮忙实例化地图了，但是我vue版baidu-map标签里已有很多逻辑，求帮忙给个思路怎么结合一下

**Comment by Dafrok** [comment]
这个扩展已经高度封装了，你的这个需求应该从 echarts 扩展入手，而不是地图
