### ISSUE TITLE
当用v-for实现多个圆时，圆的编辑卡住

### ISSUE THREAD

**Issue by songispm** [Dafrok/vue-baidu-map#446]
### 浏览器版本号

69.0.3497.32

### Vue 版本号

2.5.2

### 组件库版本号

1.0.11

### 现象描述

```
当用v-for实现多个圆时，圆的编辑卡住
```

### 完整异常信息

```
当用v-for实现多个圆时，每个圆的编辑都会卡住，而用v-for实现多个polygon时，每个多边形的编辑却没有问题
```

### 在线示例 / 仓库 URL

<bm-circle v-for="circle in circles"     :center="circle.center"                  :radius="circle.radius"                  stroke-color="blue"                  :stroke-opacity="0.5"                  :stroke-weight="2"                  :editing="true"                  @lineupdate="updateCirclePath"/>

### 复现用例

```
lineupdate函数也按文档写法，但是拉动圆的编辑小方块，却拉不动，当不写v-for就只有一个圆的时候是没问题的，外层用<template>包裹一下，把v-for写在template效果一样的
```

### 预期输出

```
多个圆形，每个圆形都能单独编辑
```

### 实际输出

```
圆形编辑不动，也有可能是我写的有问题，麻烦帮忙看看该怎么修改
```

**Comment by Dafrok** [comment]
百度地图的圆形编辑确实有点问题，你可以尝试在编辑一个的时候把其它的 editing 改成 false

**Comment by songispm** [comment]
在updateCirclePath函数里去先把其他圆editing弄成false？另外问一下除了这个回调函数会持续响应，有没有开始编辑和结束编辑的节点的函数，另外什么时候能帮忙修复一下吗辛苦
