### ISSUE TITLE
多导航功能

### ISSUE THREAD

**Issue by 531431988** [Dafrok/vue-baidu-map#448]
### 浏览器版本号

最新

### Vue 版本号

2.5.1

### 组件库版本号

最新

### 现象描述

```
支持多导航切换
```

### 完整异常信息

```
如百度地图导航切换公交、自驾、步行
```

### 在线示例 / 仓库 URL

http://map.baidu.com/?newmap=1&ie=utf-8&s=s%26wd%3D

### 复现用例

```
暂无
```

### 预期输出

```
暂无
```

### 实际输出

```
暂无
```
![image](https://user-images.githubusercontent.com/8703951/44010588-f3acd962-9ee5-11e8-80b6-7a97c2e67228.png)

**Comment by Dafrok** [comment]
每个组件都有，UI 请根据您的需求说明自行开发。

**Comment by 531431988** [comment]
是都有，我点击公交或驾车，用V-IF切换对应导航，切换不了效果，求指点
![image](https://user-images.githubusercontent.com/8703951/44010808-44542392-9ee7-11e8-980e-179c93a539c7.png)

**Comment by Dafrok** [comment]
没看懂，什么叫切换不了效果？

**Comment by 531431988** [comment]
就是：
我有 公交、驾车、步行 三个功能，我点公交时用bm-transit导航，我切换驾车时应该是bm-driving导航，但实际还是公交的，切换是用v-if做的，新人不太懂，求指点

**Comment by 531431988** [comment]
不知能否提供一个简单的tab切换导航示例，UI我可以自己写，
切换驾车如图
![image](https://user-images.githubusercontent.com/8703951/44011063-e6107536-9ee8-11e8-9f1f-f6ab8c60c9db.png)
切换公交如图
![image](https://user-images.githubusercontent.com/8703951/44011073-f74a5c7c-9ee8-11e8-9610-92b55ee25957.png)
左边筛选都是一样的，求指点如何解决

**Comment by 531431988** [comment]
你的好像是没有问题，但如果初始化给了默认地址进行导航正常，修改地址切换导航，会出现2个起点
![image](https://user-images.githubusercontent.com/8703951/44011843-99ee2928-9eed-11e8-8ead-76e144b7ec0d.png)

**Comment by 531431988** [comment]
多切换几次导航确实会出现这种问题

![Uploading image.png…]()
可能是出现了选点所导致
![Uploading image.png…]()
