### ISSUE TITLE
能否通过自定义坐标搜索附近区域

### ISSUE THREAD

**Issue by Hogg222** [Dafrok/vue-baidu-map#45]
萌新的实习生又来问你问题了（

前后台我都写，有这样一个需求想和您讨论一下
定位前提下，搜索周边保险公司（很多数据都是在本地，没有录入百度地图上），后台返回经纬度和公司信息，能通过geohash去查询附近地址吗，再通过BmMarker去渲染。

**Comment by Dafrok** [comment]
听上去是可以的，你自己维护一组 BmMarker 并实现一个查询算法即可。没有被百度地图收录的地点肯定是没法用 LocalSearch 来进行检索的。
