### ISSUE TITLE
能否在官方包里面加入polyfill的兼容插件

### ISSUE THREAD

**Issue by wekerSnail** [Dafrok/vue-baidu-map#462]
*环境*
- 安卓版本6.0
- 手机：魅族note5
- chrome内核版本：44
*问题*
- 全局引入，使用vue-baidu-map的编译文件使用正常
- 局部引入，使用为编译的源码vue组件，chrome内核40+报错，页面空白
*定位问题大概就是es的编译问题*
希望官方在未编译的版本中加入polyfill兼容插件

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
