### ISSUE TITLE
请问有BMapLib.DrawingManager的控件么？

### ISSUE THREAD

**Issue by zhangjiaqing** [Dafrok/vue-baidu-map#469]
### 在线示例 URL

http://lbsyun.baidu.com/jsdemo/demo/f0_7.htm

### 功能描述

```
鼠标绘制工具
```

### 用法示例

```
http://lbsyun.baidu.com/jsdemo/demo/f0_7.htm
```

**Comment by Dafrok** [comment]
这个功能很简单，不需要控件，请参考文档。

**Comment by zhangjiaqing** [comment]
我在文档找到了，但我想画一个矩形，不要画多边形，要怎么实现？

**Comment by Hysian** [comment]
@Dafrok 请问一下，如果我想改变鼠标的样式cursor ，该怎么实现

**Comment by Hysian** [comment]
自问自答系列
`      map.setDefaultCursor('crosshair');
`
