### ISSUE TITLE
如何获取BMapLib

### ISSUE THREAD

**Issue by malaimoo** [Dafrok/vue-baidu-map#475]
### 浏览器版本号

69

### Vue 版本号

2.5

### 组件库版本号

最新

### 现象描述

```
无法获取 BMapLib
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL
我需要设置地图显示区域，
官方设置区域的示例：	
```
	var b = new BMap.Bounds(new BMap.Point(116.027143, 39.772348),new BMap.Point(116.832025, 40.126349));
	try {	
		BMapLib.AreaRestriction.setBounds(map, b);
	} catch (e) {
		alert(e);

```
请问如何获取 BMapLib

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
MVVM 框架就要用 MVVM  的思想解决问题，这个需求用不着 BMapLib，你把 center 和 zoom 固定住就行了。

**Comment by malaimoo** [comment]
MVVM 的话，那也可以加一个显示区域的 prop

**Comment by Dafrok** [comment]
不可以，因为 JS API 没有提供。

**Comment by malaimoo** [comment]
ok, Thanks

**Comment by Dafrok** [comment]
解释一下，不能做的主要原因是为了防止 JS API 加 feature，如果 JS API 加了同名的属性或方法就会命名冲突，对组件库造成 breaking change。

**Comment by javalink** [comment]
那最后就是没法做到中心点了是吧
