### ISSUE TITLE
control修改offset不生效

### ISSUE THREAD

**Issue by JakeWoki** [Dafrok/vue-baidu-map#477]
## [BUG 反馈] control修改offset不生效

Control.vue
```
watch: {
    anchor (val) {
      this.originInstance.setAnchor(val)
    },
    offset (val) {
      this.originInstance.setOffset(val)
    }
  }
```
修改后offset函数有执行，但是没生效

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
