### ISSUE TITLE
【问题】请问bm-marker能否实现多点标注？

### ISSUE THREAD

**Issue by joekhwong** [Dafrok/vue-baidu-map#48]
尝试过用以下代码测试但不能成功实现多点标注。

<template>
  <baidu-map class="map" :center="{lng: 116.404, lat: 39.915}" :zoom="15">
    <bm-marker :position="markerPoint1" :dragging="true" @click="infoWindowOpen">
      <bm-info-window :show="show" @close="infoWindowClose" @open="infoWindowOpen">我爱北京天安门</bm-info-window>
    </bm-marker>
    <bm-marker :position="markerPoint2" :dragging="false"/></bm-marker>
  </baidu-map>
</template>

<script>
export default {
  mounted() {
  },
  data () {
    return {
      show: false,
      markerPoint1: {lng: 116.404, lat: 39.915},
      markerPoint2: {lng: 116.804, lat: 39.415},
    }
  },
  methods: {
    infoWindowClose () {
      this.show = false
    },
    infoWindowOpen () {
      this.show = true
    }
  }
}
</script>

**Comment by Dafrok** [comment]
为何不能？

**Comment by joekhwong** [comment]
尝试过用以下代码测试但不能成功。请教下面那部分出错？正确的用法是怎样的？

`<template>`
`  <baidu-map class="map" :center="{lng: 116.404, lat: 39.915}" :zoom="15">`
`    <bm-marker :position="markerPoint1" :dragging="true" @click="infoWindowOpen">`
`      <bm-info-window :show="show" @close="infoWindowClose" @open="infoWindowOpen">我爱北京天安门</bm-info-window>`
`    </bm-marker>`
`    <bm-marker :position="markerPoint2" :dragging="false"/></bm-marker>`
`  </baidu-map>`
`</template>`

**Comment by Dafrok** [comment]
http://localhost:8080/#/start/usage 第二小节

**Comment by Dafrok** [comment]
请参考 https://dafrok.github.io/vue-baidu-map/#/start/base 第一小节，以及 https://dafrok.github.io/vue-baidu-map/#/start/usage 第二小节。

**Comment by joekhwong** [comment]
明白并解决了！谢谢！
