### ISSUE TITLE
不渲染组件的情况下怎么获取Bmap类、map实例

### ISSUE THREAD

**Issue by AllenZho** [Dafrok/vue-baidu-map#481]
### 在线示例 URL

无

### 功能描述

```
不渲染组件的情况下怎么获取Bmap类、map实例
```

### 用法示例

```
不渲染组件的情况下怎么获取Bmap类、map实例
```

**Comment by Dafrok** [comment]
不渲染组件直接对着官方的 JS API 文档撸就行吧。。。

**Comment by KDWangBoss** [comment]
@Dafrok 大佬你好，有几个小疑惑可否解答一下
1. 不渲染组件的情况下撸官方api需要引入官方的js文件吗
2. Vue.use(BaiduMap)后全局有暴露这些实例吗
