### ISSUE TITLE
点聚合的minClusterSize参数类型有误

### ISSUE THREAD

**Issue by niaodan2b** [Dafrok/vue-baidu-map#484]
### 浏览器版本号

Chrome 69.0.3497.100

### Vue 版本号

2.5

### 组件库版本号

0.21.11

### 现象描述

```
根据文档，该参数为Number类型，实际传入Number类型时报错"type check failed for prop minClusterSize. Expected Object, got Number"
```

### 完整异常信息

```
type check failed for prop minClusterSize. Expected Object, got Number
```

### 在线示例 / 仓库 URL

<bml-marker-clusterer  :maxZoom="13" :averageCenter="true" :minClusterSize="1"></bml-marker-clusterer>

### 复现用例

```
暂无
```

### 预期输出

```
控制台不报错
```

### 实际输出

```
控制台报错
```

**Comment by fengchangfight** [comment]
解决了没？

**Comment by Dafrok** [comment]
哦，解决之后忘记发版了

**Comment by Dafrok** [comment]
done.
