### ISSUE TITLE
bm-local-search 搜索拿到的位置是整个城市的了。

### ISSUE THREAD

**Issue by wuchuguang** [Dafrok/vue-baidu-map#49]
`<bm-local-search :keyword="search" :location="center" :nearby="nearby" @searchcomplete="searchcomplete"></bm-local-search>`

center是深圳北的{lat,lng}
nearby:{center:center, radius:200}
searchcomplete 这个拿到的数据是龙岗，罗湖等的数据了。
组件内的load的_location值是深圳北的位置。

**Comment by wuchuguang** [comment]
searchcomplete(data){
   console.log(data.radius);//打印出来是undefined,在百试demo上是打印200
}

**Comment by wuchuguang** [comment]
vue-dev工具上看到的nearby变量是正确的，200

**Comment by Dafrok** [comment]
我在本地测试没发现问题。能否提供一个复现用例的在线展示或者精简的业务代码？

**Comment by Dafrok** [comment]
@wuchuguang ping

**Comment by Dafrok** [comment]
如果没有后续问题，我明天就关闭问题了。
