### ISSUE TITLE
Cannot read property 'Geolocation' of undefined"

### ISSUE THREAD

**Issue by JakeWoki** [Dafrok/vue-baidu-map#491]
### 浏览器版本号

Google Chrome 66.0.3359.181

### Vue 版本号

2.5.2

### 组件库版本号

0.21.11

### 现象描述

`let geolocation = new window.BMap.Geolocation()`
不渲染组件的情况上面这句报Cannot read property 'Geolocation' of undefined"。如果渲染baidu-map再使用上面那句是正常的，求助

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
这个问题和组件无关，出现错误是因为在你调用的 Geolocation 类的时候压根就没加载百度地图的 JS SDK。

**Comment by Dafrok** [comment]
http://lbsyun.baidu.com/jsdemo.htm#a1_2

**Comment by Dafrok** [comment]
http://lbsyun.baidu.com/index.php?title=jspopular/guide/show

**Comment by JakeWoki** [comment]
@Dafrok  感谢！之前是sdk没初始化完成就new window.BMap.Geolocation()才导致错误的

**Comment by Dafrok** [comment]
还有一个方法，你在 ready 事件里调用，ready 事件一定在初始化完成之后的。

**Comment by Dafrok** [comment]
界面不显示地图完全用不着组件库啊，组件库存在的意义就是为渲染视图提供方便 🤣

**Comment by JakeWoki** [comment]
有的界面不显示，有的界面显示~~o(>_<)o ~~
