### ISSUE TITLE
怎么自定义添加第三方开源库,想要一个自定义信息窗口的开源库

### ISSUE THREAD

**Issue by SaltedFishYuto** [Dafrok/vue-baidu-map#495]
### 浏览器版本号

谷歌66.0.3359.181（正式版本） （64 位）

### Vue 版本号

2.9.6

### 组件库版本号

0.21.11

### 现象描述

```
无
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
你这个需求不需要搞第三方的，添加一个用自定义覆盖物自己随便在里边画什么都行。

**Comment by SaltedFishYuto** [comment]
但是这个弹窗显示写在drew里的话,需要移动弹窗的位置才会改变呢

**Comment by SaltedFishYuto** [comment]
draw里不是移动才会变动触发吗

**Comment by SaltedFishYuto** [comment]
我只是想点击显示而已,不想移动

**Comment by Dafrok** [comment]
和移动有啥关系？

**Comment by SaltedFishYuto** [comment]
就是地图发生改变时触发,我的业务是点击坐标就触发

**Comment by Dafrok** [comment]
那和 draw 也没关系呀，你绑定一个 click 事件不就行了

**Comment by SaltedFishYuto** [comment]
大佬你的意思是坐标不写在drew里？,因为我点击坐标获取了他的经度纬度,把这个值传给自定义覆盖物,传到draw里？但是draw值是传进去了,就是需要移动才能显示出弹窗

**Comment by SaltedFishYuto** [comment]
// 点击坐标
    infoWindowOpen(item, index) {
      this.actionIndex = index;
      this.is_overlay = true;
      this.itemInfo = item;
    },
    draw({ map, el, BMap }) {
      // 弹窗坐标
      const pixel = map.pointToOverlayPixel(new BMap.Point(this.itemInfo.lng,this.itemInfo.lat));
      // 弹窗
      el.style.left = pixel.x - 70 + "px";
      el.style.top = pixel.y - 110 + "px";
    },

**Comment by Dafrok** [comment]
为什么需要移动，我始终不明白。https://dafrok.github.io/vue-baidu-map/#/zh/overlay/overlay 这个示例里出现的自定义覆盖物也不需要移动地图啊。

**Comment by SaltedFishYuto** [comment]
因为我是循环坐标的

**Comment by Dafrok** [comment]
循环和单个的有啥区别？

**Comment by SaltedFishYuto** [comment]
<hedaer-title title="地图找房"></hedaer-title>
    <baidu-map class="map" :center="center" :zoom="15" @ready="handler">
      <div v-for="(item,index) of mapHouseList" :key="item.lng">
        
        <bm-marker :position="{ lng: item.lng, lat: item.lat }" @click="infoWindowOpen(item,index)" :icon="{url:require('./images/dwfy@2x.png'), size: {width: 28, height:70 }}"> </bm-marker>
      </div>
      <bm-overlay v-show="is_overlay" pane="labelPane" class="sample" @draw="draw">
        <div class="mapInfo" @touchstart="handleDetail">
          <img class="img-left" src="./images/shouye.png" />
          <div class="right">
            <h2>2000元/月</h2>
            <h3>2室-50m</h3>
            <h3>普通装修</h3>
          </div>
          <img class="arrow-right" :src="require('./images/arrow-right.png')" />
        </div>
      </bm-overlay>
    </baidu-map>

**Comment by SaltedFishYuto** [comment]
我发邮箱可以吗动图给你看看

**Comment by Dafrok** [comment]
你可以直接发这里

**Comment by SaltedFishYuto** [comment]
其实主要我的问题是我的自定义覆盖物的坐标是动态的

**Comment by SaltedFishYuto** [comment]
是点击坐标又变化了,而整个弹窗是draw里,是移动才触发的

**Comment by Dafrok** [comment]
文档里也有说明，需要手动重绘可以调用实例方法 `reload`。

**Comment by SaltedFishYuto** [comment]
那个,作者大佬这个reload的文档,在官方哪里能发个链接吗,找不到。。

**Comment by SaltedFishYuto** [comment]
感激不尽

**Comment by SaltedFishYuto** [comment]
谢谢,我自己实现了,是我自己文档没看清楚,不好意思了,再次感谢大佬这么好的开源组件
