### ISSUE TITLE
弹出框用div做，如何定left跟top

### ISSUE THREAD

**Issue by swliu920322** [Dafrok/vue-baidu-map#496]
### 浏览器版本号

chrome

### Vue 版本号

2

### 组件库版本号

2

### 现象描述

```
由于百度地图的弹出框无法拖出容器，业务需要拖出去，页面一拖拽，map.pointToOverlayPixel生成的xy就不对了
```

### 完整异常信息

```
a
```

### 在线示例 / 仓库 URL

http://shbigdata.cnsaas.com/emergency

### 复现用例

```
1
```

### 预期输出

```
1
```

### 实际输出

```
1
```

**Comment by Dafrok** [comment]
没看明白你的示例问题在哪，不过百度地图 JS API 本身没有将覆盖物拖出地图容器外的能力，这已经超出组件库能解决的问题范围了。
你需求的这个功能，我能想到的有两种解决办法，一个是在自定义覆盖物内部声明一个 draggable 的元素，另一个是在地图容器外声明你的目标元素。
