### ISSUE TITLE
局部注册组件库

### ISSUE THREAD

**Issue by yangjing0319** [Dafrok/vue-baidu-map#499]
局部注册百度地图组件[  由于未编译的 ES 模块不能在大多数浏览器中直接运行，如果引入组件时发生运行时错误，请检查 webpack 的 loader 配置，确认 include 和 exclude 选项命中了组件库。 ]  请问怎么检查是否命中组件库？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by yangjing0319** [comment]
局部注册写法：import { BaiduMap, BmOverlay } from 'vue-baidu-map'
