### ISSUE TITLE
版权的例子也运行错误，请抽空帮忙再看下吧

### ISSUE THREAD

**Issue by JasenWu** [Dafrok/vue-baidu-map#5]
![image](https://cloud.githubusercontent.com/assets/8563465/23442719/34b1d958-fe65-11e6-8af5-ca343dd88258.png)

**Comment by Dafrok** [comment]
复现不了，这里文档没有问题。
你可以自己本地跑一下文档的开发环境对比一下。

**Comment by Dafrok** [comment]
一直没有收到反馈 先close掉了
