### ISSUE TITLE
百度地图原生api里面有个 Geocoder()方法，应该怎么用啊

### ISSUE THREAD

**Issue by IOJINDD** [Dafrok/vue-baidu-map#50]
百度地图原生api里面有个 Geocoder()方法，应该怎么复用啊，有什么组件吗，就是我想实现一个功能，点击地图上的地点，然后可以获取到那个位置上的信息。

**Comment by Dafrok** [comment]
没有组件，拿到 `BMap` 核心类访问 `Geocoder` 属性即可。vue 是负责处理视图逻辑的框架，`Geocoder` 与视图无关。

**Comment by IOJINDD** [comment]
<img width="556" alt="default" src="https://cloud.githubusercontent.com/assets/25760944/26302815/103a22da-3f18-11e7-9835-e61e23a5dd8c.png">
我是在这里引入 的，我要怎么获取 BMap 核心类啊，大侠。

**Comment by Dafrok** [comment]
文档里有写
