### ISSUE TITLE
行政区划，部分省市不可以圈选，比如天津市

### ISSUE THREAD

**Issue by zhouchen19** [Dafrok/vue-baidu-map#506]
天津市  河北省 江苏省 海南省 四川省 贵州省 宁夏回族自治区 台湾省 "香港特别行政区" "澳门特别行政区"    这些省市都不可以圈选

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
