### ISSUE TITLE
如何检索LBS云平台数据

### ISSUE THREAD

**Issue by Hardlygo** [Dafrok/vue-baidu-map#507]
![7y w uv gk e md_ qog](https://user-images.githubusercontent.com/33127984/47474560-1073bc80-d84a-11e8-8fd9-c678b31e459a.png)
检索到的LBS数据表的数据是V2？v3？v4
如何检索自己创建的表数据？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
