### ISSUE TITLE
怎么去掉标注

### ISSUE THREAD

**Issue by Ben199011** [Dafrok/vue-baidu-map#509]
![image](https://user-images.githubusercontent.com/30291896/47636377-08da4d80-db93-11e8-96cb-4b74623458a3.png)
像这样的，我想要地区检索，但又不想要红点标注，怎么去掉呢，

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by starwang666** [comment]
> ![image](https://user-images.githubusercontent.com/30291896/47636377-08da4d80-db93-11e8-96cb-4b74623458a3.png)
> 像这样的，我想要地区检索，但又不想要红点标注，怎么去掉呢，

这个问题你解决了吗？
