### ISSUE TITLE
关于enableMapClick

### ISSUE THREAD

**Issue by donxbei** [Dafrok/vue-baidu-map#513]
百度地图文档中有关于enableMapClick是否开启底图可点功能的属性, 想知道vue-baidu-map里是如何使用这个属性的,  一直找不到禁止底图可点的方法

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
