### ISSUE TITLE
百度地图的中心点始终是在左上角

### ISSUE THREAD

**Issue by chensiyuan12138** [Dafrok/vue-baidu-map#514]
<baidu-map
          class="bm-view"
          :ak="ak"
          :center="center"
          :zoom="zoom"
          :dragging="true"
          @ready="handler"
          @click="">
          <bm-marker :position="center" :dragging="true" @click=""></bm-marker>
          <bm-navigation anchor="BMAP_ANCHOR_TOP_RIGHT"></bm-navigation>
        </baidu-map>

handler ({BMap, map}) {
        this.center.lng = 116.404
        this.center.lat = 39.915
        this.zoom = 15
      }

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
