### ISSUE TITLE
第三方组件库 路书

### ISSUE THREAD

**Issue by zishuweishu** [Dafrok/vue-baidu-map#518]
### 在线示例 URL

https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/lushu

### 功能描述

```
支持自定标点  现在的bml-lushu里面的path是根据@searchcomplete="handleSearchComplete"这个事件获取的  我看了一下打印的res.getPlan(0).getRoute(0).getPath() 可能和bm-driving的start和stop有关
```

### 用法示例

```
自定义path {lng：‘’,lat:"}
```

**Comment by Dafrok** [comment]
http://api.map.baidu.com/library/LuShu/1.2/docs/symbols/BMapLib.LuShu.html 路书的文档里写了，path 的成员就是 Point 对象，你构造好 Point 对象传给它就行了。
