### ISSUE TITLE
使用bm-marker自定义图标出错

### ISSUE THREAD

**Issue by kopanya** [Dafrok/vue-baidu-map#52]
标签：
`<bm-marker 
              :position="{lng: bmap.longitude, lat: bmap.latitude}" 
              :dragging="true" 
              animation="BMAP_ANIMATION_BOUNCE" 
              :icon="{url: 'http://xxx.xxx.com/images/sign@2x.png', size: {width: 56, height: 56}}">
              </bm-marker>`
错误提示：
`[Vue warn]: Error in callback for watcher "icon": 
(found in <BmMarker>)`
`app.js:4152 TypeError: Cannot read property 'setIcon' of undefined
    at VueComponent.handler (app.js:12041)
    at Watcher.run (app.js:5254)
    at flushSchedulerQueue (app.js:5034)
    at Array.<anonymous> (app.js:3210)
    at nextTickHandler (app.js:3159)
    at <anonymous>`

**Comment by Dafrok** [comment]
先试试文档示例里的 case 在你的上下文里能不能跑起来，如果不能最好提供一下你的上下文。

**Comment by Dafrok** [comment]
更新到 0.10.6 试一下，我做了一个容错处理。如果还有问题再开新的 issue 提问。
