### ISSUE TITLE
BmPolyline组件中能不能增加对点样式的自定义，或者是怎么样允许用户自定义折线的点？

### ISSUE THREAD

**Issue by abozhang** [Dafrok/vue-baidu-map#526]
### 在线示例 URL

https://dafrok.github.io/vue-baidu-map/#/zh/overlay/polyline

### 功能描述

```
BmPolyline组件中能不能增加对点样式的自定义，或者是怎么样允许用户自定义折线的点？
```

### 用法示例

```
 <bm-polyline :path="polylinePath" stroke-color="blue" :stroke-opacity="0.5" :stroke-weight="2" :editing="true" @lineupdate="updatePolylinePath"></bm-polyline>
```

**Comment by Dafrok** [comment]
折线组件根本就没有点的概念啊

**Comment by xwyweitian** [comment]
@那么如果要实现点击折线中的点弹出自定义的信息，该怎么做呢，下面是个轨迹
![image](https://user-images.githubusercontent.com/45192189/50631595-d4fb1a00-0f7f-11e9-93fc-05877eacbfee.png)

**Comment by Dafrok** [comment]
自己声明一个相同位置的 marker 放上去啊

**Comment by myf-sky** [comment]
请问如果通过折线绘制实时运行轨迹的话，动态往polylinePath里面push数据的频率有没有要求？我现在是每200ms向polylinePath数组push一条数据从而达到前端页面动态展示运行轨迹的效果；但是遇到的问题是：随着时间增加，电脑内存，磁盘及CPU使用率都会逐渐增加，最后就会崩掉。会不会是往polylinePath里面push数据的频率太高引起的？？？
