### ISSUE TITLE
bm-marker 指定 size 无法自动缩放自定义 icon

### ISSUE THREAD

**Issue by hao-li** [Dafrok/vue-baidu-map#53]
通过 bm-marker 的 icon 属性指定尺寸（如下例）
```
:icon="{url: iconUrl, size: {width: 25, height: 35}}"
```
生成的 html 中会在 iconUrl 对应 img 外层的 div 指定
```
width: 25px;
height: 35px;
```
但是 img 自身没有指定尺寸。

如果 iconUrl 的实际尺寸比指定尺寸大，将只会显示图片的局部，而非一般预期的缩放
期望此处进行改进

**Comment by Dafrok** [comment]
百度地图 API 本身就不支持缩放吧？

**Comment by hao-li** [comment]
之前的代码是仿照百度官方实例写的，那个图片可以正常缩放（指定图片原尺寸等比例缩小的新尺寸）
下面是之前的相关代码摘要
```
const size = new BMap.Size(25, 35)
const icon = new BMap.Icon(require('icon.png'), size)
icon.imageSize = size
const marker = new BMap.Marker(new BMap.Point(lng, lat), {icon: icon})
map.addOverlay(marker)
```

**Comment by Dafrok** [comment]
我抽时间排查一下

**Comment by Dafrok** [comment]
你源码里没有定义 `imageSize`  属性

**Comment by hao-li** [comment]
看文档中关于 Icon 的描述，并未找到 imageSize 的属性
```
{
  url: String,
  size: Size,
  opts: {
    anchor: Size,
    imageOffset: Size,
    infoWindowAnchor: Size,
    printImageUrl: String
  }
}
```
尝试追加 imageSize 及 opts.imageSize 均不成功

根据百度地图文档从1.4版开始新增的 imageSize 属性，本库是否尚未支持？
> [imageSize	图标所用的图片的大小，此功能的作用等同于 CSS 中的 background-size 属性。可用于实现高清屏的高清效果。(自 1.4 新增)](http://developer.baidu.com/map/reference/index.php?title=Class:%E8%A6%86%E7%9B%96%E7%89%A9%E7%B1%BB/Icon)

**Comment by Dafrok** [comment]
这个属性确实是遗漏了，稍后修补，今天发版。

**Comment by Dafrok** [comment]
0.10.7 已发版，十分感谢您的反馈！

**Comment by hao-li** [comment]
感谢您分享这么好用的库并且如此及时响应用户反馈；）

**Comment by cxjourney** [comment]
还是没有解决。

**Comment by cxjourney** [comment]
0.21.22  
<bm-marker :position="markerPoint"
                     :icon="{url: require('@/assets/bike.png'),
                     size: {width: 32, height: 32}}">
</bm-marker>  好像没有改变
