### ISSUE TITLE
地图问题

### ISSUE THREAD

**Issue by benbtx** [Dafrok/vue-baidu-map#538]
### 浏览器版本号

Chrome 69.0.3497.92

### Vue 版本号

2.95

### 组件库版本号

0.21.14

### 现象描述

```
handler中初始地图（map）和兄弟组件通过emit传过来的坐标点（coordinate）。怎么初始化坐标点（这个坐标点是兄弟后台获取，然后emit传给地图组件的，如果在handler中初始化坐标点，有时候拿不到那个坐标点）
```

### 完整异常信息

```
handler中初始地图（map）和兄弟组件通过emit传过来的坐标点（coordinate）。怎么初始化坐标点（这个坐标点是兄弟后台获取，然后emit传给地图组件的，如果在handler中初始化坐标点，有时候拿不到那个坐标点）
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
能成功初始数据
```

### 实际输出

```
有时初始数据报错
```

**Comment by Dafrok** [comment]
文档第一章写了。放到 ready 事件里去

**Comment by benbtx** [comment]
handler就是ready事件对应的方法。地图对象handler方法中，我能拿到   。现在的问题 是兄弟组件间 ,通过总线机制传值 。$on 里有时获取不到地图；hanler里有时又获取不到兄弟之间传 的值 ？

**Comment by benbtx** [comment]
> 文档第一章写了。放到 ready 事件里去

handler就是ready事件对应的方法。地图对象handler方法中，我能拿到 。现在的问题 是兄弟组件间 ,通过总线机制传值 。$on 里有时获取不到地图；hanler里有时又获取不到兄弟之间传 的值 ？

**Comment by Dafrok** [comment]
ready 事件是全局的，你可以在兄弟组件 onReady 之后再调用你的方法。

**Comment by benbtx** [comment]
> ready 事件是全局的，每一个组件都会触发。你可以在兄弟组件 onReady 之后再调用你的方法。

每一个组件都会触发 是什么意思？没看懂。我整个页面是一个父组件，左边是一个类似树控件 的子组建，右边是地图子组件。 树控件 上也有  reay 事件？

**Comment by benbtx** [comment]
> ready 事件是全局的，每一个组件都会触发。你可以在兄弟组件 onReady 之后再调用你的方法。

有没有事例啊 ，show me your code  .可能更容易让我理解

**Comment by Dafrok** [comment]
如果不是定制地图子组件就更好办了，ready 触发之后给 store 里插个旗子，其它组件根据这个 flag 的状态来决定是不是要改地图的 model

**Comment by Dafrok** [comment]
Promise 就可以啊，不会用的话直接 v-if 也不是不行

**Comment by benbtx** [comment]
> Promise 就可以啊，不会用的话直接 v-if 也不是不行

![ddox3mh7t 4y 3w 6iy3 to](https://user-images.githubusercontent.com/19159482/49786710-ae223d00-fd5f-11e8-9fe7-493005cb4806.png)
![n x7 t leh3 m19 hgr6vio](https://user-images.githubusercontent.com/19159482/49786711-aebad380-fd5f-11e8-9735-1633d897282e.png)

看了promise ,还是没看懂把promise 放在哪解决？人员车辆数据是通过监听兄弟组件ajax返回结果获取的

**Comment by Dafrok** [comment]
promise 放在哪都无所谓呀，只要你在 ready 里拿到带着返回结果的 promise 对象就行了呀
