### ISSUE TITLE
能问下多点用js怎么加载么？

### ISSUE THREAD

**Issue by boneq** [Dafrok/vue-baidu-map#54]
能问下多点用js怎么加载么？

**Comment by Dafrok** [comment]
问题有些含糊。解释一下清楚多点是什么，js 想要加载什么。

**Comment by boneq** [comment]
我需要在地图上加载多个点怎么加载呢

**Comment by Dafrok** [comment]
我需要在vue组件里渲染多个标签怎么做呢

**Comment by boneq** [comment]
在baidu-map标签下加bm-marker标签。
我想问能不能在@ready中直接渲染多个点呢？

**Comment by Dafrok** [comment]
你说的这两件事之间我没看出什么联系，你想要实现的是什么？

**Comment by boneq** [comment]
我想在@ready中一次加载很多点在地图上，还有什么方法可以实现么？

**Comment by Dafrok** [comment]
> 我需要在vue组件里渲染多个标签怎么做呢

和 vue 组件在 mounted 生命周期里渲染很多节点的方法没有区别啊……

**Comment by Dafrok** [comment]
我现在不太明白你卡在哪了，你看过 vue 文档的这个章节吗？

https://cn.vuejs.org/v2/api/#v-for

**Comment by Dafrok** [comment]
@boneq 这里还有疑问吗？没有问题我 close 掉了

**Comment by boneq** [comment]
你意思是循环出来？我一直以为是在ready中怎么弄出来 的

**Comment by Dafrok** [comment]
你使用的是 mvvm 框架，请牢记 **数据驱动视图** 原则。
