### ISSUE TITLE
局部引入组件时，自定义组件名会导致事件绑定失效

### ISSUE THREAD

**Issue by cjjlovedsn** [Dafrok/vue-baidu-map#543]
# 局部引入组件时，自定义组件名会导致事件绑定失效
bindEvent方法是通过vm.$options._componentTag获取组件的名称，然后去查询event.js中查找到对应的方法绑定，所以如果在引入组件时使用了自定义的组件名称将导致事件绑定失败

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
