### ISSUE TITLE
局部引入组件时，自定义组件名将导致事件绑定失效

### ISSUE THREAD

**Issue by cjjlovedsn** [Dafrok/vue-baidu-map#544]
### 浏览器版本号

chrome 71.0.3578.80

### Vue 版本号

2.5.17

### 组件库版本号

0.21.14

### 现象描述

```
局部引入组件时，自定义组件名将导致事件绑定失效。查看源码发现是根据vm.$options._componentTag获取到对应的事件类型进行绑定
```

### 完整异常信息

```
*
```

### 在线示例 / 仓库 URL

*

### 复现用例

```
*
```

### 预期输出

```
*
```

### 实际输出

```
*
```

**Comment by Dafrok** [comment]
所以请按照文档的说明使用，不要用自定义组件名，地图容器和内部组件是紧耦的。就像 `Tabs` 和 `Tab` 一样不能拆开用。
