### ISSUE TITLE
bm-polyline 如何在途经点添加 bm-marker

### ISSUE THREAD

**Issue by Zhang-Yida** [Dafrok/vue-baidu-map#55]
<bm-polyline :path="polylinePath" stroke-color="#45cc6a" :stroke-opacity="0" :stroke-weight="4"                                 :editing="false"></bm-polyline>

polylinePaths: [
                    [
                        {lng: 123.439516, lat: 41.783628},
                        {lng: 123.429516, lat: 41.784221},
                        {lng: 123.424024, lat: 41.785221},
                        {lng: 123.427024, lat: 41.786221},
                        {lng: 123.427144, lat: 41.787232}
                    ]
 ]

请问如何在每个中间的转折点添加一个 maker 经停的icon

**Comment by Dafrok** [comment]
这是两个完全没有关系的组件，按照各自的的方式，该怎么添加怎么添加。

**Comment by Zhang-Yida** [comment]
不过现在通过经纬度的path数组，直接绘制了这个折线，貌似无法向折线中间的转折点上绘制图片吧？

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-baidu-map/#/zh/overlay/marker

绘制点的方法在这里，先尝试绘制第一个点吧。
