### ISSUE TITLE
可以做echart散点地图吗？

### ISSUE THREAD

**Issue by RikaLuo** [Dafrok/vue-baidu-map#550]
期望效果：
能做成这种样子的吗？地图我引用了，但是不知道该如何把这种散点图对应到地图上去，求指教：
![image](https://user-images.githubusercontent.com/19562162/50397315-8e9d0280-07aa-11e9-99c4-6649badbe0bb.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
