### ISSUE TITLE
能不能根据鼠标的移动直接画圆

### ISSUE THREAD

**Issue by ztxchong** [Dafrok/vue-baidu-map#551]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by xiaohaiH** [comment]
这个可以自己实现，用一个遮罩层盖在地图上

**Comment by ztxchong** [comment]
> 这个可以自己实现，用一个遮罩层盖在地图上

能不能给个案例，新手小白完全没思路

**Comment by xiaohaiH** [comment]
百度地图上画一个遮罩层，然后监听遮罩层上的移动事件，然后在将移动事件中的 x，y 坐标转换成经纬度就好了
