### ISSUE TITLE
不能进行实时标点

### ISSUE THREAD

**Issue by vxhly** [Dafrok/vue-baidu-map#560]
### 浏览器版本号

Google Chrome 版本 71.0.3578.98（正式版本） （64 位）

### Vue 版本号

 vue: ^2.5.17

### 组件库版本号

vue-baidu-map: ^0.21.16

### 现象描述

```
在动态设置中心点之后，并没有重绘标注点，绑定的经纬度是有更新的
```

### 完整异常信息

```
无异常信息
```

### 在线示例 / 仓库 URL

https://codesandbox.io/s/yvrq802wj1

### 复现用例

```
https://codesandbox.io/s/yvrq802wj1
```

### 预期输出

```
在动态设置中心点之后，标注的点也应该进行重新设置，或者加一个重绘的回调函数（PS：翻遍文档没找到）
```

### 实际输出

```
在动态设置中心点之后，并没有重绘标注点，绑定的经纬度是有更新的
```

**Comment by Dafrok** [comment]
你的 ready 事件没声明呀……

**Comment by vxhly** [comment]
中心点是更新了，但是红色的标点没有跟过来，用于实时标点，就是说我动态改变中心地址，红色的标点也要跟着改变到对应的位置上，地图的中心点也要实时改变

**Comment by Dafrok** [comment]
明明已经改变了呀，你自己都没检查一下 marker 的位置吗？

**Comment by Dafrok** [comment]
GeoDecorder 的参数是 GCJ02 坐标系，你把百度地图的 bd09 坐标传进去自己转自己，肯定不是你想象的那个值呀，建议先把百度地图 JS API 的文档好好梳理一下。
