### ISSUE TITLE
文档在IE11及以下版本中均无法打开

### ISSUE THREAD

**Issue by limeng1900** [Dafrok/vue-baidu-map#566]
### 相关文档 URL

https://dafrok.github.io/vue-baidu-map/#/zh/guide/painting

### 问题描述

```
ES6某些对象不支持的原因
```

### 改进建议

```
建议调整下babel
```

**Comment by Dafrok** [comment]
文档没有做兼容的打算，需求不大

**Comment by limeng1900** [comment]
> 文档没有做兼容的打算，需求不大

其实是用文档测基础功能的浏览器兼容性来的，绘制多边形在IE系列 Edage、其他一些浏览器兼容模式里会出现点偏移的情况。

**Comment by Dafrok** [comment]
你可以拿 JS API 先试试，如果有同样的问题证明 API 有 bug，可以去论坛反馈一下
