### ISSUE TITLE
移动端 想实现 长按 bm-marker 取 点  

### ISSUE THREAD

**Issue by ThinkerK** [Dafrok/vue-baidu-map#567]
### 浏览器版本号

谷歌67.0.3396.99

### Vue 版本号

2.0+

### 组件库版本号

0.21.16

### 现象描述

```
bm-marker  无 长按事件  想在 移动端 实现长按取点
```

### 完整异常信息

```
bm-marker  无 长按事件
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
移动端 想实现 长按 bm-marker 取 点  
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
官方文档里 marker 没有 touch 事件，通过 Map 类的 longpress 事件取最近的 marker 来实现吧。

**Comment by ThinkerK** [comment]
嗯嗯  我试下  谢谢你
