### ISSUE TITLE
是否存在根据一个存在的地址返回坐标或返回 bm-marker

### ISSUE THREAD

**Issue by kirin-yuen** [Dafrok/vue-baidu-map#568]
### 在线示例 URL

参考 https://blog.csdn.net/fabulous1111/article/details/80918032

### 功能描述

```
是否存在根据一个存在的地址返回坐标或返回 bm-marker
```

### 用法示例

```
参考 https://blog.csdn.net/fabulous1111/article/details/80918032
```

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-baidu-map/#/zh/map/baidu-map

文档里写了，center 属性支持字符串。
