### ISSUE TITLE
bm-boundary标签内添加事件无法正常返回参数

### ISSUE THREAD

**Issue by LinXingYao** [Dafrok/vue-baidu-map#569]
boundary是由polygon渲染的，但是同样的polygon中的事件在触发后可以正常返回event{type, target, point, pixel}这些参数，但是boundary返回的只有undefined

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
