### ISSUE TITLE
vue版本升级后报错。

### ISSUE THREAD

**Issue by jinjinwa** [Dafrok/vue-baidu-map#57]
如下：
"vue": "^2.3.3",
"vue-baidu-map": "^0.10.7",
bm-local-search组件
![image](https://user-images.githubusercontent.com/12455937/26918272-d5c30eb0-4c63-11e7-896d-2b468f639f84.png)

ps:问题找到了。
bm-local-search组件的searchcomplete方法返回的data数据结构变了。。2333
![image](https://user-images.githubusercontent.com/12455937/26918618-5e8ab472-4c65-11e7-8976-34deb8a76e55.png)

**Comment by Dafrok** [comment]
。。。。。。。。

**Comment by Dafrok** [comment]
那 issue 是不是能关了 🤣

**Comment by Dafrok** [comment]
帮您问了一下，官方的说法是你可能是调用了一个混淆过的属性，混淆的属性名在每次更新后都会发生变化，属于错误用法，建议您使用其它实现方式。
