### ISSUE TITLE
BmNavigation 控件 是否显示级别提示信息 showZoomInfo false 时不生效

### ISSUE THREAD

**Issue by benbtx** [Dafrok/vue-baidu-map#572]
### 浏览器版本号

Google Chrome 版本 71.0.3578.98（正式版本） （32 位）

### Vue 版本号

0.21.11

### 组件库版本号

无

### 现象描述

```
无
```

### 完整异常信息

```
showZoomInfo= false 时不生效，还是显示了级别提示信息
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
JS API 本身有问题，已经通过官方渠道反馈，这边先关了
