### ISSUE TITLE
mapStyle自定义后报错

### ISSUE THREAD

**Issue by juchao110** [Dafrok/vue-baidu-map#588]
我从官网下载了个性化地图的JSON，传入mapStyle 后就报错了

![image](https://user-images.githubusercontent.com/28338109/55305782-6c3f1300-5484-11e9-8445-2191154783fe.png)
@Dafrok

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
