### ISSUE TITLE
BmBoundary控件有点问题

### ISSUE THREAD

**Issue by varOneVar** [Dafrok/vue-baidu-map#593]
### 浏览器版本号

chrome

### Vue 版本号

2.5.2

### 组件库版本号

0.21.19

### 现象描述

```
strokeStyle和fillOpacity不起作用
```

### 完整异常信息

```
源代码里没使用fillOpacity参数
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by Dafrok** [comment]
resolved @0.21.20
