### ISSUE TITLE
BmLabel 如何相对坐标点居中

### ISSUE THREAD

**Issue by huangjianke** [Dafrok/vue-baidu-map#598]
### 浏览器版本号

73.0.3683.103

### Vue 版本号

2.6.6

### 组件库版本号

0.21.19

### 现象描述

```
当文字长度不一样时，如何确保文本相对于坐标点居中对齐
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
文本相对于坐标点居中对齐
```

### 实际输出

```
文本相对于坐标点没有居中对齐
```

**Comment by huangjianke** [comment]
@Dafrok

**Comment by Dafrok** [comment]
百度地图的示例里是自己去控制 offset 的。

> http://lbsyun.baidu.com/jsdemo.htm#c1_14

**Comment by Janka55** [comment]
那vue-baidu用的是bm-label，没法用setStyle咋办，bm-label里的labelStyle设置样式我一设置line-height就报错，求助
