### ISSUE TITLE
是否支持 IconSequence？

### ISSUE THREAD

**Issue by hao-li** [Dafrok/vue-baidu-map#60]
通过折线绘制移动轨迹时想显示各个节点，以便点击查看各点的时间

查看百度API发现貌似提供了 [IconSequence](http://developer.baidu.com/map/reference/index.php?title=Class:%E8%A6%86%E7%9B%96%E7%89%A9%E7%B1%BB/IconSequence) 以支持类似场景

查看文档并搜索代码后未发现相关描述，请问本库是否支持？

**Comment by Dafrok** [comment]
目前没有这个功能，文档里对于这个类的说明不够详细所以跳过了，您有什么好的建议吗？

**Comment by Dafrok** [comment]
http://bbs.lbsyun.baidu.com/forum.php?mod=viewthread&tid=112048&highlight=IconSequence

官网论坛这个帖子的最后一层有一个实现，你如果急的话可以先试试底层实现。我觉得这个东西抽象成声明式坑挺多，你对这里有什么想法吗？

**Comment by hao-li** [comment]
了解，多谢回复。

原本是在找折线（Polyline）是否有控制各节点显示样式及点击事件的属性，
之前文档看的不细，错误的提出了 IconSequence 的问题，抱歉

关于 IconSequence 并没有更好的建议

**Comment by Dafrok** [comment]
好，这个问题我抽空研究一下，如果发现更好的方式会在这里更新。
