### ISSUE TITLE
路书，实时获取坐标数据push进path中时，小车会重置为开始坐标运动

### ISSUE THREAD

**Issue by trowa1234** [Dafrok/vue-baidu-map#600]
### 浏览器版本号

73.0

### Vue 版本号

2.5.22

### 组件库版本号

0.21.20

### 现象描述

```
实时获取坐标数据push进path中时，小车会重置为开始坐标重新运动
```

### 预期输出

```
 当path更新时，小车位置不重置
```

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
