### ISSUE TITLE
使用mapStyle自定义样式后，点聚合功能异常。

### ISSUE THREAD

**Issue by xiaoqiangxxs** [Dafrok/vue-baidu-map#601]
点击聚合图标后不能显示详细的点，需要手动放大才能显示详细点，未使用自定义样式mapStyle的点聚合是正常的。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
