### ISSUE TITLE
ready事件后设置地理位置显示地图

### ISSUE THREAD

**Issue by airzhanglin** [Dafrok/vue-baidu-map#609]
ready回调时间里设置地理位置的时候，marker点能够显示，但是地图显示不了，触发拉动地图才能显示。当直接设置center位置时候就可以显示

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
