### ISSUE TITLE
跟着官网的教程做，<bm-marker>报错

### ISSUE THREAD

**Issue by zhuobinggang** [Dafrok/vue-baidu-map#61]
### 报错信息
[Vue warn]:Unknown custom element: <bm-marker> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

---

不止这一个，其他的<bm-label>，缩放控件也一样。
除了成功显示地图之外别的都干不了。

**Comment by zhuobinggang** [comment]
换了全局的就好了

**Comment by Dafrok** [comment]
和全局不全局没什么关系，推荐你好好看一下文档的这个章节。

> https://cn.vuejs.org/v2/guide/components.html

**Comment by zhuobinggang** [comment]
嗯，谢谢。我现在知道了如果不在全局引用的话，需要自己声明相应的Component，之前用的其他人的组件也是直接在入口js里面引用，所以一直搞不明白这个。

**Comment by zhuobinggang** [comment]
我想问一下，我看到map.vue源码里面写的异步加载是这个样子的：
```js
const $script = document.createElement('script')
global.document.body.appendChild($script)
$script.src = `//api.map.baidu.com/api?v=2.0&ak=${ak}&callback=_initBaiduMap`
```
但是我在vue单文件组件里这样写的时候，VUE会报错说不能异步document.write()，因为这个URL返回的是一个想要往html里写入<script>标签的函数。请问你是怎么解决这个问题的？
下面是我的代码：
```js
var script = document.createElement('script');
script.src = 'http://api.map.baidu.com/api?v=2.0&ak=$MY_KEY&callback=init';
document.body.appendChild(script);
```

**Comment by Dafrok** [comment]
不清楚，单看这两段逻辑是没区别的，你检查下上下文吧。
