### ISSUE TITLE
其他地图的经纬度如何转换成百度的经纬度

### ISSUE THREAD

**Issue by isimply** [Dafrok/vue-baidu-map#612]
请问如何其他地图的经纬度如何转换成百度的经纬度，我在功能里找不到坐标转换这个功能。用axios去调用官方的API又老提示跨域问题

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
