### ISSUE TITLE
地图无法拖动

### ISSUE THREAD

**Issue by Ruleer** [Dafrok/vue-baidu-map#619]
### 浏览器版本号

chrome73.0.3683.103

### Vue 版本号

2.9.6

### 组件库版本号

最新版

### 现象描述

```
地图引入正常，控制台没有错误信息，显示的时候地图无法拖动
```

### 完整异常信息

```
无法显示
```

### 在线示例 / 仓库 URL

https://github.com/Ruleer/campalMap

### 复现用例

```
直接在dev模式下打开网页，地图加载在右边，模块是bmap.vue
```

### 预期输出

```
地图可移动
```

### 实际输出

```
地图无法拖动
```

**Comment by Dafrok** [comment]
上 codesandbox，你的项目跑不起来

**Comment by Ruleer** [comment]
我自己的问题，已经解决啦
