### ISSUE TITLE
平移地图

### ISSUE THREAD

**Issue by yizhigui** [Dafrok/vue-baidu-map#62]
我想调用类似百度地图的：panTo(center: Point, opts: PanOptions)  方法平移地图，但是好像并没有发现该方法存在

**Comment by Dafrok** [comment]
记住你用的是 vue 不是 jQuery 。。。

**Comment by Dafrok** [comment]
你指的平移是平滑移动？

**Comment by yizhigui** [comment]
嗯，对

**Comment by yizhigui** [comment]
不是鼠标变成手型，然后移动，，是通过一个方法直接让地图移动到某一个坐标

**Comment by Dafrok** [comment]
你想要那个动画效果是吗

**Comment by yizhigui** [comment]
动画效果要，地图平移的功能也要，我直接在ready方法里面调用BMap.panTo或者map.panTo都是显示的没有定义panTo方法

**Comment by Dafrok** [comment]
平移地图的功能不就是那个动画吗？

**Comment by yizhigui** [comment]
不是的，动画跟平移是两个功能。

**Comment by Dafrok** [comment]
那平移是什么功能？

**Comment by yizhigui** [comment]
这我怎么说呢，，就是百度地图里面的panTo方法，要不你试试？？

**Comment by Dafrok** [comment]
我知道 panTo 是什么，但是没弄明白你想要什么。你想要的和文档中这个章节的第一个 case 有什么区别吗？
https://dafrok.github.io/vue-baidu-map/#/zh/context-menu/menu

**Comment by yizhigui** [comment]
嗯，，就是这个 。。好吧，，不知道这个叫上下文菜单

**Comment by yizhigui** [comment]
但是我如果不想在上下文菜单中来实现这个功能呢

**Comment by Dafrok** [comment]
照猫画虎

**Comment by Dafrok** [comment]
补充一下，我发现官方的 panTo 是没有动画的，虽然提供了 option 但是没有生效，如果你有需要的话可以用定时器算坐标实时赋值的方式实现一下。

**Comment by yizhigui** [comment]
好的，非常感谢
