### ISSUE TITLE
 c.setMapStyle is not a function  

### ISSUE THREAD

**Issue by troubleIE6** [Dafrok/vue-baidu-map#621]
按照文档的写法
![image](https://user-images.githubusercontent.com/11990352/58073690-ddbe5680-7bd5-11e9-9a07-3052f42259c0.png)
但是在浏览器上面出现   c.setMapStyle is not a function  

![image](https://user-images.githubusercontent.com/11990352/58073725-f595da80-7bd5-11e9-916f-1611a060c6d2.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by wangding123** [comment]
结局了么 我也碰到这样的问题 找了好久

**Comment by wangding123** [comment]
解决了么 我也碰到这样的问题 找了好久
