### ISSUE TITLE
elementUI框架使用dialog加载地图组件在chrome浏览器，滚轮缩放功能不能根据鼠标箭头位置缩放

### ISSUE THREAD

**Issue by wang1052303865** [Dafrok/vue-baidu-map#623]
### 浏览器版本号

 74.0.3729.131（正式版本） （32 位）

### Vue 版本号

2.5.16

### 组件库版本号

0.21.19

### 现象描述

```
elementUI框架使用dialog加载地图组件在chrome浏览器，滚轮缩放功能不能根据鼠标箭头位置缩放
```

### 完整异常信息

```
elementUI框架使用dialog加载地图组件在chrome浏览器，滚轮缩放功能不能根据鼠标箭头位置缩放
```

### 在线示例 / 仓库 URL

暂无

### 复现用例

```
暂无
```

### 预期输出

```
暂无
```

### 实际输出

```
暂无
```

**Comment by wang1052303865** [comment]
https://codepen.io/fengzhentian/pen/pLWdNZ 当前链接用chrome打开 滚动缩放 缩放中心点就偏移状态

**Comment by Dafrok** [comment]
其它 issue 里说过这个问题，是因为模态框 transform 导致 position fixed 的 containing block 发生了变化，JS API 无法正确处理位置，和组件库本身无关

**Comment by chaofan-rensheng** [comment]
@wang1052303865  有没有解决这个问题
