### ISSUE TITLE
Marker组件事件无法触发

### ISSUE THREAD

**Issue by Mrlilili** [Dafrok/vue-baidu-map#624]
### 浏览器版本号

4.0.3729.157 (正式版本) （64 位）

### Vue 版本号

2.6.10

### 组件库版本号

0.21.20

### 现象描述

```
地图的Marker组件相关事件无法正常触发
```

### 完整异常信息

```
无异常信息
```

### 在线示例 / 仓库 URL

https://codesandbox.io/s/vue-template-8tfh6?fontsize=14

### 复现用例

```
https://codesandbox.io/s/vue-template-8tfh6?fontsize=14
```

### 预期输出

```
Marker事件正常触发
```

### 实际输出

```
Marker事件未触发
```

**Comment by xiaohaiH** [comment]
楼主这个问题解决了么

**Comment by xiaohaiH** [comment]
这个问题我是在按需加载的情况下才会出现,  然后组件注册的名称与组件内部的名称不一致, 事件就无法触发

**Comment by Mrlilili** [comment]
@xiaohaiH 没有解决

**Comment by Dafrok** [comment]
最近有点忙，我 review 下

**Comment by Dafrok** [comment]
我知道为什么了，绑定事件的时候会取你对应的 tagName，你把组件名改成 `BmMarker` 就行了。这个我看看能不能优化下

**Comment by Dafrok** [comment]
修复了，请更新 0.21.21 版本

**Comment by xiaohaiH** [comment]
> 修复了，请更新 0.21.21 版本

地图容器组件的名称是 `bm-map`, 事件是 `baidu-map`;

**Comment by Dafrok** [comment]
疏忽了，除了 map、autocomplete 以外还有什么？

**Comment by Dafrok** [comment]
更新了一版，还有遗漏的话发 pr 吧

**Comment by xiaohaiH** [comment]
> 疏忽了，除了 map、autocomplete 以外还有什么？

没有了

**Comment by Dafrok** [comment]
发新版了，更新一下吧
