### ISSUE TITLE
点聚合功能加载特别慢，页面卡死。

### ISSUE THREAD

**Issue by is-nan** [Dafrok/vue-baidu-map#625]
### 浏览器版本号

谷歌版本 73.0.3683.86（正式版本） （64 位）

### Vue 版本号

2.5

### 组件库版本号

0.21.20

### 现象描述

```
点数量到达了3000左右页面卡死，请问有什么办法优化，我看有很多人数说可以修改源码的渲染方式等优化。
```

### 完整异常信息

```
点数量到达了3000左右页面卡死，请问有什么办法优化，我看有很多人数说可以修改源码的渲染方式等优化。
```

### 在线示例 / 仓库 URL

https://github.com/Dafrok/vue-baidu-map

### 复现用例

```
https://github.com/Dafrok/vue-baidu-map
```

### 预期输出

```
https://github.com/Dafrok/vue-baidu-map
```

### 实际输出

```
https://github.com/Dafrok/vue-baidu-map
```

**Comment by Dafrok** [comment]
根据 zoom 情况订制一下海量点吧，点聚合的 marker 实例太多了

**Comment by xwyweitian** [comment]
能写个例子吗

**Comment by littleantsos** [comment]
用mapV更好吧

**Comment by mylooksback** [comment]
大佬解决了么

**Comment by mxdios** [comment]
求指教，大佬解决了吗？

**Comment by is-nan** [comment]
> 求指教，大佬解决了吗？

改成使用原生高德地图了，5-8w点左右不会太卡顿.

**Comment by mxdios** [comment]
> 改成使用原生高德地图了，5-8w点左右不会太卡顿.

关键高德不支持海外地图，换成百度，结果卡死了

**Comment by is-nan** [comment]
> > 改成使用原生高德地图了，5-8w点左右不会太卡顿.
> 
> 关键高德不支持海外地图，换成百度，结果卡死了
海外地图我使用的原生谷歌地图，国内使用的高德.

**Comment by mxdios** [comment]
> 海外地图我使用的原生谷歌地图，国内使用的高德.
感谢回复，我需要一张地图呈现全球点聚合，没法分着显示。
