### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by 714871549** [Dafrok/vue-baidu-map#629]
就是
<baidu-map-comp
      ref="baidu-map-comp"
      class="baidu-map-comp"
      :center="center"
      :zoom="zoom"
      @ready="handler"
      :scroll-wheel-zoom="true"
    >
      <bm-marker
        :position="center"
        :dragging="true"
      ></bm-marker>
    </baidu-map-comp>

代码运行，地图上无法点击其他地点，只有重新刷一次才能点击

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
