### ISSUE TITLE
小弟菜鸡一枚，之前的issue也看了，但是还是真的没明白这个组件的reload方法如何调用呢？

### ISSUE THREAD

**Issue by 99bird** [Dafrok/vue-baidu-map#632]
我现在要写一个触发事件，事件触发后，我要修改地图的center和zoom，但是修改之后百度地图组件不能自动重新渲染，所以我要重新加载一个地图组建，请问，地图组件的reload方法我应该如何调用。非常感谢大佬的不吝指正

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
