### ISSUE TITLE
自定义bm-local-search 中的样式和店家的气泡样式

### ISSUE THREAD

**Issue by ztjy-fe** [Dafrok/vue-baidu-map#636]
![image](https://user-images.githubusercontent.com/36784841/59503202-5dd49500-8ed2-11e9-9e5e-9d0e2161fe73.png)
如图所示  自定义搜索后的列表和 点击列表中的地图中的bm-info-window

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
