### ISSUE TITLE
怎么禁用原生info-window信息，想自定义marker弹出内容

### ISSUE THREAD

**Issue by lsc1021** [Dafrok/vue-baidu-map#637]
![TIM截图20190617153939](https://user-images.githubusercontent.com/27761579/59586800-4f76bb00-9116-11e9-95b1-3c296e3185be.png)
![TIM截图20190617154042](https://user-images.githubusercontent.com/27761579/59586826-5d2c4080-9116-11e9-89ee-bfddcdee66cc.png)
自定义的也写了，但不知道怎么禁用原生的infowindow

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
