### ISSUE TITLE
vue中使用百度地图怎么获取实例BMap

### ISSUE THREAD

**Issue by yangh-fe** [Dafrok/vue-baidu-map#638]
### 浏览器版本号

75.0.3770.90

### Vue 版本号

2.0+

### 组件库版本号

最新

### 现象描述

```
想请教作者一个问题，在vue项目中cdn方式引入百度地图，怎么获取BMap对象
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

https://segmentfault.com/q/1010000019481377?_ea=12999523

### 复现用例

```
无
```

### 预期输出

```
获取BMap实例
```

### 实际输出

```
undefined
```

**Comment by Dafrok** [comment]
关注一下 ready 事件的参数。另外 BMap 不是实例，是核心类
