### ISSUE TITLE
热力图组件

### ISSUE THREAD

**Issue by liekkas** [Dafrok/vue-baidu-map#64]
有计划开发热力图组件么？

**Comment by Dafrok** [comment]
热力图是百度地图的 addon，本 lib 仅限封装
 http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html 中的基础组件。

**Comment by Dafrok** [comment]
如果 addon 开坑，应该会新开一个仓库，到时候会在这里通知你。
