### ISSUE TITLE
地图所有事件不执行

### ISSUE THREAD

**Issue by delete1226** [Dafrok/vue-baidu-map#643]
我的所有地图事件都不执行，是什么原因吗，我只是生成了一个地图，然后就给个点击事件。但是无法回调
template:
<baidu-map class="map" :center="center"  @click="getPoint"></baidu-map>
script:
getPoint: function (e) {
     console.log('点击')
 }

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by xiaohaiH** [comment]
哪个版本的？

**Comment by delete1226** [comment]
版本："vue-baidu-map": "^0.21.21"
然后我改为@click.native是可以获取到。但是getPoint里面去获取经纬度获取不到，不知道是方法不对还是没获取对，我getPoint(e){console.log(e.point)}是undefined,查看官网直接获取getPoint(point){console.log(point)}就没有经纬度lat lng这两个属性我打印overlay也是一样的效果，可以解答一下吗，麻烦了



------------------ 原始邮件 ------------------
发件人: "xiaohai"<notifications@github.com>; 
发送时间: 2019年6月27日(星期四) 晚上8:30
收件人: "Dafrok/vue-baidu-map"<vue-baidu-map@noreply.github.com>; 
抄送: "_Delete、"<452378531@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Dafrok/vue-baidu-map] 地图所有事件不执行 (#643)




哪个版本的？

**Comment by delete1226** [comment]
版本："vue-baidu-map": "^0.21.21"
然后我改为@click.native是可以获取到。但是getPoint里面去获取经纬度获取不到，不知道是方法不对还是没获取对，我getPoint(e){console.log(e.point)}是undefined,查看官网直接获取getPoint(point){console.log(point)}就没有经纬度lat lng这两个属性我打印overlay也是一样的效果，可以解答一下吗，麻烦了 @xiaohaiH

**Comment by xiaohaiH** [comment]
升级下版本，这个问题在 0.21.22 解决了

**Comment by delete1226** [comment]
那我地图还是绑定不了click事件呀，这是怎么回事呢，以前有人出现过这种 情况吗，或者有可能出现这种情况的原因是什么




------------------ 原始邮件 ------------------
发件人: "xiaohai"<notifications@github.com>; 
发送时间: 2019年6月27日(星期四) 晚上8:43
收件人: "Dafrok/vue-baidu-map"<vue-baidu-map@noreply.github.com>; 
抄送: "_Delete、"<452378531@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Dafrok/vue-baidu-map] 地图所有事件不执行 (#643)




native 修饰符是给元素绑定事件，跟地图的事件无关

**Comment by Dafrok** [comment]
#624
