### ISSUE TITLE
点聚合的数据从后台传过来，在显示的时候为什么有延迟，必须动一下地图 或者在请求一次才能出现聚合

### ISSUE THREAD

**Issue by mylooksback** [Dafrok/vue-baidu-map#644]
点聚合的数据从后台传过来，在显示的时候为什么有延迟，必须动一下地图 或者在请求一次才能出现聚合

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
