### ISSUE TITLE
实时更新地图的中心点坐标后，地图的缩放功能失效了

### ISSUE THREAD

**Issue by myf-sky** [Dafrok/vue-baidu-map#645]
要实时显示运行轨迹，并且实时的将运行轨迹的最后一个点设置为地图的中心点坐标，但是在运行过程中地图的缩放功能不起作用了。这个问题要怎么解决？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
