### ISSUE TITLE
通过BmPolyline实现运行轨迹的实时展示，BmPolyline绑定的数组长度过大怎么办

### ISSUE THREAD

**Issue by myf-sky** [Dafrok/vue-baidu-map#648]
[BUG 反馈] 通过BmPolyline实现运行轨迹的实时展示，BmPolyline绑定的数组长度过大怎么办
浏览器版本号
Google 75.0.3770.100

Vue 版本号
2.6.10

组件库版本号
0.21.22

现象描述
由于要通过BmPolyline实现运行轨迹的实时展示，BmPolyline绑定的数组长度受电脑内存的限制，数组长度的话要怎么办？
完整异常信息
控制台无异常
在线示例 / 仓库 URL
无线上仓库

复现用例
无
预期输出
无
实际输出
无

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
