### ISSUE TITLE
路线规划导航点与marker信息窗冲突

### ISSUE THREAD

**Issue by xlguoke** [Dafrok/vue-baidu-map#649]
鼠标触碰marker打开信息窗，当把点添加到路径规划中，生成路线后，触碰marker打开信息窗后，马上就关闭了

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
