### ISSUE TITLE
#微信坐标转换百度地图坐标

### ISSUE THREAD

**Issue by Pawning** [Dafrok/vue-baidu-map#65]
您好，我在开发过程中遇到微信jssdk获取坐标，在百度地图显示存在定位不准确问题，建议大神在api中加入坐标转换。ps：开发过程中，在并不清楚如何在baidu-map组件中的ready回调函数拿到BMap实例（我的处理是<baidu-map @ready="readyMap(BMap,map)">然后再methods的readyMap中调用BMap实例），希望大神可以在baidu-map的实例中加入使用ready回调的例子。

**Comment by Dafrok** [comment]
你要的例子，文档上真的写的很清楚了。。。

**Comment by Dafrok** [comment]
#27 坐标转换的问题已经在这里解释过了
