### ISSUE TITLE
searchcomplete 返回参数问题

### ISSUE THREAD

**Issue by JoeABCDEF** [Dafrok/vue-baidu-map#653]
![Snipaste_2019-07-08_21-25-04](https://user-images.githubusercontent.com/39638510/60813836-1d152680-a1c7-11e9-8797-8d58d6b4e1b4.png)

**你好这个参数 marker 为什么获取不到,其他的都能获取到,难道是方式不一样吗?**

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
