### ISSUE TITLE
鼠标拖动地图或者地图缩放以后，地图上的Marker点消失

### ISSUE THREAD

**Issue by wangjunfeng1991** [Dafrok/vue-baidu-map#658]
鼠标拖动地图或者地图缩放以后，地图上的Marker点消失，请问一下这个大概是什么问题导致的呢？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
