### ISSUE TITLE
是否有点聚合的功能？

### ISSUE THREAD

**Issue by dmlzj** [Dafrok/vue-baidu-map#66]
如题，有这个功能了吗？谢谢！

**Comment by Dafrok** [comment]
本库只封装包含在 http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html 中的 API，addons 请在 ready 事件中调用实例另行实现。

**Comment by dmlzj** [comment]
@Dafrok 
秒回，，谢谢，那就是可以实现了！

**Comment by Dafrok** [comment]
拿到地图实例和核心类基本上什么都可以实现，自行扩展即可。

**Comment by Dafrok** [comment]
点聚合组件已强势插入，这里是 [传送门](https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/markerclusterer)。
