### ISSUE TITLE
点聚合怎么和海量点共用，单纯点聚合在点太多的时候会加载很慢

### ISSUE THREAD

**Issue by Janka55** [Dafrok/vue-baidu-map#660]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by xiaohaiH** [comment]
海量点是基于 canvas 生成的, 两者怎么混用哦,     可以自己 canvas 实现

**Comment by Janka55** [comment]
> 海量点是基于 canvas 生成的, 两者怎么混用哦, 可以自己用 canvas 实现

对耶，我都忘了海量点用的是canvas，谢谢

**Comment by zhang6685979** [comment]
点聚合可以和mapv集成在一起实现海量数据的渲染，将marker转换成点加载到mapv图层就可以了

**Comment by willpengZH** [comment]
@zhang6685979 @Janka55 请问在vue-baidu-map里怎么获取canvas对象?
