### ISSUE TITLE
关于覆盖物和地图事件问题

### ISSUE THREAD

**Issue by sprogjavasprog** [Dafrok/vue-baidu-map#663]
[BUG 反馈] 关于覆盖物和地图事件问题
浏览器版本号

谷歌
Vue 版本号

2.5.17
组件库版本号

0.21.22
现象描述

我在地图上绑定了一个点击事件，当点击时在地图上添加一个点，这个点的覆盖物也有对应的事件，但是当我点击点触发事件时，我发现地图绑定的点击事件也被出发了，有什么处理方法，正常来说应该是只触发点的点击事件的，这样导致了重新打了个点

完整异常信息
<template>
    <div class="mapbox" style="padding-top:100px "> 
        <baidu-map :center="center" :zoom="zoom" :scroll-wheel-zoom="true" @ready="handler" style="height:800px"
                   @click="getClickInfo">   
            <bm-navigation anchor="BMAP_ANCHOR_TOP_RIGHT"></bm-navigation>
               
            <bm-map-type :map-types="['BMAP_NORMAL_MAP', 'BMAP_HYBRID_MAP']" anchor="BMAP_ANCHOR_TOP_LEFT"> 
            </bm-map-type>
             
            <bm-geolocation anchor="BMAP_ANCHOR_BOTTOM_RIGHT" :showAddressBar="true" :autoLocation="true"> 
            </bm-geolocation>
             
            <bm-city-list anchor="BMAP_ANCHOR_TOP_LEFT"></bm-city-list>
            <bm-marker v-for="marker in markers" :key="marker.id" :position="marker.geo" title="11111111" @click="markerClick">
            </bm-marker>
            
        </baidu-map>
    </div>

</template>

在线示例 / 仓库 URL
复现用例

预期输出

实际输出

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
