### ISSUE TITLE
为什么发送请求为https时候 就不会渲染地图

### ISSUE THREAD

**Issue by hufangcao** [Dafrok/vue-baidu-map#665]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by hufangcao** [comment]
为什么发送请求为https的形式就会加载不出来地图 ak请求失败 怎么解决？
