### ISSUE TITLE
<bm-marker animation="BMAP_ANIMATION_BOUNCE"></bm-marker>没有动画效果

### ISSUE THREAD

**Issue by hjsg** [Dafrok/vue-baidu-map#666]
<bm-marker :position="{lng:e.lng,lat:e.lat}" :dragging="false" animation="BMAP_ANIMATION_BOUNCE"></bm-marker>
animation没有动画效果

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
