### ISSUE TITLE
vue build之后在某些机型上无法加载地图

### ISSUE THREAD

**Issue by For-me** [Dafrok/vue-baidu-map#67]
vue2.0 npm run build之后。iphone5s safri下地图没法加载。

**Comment by Dafrok** [comment]
如果用 safari 能正常打开文档，那就检查一下你自己的业务逻辑是不是有问题。

**Comment by For-me** [comment]
同型号，同系统版本，有些又能正常显示。。

**Comment by Dafrok** [comment]
这不重要，你用不成功的机型打开文档，如果成功那就是其它问题，如果不成功你再通过 console 的日志排查一下。

**Comment by For-me** [comment]
刚才试了下。文档也无法访问

**Comment by Dafrok** [comment]
看看 console 和 network 日志异常吧

**Comment by For-me** [comment]
手机上的貌似没法这样调试吧。。

**Comment by Dafrok** [comment]
为什么不能？

**Comment by For-me** [comment]
抛了一个error.html的页面，提示页面不存在_百度搜索

**Comment by For-me** [comment]
console里面报了一个没有使用闭合标签的问题，然后这个没用使用闭合标签的来源是百度那边返回的error.html页面里的

**Comment by Dafrok** [comment]
说明静态资源没请求到，可能是被劫持了也可能是 CDN 抽了。

**Comment by Dafrok** [comment]
俗称网不好，你换个网络环境试试吧。

**Comment by For-me** [comment]
应该不会。我换了4G网络也是不行的

**Comment by Dafrok** [comment]
通过你的描述来判断只可能是这个问题，和 lib 本身无关了。

**Comment by For-me** [comment]
会不会是因为我的地图:position中的数据是动态添加的，当我数据还没有返回回来。地图就已经执行ready方法了。。导致最后实例化的地图map的坐标点为空。引起的渲染异常？如果是，应该如何解决呢？

**Comment by Dafrok** [comment]
不会。你静态资源都 404 了，都到不了渲染这一步……

**Comment by For-me** [comment]
目前为止只在那一台iphone5s的机器上重新了地图无法加载的问题。应该排除网络环境的影响，还会有其他引发这种情况的问题么？

**Comment by Dafrok** [comment]
本地代理

**Comment by witlili** [comment]
cmd 窗口显示：
| ## NPM
 @ ./docs/md lazy ^\.\/.*\.md$
 @ ./docs/routes.js
 @ ./docs/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-serve
r docs/main.js

WARNING in ./docs/md/zh/start-usage.md
Module parse failed: D:\NodeJS\node_modules\npm\vue-baidu-map-master\docs\md\zh\
start-usage.md Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| # 快速上手
|
| ## 使用
 @ ./docs/md lazy ^\.\/.*\.md$
 @ ./docs/routes.js
 @ ./docs/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-serve
r docs/main.js
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 542 kB [entry]
         + 4 hidden modules
webpack: Compiled with warnings.

在windows 7 64bit 上编译没问题，以上是cmd窗口结果。
在浏览器没法显示地图。浏览器标题vue baidu map，页面空白。

看了您说明，修改main.js添加 ，申请了baidu 的key。
import Vue from 'vue'
import BaiduMap from 'vue-baidu-map'

Vue.use(BaiduMap, {
  /* Visit http://lbsyun.baidu.com/apiconsole/key for details about app key. */
  ak: 'YOUR_APP_KEY'
})

 这个是修改 mapview.vue 文件？
 <template lang="pug">
div
</template>

<script>
export default {
  name: 'bm-view'
}
</script>

新手，谢谢不吝赐教。

**Comment by Dafrok** [comment]
提示写的很清楚，`You may need an appropriate loader to handle this file type.`。

另外无关问题请新开 ISSUE。

**Comment by For-me** [comment]
大触有没有秋秋私一个呗。。聊聊技术

**Comment by Dafrok** [comment]
QQ 不怎么上，是给猎头准备的。有相关问题 github 交流，无关问题请移步技术论坛。

**Comment by For-me** [comment]
抽空排查了一下。。与 #24 的错误类型一致。。大佬可以在文档中注明一下，若出现地图无法加载的情况，排查系统版本是否是按照4.4.4以下及Ios8(包含)以下的机器。这两者都是对Symbol的不支持导致的地图无法加载，解决方案就是加入core-js或者babel-polyfill，并且引入到生产环境中。 @Dafrok

**Comment by Dafrok** [comment]
地图组件不依赖 symblo，这个问题是 babel 本身导致的，这是共识。如果出现 polyfill 的问题服务端也不应该抛出 error.html，而是在控制台抛出 `Symble is not a function`，你遇到的应该是两个完全不同的问题。

**Comment by Dafrok** [comment]
地图组件不依赖 symblo，这个问题是 babel 本身导致的，这是共识。如果出现 polyfill 的问题服务端也不应该抛出 error.html，而是在控制台抛出 `Symblo is not a function`，你遇到的应该是两个完全不同的问题。

**Comment by For-me** [comment]
嗯。。踩到坑记住解决了就好。。

**Comment by Jesonhu** [comment]
@Dafrok 打包（npm run build）后 地图页面空白 地址栏提示：
GET file://api.map.baidu.com/api?v=2.0&ak=tEB2z1e0XNrVUs2bka1XwsIoRrlnpp6G&callback=_initBaiduMap net::ERR_FILE_NOT_FOUND
这是怎么回事？

**Comment by Jesonhu** [comment]
@Dafrok 我自己在index.html添加地址然后在打包，现在不报那个错了，但是出现了新问题;
![image](https://user-images.githubusercontent.com/18684575/28254557-670d37e8-6ae0-11e7-8b9a-247eac8adb27.png)
这该如何解决？
