### ISSUE TITLE
没有ak，却可以正常使用，也没有任何提示

### ISSUE THREAD

**Issue by zp1076753393** [Dafrok/vue-baidu-map#672]
### 浏览器版本号

Google Chrome 76.0.3809.100

### Vue 版本号

3.0.1

### 组件库版本号

最新

### 现象描述

```
在组测组件的时候，不输入ak，也能够正常使用
```

### 完整异常信息

```
0
```

### 在线示例 / 仓库 URL

0

### 复现用例

```
0
```

### 预期输出

```
不能使用，会提示百度地图api未注册
```

### 实际输出

```
使用没有任何问题
```

**Comment by Dafrok** [comment]
控制台检查元素 => ctrl+f 搜索 => 输入『https://api.map.baidu.com/getscript?v=2.0&ak=』看搜索结果

**Comment by madaono** [comment]
搜索了ak=undefined功能也能正常使用。这是啥原因？
