### ISSUE TITLE
bm-marker 自定义icon图片重复请求

### ISSUE THREAD

**Issue by lzd358194530** [Dafrok/vue-baidu-map#677]
bm-marker 自定义icon图片，使用 bm-info-window的时候 每次 window 显示和隐藏的时候 icon图片都会重新请求  重新渲染

`
<baidu-map :style="{height}" @ready="onBmReady" :scroll-wheel-zoom="true" v-bind="options">
			<bm-marker
				:position="{lng: 116.404, lat: 39.915}"
				title="123123"
				:icon="{url: 'http://kindergarten0.oss-cn-shanghai.aliyuncs.com/1566526801763%E4%B8%8B%E8%BD%BD.jpg?Expires=1881886801&OSSAccessKeyId=LTAI84levDm2b6Gy&Signature=AvZmsJLsCo4vzE%2BU9lrWCgNNq5U%3D',size: {width: 50, height: 50}}"
				@mouseover="show=true"
				@mouseout="show=false"
			>
				<bm-info-window :show="show" @close="show=false" @open="show=true">我爱北京天安门</bm-info-window>
			</bm-marker>
		</baidu-map>

`

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
