### ISSUE TITLE
聚合点过多，跳转其他页面卡死

### ISSUE THREAD

**Issue by Sshhcc** [Dafrok/vue-baidu-map#678]
页面初始化的时候加载了3000多个聚合点。然后我想浏览其他页面，点击目录，跳转到其他页面时候，就会出现卡死的情况，请问大佬有啥解决办法不？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
