### ISSUE TITLE
Wrong coordinates in map for component <bm-label>

### ISSUE THREAD

**Issue by vvizden** [Dafrok/vue-baidu-map#679]
# Wrong coordinates in map for component `<bm-label>`
##  Issue Description
It shows the image below when the browser refreshes:

![init-map](https://user-images.githubusercontent.com/32644183/63635355-65fc3e00-c694-11e9-9cfa-5f99d3ca2d0f.png)

but, these labels would be re-rendered when the map has been dragged. That likes this:

![trigger-drag](https://user-images.githubusercontent.com/32644183/63635446-4c0f2b00-c695-11e9-97fe-2080384fedb2.png)

After that, it would't be re-rendered when the map is dragged again.

Please help me, thanks!

## vue

```vue
<template>
  <baidu-map
    class="map"
    :center="{ lng: 113.61754708198265, lat: 34.79410888660694 }"
    :zoom="13"
    :scroll-wheel-zoom="true"
    @ready="handleBMapReady"
  >
    <bm-view style="width: 100%; height:200px;flex: 1;"></bm-view>
    <bm-scale anchor="BMAP_ANCHOR_TOP_RIGHT"></bm-scale>
    <bm-label
      v-for="item of data"
      :key="item.id"
      :content="item.index2"
      :position="item"
      :labelStyle="item.labelStyle"
      :offset="{width: -16, height: -32}"
    />
  </baidu-map>
</template>
```

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
