### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by witlili** [Dafrok/vue-baidu-map#68]
OS: windows 7 64bit
C:\Windows\System32>vue -V
2.8.2

C:\Windows\System32>webpack -v
2.2.0

C:\Windows\System32>npm -v
3.10.10

**package.json**
{
  "name": "vue-baidu-map",
  "version": "0.10.7",
  "description": "Baidu Map Component for Vue 2.0",
  "main": "index.js",
  "directories": {
    "doc": "docs"
  },
  "scripts": {
    "build:docs": "webpack -p --config ./build/webpack.docs.config.js",
    "build": "webpack -p --config ./build/webpack.prod.config.js",
    "dev": "webpack-dev-server --content-base docs --config ./build/webpack.docs.config.js --hot --inline",
    "deploy": "npm run build && npm run build:docs",
    "test": "karma start",
    "lint": "eslint --ext .js,.vue src docs build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Dafrok/vue-baidu-map.git"
  },
  "keywords": [
    "vue",
    "baidu-map",
    "bmap",
    "vue-baidu-map",
    "baidu",
    "map"
  ],
  "author": "Dafrok <o.o@mug.dog>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Dafrok/vue-baidu-map/issues"
  },
  "homepage": "https://github.com/Dafrok/vue-baidu-map#readme",
  "devDependencies": {
    "babel-core": "^6.21.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^6.2.10",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-es2015-modules-umd": "^6.24.0",
    "babel-preset-es2015": "^6.18.0",
    "bulma": "^0.3.0",
    "chai": "^4.0.2",
    "css-loader": "^0.26.1",
    "electron-stream": "^5.0.4",
    "eslint": "^3.19.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^2.0.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-node": "^4.2.2",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "file-loader": "^0.10.0",
    "github-markdown-css": "^2.4.1",
    "html-webpack-plugin": "^2.26.0",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-coverage": "^1.1.1",
    "karma-mocha": "^1.3.0",
    "karma-nightmare": "^0.4.8",
    "karma-webpack": "^2.0.3",
    "markdown-loader": "^0.1.7",
    "material-design-icons": "^3.0.1",
    "material-design-lite": "^1.3.0",
    "mocha": "^3.4.2",
    "nightmare": "^2.10.0",
    "prismjs": "^1.6.0",
    "pug": "^2.0.0-beta6",
    "requirejs": "^2.3.3",
    "roboto-fontface": "^0.7.0",
    "style-loader": "^0.13.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "url-loader": "^0.5.7",
    "vue": "^2.1.8",
    "vue-loader": "^10.0.2",
    "vue-markdown-loader": "^0.6.2",
    "vue-router": "^2.1.1",
    "vue-template-compiler": "^2.1.8",
    "webpack": "^2.4.1",
    "webpack-dev-server": "^2.4.4"
  },
  "peerDependencies": {
    "vue": "^2.1.8"
  }
}

谢谢，不知道还需要提供什么？

**Comment by Dafrok** [comment]
请把你的错误信息原封不动的复制粘贴到 google 里，先解决完和本库无关的问题再来提问。
