### ISSUE TITLE
组件`<bm-label>`初次渲染，坐标位置严重偏移

### ISSUE THREAD

**Issue by vvizden** [Dafrok/vue-baidu-map#680]
### 浏览器版本号

版本 78.0.3887.7（正式版本）dev （64 位）

### Vue 版本号

^2.6.10

### 组件库版本号

^0.21.22

### 现象描述

地图初次渲染，或者刷新浏览器，会出现如下效果，

![init-map](https://user-images.githubusercontent.com/32644183/63635355-65fc3e00-c694-11e9-9cfa-5f99d3ca2d0f.png)

但是当拖动一下地图，或者缩放一下，文本标签就会重新渲染，坐标发生了变化，这时是正确的坐标位置：

![trigger-drag](https://user-images.githubusercontent.com/32644183/63635446-4c0f2b00-c695-11e9-97fe-2080384fedb2.png)

再次拖动或者缩放，一切ok，不再出现上述问题。

谢谢Dafrok!

### 完整异常信息

无

### 在线示例 / 仓库 URL

暂无

### 复现用例

```vue
<template>
  <baidu-map
    class="map"
    :center="{ lng: 113.61754708198265, lat: 34.79410888660694 }"
    :zoom="13"
    :scroll-wheel-zoom="true"
    @ready="handleBMapReady"
  >
    <bm-view style="width: 100%; height:200px;flex: 1;"></bm-view>
    <bm-scale anchor="BMAP_ANCHOR_TOP_RIGHT"></bm-scale>
    <bm-label
      v-for="item of labels"
      :key="item.id"
      :content="item.index2"
      :position="item"
      :labelStyle="item.labelStyle"
      :offset="{width: -16, height: -32}"
    />
  </baidu-map>
</template>
```

### 预期输出

初次渲染，就是正确坐标位置

### 实际输出

出现了错误的坐标位置，或者说一开始有严重的偏移

**Comment by nimapier** [comment]
同样的问题，请问有解决方案了吗？

**Comment by vvizden** [comment]
> 同样的问题，请问有解决方案了吗？

太久远了，已经忘了当时怎么处理了，不过提供几种思路：
1. 尝试最新版本，看是否修复了该问题
2. 在组件挂载后，强制执行一下重渲染
3. 放弃使用 vue-baidu-map，基于百度地图 JS SDK 封装一个初始化地图的 Vue 组件，后续对地图做的任何操作直接使用 JS SDK API（推荐）

题外话：如果可以，尽量使用原生 API 自己封装一个最简 Vue 组件，后续各种操作还是基于原生 API 进行，因为原生 API 最稳定，也更灵活，还没有额外的学习成本（可能还包括队友的学习成本），而且你也不用在这留言寻找解决方案。

**Comment by nimapier** [comment]
> > 同样的问题，请问有解决方案了吗？
> 
> 太久远了，已经忘了当时怎么处理了，不过提供几种思路：
> 
> 1. 尝试最新版本，看是否修复了该问题
> 2. 在组件挂载后，强制执行一下重渲染
> 3. 放弃使用 vue-baidu-map，基于百度地图 JS SDK 封装一个初始化地图的 Vue 组件，后续对地图做的任何操作直接使用 JS SDK API（推荐）
> 
> 题外话：如果可以，尽量使用原生 API 自己封装一个最简 Vue 组件，后续各种操作还是基于原生 API 进行，因为原生 API 最稳定，也更灵活，还没有额外的学习成本（可能还包括队友的学习成本），而且你也不用在这留言寻找解决方案。

感谢耐心回复，目前我的解决方式也是思路二的方向，重新封装的成本还是有点过高了。
留言主要是想蹲一下有没有更优雅的方法以及出现这种现象的具体原因（目前排查下来可能和我所使用的离线api版本有关，并不是vue-baidu-map本身的问题）。
最后再次感谢你的耐心回复和建议~

**Comment by vvizden** [comment]
> > > 同样的问题，请问有解决方案了吗？
> > 
> > 
> > 太久远了，已经忘了当时怎么处理了，不过提供几种思路：
> > 
> > 1. 尝试最新版本，看是否修复了该问题
> > 2. 在组件挂载后，强制执行一下重渲染
> > 3. 放弃使用 vue-baidu-map，基于百度地图 JS SDK 封装一个初始化地图的 Vue 组件，后续对地图做的任何操作直接使用 JS SDK API（推荐）
> > 
> > 题外话：如果可以，尽量使用原生 API 自己封装一个最简 Vue 组件，后续各种操作还是基于原生 API 进行，因为原生 API 最稳定，也更灵活，还没有额外的学习成本（可能还包括队友的学习成本），而且你也不用在这留言寻找解决方案。
> 
> 感谢耐心回复，目前我的解决方式也是思路二的方向，重新封装的成本还是有点过高了。 留言主要是想蹲一下有没有更优雅的方法以及出现这种现象的具体原因（目前排查下来可能和我所使用的离线api版本有关，并不是vue-baidu-map本身的问题）。 最后再次感谢你的耐心回复和建议~

重新封装的成本取决于你想封装到什么程度，如果是 vue-baidu-map 这种规模的组件化，成本的确很大，如果只是简单的把百度地图 JS SDK 接入到 Vue 体系还是很简单的，使用的时候仅查阅百度 JS SDK 的 API 文档就好。像地图，图表和其他的库，市面上也会有相当多的 Vue 或 React 化封装，但在实际使用的时候，坑是一个接一个，遇到问题你可能会像今天这样花很多时间，一顿操作排查下来，却还是不确定是百度地图 JS SDK 的问题，还是中间组件化库的问题，你辗转 google，github issues，甚至给 lib owner 发邮件，也未必得到很好的解决方案，这个事情就像我们的网络，中间增加一个中间节点，不可控的因素就越多，遇到问题排查的成本也越大，而且市面上类似库的质量良莠不齐。
