### ISSUE TITLE
有没有给多个点添加信息窗口 这个的demo

### ISSUE THREAD

**Issue by hahazqa** [Dafrok/vue-baidu-map#683]
<bm-marker   @click="show" v-for="(item, index) in data.MapList" :key="index" :position="{lng: item.GPS_Y, lat: item.GPS_X}" :dragging="false" animation="BMAP_ANIMATION_BOUNCE">
        <bm-info-window :position="{lng:item.GPS_Y, lat: item.GPS_X}" :title="'<p>用户信息：'+item.TrueName+'</p>'+'<p>手机号：'+item.MobilePhone+'</p>'" :show="infoWindow.show" @close="infoWindowClose" @open="infoWindowOpen">
          <p v-text="infoWindow.contents"></p>
        </bm-info-window>
      </bm-marker>

这样写总渲染最后一个的坐标值

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
