### ISSUE TITLE
可否支持关键字输入精确到门牌号

### ISSUE THREAD

**Issue by zhangDlufei** [Dafrok/vue-baidu-map#686]
http://lbsyun.baidu.com/jsdemo.htm#a6_2这个链接的demo关键字搜出来只有地址，没有门牌号。正常搜索出某一条搜索是“北京市xxx地方”，希望搜索出来旁边会跟着一排小字，比如“北京市xxx地方 北京字xxx号（小字详细到门牌号的地址）”

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
