### ISSUE TITLE
多边形覆盖物启用编辑,如何删除多边形的某个角点

### ISSUE THREAD

**Issue by EmperorAtlantis** [Dafrok/vue-baidu-map#693]
当多边形覆盖我启用编辑时,我可以通过移动某条边的中点来增加角,但我无法删除这个角,我期望右键某个点选择删除事件来删除这个点,应该如何做呢.

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
