### ISSUE TITLE
marker能否能支持绑定visiable属性，实现图标的显示和隐藏。

### ISSUE THREAD

**Issue by wangquan06** [Dafrok/vue-baidu-map#694]
项目中大数据量marker（几百个），不使用visiable属性，显示和隐藏图层的效率很低，很慢。请帮助解决下。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
