### ISSUE TITLE
bm-marker是否能支持绑定visiable属性，实现图标显示和隐藏。

### ISSUE THREAD

**Issue by wangquan06** [Dafrok/vue-baidu-map#695]
[BUG 反馈] 地区检索
浏览器版本号
75.0.3770.100

Vue 版本号
vue2

组件库版本号
0.21.22

现象描述
项目中大数据量marker（几百个），不使用visiable属性，显示和隐藏图层的效率很低，很慢。请帮助解决下。
完整异常信息
1
在线示例 / 仓库 URL
1

复现用例
1
预期输出
1
实际输出
1

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
