### ISSUE TITLE
多个点的坐标相同，只能看到一个点，其他点都被覆盖

### ISSUE THREAD

**Issue by siyuedeqinian** [Dafrok/vue-baidu-map#697]
多个点的坐标相同，只能看到一个点，其他点都被覆盖，点击不到下边的其他点，怎么解决

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
