### ISSUE TITLE
marker 标签的 icon 可以替换么

### ISSUE THREAD

**Issue by cm060210216** [Dafrok/vue-baidu-map#7]
marker icon 如何配置，应该传入一个 BMap.Icon,  只传配置参数进去，无法实现icon。

**Comment by Dafrok** [comment]
理论上可以，Show your code

**Comment by Dafrok** [comment]
@cm060210216 确实有 bug，0.1.1 版已经修复，文档已更新示例供参考：

> https://dafrok.github.io/vue-baidu-map/#/overlay/marker
