### ISSUE TITLE
[Bug Report]在移动端文字模糊

### ISSUE THREAD

**Issue by hfq-pengyuanyuan** [Dafrok/vue-baidu-map#70]
Vue version

2.3.4

android/ios 移动端浏览器

vuev-baidu-map version

0.10.7

Steps to reproduce
在移动端文字非常模糊

image
![image](https://user-images.githubusercontent.com/27800458/27366286-b49701ba-5677-11e7-8df5-3f3c27ce930f.png)

What is Expected?
希望文字不模糊

**Comment by Dafrok** [comment]
1. 用手机打开 https://dafrok.github.io/vue-baidu-map/#/zh/start/usage 这个页面，拉到最底下，看看模不模糊。
2. 用手机打开 http://lbsyun.baidu.com/jsdemo.htm#a1_2 看最右边，看看模不模糊。

- 如果 1 / 2 都不模糊，请关掉这个 issue ，然后认真检查自己代码中的问题。
- 如果 1 / 2 都模糊，请关掉这个 issue，然后通过 [ 百度地图官方社区](http://bbs.lbsyun.baidu.com/forum.php) 反馈问题。
- 如果 1 模糊而 2 不模糊，请在 [codepen](http://bbs.lbsyun.baidu.com/forum.php) 中写一个简单的复现用例，并提供出现问题的浏览器信息。

**Comment by hfq-pengyuanyuan** [comment]
谢谢，已找到问题的原因，high-resolution的值为false时，会出现文字模糊
