### ISSUE TITLE
vue-baidu-map不兼容ie

### ISSUE THREAD

**Issue by lichuntao1996** [Dafrok/vue-baidu-map#700]
尝试安装了babel-polyfill转化，依然解决不了。
![image](https://user-images.githubusercontent.com/42344623/66696361-f7d01100-ecfd-11e9-85f7-8594a75f159b.png)

尝试安装es6-promise，解决promise问题，然鹅并没有解决。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
