### ISSUE TITLE
在element-ui中使用会报错

### ISSUE THREAD

**Issue by yousiedu** [Dafrok/vue-baidu-map#702]
在element-ui 中使用vue-baidu-map 地图页面会显示灰色 console中报
`A cookie associated with a cross-site resource at http://tieba.baidu.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`
的警告

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by ifredom** [comment]
> 在element-ui 中使用vue-baidu-map 地图页面会显示灰色 console中报
> `A cookie associated with a cross-site resource at http://tieba.baidu.com/ was set without the `SameSite`attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with`SameSite=None`and`Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`
> 的警告

解决了吗，怎么解决的？

**Comment by xiaosatufu** [comment]
解决了吗，怎么解决的？
