### ISSUE TITLE
bm-polyline上怎么添加百度地图中js的api中的IconSequence

### ISSUE THREAD

**Issue by zhangyunsheng94** [Dafrok/vue-baidu-map#704]
bm-polyline上怎么添加百度地图中js的api中的IconSequence

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by zhangyunsheng94** [comment]
- bm-polyline上怎么添加百度地图中js的api中的IconSequence
