### ISSUE TITLE
配合vuex下bm-marker能正常渲染，但bm-info-window渲染出错

### ISSUE THREAD

**Issue by loopArray** [Dafrok/vue-baidu-map#71]
```pug
 baidu-map(class="baidu-map", :center="center", :zoom="zoom", :scroll-wheel-zoom="true", @ready="onBaiduMapReady")
    bm-marker(v-for="item in List", :key="item.id", :position="{lng: item.lon, lat: item.lat}")
        bm-info-window(:position="{lng: item.lon, lat: item.lat}", :show="true") {{item.name}}
```
```
data(): {
    return {
        List: {
            return this.$store.state.List;
        }
    }
}

......

// 设置视野范围
onBaiduMapReady(baiduMap) {
        const { BMap, map } = baiduMap;

        if (this.List.length) {
            let baiduMapPoints = this.List.map(plant => {
                return {
                    lng: parseFloat(plant.lon),
                    lat: parseFloat(plant.lat)
                };
            });
            map.setViewport(baiduMapPoints);
        }
    }
```
无任何报错，但是有渲染出错的页面
![0](https://user-images.githubusercontent.com/7822744/27393808-d7bbac62-56dc-11e7-9729-17ee635f6852.png)

搞了一个晚上没搞定这个 bm-info-window

**Comment by Dafrok** [comment]
没看懂，能在 codepen 上写一个复现用例吗？

**Comment by loopArray** [comment]
看那个截图左下角，bm-info-window没有正常显示，bm-marker在地图里显示了

**Comment by Dafrok** [comment]
你确定是因为用了vuex引起的吗？

**Comment by Dafrok** [comment]
虽然还没看出原因，但是我已经在你代码里发现两处错误，info window作为marker的子组件时不需要声明 position，并且百度地图的info window只支持同时显示一个，你全都赋值为true只会显示最后一个。

**Comment by loopArray** [comment]
不确定是是不是vuex的原因，但是这些数据是异步加载的然后从vuex获取的，按理说bm-marker都能正常标记出来了，bm-info-window也应该能正常显示呀，现在看是没有css样式，也没有在地图容器里，跑到外面来了。
只有我加一个静态数据时是正常的
```
 baidu-map(class="baidu-map", :center="center", :zoom="zoom", :scroll-wheel-zoom="true", @ready="onBaiduMapReady")
    bm-marker(v-for="item in List", :key="item.id", :position="{lng: item.lon, lat: item.lat}")
    bm-info-window(:position="{lng:103.388611, lat: 35.563611}", :show="true") 测试百度地图点坐标
```
但是这样的话数据只能写死，不从item里获取了能正常显示，所以我还是觉得应该是数据动态加载的问题，但是bm-marker又能正常显示，不知道问题在哪了？
设置position是以为需要设置才能在地图容器里显示，设置为true也只是测试什么原因。代码我再改下试试。

**Comment by Dafrok** [comment]
写了一个在线演示，也是异步载的坐标点集合，但是复现不了你的问题。你对比一下有哪里不一样吧。

> https://codepen.io/Dafrok/pen/bRVQMv?editors=1010

**Comment by loopArray** [comment]
我现在测的有2中情况会出现这样的问题，都和数据有关，
```
{center: {lng: 116.410, lat: 39.920}, text: 'A'},
{center: {lng: 116.400, lat: 39.910}, text: 'B'},
{center: {lng: 116.410, lat: 39.910}, text: 'C'},
{center: {lng: 116.400, lat: 39.920}, text: 'D'}
```
当每个数据里都没有标示显隐的数据时使用全局的show: false的时候
还一个是像我那样的情况，也是返回的数据没有show字段，我用map函数给增加了一个
```
[
  {center: {lng: 116.410, lat: 39.920}, text: 'A'},
  {center: {lng: 116.400, lat: 39.910}, text: 'B'},
  {center: {lng: 116.410, lat: 39.910}, text: 'C'},
  {center: {lng: 116.400, lat: 39.920}, text: 'D'}
].map(point => {
  return {
    ...point,
    show: false
  }
)
```
都不会正常显示bm-info-window
![qq 20170622111114](https://user-images.githubusercontent.com/7822744/27416008-41083720-573d-11e7-86cc-5decf5082940.png)
附上和我的很相近的例子：
[https://codepen.io/anon/pen/BZZWwb?editors=1010](https://codepen.io/anon/pen/BZZWwb?editors=1010)

**Comment by Dafrok** [comment]
你的 case 我打开之后不停的刷新，看不了，另外所有的 infoWindow 共享一个 show 属性是错误的用法。

**Comment by loopArray** [comment]
好吧，终于搞明白了，应该是什么问题都没有，看图就知道了
![qq 20170622125928](https://user-images.githubusercontent.com/7822744/27417971-b0ca6792-574a-11e7-826d-fb8096f413d8.png)
还是你给的那个例子，这些div是一直存在的，只不过触发点击事件的时候才会变成map的一部分，所以我一直怀疑自己用的不对才导致出了问题，我用样式隐藏一下就OK了。

还有上个例子我打开是正常的，但是确实写的有问题
应该用 `Vue.set(point, 'show', false);` 不应该直接添加一个`show`属性。学艺不精，见笑了。

**Comment by Dafrok** [comment]
我看懂了，你说的这个算是个 bug，应该把这个 div 在初始化的时候就隐藏掉。稍后我看看这里好不好修，如果快的话一会儿会再发一个版本。

**Comment by Dafrok** [comment]
0.10.8 已发布，修复了 info-winodw 组件在某些场景下溢出视图的问题。
