### ISSUE TITLE
地图双指缩放时不是从双指中间变化的有没有解决方法啊？

### ISSUE THREAD

**Issue by yaogengzhu** [Dafrok/vue-baidu-map#711]
地图双指缩放时不是从双指中间变化的有没有解决方法啊？

无论怎么弄，双指放大，不是从中间变化

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
