### ISSUE TITLE
请求支持百度地图JSSDK v3.0

### ISSUE THREAD

**Issue by macnie** [Dafrok/vue-baidu-map#715]
目前的vue-baidu-map是写死JSSDK 2.0版本的，百度 3.0对自定义样式支持更好。请求更新一下，增加对百度SDK的3.0支持。最好支持自定义版本

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
