### ISSUE TITLE
地图检索BmLocalSearch中searchcomplete事件返回结果是否有变更

### ISSUE THREAD

**Issue by Heruisheng** [Dafrok/vue-baidu-map#718]
浏览器版本号
Chrome 版本 78.0.3904.97 64位

Vue 版本号
2.5.2

组件库版本号
0.21.19

现象描述
地图检索BmLocalSearch中searchcomplete事件返回结果从Ar变为Br 请确定是否有变更
![image](https://user-images.githubusercontent.com/24835193/68840881-83bec980-06fe-11ea-8a1a-ea16e72d7891.png)

完整异常信息

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
