### ISSUE TITLE
地图检索BmLocalSearch中searchcomplete事件返回结果是有变更

### ISSUE THREAD

**Issue by Heruisheng** [Dafrok/vue-baidu-map#719]
浏览器版本号
Chrome 版本 78.0.3904.97 64位

Vue 版本号
2.5.2

组件库版本号
0.21.19

现象描述
地图检索BmLocalSearch中searchcomplete事件返回结果从Ar变为Br 请确定是否有变更
![微信截图_20191114165133](https://user-images.githubusercontent.com/24835193/68841178-165f6880-06ff-11ea-83d5-7944f4da84fd.png)

在线示例 / 仓库 URL
项目未上线

复现用例
无
预期输出
无
实际输出
无

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
