### ISSUE TITLE
如何解决 路线规划的 闪烁问题

### ISSUE THREAD

**Issue by Orialian** [Dafrok/vue-baidu-map#724]
[BUG 反馈] 如何解决 路线规划的 闪烁问题
浏览器版本号
谷歌 75.0.3770.142

Vue 版本号
2.6.10

组件库版本号
0.21.22

现象描述
1：在使用 驾车规划时， 需要实时更新起止点的坐标，然而坐标更新则意味着地图重绘，所以起止点中间的路线也会更新，此时路线会出现闪烁的情况，而且在polylinesset的回调中，如果我重设路线的颜色，那么路线还会出现两种颜色，1种是默认的蓝色透明的，另1种是自定义的颜色。请问如何在起止点更新的情况下不让规划的路线出现这种闪烁的情况。
2：此外在使用中会频繁出现  Uncaught TypeError: Cannot read property 'apply' of undefined  这个错误， 特别是当应用进入后台的时候。
完整异常信息
Uncaught TypeError: Cannot read property 'apply' of undefined
    at c (eval at CZ (getscript?v=2.0&ak=t2jUoVkKPPUY3zI2peMuApXT&services=&t=20191112103629:1), <anonymous>:1:1712)
    at eval (eval at CZ (getscript?v=2.0&ak=t2jUoVkKPPUY3zI2peMuApXT&services=&t=20191112103629:1), <anonymous>:1:2340)
在线示例 / 仓库 URL
无

复现用例
<baidu-map
      class="map"
      :center="center"
      :zoom="zoom"
      :ak="key"
      @ready="initPosition"
    >
      <bm-driving
        :start="c"
        :end="isA?  a: b"
        policy="BMAP_DRIVING_POLICY_LEAST_DISTANCE"
        @searchcomplete="handleSearchComplete"
        @markersset="handlerMark"
        @polylinesset="handlerPolyline"
        :auto-viewport="autoViewport"
        :panel="false"
        :selectFirstResult="true"
      ></bm-driving>
      <bm-marker :position="a" v-if="!isA" :icon="aIcon" ></bm-marker>
      <bm-marker :position="b" :icon="bIcon" ></bm-marker>
      <bm-marker :position="c" :icon="cIcon" ></bm-marker>
    </baidu-map>

mounted() {
   this.timer = setInterval(() => {
      this.getPosition();
    }, 5000);
}

// 初始化地图和定位
    initPosition({ BMap, map }) {
      let _this = this;
      this.map = map;
      this.BMap = BMap;
      this.geolocation = !_this.geolocation && new BMap.Geolocation();
      // 开启SDK辅助定位
      _this.geolocation.enableSDKLocation();
      _this.geolocation.getCurrentPosition(function(r) {
        if (this.getStatus() === 0) {
          _this.center = r.address.city;
          let role = _this.$store.state.role;
          if (role !== 'd') {
            _this[role] = r.point;
          }
          _this.sendPosition(r.point);
        }
      });
    },
// 获取当前定位
    getPosition() {
      if (!this.geolocation) {
        return false;
      }
      // if (this.$store.state.role === 'c') {
      //   let point = this.c;
      //   point.lng = point.lng - 0 + 0.001;
      //   point.lat = point.lat - 0 + 0.001;
      //   this.sendPosition(point);
      // } else {
      let _this = this;
      _this.geolocation.enableSDKLocation();
      _this.geolocation.getCurrentPosition(function(r) {
        if (this.getStatus() === 0) {
          _this.sendPosition(r.point);
        }
      });
      _this.clearIFrame = setTimeout(() => {
        let iframe = document.querySelector('iframe:last-of-type');
        iframe && iframe.remove();
        clearTimeout(_this.clearIFrame);
      }, 300);
      // }
    },
// 起止点
    handlerMark(routes) {
      if (!this.BMap || !this.map) {
        return false;
      }
      let len = routes.length;
      this.map.removeOverlay(routes[0].marker);
      this.map.removeOverlay(routes[len - 1].marker);
      for (let i = 1; i < len - 1; i++) {
        let mm = routes[i].Om;
        this.map.removeOverlay(mm);
      }
    },
    // 规划的路线
    handlerPolyline(routes) {
      if (!this.geolocation) {
        return false;
      }
    // 重设路线的颜色和透明度
      for (let i = 0; i < routes.length; i++) {
        let polyline = routes[i].getPolyline();
        polyline.setStrokeWeight(4);
        polyline.setStrokeColor('#24AB72');
        polyline.setStrokeOpacity(0.7);
      }
    },
预期输出
0
实际输出
0

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
