### ISSUE TITLE
为地图添加信息label的时候，有没有数据抽希的接口呢

### ISSUE THREAD

**Issue by shencyber** [Dafrok/vue-baidu-map#73]
为轨迹添加label的时候 ，轨迹上的点太多，导致label加载卡死，不知道有没有实现数据抽希这一块的功能呢

**Comment by Dafrok** [comment]
数据层的问题交给 Model 层去解决，抽稀可以通过 computed 来实现。vue 本身就是用于处理视图逻辑的框架，所以组件库也只处理视图逻辑。
