### ISSUE TITLE
win10 edge浏览器 版本号Microsoft Edge 38.14393.2068.0

### ISSUE THREAD

**Issue by seu-zhang** [Dafrok/vue-baidu-map#733]
你在 edge浏览器上看看，点击的位置，跟你生成的折线位置不一样，是错乱的

复现用例如下：
https://codepen.io/Dafrok/pen/PQYNYb?editors=1010

_Originally posted by @Dafrok in https://github.com/Dafrok/vue-baidu-map/issues/264#issuecomment-361001460_

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
