### ISSUE TITLE
怎样获取到地图中的覆盖物dom

### ISSUE THREAD

**Issue by vaef** [Dafrok/vue-baidu-map#735]
希望判断点是否在地图中的圆形覆盖物中，怎样获取地图中的圆形覆盖物dom对象？用普通的document.querySelector 获取不到

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
