### ISSUE TITLE
第一次进入可加载数据，返回后点击其他数据加载的还是第一次的位置，需要页面刷新后才会改变位置

### ISSUE THREAD

**Issue by Leon0810** [Dafrok/vue-baidu-map#737]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by The-five-stooges** [comment]
遇到同样的问题，地图需要移动一下才会刷新点的位置

**Comment by Wizzercn** [comment]
@The-five-stooges 请问解决了么？

**Comment by The-five-stooges** [comment]
加一个延迟解决 @Wizzercn

**Comment by Wizzercn** [comment]
@The-five-stooges 感谢回复，弃坑，使用原生的了~
