### ISSUE TITLE
marker 聚合

### ISSUE THREAD

**Issue by shencyber** [Dafrok/vue-baidu-map#74]
请问BMMarker是否实现了百度地图的markerClusterer，用于点聚合

**Comment by Dafrok** [comment]
点聚合是百度地图的第一方插件，vue-baidu-map 组件库仅对百度地图 JS API 进行封装。如有需要，请在 ready 事件中进行插件的逻辑处理。
在后续版本中会考虑加入对用户的封装插件组件的能力。

**Comment by Dafrok** [comment]
点聚合组件已强势插入，这里是 [传送门](https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/markerclusterer)。
