### ISSUE TITLE
当页面存在滚动条时，滑动鼠标滑轮，地图缩放出现偏移

### ISSUE THREAD

**Issue by ShaShengWan-suma** [Dafrok/vue-baidu-map#744]
需要在表单中放置一个地图，通过地图中心点所在的位置动态获取经纬度。
表单通过点击按钮弹出dialog，由于表单内容较多，有滚动条，而地图在表单的最后一项，滚动条已经滚动到页面的底部，此时在地图中滚动滚轮，地图缩放中心点会出现偏移。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by nnnnnnil** [comment]
> 需要在表单中放置一个地图，通过地图中心点所在的位置动态获取经纬度。
> 表单通过点击按钮弹出dialog，由于表单内容较多，有滚动条，而地图在表单的最后一项，滚动条已经滚动到页面的底部，此时在地图中滚动滚轮，地图缩放中心点会出现偏移。

兄弟，你能说说解决方法吗？
