### ISSUE TITLE
zoom为1无法显示完整的世界范围地图

### ISSUE THREAD

**Issue by wang4978** [Dafrok/vue-baidu-map#746]
[BUG 反馈] zoom为1无法显示完整的世界范围地图
浏览器版本号
Chrome 版本 79.0.3945.88（正式版本） （64 位）

Vue 版本号
3.9.3

组件库版本号
0.21.22

现象描述
zoom为1无法显示完整的世界范围地图，实际为zoom为4的地图
完整异常信息
zoom为1无法显示完整的世界范围地图，实际为zoom为4的地图
在线示例 / 仓库 URL
复现用例

预期输出

实际输出

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
