### ISSUE TITLE
CDN引入异常

### ISSUE THREAD

**Issue by liump** [Dafrok/vue-baidu-map#750]
### 浏览器版本号

78.0.3904.97

### Vue 版本号

2.x

### 组件库版本号

null

### 现象描述

```
CDN地址异常,无法引入导致项目无法运行
```

### 完整异常信息

```
CDN地址异常,无法引入导致项目无法运行,改用npm包正常使用.
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
无
```

### 预期输出

```
无
```

### 实际输出

```
无
```

**Comment by lance-yi** [comment]
同样的问题，请楼主及时跟新一下cdn资源，我暂时找到一个，https://cdn.jsdelivr.net/npm/vue-baidu-map@0.21.22/index.min.js
