### ISSUE TITLE
polygon加入绘制和编辑功能会报错

### ISSUE THREAD

**Issue by cltest** [Dafrok/vue-baidu-map#755]
<template>
  <div>
    <baidu-map
      :center="mapConfig.center"
      :zoom="mapConfig.zoom"
      :map-click="false"
      @ready="handler"
      @mousemove="syncPolygon"
      @click="paintPolygon"
      @rightclick="newPolygon">
      <bm-polygon :path="polygon.paths" stroke-color="blue" :stroke-opacity="0.5" :stroke-weight="2" :editing="true" @lineupdate="updatePolygonPath"/>
      <bm-control v-if="editable">
        <a-button type="primary" size="small" class="m-r-15" @click="toggle('polygon')">{{ polygon.editing ? '停止绘制' : '开始绘制' }}</a-button>
        <a-button type="primary" size="small" class="m-r-15" @click="clearMap">清除</a-button>
        <a-input size="small" v-model="mapConfig.keyword" placeholder="关键词搜索" style="width: 150px"></a-input>
      </bm-control>
      <bm-view class="map-area"></bm-view>
      <bm-local-search :keyword="mapConfig.keyword" :auto-viewport="true"></bm-local-search>
    </baidu-map>
  </div>
</template>

<script>
export default {
  props: {
    area: String,
    editable: Boolean
  },
  data () {
    return {
      mapConfig: {
        keyword: '',
        center: { lng: 116.404, lat: 39.915 },
        zoom: 15,
        mapStyle: {
          styleJson: [
            {
              featureType: 'all',
              elementType: 'geometry',
              stylers: {
                hue: '#007fff',
                saturation: 89
              }
            },
            {
              featureType: 'water',
              elementType: 'all',
              stylers: {
                color: '#ffffff'
              }
            }
          ],
          style: 'grayscale'
        }
      },
      polygon: {
        editing: false,
        paths: []
      },
      currentCenter: undefined,
      currentArea: undefined,
      BMap: undefined,
      Map: undefined
    }
  },
  methods: {
    getZoom(maxLng, minLng, maxLat, minLat, map, BMap) {
      const zoom = ["50","100","200","500","1000","2000","5000","10000","20000","25000","50000","100000","200000","500000","1000000","2000000"] //级别18到3
      const pointA = new BMap.Point(maxLng, maxLat)
      const pointB = new BMap.Point(minLng, minLat)
      const distance = Math.abs(map.getDistance(pointA, pointB).toFixed(1))
      for (let i = 0, zoomLen = zoom.length; i < zoomLen; i++) {
        if (zoom[i] - distance > 0) {
          return 18 - i + 2
        }
      }
    },
    getAreaCenter(area) {
      if (!area.length) return
      let lng = 0,
        lat = 0,
        len = area.length
      area.forEach(e => {
        lng += e.lng
        lat += e.lat
      })
      return {
        lng: (lng / len).toFixed(6) || 116.404,
        lat: (lat / len).toFixed(6) || 39.915
      }
    },
    getAddress() {
      this.currentCenter = this.map.getCenter()
      const gc = new this.BMap.Geocoder()
      return new Promise((resolve, reject) => {
        gc.getLocation(this.currentCenter, (result) => {
          const addr = { ...result.addressComponents }
          this.currentArea = `${addr.province}${addr.city}${addr.district}`
          if (addr.province === addr.city) {
            this.currentArea = `${addr.city}${addr.district}`
          }
          if (this.currentArea) {
            resolve(this.currentArea)
          } else {
            reject()
          }
        })
      })
    },
    handler({ BMap, map }) {
      this.polygon.paths = this.area ? JSON.parse(this.area) : [
        {lng: 116.412732, lat: 39.911707},
        {lng: 116.39455, lat: 39.910932},
        {lng: 116.403461, lat: 39.921336}
      ]
      this.BMap = BMap
      this.map = map
      map.enableScrollWheelZoom(true)
      map.setMapStyle({ style: 'grayscale' })
      if (!this.area) return
      const { paths } = this.polygon
      const len = paths.length
      this.mapConfig.center = { ...this.getAreaCenter(paths) }
      this.mapConfig.zoom = this.getZoom(
        paths[0].lng,
        paths[parseInt(len / 2)].lng,
        paths[0].lat,
        paths[parseInt(len / 2)].lat,
        map,
        BMap
      )
    },
    updatePolygonPath (e) {
      this.polygon.paths = e.target.getPath()
    },
    addPolygonPoint () {
      this.polygon.paths.push({lng: 116.404, lat: 39.915})
    },
    toggle(name) {
      this[name].editing = !this[name].editing
    },
    clearMap() {
      this.polygon.paths = []
    },
    syncPolygon(e) {
      if (!this.polygon.editing) return
      const {paths} = this.polygon
      if (!paths.length) return
      if (paths.length === 1) {
        paths.push(e.point)
      }
      this.$set(paths, paths.length - 1, e.point)
    },
    paintPolygon(e) {
      if (!this.polygon.editing) {
        return
      }
      const {paths} = this.polygon
      paths.push(e.point)
    },
    newPolygon(e) {
      if (!this.polygon.editing) {
        return
      }
      const {paths} = this.polygon
      paths.pop()
      this.polygon.editing = false
    },
  }
}
</script>

<style lang="stylus">
.map-area
  height 500px;
.BMap_cpyCtrl
  display none
.anchorBL
  display none
.m-r-15 
  margin-right 15px
</style>

----------------------------代码如上，报错如下-------------------------------
Uncaught TypeError: Cannot read property 'R' of null
    at HTMLDocument.hj (eval at CZ (getscript?v=2.0&ak=DlOfILBde5R4gCHi5GGhv6wpOknzBIc4&services=&t=20200103103842:1), <anonymous>:1:1781)

-----------------------------------------------------------------------------------
依赖版本如下
"vue": "^2.6.10"
"vue-baidu-map": "^0.21.22"

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
