### ISSUE TITLE
bm-point-collection 组件能否取得点的其他属性信息

### ISSUE THREAD

**Issue by wuxiongliu1** [Dafrok/vue-baidu-map#757]
bm-point-collection 组件能否取得点的其他属性信息。现在在click方法里只能拿到点的经纬度，用户自定义的属性是不能设置进去并获取出来的吗？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
