### ISSUE TITLE
InternalError: "too much recursion"

### ISSUE THREAD

**Issue by taoqi0813** [Dafrok/vue-baidu-map#759]
按照文档的demo进行书写
![图片](https://user-images.githubusercontent.com/50473098/74717109-c1d20900-526a-11ea-986a-f312e2e9e62d.png)
直接报错了
![图片](https://user-images.githubusercontent.com/50473098/74717141-d1e9e880-526a-11ea-862f-71db9c1528ef.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by wangxinzhi** [comment]
驼峰命名的问题，把组件名称BaiduMap，换成baiduMap，试试
