### ISSUE TITLE
手机端不能手动选择指定的地理位置

### ISSUE THREAD

**Issue by chenyinhuan** [Dafrok/vue-baidu-map#76]
pc端可以选择，并且有返回值，手机端点击后没有效果

**Comment by Dafrok** [comment]
描述不够详细，请在 [Codepen](http://codepen.io/) 实现一个复现用例。

**Comment by Dafrok** [comment]
@chenyinhuan ping

**Comment by Dafrok** [comment]
@chenyinhuan 如果没有后续问题的话，我关闭这个 issue 了。
