### ISSUE TITLE
使用 mapvGL 创建热力柱状图报错

### ISSUE THREAD

**Issue by LiuG-lynx** [Dafrok/vue-baidu-map#761]
### 浏览器版本号

chrome 80.0.3987.122

### Vue 版本号

2.5.21

### 组件库版本号

0.21.22

### 现象描述

```
this.map.lnglatToMercator is not a function
```

### 完整异常信息

```
使用 mapvGL 创建柱状图 报错
原demo地址https://mapv.baidu.com/gl/examples/editor.html#heat-grid.html

```

### 在线示例 / 仓库 URL

https://mapv.baidu.com/gl/examples/editor.html#heat-grid.html

### 复现用例

```
 
```

### 预期输出

```
 
```

### 实际输出

```
 
```

**Comment by wfyweb** [comment]
遇到类似问题，如何扩展echarts地图呐。 https://echarts.apache.org/examples/zh/editor.html?c=lines-bmap-effect
