### ISSUE TITLE
对于覆盖物右键菜单项，callback回调函数传参失败。是不能传入自定义参数吗

### ISSUE THREAD

**Issue by dimiduhezi** [Dafrok/vue-baidu-map#762]
<bm-context-menu>
                                    <bm-context-menu-item :callback="gotoshanghai(11)" text="去上海"></bm-context-menu-item>
                                    <bm-context-menu-item :callback="gotobeijing(11)" text="去北京"></bm-context-menu-item>
                                </bm-context-menu>

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
