### ISSUE TITLE
‘v-for’循环加载信息窗口‘bm-info-window’只能加载最后一条数据的信息窗口。

### ISSUE THREAD

**Issue by Dason-zdc** [Dafrok/vue-baidu-map#764]
_代码如下；_
`<baidu-map class="map" :center="firstPoint" :zoom="15" :scroll-wheel-zoom="true">
    <bm-marker v-for="item in gwData" :position="item.position" :dragging="true" @click="infoWindowOpen">
      <bm-label :content="item.name" :offset="{width: -35, height: 30}" :labelStyle="{color: 'red', fontSize : '14px'}" title="Hover me"/>
      <bm-info-window :show="show" :width="0" @close="infoWindowClose" @open="infoWindowOpen">
        <el-link type="primary" @click="handler">click </el-link>
        <gw-table></gw-table>
      </bm-info-window>
    </bm-marker>  
  </baidu-map>`

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
