### ISSUE TITLE
CityList控件中发现城市切换不了

### ISSUE THREAD

**Issue by hunnad** [Dafrok/vue-baidu-map#77]
测试中，发现下面这段代码 _instance为空，导致城市切换出错， _instance变量不存在this中。
 CityList.vue：
const {BMap, map, _instance} = this
      this.originInstance = new BMap.CityListControl({
        anchor: global[this.anchor],
        offset: this.offset,
        onChangeBefore () {
          _instance.$emit('changeBefore')
        },
        onChangeAfter () {
          _instance.$emit('changeAfter')
        }
      })
      map.addControl(this.originInstance)

**Comment by Dafrok** [comment]
提供的信息不足，请尝试在 codepen 还原你的场景以便更好的排查问题。

**Comment by Dafrok** [comment]
我尝试复现问题成功了，是个 bug，稍后发版。

**Comment by Dafrok** [comment]
请更新至 0.10.9
