### ISSUE TITLE
调用路书中开启rotation报错

### ISSUE THREAD

**Issue by newclock** [Dafrok/vue-baidu-map#772]
![image](https://user-images.githubusercontent.com/13828123/78089594-821a4780-73fa-11ea-820e-646f09ce518d.png)
![image](https://user-images.githubusercontent.com/13828123/78089615-8ba3af80-73fa-11ea-8d94-e47c381b1964.png)
在每个拐点的地方都会报错

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by Shino161** [comment]
@Dafrok 这个问题我也出现了，能帮忙看下吗？

**Comment by agrass-GitHub** [comment]
> @Dafrok 这个问题我也出现了，能帮忙看下吗？
同遇见

**Comment by agrass-GitHub** [comment]
我找到解决办法了，开启rotation，path 需要用 ` new BMap.Point` 来生成一个新的数组。
```js
points.map((item) => {
        return new BMap.Point(item.longitude, item.latitude);
 });
````

**Comment by Shino161** [comment]
> 我找到解决办法了，开启rotation，path 需要用 ` new BMap.Point` 来生成一个新的数组。
> 
> ```js
> points.map((item) => {
>         return new BMap.Point(item.longitude, item.latitude);
>  });
> ```

效果是有了，但似乎还是会有报错

**Comment by Shino161** [comment]
> 我找到解决办法了，开启rotation，path 需要用 ` new BMap.Point` 来生成一个新的数组。
> 
> ```js
> points.map((item) => {
>         return new BMap.Point(item.longitude, item.latitude);
>  });
> ```

得到了解决，感谢
