### ISSUE TITLE
安卓手机bm-polygon 不显示

### ISSUE THREAD

**Issue by qinxuanyu** [Dafrok/vue-baidu-map#787]
安卓手机bm-polygon 不显示

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by lizhengxing123** [comment]
帅哥，我的现在也不显示，之前还显示呢，不知道啥问题

**Comment by qinxuanyu** [comment]
我也忘了，我现在移动端用高德了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Dafrok/vue-baidu-map"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月1日(星期四) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Dafrok/vue-baidu-map] 安卓手机bm-polygon 不显示 (#787)





 
帅哥，我的现在也不显示，之前还显示呢，不知道啥问题
