### ISSUE TITLE
使用全景控件，移动鼠标时，提示错误

### ISSUE THREAD

**Issue by hunnad** [Dafrok/vue-baidu-map#79]
使用全景控件时，移动鼠标， console出现错误提示:
Uncaught TypeError: Cannot read property 'Va' of null
    at HTMLDocument.eval (eval at xZ (api.map.baidu.com/getscript?v=2.0&ak=xZUAfCbeGlMn6cRA8RIqwiXGQXnG9OHQ&services=&t=20170628183224:1), <anonymous>:1:31126)

使用原生api添加正常， 	
var stCtrl = new BMap.PanoramaControl(); //构造全景控件
stCtrl.setOffset(new BMap.Size(20, 20));
map.addControl(stCtrl);//添加全景控件

以下源代码中
  load () {
      const {BMap, map, anchor, offset} = this
      this.originInstance = new BMap.PanoramaControl({
        anchor,  =>是否要修改为    anchor: global[this.anchor],
        offset
      })
      map.addControl(this.originInstance)
    }
  }
当时我这边修改了下，测试控制台还是提示错误

**Comment by Dafrok** [comment]
anchor 的位置确实有问题，这个我一会儿更新发版。你去掉 anchor 还会有错误提示吗？

**Comment by Dafrok** [comment]
0.10.10 发版了，更新一下再看看还有没有问题？

**Comment by hunnad** [comment]
更新后还是会有这样的提示，我尝试在codepen上重现下

**Comment by Dafrok** [comment]
@hunnad 排查了一下好像是 Size 封装的问题，你看下 0.10.11 版本还有这个问题吗？

**Comment by hunnad** [comment]
@Dafrok  升到0.10.11还是会有问题。查看了下，可能是watch offset参数引起的。offset参数为对象，在鼠标移动的时候，不管offset对象属性有没变化，watch都会重新设置offset的值，导致控件多次reload初始化。

  watch: {
    anchor () {
      this.reload()
    },
    offset () {
      this.reload()   // 这句
    }
  },

**Comment by Dafrok** [comment]
你是不是绑定了匿名对象？

**Comment by hunnad** [comment]
@Dafrok 看下codepen上的测试代码 https://codepen.io/hunnad/pen/VWxxqN?editors=1010&via=CodePen

我在百度地图上面加了层div,   div定时显示或者隐藏就可以导致这个问题

**Comment by Dafrok** [comment]
你绑定了一个匿名对象。这是由于百度地图 API 和 vue 的更新机制共同造成的问题，目前还没有找到很好的解决方法，暂时可用具名对象代替之，示例：https://codepen.io/Dafrok/pen/dReKgG?editors=1010。

**Comment by hunnad** [comment]
OK。具名对象没有问题。
