### ISSUE TITLE
bm-boundary 大区域套小区域的时候,怎么把大区域设置成背景色,zIndex失效?

### ISSUE THREAD

**Issue by RemiHoston** [Dafrok/vue-baidu-map#793]
![image](https://user-images.githubusercontent.com/29702261/81496234-d8778180-92e8-11ea-9feb-a70b395e2945.png)
背景盖在最上面

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
