### ISSUE TITLE
设置vue-baidu-map的宽高为0，但是加载完成后页面实际高出了20px,怎么解决

### ISSUE THREAD

**Issue by dengjiangit** [Dafrok/vue-baidu-map#795]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by dengjiangit** [comment]
我这个由于是引入vue中的app.vue中的。多出20px.导致页面高出一屏。一直出现滚动条。怎么去掉多余的20px;但是引入的iframe又是0。。
怎么去掉这多出的20px
