### ISSUE TITLE
vue-baidu-map设置为0.实际页面高出20-30像素的问题

### ISSUE THREAD

**Issue by dengjiangit** [Dafrok/vue-baidu-map#796]
这边只使用vue-baidu-map进行定位，不展示。宽高都设置了0；但是页面加载完成后实际高出了20-30多像素，导致页面一直有滚动条；怎么去掉多出的像素

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
