### ISSUE TITLE
vue-baidu-map set width height 0 bug

### ISSUE THREAD

**Issue by dengjiangit** [Dafrok/vue-baidu-map#797]
将vue-baidu-map的盒子设置成0。但是加载完成后实际高出了20-30像素。导致页面可以滚动。
怎么解决这个问题

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by HanJinLiang** [comment]
> 将vue-baidu-map的盒子设置成0。但是加载完成后实际高出了20-30像素。导致页面可以滚动。
> 怎么解决这个问题

解决了吗，我也遇到这个问题。其他页面也都会高出20px
