### ISSUE TITLE
 Vue.use(VueBaiduMap, {ak: 'oW2UEhdth2tRbEE4FUpF9E5YVDCIPYih'})报错

### ISSUE THREAD

**Issue by xlf531533465** [Dafrok/vue-baidu-map#80]
直接在html中引用js文件,然后 Vue.use(VueBaiduMap, {ak: 'oW2UEhdth2tRbEE4FUpF9E5YVDCIPYih'}),报错:
vue.js:435 [Vue warn]: Unknown custom element: <baidu-map> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

![image](https://user-images.githubusercontent.com/6892564/27783054-4931a35a-6007-11e7-8d45-d937da3e3f6a.png)

**Comment by Dafrok** [comment]
你把 全局对象 log 出来就明白了。es module 长的不是你想像的那个样子。

**Comment by xlf531533465** [comment]
![image](https://user-images.githubusercontent.com/6892564/27783721-f60a87e8-6009-11e7-8073-c58d34b910c9.png)
叫<bm-view>?这个没看太明白,大神能给解释下吗(⊙o⊙)

**Comment by Dafrok** [comment]
es module 的默认 export 在 UMD 环境下是 default 属性。

**Comment by xlf531533465** [comment]
![image](https://user-images.githubusercontent.com/6892564/27784256-2a684d5c-600c-11e7-8278-ae249c184e11.png)
我以为你已经解决了呢 (^o^)／

**Comment by Dafrok** [comment]
因为后来架构变了，加入了按需加载的 feature，只能用回这个实现了。

**Comment by Dafrok** [comment]
因为后来架构变了，加入了按需加载的 feature，只能改回来了。

**Comment by xlf531533465** [comment]
好吧 坑哭我了 哭

**Comment by Dafrok** [comment]
计划 1.0.0 release 之后会开始记录 change log，尽量避免这种麻烦问题。
