### ISSUE TITLE
请问bm-control可以自定义位置吗？参数是什么？

### ISSUE THREAD

**Issue by brahmachen** [Dafrok/vue-baidu-map#81]
发现bm-control把我的css的位置给覆盖掉了，因为它的默认位置是左上，想问一下，可以自定义html吗？参数是什么？

**Comment by Dafrok** [comment]
官方文档和示例都是用 offset 和 anchor 来控制控件位置的，CSS 这种邪道还是不用比较好。

**Comment by brahmachen** [comment]
那我只能放弃bm-control了。。

**Comment by Dafrok** [comment]
为何？

**Comment by brahmachen** [comment]
布局比较复杂，重构的之前用css实现的代码，现在是在地图组件外部用div实现的

**Comment by Dafrok** [comment]
anchor 和 offest 定位其实原理很简单，移植也很简单，并没有涉及多少能和 css 冲突的属性，为了保证可维护性，万不得已再尝试用 CSS 吧。

**Comment by brahmachen** [comment]
嗯。。有时间再改。主要是用在外部可以直接用上原来的CSS
