### ISSUE TITLE
我要找到bm-marker 下面对应的bm-label 怎么获取呢？

### ISSUE THREAD

**Issue by yingjunX** [Dafrok/vue-baidu-map#82]

**Comment by Dafrok** [comment]
https://vuejs.org/v2/api/#ref

**Comment by Dafrok** [comment]
如果你想访问 BMap.Label 实例的话就访问 vm 的 originInstance 属性

**Comment by yingjunX** [comment]
<bm-marker @mouseover="abc" v-for="a  in map_point"  :position="{lng: a.lng, lat: a.lat}":dragging="true">
       <bm-label ref="myLabel"  content="我爱北京天安门" :labelStyle="{color: 'red', fontSize : '24px'}" :offset="{width: -35, height: 30}"/>
     </bm-marker>

我的marker 和label都是循环生成的   怎么找到对应的呢

**Comment by Dafrok** [comment]
循环和不循环有什么区别？

**Comment by yingjunX** [comment]
"如果你想访问 BMap.Label 实例的话就访问 vm 的 originInstance 属性"  可以具体一点不？感谢

**Comment by Dafrok** [comment]
已经很具体了，你哪一部分不明白？

**Comment by yingjunX** [comment]
vm 的 originInstance 属性 不是很清楚  去网上查也查不到

**Comment by Dafrok** [comment]
vm 就是 vue 组件实例，originInstance 我在是 vm 上定义的一个私有属性。

**Comment by TonyLuo** [comment]
@Dafrok 有没有使用originInstance的例子可以供参考呀？
我想通过BMap的实例进行调用逆地址解析，但不知道怎么能拿到实例

var map = new BMap.Map("allmap");
	var point = new BMap.Point(116.331398,39.897445);
	map.centerAndZoom(point,12);
	var geoc = new BMap.Geocoder(); 
geoc.getLocation(pt, function(rs){
			var addComp = rs.addressComponents;
			alert(addComp.province + ", " + addComp.city + ", " + addComp.district + ", " + addComp.street + ", " + addComp.streetNumber);

http://developer.baidu.com/map/jsdemo.htm#i7_2

**Comment by TonyLuo** [comment]
这是我的例子，供有需要的同学参考   
 <baidu-map ref="baiduMap" >

        let bmap = this.$refs.baiduMap.BMap
        let geocoder = new bmap.Geocoder()
        geocoder.getLocation(e.point, function (rs) {
          let addComp = rs.addressComponents;
          self.address = addComp.province + ", " + addComp.city + ", " + addComp.district + ", " + addComp.street + ", " + addComp.streetNumber

          console.log(self.address);
        })

**Comment by yizhixiaoyao0** [comment]
我在mounted里面调用let geocoder = new bmap.Geocoder() 报错undefined 
ref我也写了 求问。。怎么解决
