### ISSUE TITLE
bm-info-window第一次可以点击出来，当定时更新位置后就点击不出来了

### ISSUE THREAD

**Issue by zhouxiaopin** [Dafrok/vue-baidu-map#821]
html:
<bm-marker v-for="(item,index) in busGpsData" :key="index+'-'+item.busNo" :position="{lng: item.lngBd, lat: item.latBd}" 
       :icon="{url: item.iconUrl, size: {width: 21, height: 25}}"
       @click="infoWindowOpen(item)">
        <bm-info-window :show="item.show" @close="infoWindowClose(item)" @open="infoWindowOpen(item)">
            <div>{{item.busPlate}} {{ parseFloat(item.speed).toFixed(2)+'km/h'}}</div>

        
        </bm-info-window>
      </bm-marker>

js:
export default {
  name: "LineBus",
  data() {
    return {
      center: { lng: 0, lat: 0 },
      zoom: 3,
    
      // 查询参数
      queryParams: {
        lineNo: undefined,
      },

      map:undefined,
      //线路车辆gps信息
      busGpsList:[],
      //定时请求车辆gps定时器id
      intervalRequestBusGpsId:undefined,
    };
  },
  computed: {
    lineSelectPageSize() {
      return this.pageSize < this.filterLine.length
        ? this.pageSize
        : this.filterLine.length;
    },
    linePaths(){
      if(!this.selectLineDetail||this.selectLineDetail.length < 1){
        return [];
      }
      return this.selectLineDetail.map(item => {
        return item.map(item1 => {
           return {lng: item1.x, lat: item1.y};
        });
      });
    },
    busGpsData(){
      if(!this.busGpsList||this.busGpsList.length < 1){
        return [];
      }
      return this.busGpsList.map(item => {
        this.$set(item, 'show', false);
        //上下行
        let direction = '';
        if (item.direction == '0'){
            direction = '上行';
        }else if (item.direction == '1'){
            direction = '上行';
        }
        item.direction = direction;

         //10分钟
        let today = new Date();
        let dateTime = 1000*60*10; //10分钟的毫秒数
        let gpsTimeDate = new Date(Date.parse(item.gpsTime.replace(/-/g,"/")));
        let min = Math.floor((today.getTime()-gpsTimeDate.getTime())/dateTime);
        let iconImgName = '';
        if (min > 10){
            iconImgName = 'car4'
        }else{
            if (item.passengerFlow>400){
              iconImgName = 'car1'
            }else if (item.passengerFlow>200){
              iconImgName = 'car2'
            }else{
              iconImgName = 'car3'
            }
        }
        this.$set(item, 'iconUrl', require(`@/assets/image/map/car/${iconImgName}.png`));
        return item;
      });
    },
  },
  created() {

  },
  methods: {
    /**********事件处理***********/

    infoWindowClose (item) {
      item.show = false;
    },
    infoWindowOpen (item) {
      item.show = true;
    },

    /** 搜索按钮操作 */
    handleQuery() {

      this.requestLineDetailInfo(queryParams.lineNo);
      this.requestBusGpsInfo(queryParams.lineNo);
       if (this.intervalRequestBusGpsId) {
         clearInterval(this.intervalRequestBusGpsId);
     }
       this.intervalRequestBusGpsId = setInterval(() => {
        this.requestBusGpsInfo(queryParams.lineNo);
       }, 10*1000);
      
    },

    /*线路下拉框相关结束*/
    // 百度地图加载完毕
    bmReadyHandler({ BMap, map }) {
      // console.log(BMap, map);
      map.enableScrollWheelZoom();
      this.map = map;
      this.center.lng = 113.3225;
      this.center.lat = 23.1295;
      this.zoom = 12;

    },
    /********网络请相关*********/

    /** 查询车辆gps信息 */
    requestBusGpsInfo(lineNo) {
      getBusGpsInfo({lineNo}).then(
        response => {
          if (response.code == 200) {
            this.busGpsList=response.data;
            console.log(this.busGpsList);
          }else{
            this.msgInfo(response.msg);
          }
          
        }
      );
    },
  },
  components: {},
};

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by zhouxiaopin** [comment]
<template>
<bm-marker v-for="(item,index) in busGpsData" :key="index+'-'+item.busNo" :position="{lng: item.lngBd, lat: item.latBd}"
:icon="{url: item.iconUrl, size: {width: 21, height: 25}}"
@click="infoWindowOpen(item)">
<bm-info-window :show="item.show" @close="infoWindowClose(item)" @OPEN="infoWindowOpen(item)">


{{item.busPlate}} {{ parseFloat(item.speed).toFixed(2)+'km/h'}}




    </bm-info-window>
  </bm-marker>
</template>
