### ISSUE TITLE
网址链接打不开了

### ISSUE THREAD

**Issue by wengmm** [Dafrok/vue-baidu-map#823]
https://dafrok.github.io/vue-baidu-map/#/zh/index 网址打不开了。。。。。。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by wengmm** [comment]
[https://dafrok.github.io/vue-baidu-map/#/zh/index](url)`网址打不开了`
