### ISSUE TITLE
切换policy没有效果？

### ISSUE THREAD

**Issue by brahmachen** [Dafrok/vue-baidu-map#83]
路径规划，手动切换policy没有看到效果。。

`<bm-driving v-if="showDriving" policy="policy" :panel="false" start="北京" end="上海" :auto-viewport="true">  </bm-driving>`

其中policy是一个data，我切换policy为相应的值，是String类型，如下所示

`this.policy = this.typeResult[1];`

为啥没看到地图上有变化？没有看到策略对应的效果？
我这样操作有什么问题吗？

**Comment by Dafrok** [comment]
:

**Comment by brahmachen** [comment]
使用以下代码更改规划的策略，并没有发现路径有任何变化

```html
<template>
	<div id="app">
		<baidu-map style="width:100%;height: 300px;">
			<bm-driving start="新街口" end="新街口" startCity="北京" endCity="南京" :auto-viewport="true" :policy="policy">
			</bm-driving>
			<bm-control>
				<button @click="change">
		  		更改策略
		  	</button>
			</bm-control>
		</baidu-map>
	</div>
</template>

<script>
	export default {
		name: 'app',
		data() {
			return {
				showDriving: true,
				policy: "BMAP_DRIVING_POLICY_LEAST_DISTANCE"
				//BMAP_DRIVING_POLICY_LEAST_TIME
			}

		},
		methods: {
			change() {
				this.policy = "BMAP_DRIVING_POLICY_LEAST_TIME"
			}
		}
	}
</script>

<style>

</style>
```

**Comment by Dafrok** [comment]
放 codepen 吧，我抽空看下

**Comment by brahmachen** [comment]
我codepen的账号暂时没找回密码来。。

**Comment by Dafrok** [comment]
codepen 可以直接用 github 登录

**Comment by brahmachen** [comment]
还是需要用 github 账号链接一个 codepen 账号，最后提示 You can no longer verify your account via email. Contact support@codepen.io.

**Comment by Dafrok** [comment]
其它在线演示也可

**Comment by brahmachen** [comment]
看看吧，放到了 codepen 上了
https://codepen.io/brahmachen/pen/WOKEOq

**Comment by Dafrok** [comment]
根据你的问题我找到了百度地图 JS API 的一个 bug，在设置 policy 的时候 query string 不包含途经点……我先反馈一下把这个解决了再处理你的问题。

**Comment by brahmachen** [comment]
这个bug不小啊 =_=

**Comment by Dafrok** [comment]
更新到 11.0.0 了，试一试吧。

**Comment by brahmachen** [comment]
现在codepen是最新的版本吗？测试结果是没什么变化

我本地测也是一样结果

**Comment by Dafrok** [comment]
我发现问题在哪了，可是不太好改，我花两三时间弄一下。

**Comment by Dafrok** [comment]
0.11.1 解决了这个 bug

**Comment by brahmachen** [comment]
嗯。。步行和公交的貌似还没改

**Comment by Dafrok** [comment]
不应该啊。。我都改了。。

**Comment by Dafrok** [comment]
步行公交已经统一改了，你看 [commit log](https://github.com/Dafrok/vue-baidu-map/commit/c3d0c336ed5bccf9e8eabb87e4a18d2ebdfe37b1) 就知道。现在是又有什么新问题了？

**Comment by brahmachen** [comment]
稍等 我再测测

**Comment by brahmachen** [comment]
切换公交的policy确实没反应，步行没测

**Comment by Dafrok** [comment]
奇怪了，我再验证下。

**Comment by Dafrok** [comment]
步行没有 policy 参数…………

**Comment by Dafrok** [comment]
淦，把 Bus 组件当成公交换乘了，改错了。更新 0.11.2 了。

**Comment by brahmachen** [comment]
不过，经过最近的使用，发现还是不能成功的切换公交的策略
