### ISSUE TITLE
编译之后存在symbol的引用

### ISSUE THREAD

**Issue by For-me** [Dafrok/vue-baidu-map#84]
代码内部使用了for(item of list)这种类似的语法情况下，会调用Symbol.iterator属性，用于区分是否'可遍历'；但是看你的package.json中的配置并没有对该语法的转换，所以在用户直接引用你的build版本地图时，会触发crash，包括我使用babel-runtime来处理第三方库的转换问题，也无效。我认为这不是用户的配置问题。

**Comment by Dafrok** [comment]
事实上 polyfill 能够解决的问题都是开发者本身应解决的问题，babel-plugin-transform-runtime 解决的并不是 API 层面的问题，而是 syntax 层面的，不是任何 polyfill 能抹平的。
把 polyfill 编译进源码是万万不可取的。举个简单的例子，你的项目依赖了 100 个第三方 lib ，每个第三方依赖全部依赖 Symblo 类。此时你觉得应该在每个 lib 里跑一遍 polyfill 总共引入一百次还是让开发者自行引入一次？

**Comment by For-me** [comment]
这样说的话倒还能够理解，只是我觉得在一些错误处理情况下，还是不够友好，排查这个问题还是花了一些时间。。哈哈哈哈。
