### ISSUE TITLE
地图缩放性能差，闪白屏

### ISSUE THREAD

**Issue by lzlasome** [Dafrok/vue-baidu-map#840]
### 浏览器版本号

chrome 84.0.4147.125

### Vue 版本号

4.4.1

### 组件库版本号

0.21.22

### 现象描述

```
Npm引入地图后每次缩放地图都会闪一下白屏，放大地图按理中间本来加载好的不会变动，只是周围重新渲染，但执行完之后还是会再闪一下白屏，好像又加载了一遍一样
```

### 完整异常信息

```
无
```

### 在线示例 / 仓库 URL

www.lizhaolinawesome.cn

### 复现用例

```
地图缩放
```

### 预期输出

```
不闪白屏
```

### 实际输出

```
闪白屏
```

**Comment by qiuzhaofeng** [comment]
why closed
