### ISSUE TITLE
Vue Baidu Map 卫星图自定义瓦片图不显示

### ISSUE THREAD

**Issue by Anniezandr** [Dafrok/vue-baidu-map#846]
**[BUG 反馈] 卫星图自定义瓦片图不显示**

### 浏览器版本号
版本 85.0.4183.83（正式版本） （64 位）

### Vue 版本号
"vue": "^2.6.11",

### 组件库版本号
"vue-baidu-map": "^0.21.22",

### 现象描述
自定瓦片图 map-type="BMAP_HYBRID_MAP"时候，使用<bm-tile :isTransparentPng="true"tileUrlTemplate="http://192.168.0.107:3002/tiles/{Z}/tile-{X}_{Y}.png"></bm-tile>，请求瓦片图接口时候tileUrlTemplate里面的X会变成undefined，导致一块块自定义瓦片图没法下载，如下图：
![60478e319cb6c8685603b94292001984](https://user-images.githubusercontent.com/46767287/92692556-ed3b5300-f376-11ea-94c8-8911f75f49f0.png)

### 完整异常信息
但是may-type属性不设置的时候，自定义瓦片图就能正常显示，如下：
![536b5284af279dfa91dedba1e2dbba09](https://user-images.githubusercontent.com/46767287/92692677-15c34d00-f377-11ea-86f4-0198d97a26e4.png)
异常如下：
![7cd6087e8490291f36681511656d1818](https://user-images.githubusercontent.com/46767287/92692712-2247a580-f377-11ea-937b-036a1ab8b68d.png)

代码片段如下：
![carbon](https://user-images.githubusercontent.com/46767287/92692797-4c00cc80-f377-11ea-9f93-82b8a3683423.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
