### ISSUE TITLE
请问vue-baidu-map已经加了输入提示示例的功能了吗？我在文档中没找到该功能的描述

### ISSUE THREAD

**Issue by gdutwyg** [Dafrok/vue-baidu-map#85]

**Comment by Dafrok** [comment]
暂时没有，因为这个东西的视图和输入框耦合太大，做成组件似乎不太合适，您有什么好的建议吗？

**Comment by gdutwyg** [comment]
我现在还遇到一个问题，目前我在的vue项目里面使用官方的输入提示示例，但是这个提示示例位置是相对于body的，如果我输入框滚动，它并不会随我输入框滚动，有没有解决方法？

**Comment by Dafrok** [comment]
这个去论坛问吧。官方给的说法是不要用 Autocomplete 类，直接调 web api 拿检索数据，UI 自己去实现或者用现成的。

**Comment by Dafrok** [comment]
11.0.0 增加了 [自动填充组件](https://dafrok.github.io/vue-baidu-map/#/zh/other/auto-complete)

因为 UI 没办法定制，所以实现比较简陋。

**Comment by Dafrok** [comment]
这个东西官方推荐还是自己调接口自己写 UI 的方式来做。

**Comment by gdutwyg** [comment]
好的，谢谢

**Comment by gdutwyg** [comment]
应该是调用LocalSearch这个方法，然后自己再构造ui显示

**Comment by For-me** [comment]
简单点自己直接autoComplate构造方法来获取数据并且填充到UI里

**Comment by gdutwyg** [comment]
明白了，它好像有onSearchComplete这个属性，是用这个属性吧？
