### ISSUE TITLE
点过多聚合时 卡顿问题

### ISSUE THREAD

**Issue by JamesBound** [Dafrok/vue-baidu-map#851]
<bml-marker-clusterer
        :averageCenter="true"
      >
        <div
          v-for="(marker, i) of markers"
          :key="i">
          <bm-marker
            :dragging="true"
            animation="BMAP_ANIMATION_BOUNCE"
            :icon="{url: marker.url, size: { width: 300, height: 171 }}"
            :position="{lng: marker.lng, lat: marker.lat}"
            @click="infoWindowOpen(marker)"
          >
          </bm-marker>
        </div>
      </bml-marker-clusterer>

当markers数组 数量超过5000时 卡顿非常明显

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
