### ISSUE TITLE
baidu-map 标签  点击事件 为什么点击输出的 没有point

### ISSUE THREAD

**Issue by DuoDir** [Dafrok/vue-baidu-map#853]
baidu-map 标签  点击事件 为什么点击输出的 没有point
![image](https://user-images.githubusercontent.com/27777607/93552215-7b7c8e00-f9a2-11ea-98ad-8334dc5cdad8.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
