### ISSUE TITLE
移动端不支持手指缩放功能，pinch-to-zoom失效？

### ISSUE THREAD

**Issue by yu2999** [Dafrok/vue-baidu-map#855]
PC端Chrome调试移动端时scroll-wheel-zoom失效，vue3，官网的例子好像也不行，两个手指移动缩放也不得行
代码如下：
<template>
  <baidu-map class="map" :center="{lng: 116.404, lat: 39.915}" :zoom="15" :scroll-wheel-zoom="true">
  </baidu-map>
</template>

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
