### ISSUE TITLE
看你的头像，我不禁想问你，你是同志嘛？

### ISSUE THREAD

**Issue by martinwithyou** [Dafrok/vue-baidu-map#859]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by xiaohuno1** [comment]
hhhh 那你是同志吗？

**Comment by xiaohuno1** [comment]
> _No description provided._

哈哈哈哈哈 那你是同志嘛？
