### ISSUE TITLE
手机浏览器一片空白,pc端正常显示

### ISSUE THREAD

**Issue by Jesonhu** [Dafrok/vue-baidu-map#86]
vue:
2.3.3

vue-baidu-map
0.10.8

pc
window 10 64位

手机(wifi)
华为荣耀8

手机浏览器浏览地图不能加载，pc可以正常显示。且手机浏览时 baidu-map标签@ready="xxx" ready里面弹出页不执行说明没走这一步
具体代码展示
[https://codepen.io/Jesonhu/pen/pwZPxp](https://codepen.io/Jesonhu/pen/pwZPxp)

**Comment by Dafrok** [comment]
#24 遇到问题可以先搜下别人的 issue

**Comment by Jesonhu** [comment]
@Dafrok 大佬我的手机是安卓7.0的系统呢？
可能的问题解决尝试是不是这样？
1 npm install babel-polyfill --save-dev
2 main.js: import 'babel-polyfill'

**Comment by Dafrok** [comment]
有问题先看 console，不是所有人都有你的测试机。

**Comment by Jesonhu** [comment]
@Dafrok 我引入babel-polyfill 手机浏览器就可以访问了 我现在用vue做单页面 最后都是要在手机上调试 但是手机目前只能我目前只能alert调试。有没有推荐的工具可以console手机端的调试结果

**Comment by Dafrok** [comment]
chrome 就可以……
