### ISSUE TITLE
加载地图图片API不稳定,图片加载失败

### ISSUE THREAD

**Issue by guojunliang2** [Dafrok/vue-baidu-map#866]
获取图片API：https://api.map.baidu.com/customimage/tile?xx

获取失败，地图会有部分区域为白色方块
![image](https://user-images.githubusercontent.com/28854860/98346502-04ce4980-2051-11eb-9b18-c50e189663d4.png)

请问这种有什么方法解决吗？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
