### ISSUE TITLE
vue-baidu-map 如何手动定位到当前位置

### ISSUE THREAD

**Issue by weiweidong1993** [Dafrok/vue-baidu-map#868]
**手动定位**  不是**自动定位**

类似于打卡签到,目前已实现功能是一进入页面显示的是打卡的区域的大图

右下角用了vue-baidu-map的定位功能  点击 后居然定位到了市中心 偏差太大 ???

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by weiweidong1993** [comment]
紧急 在华为搞SB项目 无法截图
