### ISSUE TITLE
如何覆盖style样式

### ISSUE THREAD

**Issue by hdp198** [Dafrok/vue-baidu-map#871]
<div class="gc-comments" data-repos="nimojs/github-comments" data-issues="1" >
    <div class="gc-comments-title">
       使用内联式无法覆盖
    </div>
</div>

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
