### ISSUE TITLE
路书功能

### ISSUE THREAD

**Issue by feichaoyu** [Dafrok/vue-baidu-map#877]
1.请问路书的暂停和停止都是play=false？那怎么区分这两个事件呢？（我看文档上那个开始和暂停可以使用，可以提供下代码吗？）
2.路书的移动速度能在运动途中修改吗？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
