### ISSUE TITLE
polyline 在手机中zoom默认大于14的时候不显示

### ISSUE THREAD

**Issue by shoyuf** [Dafrok/vue-baidu-map#88]
手机（包括chrome模拟）上不显示，电脑正常

**Comment by shoyuf** [comment]
```
<baidu-map class="map" :center="center" @ready="getLine" zoom="14" v-show="showMap">
        <bm-polyline :path="centers" stroke-color="red" :stroke-opacity="0.5" :stroke-weight="4"></bm-polyline>
      </baidu-map>
```
```
centers:Array[3]
0:Object
lat:"30.661795"
lng:"104.082454"
spotId:29
1:Object
lat:"30.663287"
lng:"104.080155"
spotId:30
2:Object
lat:"30.663287"
lng:"104.083604"
spotId:31
```

**Comment by Dafrok** [comment]
文档中的实例也不显示吗？

**Comment by Dafrok** [comment]
文档中的示例放大后也不显示 polyline 吗？

**Comment by shoyuf** [comment]
是的

**Comment by Dafrok** [comment]
所有机型均不显示？

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-baidu-map/#/zh/overlay/polyline

**Comment by Dafrok** [comment]
用移动端访问这个页面，zoom 值为 15 ，chrome 模拟器依然正常。

**Comment by For-me** [comment]
我用三星的7.0系统和ios9.0以上系统访问没问题，无法访问的问题是否是ios8及以下，安卓4.4.4以下版本？试试加入babel-polyfill

**Comment by Dafrok** [comment]
@For-me 跟 polyfill 应该关系不大，他说是 zoom > 14 才会出这个问题，比较诡异。

**Comment by For-me** [comment]
我手边的手机测试都正常，只有让他提供对应的系统和手机版本才方便定位问题。

**Comment by shoyuf** [comment]
"vue": "^2.3.3"  "vue-baidu-map": "^0.10.7"
刚刚上传了份[demo](http://shoyuf.coding.me/funmitech-travel/#/tourist/traveldetail/scenic/spotline/3)
打开了devtool可以看到数据，需要贴出页面的代码吗？

**Comment by Dafrok** [comment]
可以在 codepen 上实现一个简单的复现用例

**Comment by shoyuf** [comment]
https://codepen.io/anon/pen/LLqzgy/

找到原因了。。原因是默认设置的center为lng0和lat0
异步加载center的值导致移动端划线的canvas left值 超限 3.07385e+06px
在chrome桌面端使用的svg绘图则没这个问题

**Comment by Dafrok** [comment]
学习了，你的 issue 很有参考价值

**Comment by Dafrok** [comment]
这个 issue 是不是可以关掉了？
