### ISSUE TITLE
bm-marker 指定 size 无法自动缩放自定义 icon

### ISSUE THREAD

**Issue by BugVSbug** [Dafrok/vue-baidu-map#886]
:icon="{url: wifiIcon, size: {width: 40, height: 50}}
size设置的是dom的width和height，不是背景图的宽高，百度地图api中有

const size = new BMap.Size(25, 35)
const icon = new BMap.Icon(require('icon.png'), size)
icon.imageSize = size
const marker = new BMap.Marker(new BMap.Point(lng, lat), {icon: icon})
map.addOverlay(marker)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by JunevaYang** [comment]
:icon="{
          url: require('@/assets/location.png'),
          size: { width: 100, height: 100 },
          opts: {
            imageSize: { width: 22, height: 22 },
          },
        }"
