### ISSUE TITLE
在Weex中使用报错 property 'Yb' of undefined

### ISSUE THREAD

**Issue by wqjGitHub** [Dafrok/vue-baidu-map#89]
Uncaught (in promise) TypeError: Cannot set property 'Yb' of undefined
    at La.enableDragging (getscript?v=2.0&ak=xxxxxxxxx&services=&t=20170707103901:1)
    at VueComponent.setMapOptions (baiduMap.js:494)
    at boundFn (vue.runtime.js:171)
    at VueComponent.init (baiduMap.js:494)
    at VueComponent.boundFn [as init] (vue.runtime.js:170)
    at VueComponent.initMap (baiduMap.js:494)
    at boundFn (vue.runtime.js:170)
    at <anonymous>

weex的项目使用的Vue 2.0实现

这个是baiduMap.vue : 
<template>
    <baidu-map class="bm-view" ak="xxxxxxxxxxxx">
    </baidu-map>
    
</template>

<script>
import { BaiduMap } from 'vue-baidu-map'
export default {
    components: {
        BaiduMap
    }
}
</script>

<style>
.bm-view {
    width: 100%;
    height: 100%;
    background-color: green;
}
</style>

**Comment by Dafrok** [comment]
你先确定一下和 weex 有没有关系。

**Comment by wqjGitHub** [comment]
在纯粹的vue项目中，是完全正常的，应该是应为weex的关系，报这个错是否是没有读取到指定的root节点的关系？

**Comment by Dafrok** [comment]
貌似不是。看你的报错信息是 initMap 那步出的问题，在 `map.enableDragging()` 加个 debugger 看看各变量符不符合预期吧。

**Comment by wqjGitHub** [comment]
在node_muldes中引用的index.js的压缩文件，我使用import { BaiduMap } from 'vue-baidu-map/src/index'后报baiduMap.js:557 Uncaught SyntaxError: Unexpected token import错误，无法继续。

**Comment by Dafrok** [comment]
你这是 babel 没编译 import。。。

**Comment by wqjGitHub** [comment]
谢谢了，重新给实现了一个，基本功能已经OK了。

**Comment by Dafrok** [comment]
是什么原因造成的？

**Comment by wqjGitHub** [comment]
大概原因是new BMap.Map($el)，其中的$el不对，在weex下this.$refs.view取到后要再加上.$el才能取到对应的节点。

**Comment by Dafrok** [comment]
这看起来是个比较棘手的问题，有好几个组件都用到了 $el。你的 infoWindow 组件是不是也有这个问题？

**Comment by wqjGitHub** [comment]
这个没测过，最初的时候就没过去，后面的就没测试过了。

**Comment by Dafrok** [comment]
如果你觉得有必要可以发个 pr，我再发一版

**Comment by Dafrok** [comment]
@wqjGitHub 有 pr 计划吗

**Comment by wqjGitHub** [comment]
没有。
