### ISSUE TITLE
sdk可以更换为3吗

### ISSUE THREAD

**Issue by dpgirl** [Dafrok/vue-baidu-map#890]

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by dpgirl** [comment]
大佬，这插件的sdk可以更换为版本3吗？要怎么更换？版本2去掉路线图，城市位置不准

**Comment by dpgirl** [comment]
大佬，这插件的sdk可以更换为版本3吗？要怎么更换？版本2去掉路线图，城市位置不准
