### ISSUE TITLE
Vue2 中引用地图插件报错额。

### ISSUE THREAD

**Issue by beckyzhan** [Dafrok/vue-baidu-map#9]
![qq 20170308165938](https://cloud.githubusercontent.com/assets/10825353/23696984/eeccf73a-0420-11e7-8bb6-d9d3f32c36e1.png)
![qq 20170308170222](https://cloud.githubusercontent.com/assets/10825353/23697018/09f686ca-0421-11e7-8c1a-8bc5ac90a14e.png)

**Comment by Dafrok** [comment]
Components 中不用注册，Vue.use 的时候已经把所有组件都注册好了。
