### ISSUE TITLE
cdn的方式引入时，如何初始化map?

### ISSUE THREAD

**Issue by xiaozefeng** [Dafrok/vue-baidu-map#90]
## 使用cnd引入时，不知道如何初始化地图

**Comment by Dafrok** [comment]
你把全局对象打印出来就知道了。问这个的比较多，其它 ISSUE 里有答案，我抽时间加入示例吧。

**Comment by Dafrok** [comment]
文档已更新 https://dafrok.github.io/vue-baidu-map/#/zh/start/usage
