### ISSUE TITLE
[BUG 反馈] bml-lushu 移动物体不随路径旋转朝向，并且没有调整路线视野

### ISSUE THREAD

**Issue by zxzxac110** [Dafrok/vue-baidu-map#900]
浏览器版本号
oogle Chrome 79.0.3945.88（正式版本） （32 位

Vue 版本号
2.6.11

组件库版本号
0.21.22

现象描述
bml-lushu 移动物体不随路径旋转朝向，并且没有调整路线视野
完整异常信息
页面报警 index.js?bd0c:1 Uncaught TypeError: Cannot read property 'x' of undefined
    at i.setRotation (index.js?bd0c:1)
    at eval (index.js?bd0c:1)
在线示例 / 仓库 URL
![示例](https://imgtu.com/i/6hR68H)
https://imgtu.com/i/6hR68H

复现用例
<template>
  <div class="map-box po-re"
       v-loading="Loading"
       element-loading-background="rgba(159, 215, 252, 0.8)">
    <div v-if="type === 2"
         class="po-ab my-date-picker">
      <el-date-picker :clearable="false"
                      v-model="reqData.start_time"
                      type="date"
                      class="my-el-date-picker"
                      style="width:135px;"
                      placeholder="选择日期"
                      value-format="yyyy-MM-dd"
                      @change="getData()"
                      :picker-options="pickerOptions"></el-date-picker>
      <el-button @click="lookTrack">查看移动轨迹</el-button>
    </div>
    
    <div v-if="!(haveData) && !(Loading)"
         class="position-absolute mask"></div>
    <baidu-map id="map"
               ref="map"
               class="map"
               ak=""
               :center="center"
               :zoom="zoom"
               scroll-wheel-zoom
               @ready="ready">
      <bm-navigation anchor="BMAP_ANCHOR_TOP_LEFT"
                     class="navigation"></bm-navigation>

      
      <bm-polyline v-if="type === 2"
                   :path="polylinePath"
                   stroke-color="#0088FF"
                   strokeStyle="dashed"
                   :stroke-opacity="5"
                   :stroke-weight="5"></bm-polyline>

      
      <bm-marker v-for="(item,index) of dotList"
                 :key="index"
                 :position="item"
                 animation
                 :icon="{url: mpaMarker, size: {width: 28, height: 37} }"
                 :offset="{width: 0, height: -19}"
                 @click="infoWindowOpen(item,index)">
        <bm-label v-if="item.name || index === dotList.length - 1"
                  :content="item.name || name"
                  :position="item"
                  :labelStyle="{color: '#0088FF', fontSize : '14px',border : '2px solid #0088FF', padding:'0 5px' ,transform: 'translateX(-50%)'}"
                  :offset="{width: 14, height: 40}" />
        <bm-info-window :show="item.toop"
                        @close="infoWindowClose(item,index)"
                        :width="200">
          <div class="d-flex">
            <span class="font-bold pr-2"
                  style="color: #9a9a9a">·</span>
            <span class="font-14">{{item.start_time_his}}（{{item.duration | timeFormat('00:00:00')}}）</span>
          </div>
          <div class="d-flex">
            <span class="font-bold pr-2"
                  style="color: #9a9a9a">·</span>
            <span class="font-14">{{item.address}}</span>
          </div>
        </bm-info-window>
      </bm-marker>

      <bml-lushu @stop="reset"
                 :path="polylinePath"
                 :icon="icon"
                 :play="play"
                 :speed="2000"
                 :autoView="true"
                 :rotation="true">
      </bml-lushu>
    </baidu-map>
  </div>
</template>

<script>
import { BaiduMap, BmMarker, BmLabel, BmPolyline, BmInfoWindow, BmNavigation, BmlLushu } from 'vue-baidu-map'

export default {
  components: {
    BaiduMap,
    BmMarker,
    BmLabel,
    BmPolyline,
    BmInfoWindow,
    BmNavigation,
    BmlLushu
  },
  props: {
    row: { // 个人信息
      type: Object,
      default: () => { }
    },
    Paths: { // 初始数据
      type: Array,
      default: () => []
    },
    type: { // 1点图 2 折线图
      type: Number,
      default: 1
    }
  },
  data () {
    return {
      reqData: {
        start_time: '',
      },
      create_time: [],
      pickerOptions: {
        disabledDate: time => {
          let end = new Date()
          end.setHours(0);
          end.setMinutes(0);
          end.setSeconds(0);
          end.setDate(end.getDate() + 1);
          end.setTime(end.getTime() - 1000);
          return time.getTime() > end.getTime()
        }
      },
      center: { lng: 0, lat: 0 },
      zoom: 10,
      map: null,
      polylinePath: [], // 折线图数据
      dotList: [], // 窗口数据
      mpaMarker: require('../assets/images/common/map_dot.png'),
      Loading: false,
      name: '',
      dataUpdating: false,
      play: false,
      icon: {
        url: 'http://api.map.baidu.com/library/LuShu/1.2/examples/car.png',
        size: { width: 52, height: 26 },
        opts: { anchor: { width: 27, height: 13 } }
      }
    }
  },
  mounted () {
    const start = new Date();
    this.reqData.start_time = this.formatTime(start)
  },
  watch: {
    row () { // 成员发生改变
      this.getData()
    },
  },
  computed: {
    haveData () {
      return this.dotList.length > 0
    },
  },
  methods: {
    reset () {
      this.play = false
    },
    lookTrack () {
      this.play = true
    },
    infoWindowClose (item, index) {
      if (item._id !== this.dotList[index]._id) {
        return
      }
      if (this.dataUpdating) {
        this.dataUpdating = false
        return
      }
      if (this.dotList[index]) {
        item.toop = false
        this.$set(this.dotList, index, item)
      }
    },
    infoWindowOpen (item, index) {
      this.WindowDataChange(item, index, !item.toop)
    },
    WindowDataChange (item, index, bol) {
      if (this.dotList[index]) {
        let arr = this.dotList.map((e, i) => {
          if (i === index) {
            e.toop = bol
          } else {
            e.toop = false
          }
          return e
        })
        this.dotList = arr
      }
    },
    autoCenter () {
      this.dataUpdating = true
      var view = this.map.getViewport(eval(this.dotList))
      this.zoom = view.zoom;
      if (this.type === 2) {
        let obj = this.dotList[this.dotList.length - 1]
        this.center = {
          lat: obj.lat,
          lng: obj.lng
        }
      } else {
        this.center = view.center;
      }
    },
    ready ({ BMap, map }) {
      console.log('初次渲染')
      this.map = map
      this.BMap = BMap
      this.dotList = JSON.parse(JSON.stringify(this.Paths))
      this.autoCenter()
    },
    async getData () {
      this.Loading = true
      if (this.create_time) {
        this.reqData.begin_time = this.create_time[0]
        this.reqData.end_time = this.create_time[1]
      } else {
        this.reqData.begin_time = this.reqData.end_time = ''
      }
      try {
        let res = await this.$api.getOneLocation(this.row.company_user_id, this.reqData)
        if (res.length < 1) {
          this.dotList = []
          this.autoCenter()
        } else {
          this.dotList = res.map((e, i) => {
            if (i === res.length - 1) {
              e.toop = true
            } else {
              e.toop = false
            }
            return e
          })
          this.autoCenter()
        }
        this.polylinePath = JSON.parse(JSON.stringify(this.dotList)) // 解决折线数据变化是导致页面重绘问题
        this.Loading = false
        this.name = this.row.company_user.name
      } catch (e) {
        this.Loading = false
      }
    }
  }
};

</script>
预期输出
无
实际输出
无

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
