### ISSUE TITLE
创建LocalSearch对象时出现错误

### ISSUE THREAD

**Issue by Smithjoppa** [Dafrok/vue-baidu-map#903]
`this.BMapCore = BMap;this.map = BMap.map;this.map.clickable = false;this.mapGeo = new this.BMapCore.BMap.Geocoder();this.mapLoadComplete[0] = true; if(!)this.mapLoadComplete[1]) { 如果 (!isEmpty(this.level3Regions) {this.convertPlaceNameToLatLng(this.level3Regions, false);this.mapLoadComplete[1] = true;}}this.LocationRequestDevice();let local = this.BMapCore.BMap.LocalSearch(this.map);`

视图显示

`<百度地图:center="bmCenter":min-zoom="minZoom":scroll-wheel-zoom="true":zoom="mapZoom"@ready="mapReady"@resize="mapResizeListener"@zoomend="zoomEndListener"@zoomstart="zoomStartListener"ref="map"style="float: left; width: 100%; height: 100%"z-index="1"><!--版权信息--><bm-版权:copyright="copyright"anchor="BMAP_ANCHOR_TOP_LEFT"style="font-size: 20px; color: #e1f3d8"></bm-版权><!--设备点的详细信息--><我的覆盖:active="active":position="overlayDeviceInfo"@deviceItemClickListener="deviceItemClickListener"@getLocationClick="leftRegionSelectListener"@regionSelect="leftRegionSelectListener"ref="overlay"></我的覆盖></百度地图>`

控制台报告

`[Vue warn]: Error in event handler for "ready": "TypeError: this.qn is not a function. (In 'this.qn(a)', 'this.qn' is undefined)"`

我该如何去创建这个对象

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
