### ISSUE TITLE
引入路书组件问题

### ISSUE THREAD

**Issue by xiaowanhashi** [Dafrok/vue-baidu-map#91]
你好，我现在项目中要实现根据动态的GPS画线然后根据这条线实现路书回放的功能，现在我在map.vue中按照你的方式这样引入的路书文件
initLuShu (BMapLib) {
      this.BMapLib = BMapLib
    },
    getLuShuScript () {
      if (!global.BMapLib) {
        global.BMapLib = {}
        global.BMapLib._preloader = new Promise((resolve, reject) => {
          global._initBaiduLib = function () {
            resolve(global.BMapLib)
            global.document.body.removeChild($scriptLushu)
            global.BMapLib._preloader = null
            global._initBaiduLib = null
          }
          const $scriptLushu = document.createElement('script')
          global.document.body.appendChild($scriptLushu)
          $scriptLushu.src = '//api.map.baidu.com/library/LuShu/1.2/src/LuShu_min.js'
          $scriptLushu.onreadystatechange = function () {
            if (this.readyState === 'complete') {
              global._initBaiduLib()
            }
          }
          $scriptLushu.onload = function () {
            global._initBaiduLib()
          }
        })
        return global.BMapLib._preloader
      } else if (!global.BMapLib._preloader) {
        return Promise.resolve(global.BMapLib)
      } else {
        return global.BMapLib._preloader
      }
    }
  },
  created () {
    const {getMapScript, initMap, getLuShuScript, initLuShu} = this
    getMapScript()
      .then(function (BMap) {
        initMap(BMap)
        getLuShuScript()
          .then(initLuShu)
      })
  },

然后在polyline.vue中通过props 暴露出去的路书属性如下：
luShuStart: {
      type: Boolean,
      default: false
    },
    addLuShu: {
      type: Boolean,
      default: false
    },
    luShuProps: {
      type: Object,
      default: function () {
        return {
          defaultContent: '动车继续前行',
          speed: 20000,
          autoView: false,
          enableRotation: false
        }
      }
    },
    luShuIcon: {
      type: Object,
      default: function () {
        return {}
      }
    }

紧接着 我就直接watch 下面两个属性
luShuStart (val) {
      // debugger
      val && this.lushu.start()
    },
    luShuIcon (val) {
      const {BMap} = this
      // debugger
      this.originInstance.setIcon(createSymbol(BMap, val))
    }

最后我在load 方法中 添加这个addLuShu，luShuProps属性 并且让它挂载到this.lushu下面
load () {
      const {BMap, BMapLib, map, path, strokeColor, strokeWeight, strokeOpacity, strokeStyle, editing, massClear, clicking, addLuShu, luShuProps} = this
      var points = path.map(item => createPoint(BMap, {lng: item.lng, lat: item.lat}))
      const overlay = new BMap.Polyline(points, {
        strokeColor,
        strokeWeight,
        strokeOpacity,
        strokeStyle,
        enableEditing: editing,
        enableMassClear: massClear,
        enableClicking: clicking
      })
      this.originInstance = overlay
      addLuShu && (this.lushu = BMapLib.LuShu(map, points, luShuProps))
      map.addOverlay(overlay)
      bindEvents.call(this, overlay)
    }

我在前台这边绑定属性后改变lushustart这个状态的时候提示我 start这个方法未定义，现在不知道是哪出问题...
<bm-polyline  :path="gpsLine" stroke-color="blue" :stroke-opacity="0.5" :stroke-weight="4" :luShuStart="luShuStart" :luShuIcon="getSymbol"></bm-polyline>

**Comment by Dafrok** [comment]
我怎么觉得这个 issue 和仓库无关呢，引入第三方库不需要改源码。

**Comment by xiaowanhashi** [comment]
但是我现在要在这个vue-map中使用，我看到这边百度路书的库是要在百度地图加载之后才行的

**Comment by Dafrok** [comment]
那就在它加载完成后再你再手动加载就好了，怎么在加载完毕后执行你的 handler 在文档里写的很清楚，并不需要改源码。

**Comment by xiaowanhashi** [comment]
我刚刚试了两种方法，在mounted中去执行getScriptLushu方法去加载路书，然后在map的@ready方法中去打印，还有一种是直接在map的@ready方法中去执行getScriptLushu方法去加载路书，打印结果都是没有BMapLib这个对象 /(ㄒoㄒ)/~~

**Comment by Dafrok** [comment]
你可以直接在头部插 script 标签啊……

**Comment by Dafrok** [comment]
反正 vue-baidu-map 在初始化的时候是会探测 BMap 对象的，一开始就加载进来也并无影响。

**Comment by xiaowanhashi** [comment]
这么玩过的还是不行，我当时做的时候直接copy你的源码，然后直接统一在main.js中引入进来的，没有install到项目 cdn的也试过 当时是直接在index.html单纯引入你的cdn地址然后下面在加一行lushu的库，我这边组件要怎么全局引入时候找不到vuebaidumap这个对象的...

**Comment by Dafrok** [comment]
就给一点提示，首先你在 @ready 事件中能拿到 `BMap` 类和 `map` 实例，在这之后你去执行加载路书的脚本，无论用什么方法我不管，总之加载进来你就能拿到路书的对象，那么现在你拿到了这三个对象之后，还有什么不能做的事情吗？

**Comment by xiaowanhashi** [comment]
在这之后我执行加载路书的脚本之后，我拿不到这个路书的对象.......

**Comment by Dafrok** [comment]
那说明你的方法是错的，无论放到哪都拿不到路书对象，和组件库没有关系。

**Comment by xiaowanhashi** [comment]
我复制了你的getMapScript方法改了路径,去加载进来，的..行吧我再找找，非常谢谢你

**Comment by Dafrok** [comment]
建议你去官网看看怎么用最朴实的方法进行异步加载，我的加载方法是针对自己的 case 封装过的，如果场景不同照搬肯定是有问题的。

**Comment by xiaowanhashi** [comment]
嗯嗯 谢谢 之前也试过了 @ready事件中创建一个script然后append到body中去 还是拿不到。。哪里出问题了我在找找

**Comment by Dafrok** [comment]
百度地图 API 是 JSONP 加载的，所以可以通过回调函数拿到 BMap 对象，路书我没用过，但是看你的形容貌似是不一样的。

**Comment by xiaowanhashi** [comment]
搞了个把小时还是没好，我现在的问题就是如何在引入你这个地图组件之后再引入路书库的问题。。。貌似只能在源码上改,还是原来的样子 这次在initlushu的时候也跟着emit一个ready出去 顺便把lushu也传过去了，@ready的时候通过打印参数lushu，这个对象就是路书对象，但是对象下面的方法明明都是有的 但是调用的时候却提示报错

**Comment by Dafrok** [comment]
粗看了下路书的源码，完全同步的。你实在不行就把源码下下来包装一个函数里，在 ready 句柄里执行一下都可以。

**Comment by xiaowanhashi** [comment]
我现在用了一个极端的方法，在initlushu的时候ready出去 把lushu也传过去了，然后在@ready的时候把lushu这个对象直接深拷贝出来给了我vue data中定义的一个空对象 我现在通过这个拷贝的对象访问是能访问到了下面的方法，但是又遇到一个问题了，我必须实例化这个类，才能调用这个方法，但是在vue data中定义的对象好像是没有办法去实例化....很尴尬

**Comment by Dafrok** [comment]
为啥要放到 data 里？

**Comment by xiaowanhashi** [comment]
computed? 然后我在直接new 一个？

**Comment by Dafrok** [comment]
https://codepen.io/Dafrok/pen/eRXmLj

你这个需求真的有这么难么……………………

**Comment by xiaowanhashi** [comment]
你这是cdn引入的吧？ 我是工程化的，如果在index.html里面引入这cdn我use不了啊

**Comment by Dafrok** [comment]
工程化为什么不能 CDN 引入？

**Comment by xiaowanhashi** [comment]
在index.html中引入，我use不了啊，VueBaiduMap这个对象找不到...

**Comment by Dafrok** [comment]
1. CDN 是干什么用的
2. 工程化和模块化用来解决什么问题的
3. 百度地图 API 本质上是怎么引入的
4. 路书本质上是怎么引入的
5. 工程化和 CDN 引入有什么矛盾
6. 使用 CDN 引入会给你带来什么问题

思考这 6 个问题，然后再写代码。

**Comment by Dafrok** [comment]
> 在index.html中引入，我use不了啊，VueBaiduMap这个对象找不到...

请参照示上面发的在线示例解决 。

**Comment by xiaowanhashi** [comment]
我前后都看了一遍，我是真的use的时候，这个对象是拿不到的啊，我就一个入口的index.html  看着你的文档 在页面引入<script src="https://unpkg.com/vue-baidu-map"></script> 

对于用vue-cli构建的项目我要哪去调用这段代码？
Vue.use(VueBaiduMap.default, {
  ak: 'C6bKwIcQvm2gPPUIPjpSQpVD'
})
main.js试过了没有VueBaiduMap这个对象的
很抱歉问得问题都比较没水平，但是就这个路书的问题确实是花了好久时间没解决，希望多多包涵，

**Comment by Dafrok** [comment]
照着示例一个字节一个字节地对比，看看到底哪出问题。

**Comment by Dafrok** [comment]
我已经把刚才的示例更新了，逻辑上和是否 CDN 引入已经完全没有关系了，如果再弄不懂我真的不知道该怎么告诉你了……

**Comment by xiaowanhashi** [comment]
看到了，你之前跟我提到过的，源码包装一个函数然后在ready中执行一下，试过了不行，我如果要用还是要实例化这个对象，所以我想是不是直接页面级的引入才有效果，因为我之前试过了页面级引入百度地图和路书两个script，然后定义个map.vue，在里面可以任意的实例化百度的对象并且调用其下的方法，

所以我一直问你在index.html 页面引入<script src="https://unpkg.com/vue-baidu-map"></script>
然后在main.js中调用这段代码对不对
Vue.use(VueBaiduMap.default, {
ak: '我的ak'
})
因为我use的时候 VueBaiduMap这个对象没有 真的很感谢你耐心的帮我

**Comment by Dafrok** [comment]
检查下执行顺序吧

**Comment by Dafrok** [comment]
顺手封装了一个路书的 npm 包，我认为这个问题做到这一步已经没法再简单了，不做后续讨论了。

https://github.com/Dafrok/BMapLib.LuShu

**Comment by xiaowanhashi** [comment]
万分感谢！因为我的几个问题让你重新封装了方法，我是半路接手别人的项目，也是第一次做基于GPS定位的业务，很感谢你，学到很多东西，方不方便留个QQ号码吗？对于一个陌生人来说希望能跟认识前辈很高兴，希望能多多接触学习(不打扰)

**Comment by Dafrok** [comment]
QQ 不怎么用。刚才封装的那个库有个加载顺序的 bug ，现在修复了。再有问题去那边提吧。

**Comment by xiaowanhashi** [comment]
好的，

**Comment by Dafrok** [comment]
路书组件已强势插入，[传送门](https://dafrok.github.io/vue-baidu-map/#/zh/bmaplib/lushu)。

**Comment by xiaowanhashi** [comment]
666
