### ISSUE TITLE
自定义覆盖物前两次点击信息窗体都正常显示，第三次点击信息窗体不再显示的问题

### ISSUE THREAD

**Issue by liyaxu123** [Dafrok/vue-baidu-map#913]
问题描述：自定义覆盖物前两次点击信息窗体都可以正常显示，第三次点击自定义覆盖物，信息窗体的show为true也不再显示。
当我把<script type="text/javascript" src="//api.map.baidu.com/getscript?v=3.0&ak=xxxx"></script>标签引入index.html里面后发现正常了，这是什么情况？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
