### ISSUE TITLE
在使用IE时候报错

### ISSUE THREAD

**Issue by GengHH** [Dafrok/vue-baidu-map#916]
[
![image](https://user-images.githubusercontent.com/17879467/114503637-37174f00-9c60-11eb-941c-b931c9a3ad9b.png)
](url)

使用的是vue 2.x和IE11;   
使用 import BaiduMap from 'vue-baidu-map/components/map/Map.vue';  在IE中报错如上图；
请问此组件是不是不支持IE？ 还是有办法可以解决？

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
