### ISSUE TITLE
在ready中获取map是怎么获取的？

### ISSUE THREAD

**Issue by FoxMissing** [Dafrok/vue-baidu-map#92]
如果我var map = new BMap.Map("div1");这样写的话，会报错，BMap not defined;
还有一个问题，这个定位的功能貌似是一个按钮点击之后进行的，我在源码里面找不到相关定位的方法，我想要在进入界面后就调用定位的方法而不用点击按钮，求解

**Comment by Dafrok** [comment]
第一个问题在文档里写的很详细了，你再仔细看看吧。
第二个问题在以前 issue 里讨论过了，你再认真找找吧。
