### ISSUE TITLE
start-usage md

### ISSUE THREAD

**Issue by yezongyang** [Dafrok/vue-baidu-map#93]
<img width="445" alt="74f4e179-0603-47cf-8995-a8f7b1992bad" src="https://user-images.githubusercontent.com/8924156/28196567-1eff4b98-6884-11e7-8051-8a962a8c4287.png">

it shoud be 'this.center = {}'

**Comment by Dafrok** [comment]
我来改还是你直接发个 pr ？

**Comment by yezongyang** [comment]
你顺便改一下吧，我就不发pr了

**Comment by Dafrok** [comment]
好
