### ISSUE TITLE
多边形可编辑 如何添加右键删除可编辑点？

### ISSUE THREAD

**Issue by ennis1091** [Dafrok/vue-baidu-map#933]
多边形可编辑 再添加一个编辑点后如何在此编辑点上右键删除编辑点，和百度地图api官方demo上的操作一样

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
