### ISSUE TITLE
marker显示不正常

### ISSUE THREAD

**Issue by qq178582223** [Dafrok/vue-baidu-map#935]
使用自定义marker的时候，只显示了一部分，用官方的marker也只显示一部分
![image](https://user-images.githubusercontent.com/38998923/121785304-a3281c00-cbeb-11eb-97e6-5c8cf348a1e6.png)
![image](https://user-images.githubusercontent.com/38998923/121785317-baffa000-cbeb-11eb-8376-d199003d8968.png)

自定义的代码如下：
![image](https://user-images.githubusercontent.com/38998923/121785339-d2d72400-cbeb-11eb-8368-7b3c7c94d3ea.png)

我已检查路径，并已确定图标有加载，就是显示不全，还望给予帮助解决。十分感谢

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
