### ISSUE TITLE
自定义bm-marker的icon，什么也不显示？

### ISSUE THREAD

**Issue by f43310** [Dafrok/vue-baidu-map#938]
`      <bm-marker
        :position="autoLocationPoint"
        :icon="{
          url: 'https://z3.ax1x.com/2021/07/13/WkI7o4.png',
          size: { width: 18, height: 18 }
        }"
        v-if="initLocation"
      >`

去掉icon属性会显示图标。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
