### ISSUE TITLE
事件冒泡

### ISSUE THREAD

**Issue by yanyunpiaomiao** [Dafrok/vue-baidu-map#939]
自定义覆盖物有严重的事件冒泡，拖动点击之类的事件都会传递到地图事件上，需要自己写很多阻止事件，希望可以放到组件默认阻止有需要传参开启..........

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
