### ISSUE TITLE
轨迹回放，点击停止之后，点击开始 如何让他从头开始播放

### ISSUE THREAD

**Issue by 15832072300** [Dafrok/vue-baidu-map#942]
` <baidu-map class="map" :center="{lng: 116.404, lat: 39.915}" :zoom="8">
        <bm-driving start="天安门" end="百度大厦" @searchcomplete="handleSearchComplete" :panel="false" :autoViewport="true" :autoView="true"></bm-driving>
        <bml-lushu @stop="reset" :path="path" :icon="icon" :speed="speed" :play="play" :rotation="true">
        </bml-lushu>
      </baidu-map>
      <div id="result" />
      <div class="btn_area">
        <div>
          <el-button id="run" size="mini" @click="handlerStart">开始</el-button>
          <el-button id="stop" size="mini" @click="handlerStop">停止</el-button>
          <el-button id="pause" size="mini" @click="handlerPause">暂停</el-button>
          <span class="sudu">速度</span>
        </div>
        <div class="block">
          <el-slider :min="1000" :max="20000" v-model="speed" @change="handlerSliderChange"></el-slider>
        </div>`

`handlerStart() {
      this.play = true;
    },
    handlerStop() {
      this.play = false;
    },
    handlerPause() {
      this.play = false;
    },
    /**
     * slider-change事件
     */
    handlerSliderChange(e) {
      // console.log(e)
    },
    reset() {
      this.play = false;
      console.log(this.path);
    },
    handleSearchComplete(res) {
      this.path = res.getPlan(0).getRoute(0).getPath();
    },`

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
