### ISSUE TITLE
城市列表搜索框回车有问题

### ISSUE THREAD

**Issue by icooloop** [Dafrok/vue-baidu-map#949]
![image](https://user-images.githubusercontent.com/70699443/133358825-2c0b8e1a-1bf6-4586-af00-5a802bfff394.png)
![image](https://user-images.githubusercontent.com/70699443/133358951-8c14048f-fd9f-4c5e-8113-e63ba9f0a154.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
