### ISSUE TITLE
How can I edit the points in the BmPolyline?

### ISSUE THREAD

**Issue by AkatQuas** [Dafrok/vue-baidu-map#95]
It seems these points are kinda instance of BmMarker.
I can drag and move these points.
But there is no response if I just cilck the point.
Whereas, the lineevent would be triggered if I click the line/ path.
How can I listen to the events on these points, and more than that, I want to remove some points by dbclick, is that possible? 
Codes are like the followings:
    
    <bm-polyline                    
        :path="polyline"
        :stroke-opacity="0.5"
        :editing="true"
        @click="lineevent"
    ></bm-polyline>

**Comment by Dafrok** [comment]
```
...
onLineUpdate(e) {
  const markers = e.target.getPath()
  markers.forEach(marker => marker.addEventListener('click', handler))
}
...
```

**Comment by Dafrok** [comment]
Oh, that's my mistake, sorry about that. After reading the [documentation](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a3b11), I found nowhere to get those markers. I suppose you should submit this issue to the [official community](http://bbs.lbsyun.baidu.com/forum.php).

**Comment by Dafrok** [comment]
Oh, that's my mistake and sorry about that. After reading the [documentation](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference.html#a3b11), I found nowhere to get those markers. I suppose you should submit this issue to the [official community](http://bbs.lbsyun.baidu.com/forum.php).

**Comment by AkatQuas** [comment]
well, I just find an alternative way to remove one marker by removing the point in the path array.
Seems fine.
