### ISSUE TITLE
城市列表搜索框回车问题

### ISSUE THREAD

**Issue by icooloop** [Dafrok/vue-baidu-map#950]
[城市列表搜索框回车问题](https://dafrok.github.io/vue-baidu-map/#/issues)城市列表里的搜索框 按回车会导致页面崩溃。

![1631672089985_C4164E28-7A89-4945-A005-B6409A4CDDE5](https://user-images.githubusercontent.com/70699443/133359369-14fa555f-c455-414c-922b-a528581ff73a.png)

![1631672106792_78C502D5-DDEF-49b5-81E0-8694AB35B001](https://user-images.githubusercontent.com/70699443/133359359-73310580-8654-49f4-9e09-df7401ae4d04.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
