### ISSUE TITLE
文档中 设置自定义主题demo 图块加载失败

### ISSUE THREAD

**Issue by ZoeC5** [Dafrok/vue-baidu-map#955]
### 浏览器版本号

chrome 94.0.4606.81

### Vue 版本号

2.6.10

### 组件库版本号

0.21.22

### 现象描述

```
部分地图图块加载失败, 几乎必现.
```

### 完整异常信息

```
GET https://api.map.baidu.com/customimage/tile?&x=12653&y=4712&z=16&udt=20211013&scale=1&ak=oW2UEhdth2tRbEE4FUpF9E5YVDCIPYih&styles=t%3Aall%7Ce%3Ag%7Cs%3A89%7Ch%3A%23007fff%2Ct%3Awater%7Ce%3Aall%7Cc%3A%23ffffff net::ERR_EMPTY_RESPONSE
```

### 在线示例 / 仓库 URL

https://dafrok.github.io/vue-baidu-map/#/zh/map/baidu-map

### 复现用例

```
打开示例网页->地图->地图容器->设置自定义主题->双击地图放大
```

### 预期输出

```
地图加载完整
```

### 实际输出

```
部分地图图块加载不出
```

**Comment by apgk** [comment]
基本没得救，升级3.0 然后采用setMapStyleV2 才行  webgl部分功能无效。。。。。。。。

**Comment by apgk** [comment]
目前我的做法就是引入一个不完整的包 vue-baidu-map-v3  然后再handle里面采用 map.setMapStylev2(自定义样式)

**Comment by 418545106** [comment]
> 目前我的做法就是引入一个不完整的包 vue-baidu-map-v3 然后再handle里面采用 map.setMapStylev2(自定义样式)

请问一下大佬具体方法怎么做。

**Comment by a83988029** [comment]
我也是遇到这个问题。

**Comment by a83988029** [comment]
https://www.jianshu.com/p/55777787e1c1 这个办法可以解决
