### ISSUE TITLE
局部引用出错

### ISSUE THREAD

**Issue by richardQJ** [Dafrok/vue-baidu-map#96]
BaiduMap.vue
`<template>
  <baidu-map class="bm-view"></baidu-map>
</template>
<script>
import BaiduMap from 'vue-baidu-map'
export default {
  name: 'BaiduMap',
  components: { BaiduMap }
}
</script>
<style>
  .bm-view{
    width:100%;
    height:300px;
  }
</style>
`
error message:
[object Error]{description: "Out of stac...", message: "Out of stac...", name: "Error", number: -2146828260, stack: "Error: Out ..."}
stack"Error: Out of stack space ...

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-baidu-map/#/zh/start/usage

请以字节为单位对照您的代码和文档上的区别

**Comment by richardQJ** [comment]
谢谢，解决了
