### ISSUE TITLE
marker使用自定义icon后无法触发点击事件

### ISSUE THREAD

**Issue by liusl0503** [Dafrok/vue-baidu-map#961]
`<!--`

注意：请使用 [ISSUE 生成器](https://dafrok.github.io/vue-baidu-map/#/issues) 创建新 ISSUE，不符合条件的 ISSUE 将被机器人自动关闭！

Attention: Please create issues according to [issue generator](https://dafrok.github.io/vue-baidu-map/#/issues), or bot will close it.

-->

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
