### ISSUE TITLE
百度底层能否更新,BMap实例现在百度升级为BMapGL实例，组件能否也升级下

### ISSUE THREAD

**Issue by 520wsl** [Dafrok/vue-baidu-map#966]
百度底层能否更新,BMap实例现在百度升级为BMapGL实例，组件能否也升级下

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
