### ISSUE TITLE
地图类型设置

### ISSUE THREAD

**Issue by richardQJ** [Dafrok/vue-baidu-map#97]
BaiduMap.vue
`<template>
  <baidu-map class="bm-view" ak="WfiQkbC1s2hMzVEf0duhSa3aQbYGM4jK" :center="center" @ready="handler">
  </baidu-map>
</template>

<script>
import {BaiduMap} from 'vue-baidu-map'
export default {
  components: {
    BaiduMap
  },
  data () {
    return {
      center: {lng: 0, lat: 0
      }
    }
  },
  methods: {
    handler ({BMap, map}) {
      console.log(BMap, map)
      this.center.lng = 121.48
      this.center.lat = 31.22
      map.setCurrentCity('上海')
      map.setMapType(BMAP_PERSPECTIVE_MAP)
      map.setZoom(22)
    }
  }
}
</script>

<style>
.bm-view {
  width: 100%;
  height: 500px;
}
</style>
`
我的代码格式是正确的复制过来就这样了，而且不加地图类型设置是正确显示的。错误信息：
 ERROR  Failed to compile with 1 errors                                                                         15:48:57

 error  in ./src/components/MapBaidu.vue

  ✘  http://eslint.org/docs/rules/no-undef  'BMAP_PERSPECTIVE_MAP' is not defined
  src\components\MapBaidu.vue:25:22
        map.setMapType(BMAP_PERSPECTIVE_MAP)
                        ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/no-undef

 @ ./src/router/index.js 7:0-45
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

另外我想用默认三维地图，可以吗？在网页开发情况下实现了，这个vue cil开发感觉局限性很大呢

**Comment by Dafrok** [comment]
你能把代码块组织整齐吗……

**Comment by richardQJ** [comment]
不是我不想弄整齐，你这里代码复制过来就这样了，
`<template>
  <baidu-map class="bm-view" ak="WfiQkbC1s2hMzVEf0duhSa3aQbYGM4jK" :center="center" @ready="handler">
  </baidu-map>
</template>

<script>
import {BaiduMap} from 'vue-baidu-map'
export default {
  components: {
    BaiduMap
  },
  data () {
    return {
      center: {lng: 0, lat: 0
      }
    }
  },
  methods: {
    handler ({BMap, map}) {
      console.log(BMap, map)
      this.center.lng = 121.48
      this.center.lat = 31.22
      map.setCurrentCity('上海')
      map.setMapType(BMAP_PERSPECTIVE_MAP)
      map.setZoom(22)
    }
  }
}
</script>

<style>
.bm-view {
  width: 100%;
  height: 500px;
}
</style>
`

**Comment by richardQJ** [comment]
哦，我明白了，vue-baidu-map，操作都是在标签里定义，之前用的网页里都是js文件里，还按以前套路来呢，这回明白了。

**Comment by Dafrok** [comment]
markdown 有一个语法叫做代码块 用于代码排版 你这一大坨看得我直犯晕…
