### ISSUE TITLE
<bm-driving>组件  @searchcomplete 事件回调返回的参数经常性出现undefind

### ISSUE THREAD

**Issue by Jungege5858** [Dafrok/vue-baidu-map#972]
![image](https://user-images.githubusercontent.com/34880767/149258144-301d3c7f-6e5f-4425-9414-80d8a8081649.png)
![image](https://user-images.githubusercontent.com/34880767/149258608-d81436d3-12fa-4c43-985b-1aa9ef7e350d.png)
![image](https://user-images.githubusercontent.com/34880767/149258374-01420628-7759-4545-9942-775ec741416d.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by Jungege5858** [comment]
您发的邮件我已收到！谢谢来信！
