### ISSUE TITLE
bm-label鼠标悬浮

### ISSUE THREAD

**Issue by Eron-liu8** [Dafrok/vue-baidu-map#979]
bm-label鼠标悬浮后，如何实现当前label置顶到最顶层

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。

**Comment by Eron-liu8** [comment]
bm-label鼠标悬浮后，如何实现当前label置顶到最顶层
