### ISSUE TITLE
enableMapClick这个属性怎么添加

### ISSUE THREAD

**Issue by qkzzxb** [Dafrok/vue-baidu-map#98]
你好,我想禁止弹出百度自带的详细信息,需要设置enableMapClick:false,
`<baidu-map class="map-inner"  :enableMapClick="false">
</baidu-map> `
怎么用才可以生效

**Comment by qkzzxb** [comment]
怎么用生效= =手误

**Comment by Dafrok** [comment]
请耐心并细心阅读 [文档](https://dafrok.github.io/vue-baidu-map/#/zh/map/baidu-map)

**Comment by Shangri-GitHub** [comment]
试试👀
<baidu-map class="map-inner" :mapClick="false"> </baidu-map>
