### ISSUE TITLE
鼠标滚轮滚动时，地图缩放中心点出现偏移问题

### ISSUE THREAD

**Issue by embracecode** [Dafrok/vue-baidu-map#981]
需要做一个新增功能，通过点击按钮功能弹出嵌套表单的dialog，动态根据地图中心点位置获取中心点经纬度。
但是由于表单项较多，表单dialog弹出后页面是有滚动条的，而地图位于表单的底部。
当用户编辑到表单的地图位置时，滚动条已经到底，此时通过滚轮缩放地图时，缩放中心点出现偏移，并不是以鼠标所在位置进行缩放。

要求只能用百度地图做 缩放中心点偏移问题  不知道怎么解决

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
