### ISSUE TITLE
bm-auto-complete 组件检索功能在h5上无法显示检索结果 会出现层级问题

### ISSUE THREAD

**Issue by embracecode** [Dafrok/vue-baidu-map#982]
<bm-control>
                <bm-auto-complete v-model="searchPlace" class="bm-auto-sty" :sugStyle="{zIndex: 999999}" @confirm="handleConfirm">
                    <van-search id="custom-component-input" style="z-index: 999999" class="custom-component-input" v-model="searchPlace" placeholder="请输入要搜索的地址"/>
                </bm-auto-complete>
            </bm-control>

无法显示检索结果，在pc端正常显示结果 在h5端没有检索结果

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
