### ISSUE TITLE
vue3使用element的dialog导致地图只展示灰底

### ISSUE THREAD

**Issue by swey01** [Dafrok/vue-baidu-map#986]
在线示例 URL
无

功能描述
在页面调试功能正常，使用dialog的方式弹出后，地图只显示灰色背景，这两个页面使用了同一个vue文件

用法示例
无

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
