### ISSUE TITLE
多边形在移动端编辑点出现地图bug

### ISSUE THREAD

**Issue by ZBW9290816** [Dafrok/vue-baidu-map#988]
多边形在移动端的编辑只有在map不可拖动状态下
可编辑，map容器设置为map.disableDragging()，当多边形可以编辑状态下，将点拖到地图边缘就会出现视频bug，地图一直移动，停止不下来。

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
