### ISSUE TITLE
BMapLib.SearchInfoWindow 请问怎么使用默认的信息窗？

### ISSUE THREAD

**Issue by ppLao** [Dafrok/vue-baidu-map#99]
[http://developer.baidu.com/map/jsdemo.htm#d0_4](url)

请问如何使用百度地图这个例子的默认信息窗？谢谢！

**Comment by Dafrok** [comment]
Addons 的问题请移步 [官方社区](http://bbs.lbsyun.baidu.com/forum.php)

**Comment by ppLao** [comment]
厄，抱歉。我是在vue里面用的

**Comment by ppLao** [comment]
勉强算是做到效果，不过不知道过程是否正确

>handler ({BMap, map}) {
               require('~plugins/SearchInfoWindow_min')  //这里我把http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.js下载了引入
//还有一个css，需要自己引入
                let content = '<div style="margin:0;line-height:20px;padding:2px;">' +
                    '地址：北京市海淀区上地十街10号<br/>电话：(010)59928888<br/>简介：百度大厦位>于北京市海淀区西二旗地铁站附近，为百度公司综合研发及办公总部。' +
                    '</div>';
                let searchInfoWindow = new BMapLib.SearchInfoWindow(map, content, {
                    title  : "百度大厦",      //标题
                    width  : 290,             //宽度
                    height : 105,              //高度
                    enableSendToPhone:false,
                });
                let poi = new BMap.Point();
                poi.lng = 116.324852;
                poi.lat = 40.057031;
                searchInfoWindow.open(poi);
            }

这个handler是写在ready回调那里的
