### ISSUE TITLE
驾车路线规划

### ISSUE THREAD

**Issue by liu3238** [Dafrok/vue-baidu-map#993]
![image](https://user-images.githubusercontent.com/100775634/181160497-b5295dcf-df8a-41f7-93df-b45cafadf0d5.png)
这个驾车路线的时候总是报这几个错误，官网和自己调用的总是出这个错，时有时没有

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
