### ISSUE TITLE
在vite打包下global使用报错, 希望可以声明一下解决

### ISSUE THREAD

**Issue by Hmap-Mr** [Dafrok/vue-baidu-map#994]
# 在vite打包下global使用报错, 希望可以声明一下解决
(An error was reported when using [global] under [Vite] packaging. I hope you can declare it to solve the problem)

### 使用vite会报错
(It has bug with vite build bag)
![image](https://user-images.githubusercontent.com/48115485/182065726-5846cec0-79ba-4fc0-94e9-a9e1df4b746e.png)

### 报错代码(bug code)
![image](https://user-images.githubusercontent.com/48115485/182065791-768b1cec-5c11-4ae9-a49b-7c00b8521bad.png)

**Comment by Dafrok** [comment]
Auto closed by issues bot. Please create your issue by issue generator.

当前问题由机器人自动关闭，请使用 ISSUE 生成器提交您的问题。
